### ISSUE TITLE
double spaces in tspan

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1001]
Prozessing [File:Oxygen480-mimetypes-hidef-application-rtf.svg](https://commons.wikimedia.org/wiki/File:Oxygen480-mimetypes-hidef-application-rtf.svg)
> $ svgo -i [input.svg.txt](https://github.com/svg/svgo/files/2195767/input.svg.txt) -o [output.svg.txt](https://github.com/svg/svgo/files/2195772/output.svg.txt) --indent=1 --disable=removeUnknownsAndDefaults

leads to a removement of double spaces in tspan

Maybe related to https://github.com/svg/svgo/issues/878

----
[input.svg](https://github.com/svg/svgo/files/2195767/input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg font-family="ScriptS" font-size="5" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" xml:space="preserve">
 <text x="26.5" y="11.3" font-family="ScriptS" font-size="5" xml:space="preserve">
  <tspan x="26.5" y="11.3" dx="0,0,.47,0,0,0,0,0,.47,0,0,0,0,0,.47,0,0,0,0,0,.47,0,0,0,.47" xml:space="preserve">  Lorem ipsum dolor sit amet, </tspan>
  <tspan x="26.5" y="19.3" dx="0,0,0,0,0,0,0,0,0,0,0,0,0,2.95,0,0,0,0,0,0,0,0,0,0,2.95">consectetuer adipiscing elit. </tspan>
  <tspan x="26.5" y="35.3">dui. Nam a nunc. </tspan>
  <tspan x="26.5" y="43.3" dx="0,0,3.01,0,0,3.01,0,0,0,3.01,0,0,0,0,0,0,0,0,0,3.01" xml:space="preserve">  In hac habitasse platea </tspan>
  <tspan x="26.5" y="51.3" dx="0,0,0,0,0,0,0,0,0,0,2.25,0,0,0,0,0,0,0,0,0,0,2.25">dictumst. Vestibulum viverra </tspan>
  <tspan x="26.5" y="67.3">vitae velit euismod aliquet. </tspan>
  <tspan x="26.5" y="75.3" dx="0,0,0,1.1,0,0,0,0,0,1.1,0,0,1.1,0,0,0,0,0,0,1.1" xml:space="preserve">   Donec ut purus. Phasellus </tspan>
  <tspan x="26.5" y="83.3" dx="0,0,0,0,0,0,1.8,0,0,0,0,1.8,0,0,0,0,0,0,0,0,0,1.8">magna sem, vulputate eget, </tspan>
 </text>
</svg>
```
![input](https://user-images.githubusercontent.com/15687581/42734939-776bf0e0-884c-11e8-9ece-72107efa3f63.png)

----
[output.svg.txt](https://github.com/svg/svgo/files/2195772/output.svg.txt)
```svg
<svg font-family="ScriptS" font-size="5" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" xml:space="preserve">
 <text x="26.5" y="11.3" font-family="ScriptS" font-size="5" xml:space="preserve">
  <tspan x="26.5" y="11.3" dx="0,0,.47,0,0,0,0,0,.47,0,0,0,0,0,.47,0,0,0,0,0,.47,0,0,0,.47" xml:space="preserve"> Lorem ipsum dolor sit amet, </tspan> <tspan x="26.5" y="19.3" dx="0,0,0,0,0,0,0,0,0,0,0,0,0,2.95,0,0,0,0,0,0,0,0,0,0,2.95">consectetuer adipiscing elit. </tspan> <tspan x="26.5" y="35.3">dui. Nam a nunc. </tspan> <tspan x="26.5" y="43.3" dx="0,0,3.01,0,0,3.01,0,0,0,3.01,0,0,0,0,0,0,0,0,0,3.01" xml:space="preserve"> In hac habitasse platea </tspan> <tspan x="26.5" y="51.3" dx="0,0,0,0,0,0,0,0,0,0,2.25,0,0,0,0,0,0,0,0,0,0,2.25">dictumst. Vestibulum viverra </tspan> <tspan x="26.5" y="67.3">vitae velit euismod aliquet. </tspan> <tspan x="26.5" y="75.3" dx="0,0,0,1.1,0,0,0,0,0,1.1,0,0,1.1,0,0,0,0,0,0,1.1" xml:space="preserve"> Donec ut purus. Phasellus </tspan> <tspan x="26.5" y="83.3" dx="0,0,0,0,0,0,1.8,0,0,0,0,1.8,0,0,0,0,0,0,0,0,0,1.8">magna sem, vulputate eget, </tspan>
 </text>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/42734949-7d2bead0-884c-11e8-87b7-eba30d6e8638.png)

----
Differences:

two spaces reduced to one space

|![input](https://user-images.githubusercontent.com/15687581/42734977-eacf246c-884c-11e8-8f1a-73b0785670e7.png)|<--input

|![output](https://user-images.githubusercontent.com/15687581/42734975-e720396e-884c-11e8-840b-f5bca85b1a67.png)|<--Output

----
<details>
<summary>Copyright of the picture</summary>

License: [LGPLv3](https://www.gnu.org/copyleft/lgpl.html)

Author: [The Oxygen Team](https://github.com/KDE/oxygen-icons/blob/master/AUTHORS), [KDE](https://techbase.kde.org/Projects/Oxygen/Licensing)

Source: https://github.com/KDE/oxygen-icons5

Details: [https://commons.wikimedia.org/wiki/File:Oxygen480-mimetypes-hidef-application-rtf.svg](https://commons.wikimedia.org/wiki/File:Oxygen480-mimetypes-hidef-application-rtf.svg)

</details>

**Comment by tigt** [comment]
This is indeed a bug, but last I checked browser support for `xml:space` in SVG is patchy.

For example, [neither IE nor Edge respects it](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/817824/), and I think Firefox may have issues with it as well.

You may have to convert double spaces to alternate between spaces and non-breaking spaces for that reason anyway.

**Comment by JoKalliauer** [comment]
@tigt 
changing spaces to non-breaking spcaes does not help at all
- optimizers such as SVGO replaces non-breaking spaces with normal spaces
- see #1029 or #878 

about support:
Firefox supports xml:space since Firefox 3 (see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space#Browser_compatibility ) and Firefox displays it in almost all cases correctly. 
(But every common Browser displays https://commons.wikimedia.org/wiki/File:SVG_test_text_tspan_ws.svg differently, and none correct.)

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
