### ISSUE TITLE
Is there a way to use this in the browser?

### ISSUE THREAD

**Issue by MauriceMahan** [svg/svgo#1010]
Via the <script> tag. Without node.js or SVGOMG.

**Comment by GreLI** [comment]
Not for now. SVGO is tightly bound to Node.js API, there is no browser interface for it, unfortunately. It can be adopted of course but with some considerable efforts.

**Comment by cancerberoSgx** [comment]
Check this https://github.com/svg/svgo/issues/1050

Also I think https://jakearchibald.github.io/svgomg/ runs as a static application (https://github.com/jakearchibald/svgomg/issues/88#issuecomment-290986043)so I think it's possible. @GreLI Could you please clarify on this ? Thanks
