### ISSUE TITLE
Using svgo to optimize a 60M svg error

### ISSUE THREAD

**Issue by jkfhto** [svg/svgo#1012]
![image](https://user-images.githubusercontent.com/27767452/43873744-76ad5334-9bba-11e8-9558-eb2de1cd939c.png)

**Comment by GreLI** [comment]
Try disabling some plugins. Notably, `mergePaths`—it's not that friendly to large files.

**Comment by jkfhto** [comment]
I still get an error after disabling the mergePaths plugin

![image](https://user-images.githubusercontent.com/27767452/43890929-abdb4e9a-9bfa-11e8-87e5-f794b909c68a.png)

**Comment by jkfhto** [comment]
Disabled a lot of plugins for optimization or caused an error
![image](https://user-images.githubusercontent.com/27767452/43936247-574e8550-9c8a-11e8-99c6-a13da5faf5c9.png)

**Comment by GreLI** [comment]
Probably, your file is just too big. May be you have touched some limits.

**Comment by jkfhto** [comment]
Is there any other way to solve this problem?

**Comment by GreLI** [comment]
Not that I know, sorry.

**Comment by jkfhto** [comment]
Still thank you for your answer
