### ISSUE TITLE
Modernize SVGO

### ISSUE THREAD

**Issue by gregberge** [svg/svgo#1016]
I am the author of SVGR, a library to transform SVG into React Components. It offers build in support of SVGO.

SVGO is a great library and widely used! The work achieved since the beginning is amazing, thanks for that. Today SVGO is a little "old", code is written in ES5, documentation is not very handy, it does not offer synchronous mode (see #1015), there is a lot of issues and a lot of PR.

I think the project should be modernized and I would be happy to help you. SVGO is a big part of SVGR and it could be awesome to work together. SVGR is based on H2X, a traverser for HTML, it can modify the DOM using plugin like Babel does for JavaScript. Meaning we could be able to do all kind of optimizations.

We can continue to talk here or you can contact me on my Twitter (https://twitter.com/neoziro).

**Comment by TrySound** [comment]
Hi @gregberge. Gonna work on modernising. Already reduced amount of dependencies.
