### ISSUE TITLE
Request: ability to resize SVG

### ISSUE THREAD

**Issue by benfrain** [svg/svgo#102]
This is perhaps a little out of scope. However, it would be have ability to alter width and height attributes within all SVGs. For example, given a folder (called 'test') full of SVGs, here is the pseudo code I was thinking of:

```
svgo -f test --disable removeViewBox resizeWidth 96px resizeHeight 56px
```

Would that be possible? 

Extending this idea further (although obviously more complicated to implement), how feasible would it be to generate one dimension when the other is defined. Perhaps the ratio could be retained to work out the other (e.g. if width given, height is created relative to it):

```
svgo -f test --disable removeViewBox resizeWidth 96px resizeHeight auto
```

Perhaps by using width/height attributes first and if not available, the viewbox???

**Comment by jraoult** [comment]
@mattaningram @benfrain just in case you are still looking for a solution for your use case: https://github.com/svg/svgo/blob/master/plugins/removeDimensions.js

**Comment by mattaningram** [comment]
@jraoult Oh nice, thanks!

**Comment by benfrain** [comment]
Great, thanks

**Comment by GreLI** [comment]
Yes, it's out of scope, and there are a lot of issues with `viewBox`, resizing etc, so it isn't clear what to do in different cases.
