### ISSUE TITLE
cleanupNumericValues: viewBox regex is buggy

### ISSUE THREAD

**Issue by bobaaaaa** [svg/svgo#1024]
The following regex is wrong or needs a empty string filter:
https://github.com/svg/svgo/blob/174c37208017e5909d5f7db2e8faba49663a945a/plugins/cleanupNumericValues.js#L43

### Actual
```js
"0, 0, 25, 20".split(/[ ,]/g) // ["0", "", "0", "", "25", "", "20"]
```

### Expected
```js
"0, 0, 25, 20".split(/[ ,]/g).filter(Boolean) // ["0", "0", "25", "20"]
```

### SVG Example
Input:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0, 0, 20, 20">
  <rect width="20" height="20" fill="rgba(255,255,255,.85)" rx="20"/>
</svg>
```
Output:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 0 0 20 20">
  <rect width="20" height="20" fill="rgba(255,255,255,.85)" rx="20"/>
</svg>
```

### SVG Specification
[viewBox Attributes](https://www.w3.org/TR/SVG11/coords.html#ViewBoxAttribute)
> The value of the ‘viewBox’ attribute is a list of four numbers \<min-x\>, \<min-y\>, \<width\> and \<height\>, separated by whitespace and/or a comma [...]

**Comment by tigt** [comment]
Changing the regex to `/[ ,]+?/g` should work, I think — I’ll open a PR for it.
