### ISSUE TITLE
Running twice yields different results

### ISSUE THREAD

**Issue by chrleon** [svg/svgo#1027]
given this starting file (carousel-nosvgo.svg)
`<?xml version="1.0" encoding="UTF-8"?>
<svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>carousel</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <path d="M11,24 L11,9 L21,9 L21,24 L11,24 Z M13,11 L13,22 L19,22 L19,11 L13,11 Z M6,11 L10,11 L10,22 L6,22 L6,11 Z M22,11 L26,11 L26,22 L22,22 L22,11 Z" id="path-1"></path>
    </defs>
    <g id="carousel" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <mask id="mask-2" fill="white">
            <use xlink:href="#path-1"></use>
        </mask>
        <use fill="#444444" fill-rule="nonzero" xlink:href="#path-1"></use>
    </g>
</svg>`

running node test.js in terminal

    use strict;
    var FS = require('fs'),
        PATH = require('path'),
        SVGO = require('./node_modules/svgo'),
        filepath = PATH.resolve(__dirname, 'carousel-nosvgo.svg'),
    svgo = new SVGO({
      plugins: [{
        cleanupAttrs: true,
      },{
        removeDoctype: true,
      },{
        removeXMLProcInst: true,
      },{
        removeComments: true,
      },{
        removeMetadata: true,
      },{
        cleanupListOfValues: true,
      },{
        removeTitle: true,
      },{
        removeDesc: true,
      },{
        removeUselessDefs: true,
      },{
        inlineDefs: {
          onlyUnique: true
        }      
      },{
        removeEditorsNSData: true,
      },{
        removeEmptyAttrs: true,
      },{
        removeHiddenElems: true,
      },{
        removeEmptyText: true,
      },{
        removeEmptyContainers: true,
      },{
        removeViewBox: false,
      },{
        cleanupEnableBackground: true,
      },{
        convertStyleToAttrs: true,
      },{
        convertColors: true,
      },{
        convertPathData: true,
      },{
        convertTransform: true,
      },{
        removeUnknownsAndDefaults: true,
      },{
        removeNonInheritableGroupAttrs: true,
      },{
        removeUselessStrokeAndFill: true,
      },{
        removeUnusedNS: true,
      },{
        minifyStyles:true,
      },{
        cleanupIDs: {
          remove: true,
          minify: false,
          prefix: '',
          preserve: [],
          force: true
        }
      },{
        cleanupNumericValues: true,
      },{
        moveElemsAttrsToGroup: true,
      },{
        moveGroupAttrsToElems: true,
      },{
        collapseGroups: true,
      },{
        removeRasterImages: false,
      },{
        mergePaths: true,
      },{
        convertShapeToPath: true,
      },{
        sortAttrs: {
          order: [
            "d", "points",
            "id",
            "fill", "stroke", "marker",
            "width", "height",
            "x", "x1", "x2",
            "y", "y1", "y2",
            "cx", "cy", "r"
          ]
        }
      },{
        removeDimensions: true,
      },{
        removeAttrs: {attrs: '(stroke|fill)'},
      }]
    });
    FS.readFile(filepath, 'utf8', function(err, data) {
    if (err) {
        throw err;
    }

    svgo.optimize(data, {path: filepath}).then(function(result) {
        console.log(result.data);
        // {
        //     // optimized SVG data string
        //     data: '<svg width="10" height="20">test</svg>'
        //     // additional info such as width/height
        //     info: {
        //         width: '10',
        //         height: '20'
        //     }
        // }
    });

returns this SVG code

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32"><defs><path d="M11 24V9h10v15H11zm2-13v11h6V11h-6zm-7 0h4v11H6V11zm16 0h4v11h-4V11z" id="path-1"/></defs><use fill-rule="nonzero" xlink:href="#path-1"/></svg>`

When I save that code as a new svg, and run the same test.js again on that SVG, i get this SVG in return, like I want it to be. 

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M11 24V9h10v15H11zm2-13v11h6V11h-6zm-7 0h4v11H6V11zm16 0h4v11h-4V11z"/></svg>`

How can I get the last piece of code in one go? I thought multipass was the way to go, so I changed the number of multipasses to 20 (since it required two times) and also to 100 but no change.

Any input here would be greatly appreciated. 👍

**Comment by chrleon** [comment]
I removed some '' as they interfered with formatting.

**Comment by aturingmachine** [comment]
Hey do you have any updates on this? I am getting the same outcome.

**Comment by DavidHenri008** [comment]
I am also experiencing this issue where running twice svgo on same file with option revoveAttrs removes the stroke on first path and then any stroke-XXX attributes...
```json
   {
      "removeAttrs": {
        "attrs": "(stroke|fill)"
      }
    },
```

**Comment by TrySound** [comment]
Hi! Could you try svg v2 with multipass (boolean) enabled?
