### ISSUE TITLE
Problem when svgo gets called on empty folder

### ISSUE THREAD

**Issue by X-Tender** [svg/svgo#1034]
I don't know why this happen but since some time I cant run svgo on an empty folder (its called in a npm task run) it throws an error and break the task
```
> svgo -f src/svg/ --pretty --config cfg/svgo.config.json

Processing directory 'src/svg/':

Error: No SVG files have been found in 'src/svg/' directory.
    at processDirectory (/Users/paul/www/boilerplates/node_modules/svgo/lib/svgo/coa.js:365:24)
    at readdir.then.files (/Users/paul/www/boilerplates/node_modules/svgo/lib/svgo/coa.js:349:39)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@2.1.2 svgo: `svgo -f src/svg/ --pretty --config cfg/svgo.config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@2.1.2 svgo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Version 1.1.1
Webpack 4.19.1
webpack-cli 3.1.0

**Comment by GreLI** [comment]
Well, it says so

> Error: No SVG files have been found in 'src/svg/' directory.

Works as intended.

**Comment by X-Tender** [comment]
I made some additional changes. When I use the 0.7.2 Version it works and I only get the Message printed out. When I upgrade to at least 1.0.0 it behaves as described above.
Can you tell me which version fo node you're using? I'm on 6.9.1 here

**Comment by SlimMarten** [comment]
@GreLI I am struggling with the same problem.

**Comment by tobiasstraub** [comment]
@X-Tender @GreLI @martenzander 
Is there a fix? How you solved this, guys?

**Comment by TrySound** [comment]
Close for now. If this is still an issue ping me please.
