### ISSUE TITLE
switch to `cssnano` from `csso`

### ISSUE THREAD

**Issue by evilebottnawi** [svg/svgo#1036]
Why?
- `cssnano` is more stable and has more minification features. 
- `csso` doesn't have active maintainers https://github.com/jakubpawlowicz/clean-css/issues/1044.
- Based on `postcss` (using in many popular tools like `prettier`, `stylelint`, `webpack` and etc).

Or maybe we should avoid install css minificator and minification css, developers must decide for himself what to use.

**Comment by tigt** [comment]
Did you mean to title this issue “switch to cssnano from ***csso***”?

**Comment by evilebottnawi** [comment]
@tigt yes, sorry :disappointed:

**Comment by GreLI** [comment]
Actually, CSSO has got active maintainer recently, and he is the person who adopted it in SVGO 😛.

**Comment by evilebottnawi** [comment]
@GreLI Maybe we can feature to switch on other minification, now a lot of people use another minification like `cssnano`, `cssmin` and etc, it is not god have two package for same purpose in your node_modules

**Comment by strarsis** [comment]
@evilebottnawi, @GreLI: See this PR https://github.com/svg/svgo/pull/1127.
It can be merged when css-nano is released with sync support.

**Comment by GreLI** [comment]
Closing, since there is no reasonable answer to question «why» in practical matter. Changing just in praise of changes is not an option. CSSO also has unique feature, that cssnano doesn't have.

**Comment by strarsis** [comment]
@GreLI: Would having an extra plugin "minifyStyles-cssnano", that can be enabled, an alternative?

**Comment by evilebottnawi** [comment]
@GreLI 
> CSSO also has unique feature, that cssnano doesn't have.

Example?

**Comment by GreLI** [comment]
> Example?

See #640

**Comment by strarsis** [comment]
@GreLI: So `cssnano` would have to support element usage data to be considered as an alternative to `csso`?
