### ISSUE TITLE
convertStyleToAttrs removes color

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1040]
Processing [File:2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg](https://commons.wikimedia.org/wiki/File:2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg) with default options removes the color of countries:

svgo -i [Bug1040_Input2.svg.txt](https://github.com/svg/svgo/files/2409166/Bug1040_Input2.svg.txt) -o [Bug1040_Output2.svg.txt](https://github.com/svg/svgo/files/2409167/Bug1040_Output2.svg.txt) --pretty --indent=1 --enable=convertStyleToAttrs

# Input
[Bug1040_Input2.svg.txt](https://github.com/svg/svgo/files/2409168/Bug1040_Input2.svg.txt)

![bug1040_input2](https://user-images.githubusercontent.com/15687581/45933244-5b6b8d00-bf89-11e8-8e92-09adb41c4757.png)

# Output
[Bug1040_Output2.svg.txt](https://github.com/svg/svgo/files/2409176/Bug1040_Output2.svg.txt)

![bug1040_output2](https://user-images.githubusercontent.com/15687581/45933252-70e0b700-bf89-11e8-8dea-95afc6b39c80.png)

<details>

----
It seems to be a more complicated bug since editiong the file changes the Processiong of other parts.
----

<summary>Copyright</summary>

License: CC0

Author: [Mikael Häggström](https://commons.wikimedia.org/wiki/User:Mikael_H%C3%A4ggstr%C3%B6m)

Details (and Source): https://commons.wikimedia.org/wiki/File:2016_Angola_and_DR_Congo_yellow_fever_outbreak.svg

</details>

**Comment by TrySound** [comment]
convertStyleToAttrs will be disabled by default in the next release
https://github.com/svg/svgo/pull/1365

**Comment by JoKalliauer** [comment]
@TrySound : Does "solved in master" mean, that the bug does not occur with default configuration, but might occur with different settings? Does it mean that features which are disabled by default are marginally maintained?

**Comment by TrySound** [comment]
Solved the problem with default configuration, right. I consider this plugin unsafe for now. Though removing it would be breaking change. Maybe it will come back later with more flexible architecture.

**Comment by JoKalliauer** [comment]
I make workarounds for [LibrsvgBugs](https://commons.wikimedia.org/wiki/User:JoKalliauer#Repairing_damaged_SVGs_(minor_edits)), librsvg might be more buggy than svgo, so convertStyleToAttrs is usefull for me, even I know it is buggy.
I prefer having buggy beta-features, even if they are not officially maintained.

Maybe keep buggy features and declare in the Docs that they are buggy and not officially maintained, and hide them e.g. in  `svgo --show-plugins`. Maybe make a terminal-warning-output if enabled.

**Comment by TrySound** [comment]
Sure, if the problem will not be resolved I will add warning or something.

**Comment by TrySound** [comment]
https://github.com/svg/svgo/releases/tag/v2.1.0
