### ISSUE TITLE
inlineStyles does not work

### ISSUE THREAD

**Issue by nikkwong** [svg/svgo#1042]
input 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><style>.cls-2{fill:#1bb5ec}.cls-3{fill:#364f6b}</style></defs><g id="_3d_glasses" data-name="3d glasses"><path fill="none" d="M0 0h32v32H0z"/><rect class="cls-2" x="5" y="12" width="10" height="8" rx="1" ry="1"/><rect class="cls-2" x="17" y="12" width="10" height="8" rx="1" ry="1"/><path class="cls-3" d="M29 8H3a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h9.68a10.22 10.22 0 0 0 3-.84 1 1 0 0 1 .64 0 10.3 10.3 0 0 0 3 .84H29a2 2 0 0 0 2-2V10a2 2 0 0 0-2-2zm0 14h-9.68a24.79 24.79 0 0 1-2.32-.74 3.08 3.08 0 0 0-1.9 0c-.27.09-2.12.74-2.37.74H3V10h26z"/><path class="cls-3" d="M6 20h8a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm1-6h6v4H7zm11 6h8a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1h-8a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm1-6h6v4h-6z"/></g></svg>`

command
`svgo --enable=inlineStyles ~/glasses.svg`

output
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><style>.cls-2{fill:#1bb5ec}.cls-3{fill:#364f6b}</style></defs><g id="_3d_glasses" data-name="3d glasses"><path fill="none" d="M0 0h32v32H0z"/><rect class="cls-2" x="5" y="12" width="10" height="8" rx="1" ry="1"/><rect class="cls-2" x="17" y="12" width="10" height="8" rx="1" ry="1"/><path class="cls-3" d="M29 8H3a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h9.68a10.22 10.22 0 0 0 3-.84 1 1 0 0 1 .64 0 10.3 10.3 0 0 0 3 .84H29a2 2 0 0 0 2-2V10a2 2 0 0 0-2-2zm0 14h-9.68a24.79 24.79 0 0 1-2.32-.74 3.08 3.08 0 0 0-1.9 0c-.27.09-2.12.74-2.37.74H3V10h26z"/><path class="cls-3" d="M6 20h8a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm1-6h6v4H7zm11 6h8a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1h-8a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1zm1-6h6v4h-6z"/></g></svg>`

**Comment by nikkwong** [comment]
Ok, got it, this api is like an enigma to figure out. For those who stumble upon this:

```
var _svgo = new svgo({
    plugins: [{
        inlineStyles: {
            onlyMatchedOnce: false
        }
    }]
})
```

**Comment by minimaluminium** [comment]
@nikkwong You're a hero!
