### ISSUE TITLE
SVGO improperly alters text spacing

### ISSUE THREAD

**Issue by lrehmann** [svg/svgo#1044]
SVGO is causing some alteration to the SVG leading to overlapping text for some files.
I've altered the precision as well as disabled all SVGO plugins, but the end result is the same:
Output:
![screen shot 2018-09-26 at 3 55 31 pm](https://user-images.githubusercontent.com/6685076/46113816-c93fd080-c1a4-11e8-8271-a860cd34ef56.png)
Input:
![screen shot 2018-09-26 at 3 55 36 pm](https://user-images.githubusercontent.com/6685076/46113810-c644e000-c1a4-11e8-8f56-67d6043c31aa.png)

Here is the particular SVG files (INPUT: 1.svg, OUTPUT: 1.svgo.svg)
[svgo-overlapping-text 2.zip](https://github.com/svg/svgo/files/2421859/svgo-overlapping-text.2.zip)

I've narrowed this issue down to SVGO removing what it deems unncessary whitespace without altering the associated tspan formatting causing the tspan x and y coordinates to become offset from the original character placment values.

**Comment by XhmikosR** [comment]
@TrySound it seems this works fine in v2.1.0, but please confirm

**Comment by TrySound** [comment]
Yeah, fixed it recently. Forgot to close.
