### ISSUE TITLE
"Collapse useless groups" collapsing not useless groups

### ISSUE THREAD

**Issue by utilmind** [svg/svgo#1045]
Hello! This issue was noticed in svgo v1.0.5.

Option "collapseGroups" (or "Collapse useless groups" in SVGOMG) removing <g> tags and filter attributes to images, that does not work -- image doesn't displayed properly.

Attached file demonstrates the problem -- just try to compress it with and without "collapseGroups" option.

[Charivniy-Vechir.zip](https://github.com/svg/svgo/files/2423862/Charivniy-Vechir.zip)

**Comment by tmorehouse** [comment]
I'm running into this same issue.

```xml
  <defs>
    <filter id="a">
      <feDropShadow dx="0" dy="25" stdDeviation="25" flood-opacity="0.65" />
    </filter>
</defs>
```

is being turned into this:

```xml
<defs><filter id='a'/></defs>
```

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.6.1
