### ISSUE TITLE
cleanupIDs Plugin Not Doing What's Expected

### ISSUE THREAD

**Issue by LarryAzevedo** [svg/svgo#1046]
Using `cleanupIDs` on an SVG that does not contain a `<style>` tag will work.

However, if the SVG has a `<style>` tag in it, it will not.  For example, this SVG got it's id attribute removed completely (good):
```
<svg id="Layer1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">
    <path>...</path >
```
But this one will not (bad):
```
<svg id="Layer1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">
    <style>...</style>
```

**Comment by elrumordelaluz** [comment]
Seems based on [this check](https://github.com/svg/svgo/blob/54f92ce2deccdbd3177b711b06aa0cf928039c4c/plugins/cleanupIDs.js#L57).

You have to pass `force: true` in case `<style>` or `<script>` is present.

In CLI you have to do something like: 

```
svgo input.svg --config '{ "plugins": [ { "cleanupIDs": { "force": true } }] }'
```

**Comment by GreLI** [comment]
Yep, SVGO can't say whether IDs are used in script or styles, so it doesn't remove them in that case.

**Comment by theasteve** [comment]
@GreLI is `{ "cleanupIDs": { "force": true } }` removed unused SVGs?
