### ISSUE TITLE
stdout when processing a folder

### ISSUE THREAD

**Issue by elrumordelaluz** [svg/svgo#1054]
As I understand reading `coa` part of `svgo` to show processed data as `stdoud` needs to be 
```js
output ==  '-'
``` 
but also be a single file input.
 
Is there a reason? It could be difficult to `stdout` the strings concatenated?

**Comment by GreLI** [comment]
It just doesn't make sense, I think.

**Comment by elrumordelaluz** [comment]
ok, just asking because was trying to pipe the output to be proccessed with [this tool](https://github.com/elrumordelaluz/svgson-cli) and for single file works perfect.
