### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rugk** [svg/svgo#1055]
Fedora Magazine [claims](https://fedoramagazine.org/design-faster-web-pages-part-2-image-replacement/) this tool is not actively developed anymore?

IMHO this does not look like that. Could you clarify this?

**Comment by justrhysism** [comment]
@rugk Your link points to DuckDuckGo...

**Comment by rugk** [comment]
Uuups… fixed, here is the correct one: https://fedoramagazine.org/design-faster-web-pages-part-2-image-replacement/

**Comment by GreLI** [comment]
Well, I'd say this claim is correct. I'm doing some things (mostly bugfixing) from time to time, but have a little time to develop.

**Comment by justrhysism** [comment]
Invite some new maintainers/collaborators on board? Seems plenty of people are keen to contribute.

**Comment by GreLI** [comment]
Not many people are really interested in it, unfortunately.

**Comment by justrhysism** [comment]
⭐️ 10,000+ stars on GitHub, surely there is.

**Comment by shoogle** [comment]
@GreLI, you could start by putting someone else in charge of a new semi-official repository just for plugins, then you would only have to maintain the core plugins and the API.

This would speed up development of new plugins while keeping the core code safe. You can merge the most popular ones into the core.

**Comment by shoogle** [comment]
@GreLI, could you link to the relevant issues in the tracker, or maybe label them as "priority", or apply a milestone, or something like that? It would be good to have some idea what needs doing.

**Comment by GreLI** [comment]
It's just ideas, not really specified. Some pieces of them can be seen here or there. Some quick thaughts:
1) Better parser. Currently sax-js is used, but it has limitations. E.g. some work is needed to preserve white-space (with `xml-preserve` or `white-space` style). Also, parse path data syntax, styles, etc. Perhaps lazy.
2) Better plugins system. Now it works consequently and therefore have issues with order of execution. E.g. some plugin is best to run after another in some case, and with directly opposite order in another. Could be event driven (e.g. `collapseGroups` may execute as soon as there is some `<g>` without attributes after some transformations).
3) Plugin system should work not only on elements, but with path data.
4) Some better API. E.g. quick check for next node in path data regardless of whether there a start or end of path.
5) It would be nice to have CSS object tree along with document tree for styling checks. E.g. not every transformation can be applied in presence of strokes.

**Comment by GreLI** [comment]
Also, could be cool if core automatically apply every action to check whether it efficient or should be reverted.

**Comment by strarsis** [comment]
@shoogle: Using jsdom would probably also get rid of many redundancies like the code introduced by the inlineStyles plugin.

**Comment by sk-** [comment]
@GreLI could we start with the following:
- Closing old issues and prs. I'd close everything older than 2 years. For the rest I'd manually go through it triaging it.
- Granting access to interested developers: maybe those active in issues and prs in the last 6 months.
- Remove support for EOL node versions.

**Comment by sk-** [comment]
@GreLI it'd be great to have a definitive answer, either:

- whether you would accept any external maintainers. I think this is the best course of action given the adoption of the project.
- whether this project is no longer maintained. I think it is fair as people are still submitting PRs and is being depended by more than 2 million projects.

@strarsis, @shoogle, @justrhysism would you be interested on collaborating as maintainers?

**Comment by strarsis** [comment]
@sk-: Yes, I use svgo extensively and contribute from time to time.

**Comment by strarsis** [comment]
PR for replacing sax with saxes: https://github.com/svg/svgo/pull/1281

**Comment by paulocoghi** [comment]
I developed a library, [alumna/unitflow](https://github.com/alumna/unitflow), to solve situations exactly like GreLi's item # 2.

It's possible to specify a sequence for svgo plugins execution (called a "flow") and, if parallelism is desired, through separated flows it's possible to define dependencies between desired plugins on different flows, that will be fully respected in a fully reactive manner.

Uniflow is made in pure JS, it has 0 dependencies and only 1.3kB, it's 100% tested, 100% asynchronous and it's available both in CommonJS and ESM formats.

**Comment by paulocoghi** [comment]
It's also possible to define multiple flows programmatically with different combinations of plugins sequence, and check which one provides the best results.

**Comment by strarsis** [comment]
@paulocoghi: That's great, something between native JS and webpack.
Could it also be used in an agnostic way to extract resources inside the SVG file (like inline raster images), 
then process these separately, like compressing or saving them as external files, 
and then either re-embedding these into the SVGs (inlining or an external reference), so also like gulp?
Because using something like webpack for this would lock svgo completely into webpack and would not allow simple, standalone use.

**Comment by paulocoghi** [comment]
@strarsis yes, exactly! Like gulp, but much simpler :)

**Comment by deepsweet** [comment]
SVGO project is currently looking for new maintainer(s), please see #1320
