### ISSUE TITLE
Disabling multiple plugins does not work on Windows

### ISSUE THREAD

**Issue by DJ4ddi** [svg/svgo#1063]
Hi there.

As noted in #900 and #1019, the curly braces for enabling or disabling multiple plugins does not work on Windows. Using `--disable=pluginName` multiple times results in a 

> TypeError: Cannot create property 'pluginName' on string 'pluginName'
> at changePluginState (coa.js:317:37)
> ...

Please merge #1019 or allow using the disable argument multiple times to avoid having to create a configuration file for every plugin combination.

Regards,
Addi

**Comment by DeeDeeG** [comment]
This issue might be fixed now that #1019 is merged.

**Comment by GreLI** [comment]
Comma-separated list like `--disable=plugin1,plugin` should work since SVGO v1.2.0.
