### ISSUE TITLE
How to keep IDs?

### ISSUE THREAD

**Issue by kopax** [svg/svgo#1065]
I have animated a SVG in react and I have my css in my react app, I want to optimize the svg.

I have tried to disable `cleanupIDs` but there is some cleanup I don't know how to disable.

How can I tell svgo to not touch the element with an ID?

**Comment by shoogle** [comment]
Putting this information together:

- Each SVG optimization is done by a [separate plugin](https://github.com/svg/svgo#what-it-can-do) to SVGO.
- One of the plugins is called [`cleanupIDs`](https://github.com/svg/svgo/blob/master/plugins/cleanupIDs.js).
- SVGO has a [`--disable` option](https://github.com/svg/svgo#usage) to disable a particular plugin (or multiple plugins).

We get:

```bash
svgo --disable=cleanupIDs file.svg
```
