### ISSUE TITLE
how to set the prefixIds in .svgo.yml ?

### ISSUE THREAD

**Issue by kopax** [svg/svgo#1066]
I am trying to configure `.svgo.yml` for the first time and I found hard to understand the name of every parameter for every module.

So far, the `cleanupIDs` plugin does not satisfy me because it is still conflicting colors within my page.

is there a way to set a random value to `prefixIds` plugins?

**Comment by shepmaster** [comment]
I used this as my config file:

```yml
full: true
plugins:
  - prefixIds: true
```

And then ran the svgo binary against the SVGs; this used the filename as the prefix for me.

**Comment by kopax** [comment]
thanks!
