### ISSUE TITLE
Convert translates into path data

### ISSUE THREAD

**Issue by slavafomin** [svg/svgo#1069]
Hello!

Thank you for this great tool!

However, I have the following weird file:
<img width="845" alt="screen shot 2018-12-26 at 17 46 13" src="https://user-images.githubusercontent.com/1702725/50449129-43aff600-0936-11e9-9777-b61a0f501516.png">

Notice the multiple translates almost cancelling each other.

Is there a way to update the path data in order to remove those translates from the SVG, but preserve the exact same look of the graphics?

Thank you!

---

Right now, the tool's output looks a bit different from the original image (image has different size and it has slightly different coordinates).

---

Here's the problematic source file:
https://gist.github.com/slavafomin/2ff2426498c0510a3db4ed05d3220472

**Comment by TrySound** [comment]
Looks like this is fixed

**Comment by specious** [comment]
If I'm not mistaken, #624 appears to be precisely about this.
