### ISSUE TITLE
SVG file breaks folder optimization

### ISSUE THREAD

**Issue by oraslaci** [svg/svgo#1071]
Hey,
I tried to optimize a whole folder containing svg files. One of the files gave an error and svgo exited leaving the rest of the files (until that particular file) empty. It may happen that the file is malformatted, but I would expect that  this error should not destroy the rest of the files.

See the output and culprit file below:
```
svgo ~/src/icon_zoomin_black.svg
Error in parsing SVG: Unbound namespace prefix: "sodipodi"
Line: 16
Column: 106
Char: >
```

(I had to rename the file so I can upload it)
[icon_zoomin_black.txt](https://github.com/svg/svgo/files/2726743/icon_zoomin_black.txt)

Opening and saving the file with inkscape solves the issue.

Cheers,
Laszlo.

**Comment by GreLI** [comment]
File is broken XML: as it's says—“sodipodi” namespace isn't declared, so it breaks.

**Comment by JoKalliauer** [comment]
@oraslaci 

You need to add ` xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" ` in the `<svg`-tag

[icon_zoomin_black.svg.txt](https://github.com/svg/svgo/files/2752513/icon_zoomin_black.svg.txt)
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" style="enable-background:new 0 0 500 500" id="Layer_1" version="1.1" viewBox="0 0 500 500">
 <style type="text/css">
  .st0{fill:#FFFFFF;}
 </style>
 <g id="g5363" transform="translate(-26.7148 60.717)">
  <rect id="rect4825_1_" width="312" height="90.8" x="18.9" y="248.6" transform="matrix(.7071 -.7071 .7071 .7071 -156.666 209.741)"/>
  <path d="M96.7,438.3l-66.1-66.1L253,149.7l66.1,66.1L96.7,438.3z M34.3,372.2l62.3,62.3l218.7-218.7L253,153.5L34.3,372.2z"/>
  <path id="path4823_1_" d="m436.9 215.4c-52.2 52.2-136.8 52.2-189 0s-52.2-136.8 0-189 136.8-52.2 189 0 52.2 136.8 0 189z" class="st0" sodipodi:cx="329.658" sodipodi:cy="437.197" sodipodi:rx="73.584" sodipodi:ry="73.584" sodipodi:type="arc"/>
  <path d="m342.4 301.4c-46.3 0-92.5-17.6-127.7-52.8-70.4-70.4-70.4-185 0-255.4 34.1-34.1 79.5-52.9 127.7-52.9s93.6 18.8 127.7 52.9c70.4 70.4 70.4 185 0 255.4-35.2 35.2-81.5 52.8-127.7 52.8zm0-267.2c-23.2 0-44.9 9-61.3 25.4-33.8 33.8-33.8 88.8 0 122.6s88.8 33.8 122.6 0 33.8-88.8 0-122.6c-16.4-16.4-38.2-25.4-61.3-25.4z"/>
  <path id="rect5335_1_" d="m323.8 57.1v45.2h-45.2v37.1h45.2v45.2h37.1v-45.2h45.2v-37.1h-45.2v-45.2h-37.1z" inkscape:connector-curvature="0"/>
  <path d="m361.5 185.2h-38.2v-45.2h-45.2v-38.2h45.2v-45.2h38.2v45.2h45.2v38.2h-45.2v45.2zm-37.1-1.1h36v-45.2h45.2v-36h-45.2v-45.2h-36v45.2h-45.2v36h45.2v45.2z"/>
 </g>
</svg>
```
![icon_zoomin_black svg txt](https://user-images.githubusercontent.com/15687581/51078590-ca473000-16b7-11e9-8749-b5e94acea628.png)

**Comment by oraslaci** [comment]
Hey,
Thank you for your replies. I solved the problem with inkscape, by opening and saving the file. 
The file clearly has problem, but my main concern is rather, that svgo breaks the rest of the files in the folder, leaving them empty.
I think that should be adressed inside svgo.
Have a good one,
László.

**Comment by JoKalliauer** [comment]
Issue can be closed

**Comment by MichaelJCole** [comment]
Hi, I'd like to use svgo in an asset pipeline, but it is failing catastrophically with this error.

This is the command I'm using:

```
svgo \
  --pretty \
  --disable=removeViewBox \
  --enable=sortAttrs,removeDimensions  \
  -r \
  -f .
```

On the first run, it works.

On the second run, it failed with the OP's error.  

This command works on both runs:

```
svgo \
  --pretty \
  --disable=removeViewBox \
  --enable=removeDimensions  \
  -r \
  -f .
```

So I think this is masking a bug in `sortAttrs`.  I have 100s of SVG's so didn't search for the particular broken one.
