### ISSUE TITLE
SVGO minifying stripping out <g>

### ISSUE THREAD

**Issue by robcalcroft** [svg/svgo#1072]
I'm using parcel, and when im parsing the following, svgo is stripping out the `<g>` tag when I do a minified production build, is this a bug or is there some extra SVG attributes I need to add to ensure svgo doesn't strip anything out.

```svg
<svg class="rounded-top" preserveAspectRatio="none" height="50" viewBox="0 0 1440 40" xmlns="http://www.w3.org/2000/svg">
      <g>
        <defs>
          <filter id="glow">
            <fegaussianblur class="blur" result="coloredBlur" stddeviation="3.5"></fegaussianblur>
            <femerge>
              <femergenode in="coloredBlur"></femergenode>
              <femergenode in="coloredBlur"></femergenode>
              <femergenode in="coloredBlur"></femergenode>
              <femergenode in="SourceGraphic"></femergenode>
            </femerge>
          </filter>
        </defs>
        <path d="M0 30.013C239.659 10.004 479.143 0 718.453 0S1198.28 10.004 1440 30.013V40H0v-9.987z" fill="#FFF" fill-rule="evenodd"/>
      </g>
    </svg>
```

It outputs

```svg
<svg class="rounded-top" preserveAspectRatio="none" height="50" viewBox="0 0 1440 40"><path d="M0 30.013C239.659 10.004 479.143 0 718.453 0S1198.28 10.004 1440 30.013V40H0v-9.987z" fill="#FFF" fill-rule="evenodd"/></svg>
```

The SVG itself is a white shape so won't be easily viewable on a white background 😄

**Comment by Volker-E** [comment]
A useless `g` (useless as in not carrying any attributes) doesn't _provide anything_ for the visual rendering of the file in this case and can be removed without issue. It might have been inserted by SVG export library under a more generalized ruleset.
https://github.com/svg/svgo/blob/master/plugins/collapseGroups.js is your plugin you want to disable in case you want to leave the `g` element in.
