### ISSUE TITLE
collapseGroups not working with --disable=convertStyleToAttrs

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1073]
Prozessing [File:Capital not largest city.svg](https://commons.wikimedia.org/wiki/File:Capital_not_largest_city.svg)  with

$ svgo -i [Input.svg.txt](https://github.com/svg/svgo/files/2752476/Input.svg.txt) -o [Output.svg.txt](https://github.com/svg/svgo/files/2752477/Output.svg.txt) --pretty --indent=1 --disable=convertStyleToAttrs  --enable=collapseGroups

breaks the file.

Most likely related to https://github.com/svg/svgo/issues/1007

# Input
[Input.svg.txt](https://github.com/svg/svgo/files/2752476/Input.svg.txt)
![input](https://user-images.githubusercontent.com/15687581/51078103-5bb2a400-16b0-11e9-83b3-920683024267.png)

# Output
[Output.svg.txt](https://github.com/svg/svgo/files/2752477/Output.svg.txt)
![output](https://user-images.githubusercontent.com/15687581/51078105-64a37580-16b0-11e9-904a-15ee0bcf0a1c.png)

<details>

<summary>Copyright/Copyleft</summary>

Author: https://commons.wikimedia.org/wiki/User:NuclearVacuum

Lizense: {{self|cc-by-sa-3.0|GFDL}}

source: https://commons.wikimedia.org/wiki/File:Capital_not_largest_city.svg

</details>

**Comment by TrySound** [comment]
Looks like it's fixed already
