### ISSUE TITLE
SVGO strips styles

### ISSUE THREAD

**Issue by ossinkine** [svg/svgo#1077]
[svgs.zip](https://github.com/svg/svgo/files/2776583/svgs.zip)

Before.svg contains styles for shapes but after SVGO processing it does not contain them anymore and also shapes do not contain according attributes.

**Comment by popbee** [comment]
You can turn off the inline styles option to keep them. Worked with your example.
This tool does not work well with more complex CSS selectors when inlining styles.
Also I see the styles being stripped off (empty `<style>` block) only when both minify and inline are used together.

**Comment by strarsis** [comment]
@ossinkine, @popbee: Disabling the [`onlyMatchedOnce`](https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js#L8) option seems to be a workaround around this issue.
Hm, the `onlyMatchedOnce` apparently has a bug that causes loss of styles, 
the `cls-3` class in your example input SVG matches multiple time, hence it is affected.

**Comment by cneeson** [comment]
Neither of these approaches worked for me unfortunately. I am using `svgo` in combination with `rollup-plugin-react-svg` to export React component library SVGs. No matter what I try, the `styles` property always resolves as an empty object. (apologies, had to upload each of them as `txt` files as `js` and `svg` weren't supported)

Test case:
[before.txt](https://github.com/svg/svgo/files/3256730/before.txt)
[after.txt](https://github.com/svg/svgo/files/3256733/after.txt)
[rollup.config.txt](https://github.com/svg/svgo/files/3256744/rollup.config.txt)

**Comment by strarsis** [comment]
@cneeson: It is probable that the `svgo` options you set in webpack aren't passed to `svgo`.
Have you tried to disable some plugins or set some options and check whether this changes the output?

**Comment by cneeson** [comment]
@strarsis thanks for getting back. Think I have confirmed that the options aren't being passed to `svgo`, there are illustrator comments throughout the test SVG that are removed by `svgo`, even when I set the `removeComments` option to false.

**Comment by strarsis** [comment]
@cneeson: So you have to find out what part of your webpack setup doesn't pass the options to `svgo`.

**Comment by strarsis** [comment]
@ossinkine, @cneeson: Were you able to fix the issue?

**Comment by ossinkine** [comment]
@strarsis No, we just slightly modified the svgs so that svgo processes them correctly.

**Comment by alexeychikk** [comment]
I've disabled `inlineStyles` and `removeStyleElement` but style element still gets stripped.

**Comment by strarsis** [comment]
@alexeychikk: Are you sure that those plugins are really disabled?

**Comment by strarsis** [comment]
Stripped down SVG for reproducing the issue:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.49 35.68">
  <defs>
    <style>
      .wrapper.cls-1 {
        isolation: isolate;
      }

      .wrapper .some-stroke {
        stroke: #e8ce3a;
      }
    </style>
  </defs>
  <g class="wrapper cls-1">
    <polyline class="some-stroke" points="22.75 22.2 8.43 7.18 13.4 1.9 32.09 1.9 37.06 7.18 22.75 22.2 17.9 10.27 17.96 7.18"/>
    <polyline class="some-stroke" points="22.75 22.2 27.38 10.27 27.38 7.18"/>
  </g>
</svg>

````
