### ISSUE TITLE
svgo *.svg doesn't work

### ISSUE THREAD

**Issue by Roman52** [svg/svgo#1079]
Hello!
I can't understand why svgo *.svg doesn't work for me. 
svgo image.svg works, but svgo *.svg doesn't.
It gives an [error no such file or directory ...](http://joxi.net/bmobNVZu3MDMwr)

**Comment by GreLI** [comment]
I'm afraid that's Windows issue. Usually shell passes all svg filenames.

**Comment by grig0ry** [comment]
Use Git Bash on Windows.

**Comment by Roman52** [comment]
@grig0ry git bash works, thank you!

**Comment by kylemh** [comment]
I'm seeing this issue on a Mac using SVGO in conjunction with `lint-staged`.

`yarn svgo *.svg --pretty --config=svgo.config.format.json`

```Error: Error: no such file or directory '*.svg'.```

**Comment by kylemh** [comment]
Looks like on v10 of lint-staged you'll just wanna do:

```js
"**/*.svg": [
  "svgo"
]
```

(plus whatever flags, but no file or folder targeting)
