### ISSUE TITLE
Ellipses not converted with option enabled

### ISSUE THREAD

**Issue by buisine** [svg/svgo#1086]
Hi,

    svgo --version
    1.2.0
looklike ellipse element are not converted to paths

made test on commande line like :

➜ svg svgo --enable=convertShapeToPath 1.svg

➜ svg svgo --enable=convertShapeToPath --config=conf.json --pretty 1.svg

with config.json having { "convertArcs": true }

also tried :

    {
      "pretty": true,
      "multipass": true,
      "floatPrecision": 2,
      "plugins": [
        {
          "name": "convertShapeToPath",
          "enabled": true,
          "params": {
            "convertArcs": true
          }
        }  
      ]
    }

**Comment by GreLI** [comment]
`plugins` array in config has different format. Like:
"plugins": [
    { "convertShapeToPath": { "convertArcs": true } }  
  ]
