### ISSUE TITLE
The js-yaml dependency are vulnerable

### ISSUE THREAD

**Issue by mhsalves** [svg/svgo#1088]
The audits are showing a vulnerability in the version under 3.13.0 of `js-yaml` which need be updated

![image](https://user-images.githubusercontent.com/30807170/54790763-a94a1080-4c0d-11e9-8be5-7c47b66976be.png)

I'm using a process of deploy which needs all security vulnerabilities is 0 and i'm using a lib which use yours.

<details>
<summary>Vulnerability of lib i'm using</summary>

![image](https://user-images.githubusercontent.com/30807170/54791850-08118900-4c12-11e9-8965-991044b5f037.png)

</details>

**Comment by eugestarr** [comment]
Submitted a PR with fix

**Comment by muescha** [comment]
PR merged...
