### ISSUE TITLE
xml space preserve whitespace

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1095]
Prozessing [File:Battle_of_Baghuz_(2019)-ar.svg](https://commons.wikimedia.org/wiki/File:Battle_of_Baghuz_(2019)-ar.svg) adds to wrong spaces

svgo -i [Input.svg.txt](https://github.com/svg/svgo/files/3076674/Input.svg.txt) -o [Output.svg.txt](https://github.com/svg/svgo/files/3076675/Output.svg.txt) --pretty --indent=1  --disable=removeUnknownsAndDefaults

This issue might be related to #522 , #591 , #634 , #878 , #1001 , #1029 , 

# Input
[Input.svg.txt](https://github.com/svg/svgo/files/3076674/Input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg font-family="DejaVu Sans, sans-serif, Sans" font-size="20" viewBox="0 0 120.45 20" xmlns="http://www.w3.org/2000/svg">
 <text x="-1.37" y="15.2" xml:space="preserve">مدينة   الخيام</text>
</svg>

```

![Input](https://user-images.githubusercontent.com/15687581/56084687-f39e6600-5e36-11e9-8daf-0cf4d7f7219b.png)

# Output
[Output.svg.txt](https://github.com/svg/svgo/files/3076675/Output.svg.txt)
```svg
<svg font-family="DejaVu Sans, sans-serif, Sans" font-size="20" viewBox="0 0 120.45 20" xmlns="http://www.w3.org/2000/svg">
<text x="-1.37" y="15.2">مدينة الخيام</text
</svg>

```

![Output](https://user-images.githubusercontent.com/15687581/56084686-eda88500-5e36-11e9-89bf-50ecb42a8038.png)

----
<details>
<summary>Copyright of the picture</summary>

License: [cc-by-sa-4.0](https://creativecommons.org/licenses/by-sa/4.0)

Author: Original: {{U|Rr016}} / *Derivative: {{U|باسم}}

Details (and Source): https://commons.wikimedia.org/wiki/File:Battle_of_Baghuz_(2019)-ar.svg

</details>

**Comment by GreLI** [comment]
Yeah, it's duplicate and unlikely will be supported in near future, since it's a parser issue.
