### ISSUE TITLE
js-yaml vulnerable dependency strikes again

### ISSUE THREAD

**Issue by kaungst** [svg/svgo#1099]
Looks like it needs to be bumped to >= 3.13.1

https://www.npmjs.com/advisories/813

<img width="720" alt="Screen Shot 2019-04-15 at 4 40 21 PM" src="https://user-images.githubusercontent.com/2354132/56172222-48f48780-5f9d-11e9-92e7-2d86ac3f7491.png">

**Comment by GreLI** [comment]
Fixed in v1.2.2.
