### ISSUE TITLE
convertTransform not always converting matrix properly (version 1.2.2)

### ISSUE THREAD

**Issue by stevebrisebois** [svg/svgo#1101]
Attached source file and resulting file for reproduction: 
[sourceAndTarget.zip](https://github.com/svg/svgo/files/3099383/sourceAndTarget.zip)

Original transform is "matrix(-0.10443115234375 0 0 -0.10443115234375 182.15 61.15)"
Resulting transform is "translate(182.15 61.15) scale(.10443)"

Is seems like matrix "translate(182.15 61.15) rotate(180) scale(.10443)" is working.

**Comment by GreLI** [comment]
Nice catch! Thanks for reporting.

**Comment by GreLI** [comment]
SVGO v1.3.0 with the fix is released.
