### ISSUE TITLE
svgo "background: none" transform

### ISSUE THREAD

**Issue by balajmarius** [svg/svgo#1102]
Runing svgo on

```svg
<svg style="background: none" />
```
Will return 

```svg
<svg style="background: 0 0" />
```

Any idea how I can prevent this behavior?

**Comment by strarsis** [comment]
@balajmarius: Looks like CSS minification, you could try to disable the [minifyStyles plugin](https://github.com/svg/svgo/blob/master/plugins/minifyStyles.js) or [pass CSSO options](https://github.com/svg/svgo/blob/master/plugins/minifyStyles.js#L10) for disabling optimization of `background` (https://github.com/css/csso#compressast-options).
