### ISSUE TITLE
Replace xlink:href with href

### ISSUE THREAD

**Issue by nikkwong** [svg/svgo#1103]
Hi, I was wondering if anyone knew a good way to change `xlink:href` attribute to `href`. I am working with some plugins that are buggy with `xlink:href` support but have great `href` support. What would be the best way to do this? Thanks.

**Comment by GreLI** [comment]
SVGO doesn't save in SVG 2 yet due to lack of its support. However, it can already parse some parts from SVG 2 like some new properties or prefixless `href` attribute.

Such an optimization is totally possible, though it has to be optional one. A PR would be welcome.

**Comment by nikkwong** [comment]
Thanks for the response. Would it be naive to just do a blind replace? I realize SVG is complicated so I'm not sure if there are some considerations to take into account here.  `svgString.replace(new RegExp('xlink:href', 'g'), 'href');`

**Comment by GreLI** [comment]
Well, it's not perfect (I'd added at least `\b` at the start and at the end), but in 99% it would be ok, I think.

**Comment by nikkwong** [comment]
Sweet. Thanks for the help and awesome library.

**Comment by itayox** [comment]
I've written a very basic plugin to handle this case if it helps anyone..

```javascript
'use strict';

exports.name = 'removeXlink';
exports.type = 'visitor';
exports.active = true;
exports.description = 'remove "xlink:" prefix from attributes';

exports.fn = () => {
  return {
    element: {
      enter: node => {
        for (const name of Object.keys(node.attributes)) {
          if (name === 'xlink:href') {
            node.attributes['href'] = node.attributes[name];
            delete node.attributes['xlink:href'];
          }
        }
      },
    },
  };
};
```
