### ISSUE TITLE
[BUG] inkscape --disable=removeEditorsNSData without  --disable=removeUnusedNS removes xmlns:inkscape; Error in parsing SVG: Unbound namespace prefix: "inkscape"

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1107]
Processing [File:Test.svg](https://commons.wikimedia.org/wiki/File:Test.svg) with ` --disable=removeEditorsNSData` leads to a damaged file and `--disable=removeEditorsNSData --multipass` leads to an error:
`Error in parsing SVG: Unbound namespace prefix: "inkscape"`

 svgo -i $[Input.svg.txt](https://github.com/svg/svgo/files/3195108/Input.svg.txt) -o [Output.svg.txt](https://github.com/svg/svgo/files/3195109/Output.svg.txt) --pretty --indent=1 --disable=removeXMLProcInst --disable=removeDoctype  --disable=removeEditorsNSData --multipass

## Input
[Input.svg.txt](https://github.com/svg/svgo/files/3195108/Input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="620" height="472" inkscape:version="0.92.2 (5c3e80d, 2017-08-06)" sodipodi:docname="20190401041014!Test2.svg" font-size="180" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd">
 <text x="59.49" y="174.47">TEST</text>
</svg>
```

## Output
[Output.svg.txt](https://github.com/svg/svgo/files/3195109/Output.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="620" height="472" inkscape:version="0.92.2 (5c3e80d, 2017-08-06)" sodipodi:docname="20190401041014!Test2.svg" font-size="180">
 <text x="59.49" y="174.47">
  TEST
 </text>
</svg>
```

## Solution
disable removing of `xmlns:` when `--disable=removeEditorsNSData` is used

<details>

<summary>Copyright</summary>

license: Public Domain
Author: unknown
source: https://commons.wikimedia.org/wiki/File:Test.svg

</details>

**Comment by GreLI** [comment]
Turns out it's a bug in `removeUnusedNS`

**Comment by JoKalliauer** [comment]
@GreLI : I updated with `npm install -g svgo` but this issue still occours. How can I install this newest version?

**Comment by GreLI** [comment]
SVGO v1.3.0 with the fix is released.

**Comment by JoKalliauer** [comment]
Thanks! I can confirm the issue is fixed.
