### ISSUE TITLE
[Feature Request] Plugin to remove CSS variables

### ISSUE THREAD

**Issue by Kerndog73** [svg/svgo#1108]
CSS variables are supported by web browsers so if an SVG that uses CSS variables is displayed in a browser, it will look fine. However, if the SVG is given to an SVG editing program (like Inkscape for example), the stylesheet won't be parsed (because of the `--`). CSS variables aren't part of standard SVG. They're an extension provided by web browsers.

Removing CSS variables while still ensuring that the resulting SVG looks the same is not a trivial task (unless there's a similar feature in SVG that I'm not aware of). It will make the resulting file larger but also make it more compatible with programs that aren't web browsers. I'm currently in the process of doing this by hand and it would be awesome if there was a tool that did it for me!

**Comment by strarsis** [comment]
@Kerndog73: [`postCSS`](https://github.com/MadLittleMods/postcss-css-variables) comes to mind, the SVG styles could be just passed to it for processing. 
CSS variables in inline styles are possible, too, so these have to be interpolated, too (even before using postcss on the external/element styles).

**Comment by Kerndog73** [comment]
@strarsis Looks good! This sort of thing probably doesn’t make sense for svgo because CSS variables are just a way of avoiding a big copy-and-paste in *hand-written* SVGs. Editors don’t use them.
