### ISSUE TITLE
SVG convert style inline

### ISSUE THREAD

**Issue by ciarlystreet** [svg/svgo#1110]
I'm trying to put the style of a svg inline. With node.js svgo tool you can do it with the command:
```
svgo path/to/file.svg --enable=inlineStyles  --config '{ "plugins": [ { "inlineStyles": { "onlyMatchedOnce": false } }] }' --pretty
```

I created this php script for do it:
```
require __DIR__ . '/vendor/autoload.php';
use Spatie\ImageOptimizer\OptimizerChain;
use Spatie\ImageOptimizer\Optimizers\Svgo;
 $optimizerChain = (new OptimizerChain)
            ->addOptimizer(new Svgo([
                '--enable=inlineStyles',
                '--config \'{ "plugins": [ { "inlineStyles": { "onlyMatchedOnce": false } }] }\'',
                '--pretty'
            ]));
$optimizerChain->optimize('path/to/file.svg');
```

but the svg generated is same to original.
Can you help me to find and understand the error?

**UPDATE:**
I implemented the logs that return the following error:
name.ERROR: Process errored with `sh: svgo: command not found ` 
but if I open the terminal and enter svgo, the command works as expected.

**Comment by strarsis** [comment]
@ciarlystreet: When commands are entered into shell, a binary/executable with that name is searched through all paths in the `PATH` environment variable (which is set at shell startup, it can also differ from shell to shell and user to user).
Using a PHP script, the `PATH` environment variable can be different than to what is set for the shell or not set at all.
You can find out the complete absolute path to the `svgo` executable by using the command `which svgo` on your shell.

You can use the absolute path to `svgo` in your PHP script.
However, to make this more robust you may want to look into a way of finding the `svgo` with proper version, or installing it with the optimizer project instead just hardcoding it for a particular server.

**Comment by GreLI** [comment]
Seems like not a SVGO question.
