### ISSUE TITLE
Remove elements outside of inkscape page

### ISSUE THREAD

**Issue by wclr** [svg/svgo#1116]
svgo 1.2.2

I have the folloing svg drawing in inkscape:

![image](https://user-images.githubusercontent.com/736697/58890887-eac66400-8704-11e9-99b3-8bf0b2bf0801.png)

Here is input svg file content:
https://gist.github.com/whitecolor/f2a7561e8224ded0a88765f52431b694

I want an element that is outside "the page" be removed from resulting file, I tried configure as
```
 plugins: [
    { removeHiddenElems: true },
    { removeOffCanvasPaths: true }
]
```
Also tried:
```
svgo t-shirt.svg -o output.svg --enable=removeOffCanvasPaths --enable=removeHiddenElems
```

But it doesn't remove "woman's t-shirt" in this file is not removed in the output.

**Comment by whitecolor** [comment]
@JoshyPHP
Hey, as the author of `removeOffCanvasPaths` plugin do you have any suggestions?

**Comment by hugolpz** [comment]
@whitecolor, @JoshyPHP did you find a way ? I do the same, no success. My command and test files 

```bash
node ./node_modules/svgo/bin/svgo --enable=removeOffCanvasPaths --pretty --input=./mini.svg --output=./out.svg
``` 

![Screenshot_2020-09-29_23-15-01](https://user-images.githubusercontent.com/1420189/94617294-9fe14000-02a9-11eb-9df3-bf497dad6ee1.png)

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="48"
   height="48"
   viewBox="0 0 12.7 12.7"
   version="1.1"
   id="svg8">
  <rect
     y="1.3607056"
     x="-9.0714226"
     height="6.8035717"
     width="14.906703"
     id="rect815"
     style="opacity:1;fill:#008000;fill-opacity:1;stroke:none;stroke-width:0.02408044;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1" />
  <path
     id="rect826"
     d="M 7.929864,2.12516 H 24.671239 V 6.63539 H 7.929864 Z"
     style="opacity:1;fill:#008000;fill-opacity:1;stroke:none;stroke-width:0.02077783;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1" />
  <path
     style="opacity:1;fill:#008000;fill-opacity:1;stroke:none;stroke-width:0.00729558;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1"
     d="m 26.658799,2.12516 h 2.064006 v 4.51023 h -2.064006 z"
     id="path838" />
  <path
     style="fill:none;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
     d="M 3.2826272,9.7940676 1.7758474,11.569915"
     id="path828"/>
  <path
     style="fill:none;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
     d="M 5.865678,11.462288 4.143644,14.422034"
     id="path830" />
  <path
     style="fill:none;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
     d="M 10.116949,13.776271 8.4487286,17.274152"
     id="path832" />
</svg>
```

**Comment by JoshyPHP** [comment]
That's the first time I see this issue, I must have missed the notification. The solution for the SVG in the original issue is to disable `mergePaths`. First you optimize with `removeOffCanvasPaths` enabled and `mergePaths` disabled, then you can optimize it again with the default settings.

**Comment by hugolpz** [comment]
@JoshyPHP : Hi, you went faster than me ! I continued digging and made a run with ALL plugins off, and `--enable=removeOffCanvasPaths`. It works better. I'am moving toward the same conclusion as you (testing within minutes.)

**Comment by hugolpz** [comment]
@GreLI : **Closed please.** I consider this issue solved and ready to be closed.

Also, please add trusted PR contributors as owners. The project is inactive for past 10 months despite numerous pull requests. Open project periodically need new contributors, please welcome them.

**Comment by hugolpz** [comment]
@GreLI : please delegate SVGO management to active contributors.

**Comment by hugolpz** [comment]
@TrySound: Hello, thanks for closing that. I'am retesting this solution and SVGO had so many update that the shell commands cited [above][https://github.com/svg/svgo/issues/1116#issuecomment-701009682] doesnt work. I will dig into this this next 2 hours. But given you are online, if you know the new command syntax to use on the top of the head, feel free to short-circuit my digging and post the answer here. 👍🏼

**Comment by TrySound** [comment]
`--enable` and `--disable` were removed in v2. You can use preset-default preset to disable plugins.

**Comment by hugolpz** [comment]
I'am finding my way indeed. It's cool to see this project rolling again, thank you & the team : )

**Comment by hugolpz** [comment]
Ok. I got it working. And I would like to improve your readme.md. Both for clarity, and to state that plugin declaration order in the config file matters. I will make a pull request.
