### ISSUE TITLE
Update dependency js-yaml version to >=3.13.1 

### ISSUE THREAD

**Issue by donLucho** [svg/svgo#1119]
Hi. 

Pursuant to two advisories (https://npmjs.com/advisories/788 and https://npmjs.com/advisories/813 ), I would like to respectfully request that you update a dependency found in svgo as it relates to js-yaml. Apparently, if the version of js-yaml is updated to a version that is greater than or equal to 3.13.1 ( >=3.13.1 ), in an ideal world both of the aforementioned advisories should be cured. 

Thanks in advance.

p.s. I ran an npm audit and the path field indicated that svgo is the vulnerable package: 
gulp-cssnano > cssnano > postcss-svgo > svgo > js-yaml

**Comment by flakeparadigm** [comment]
The dependency has been updated in the `package.json`, however there has not been a new release created. As soon as a new release is made to npm, then it should be fixed.

**Comment by flakeparadigm** [comment]
The vulnerability seems to have been fixed in the latest versions of this library and all the way up through cssnano. I suspect the issue is that you're using `gulp-cssnano` in the first place, which is no longer maintained (https://github.com/ben-eb/gulp-cssnano), and will likely never be updated to use newer versions of cssnano.

**Comment by donLucho** [comment]
Hey, @flakeparadigm! I wanted to say thank you for the advice. It was golden! My project(s) required a few changes in workflow and in the end the project(s) worked just fine, too. Ta!

**Comment by paoga87** [comment]
> The vulnerability seems to have been fixed in the latest versions of this library and all the way up through cssnano. I suspect the issue is that you're using `gulp-cssnano` in the first place, which is no longer maintained (https://github.com/ben-eb/gulp-cssnano), and will likely never be updated to use newer versions of cssnano.

@flakeparadigm do you have a recommendation on an alternative tool to replace `gulp-cssnano`?

**Comment by flakeparadigm** [comment]
@paoga87 No, I don't really have any recommendations as I've moved away from using gulp. Sorry.

**Comment by paoga87** [comment]
> @paoga87 No, I don't really have any recommendations as I've moved away from using gulp. Sorry.

No problem. I used gulp-clean-css instead and that solved my issues. Do you mind sharing what you're using now, instead of gulp?
