### ISSUE TITLE
Forcing absolute paths does not work

### ISSUE THREAD

**Issue by Webbmekanikern** [svg/svgo#1123]
## Command
```
svgo --disable=cleanupIDs,removeViewBox,convertStyleToAttrs,inlineStyles,mergePaths,moveElemsAttrsToGroup,moveGroupAttrsToElems,collapseGroups --enable=removeXMLNS --config='{"convertArcs":true,"forceAbsolutePath":true}' --input='input.svg' --output='output.svg'
```

## Expected result
An SVG where all paths are absolute (e.g. no lowercase "m").

## Actual result
No paths are absolute, like it is ignoring the `forceAbsolutePath` option.

**Comment by GreLI** [comment]
There is no `forceAbsolutePath` option.

**Comment by Webbmekanikern** [comment]
So what is this?

https://github.com/svg/svgo/blob/580063522638e9e301d32effa7035a577db96354/plugins/convertPathData.js#L26

**Comment by GreLI** [comment]
Oh, that's quite recent. Your config is incorrect. You should pass an option to the plugin. Like
```json
{"plugins": ["convertArcs",{"convertPathData": {"forceAbsolutePath": true}}]}
```

**Comment by Webbmekanikern** [comment]
Ah okay - thanks for this. Why doesn't `convertArcs` need that kind of config?

https://github.com/svg/svgo/blob/54f92ce2deccdbd3177b711b06aa0cf928039c4c/plugins/convertShapeToPath.js#L10

**Comment by GreLI** [comment]
It does. Why do you think so?

**Comment by Webbmekanikern** [comment]
I assumed that from your example (and my current code), but I noticed now that `convertArcs ` didn't work either, haha. Now it works:

```
svgo --disable='cleanupIDs,removeViewBox,convertStyleToAttrs,inlineStyles,mergePaths' --enable='removeXMLNS' --config='{"plugins":[{"convertShapeToPath":{"convertArcs":true}},{"convertPathData":{"forceAbsolutePath":true}}]}' --input='input.svg' --output='output.svg'
```

Thanks a lot for your help and impressive response time. Maybe we should add a config example in the `README.md`?
