### ISSUE TITLE
Modifying ids and not modifying classes does not work

### ISSUE THREAD

**Issue by marlebsie** [svg/svgo#1129]
Is it possible to generate unique ids without changing classes while having cleanupIDs plugin enabled?

The config below does modify ids and does not modify classes. However id collisions occur when importing the same file twice.
```
svgoConfig: {
              plugins: [
                {
                  prefixIds: {
                    prefixIds: true,
                    prefixClassNames: false,
                  }
                }
              ]
            }
```
The config below provides unique ids. The problem is that it also modifies class names, which is very unexpected (is it a bug or a feature?).
```
svgoConfig: {
              plugins: [
                {
                  cleanupIDs: {
                    prefix: {
                      toString() {
                        this.counter = this.counter || 0;

                        return `_${this.counter++}`;
                      }
                    },
                  },
                  prefixIds: {
                    prefixIds: true,
                    prefixClassNames: false,
                  }
                }
              ]
            }
```
adding ``` minify: false ``` to cleanupIDs does not change anything

Any cleanupIDs configuration (except turned off) results in modification of class names. Is it possible to avoid it (like in prefixIds)?

**Comment by marlebsie** [comment]
i acheved the wanted effect like this:
```
            svgoConfig: {
              plugins: [
                {
                  prefixIds: {
                    delim: {
                      toString() {
                        this.counter = this.counter || 0;

                        return `_c${this.counter++}_h${hash(relative(context, resource))}_`;
                      }
                    },
                    prefixIds: true,
                    prefixClassNames: false,
                  }
                }
              ]
            }
```
But it does not change the fact that cleanupIDs always change class names

**Comment by alanmcginnis** [comment]
This one has me baffled as well. I have tried quite a few different configs and my class names always get prefixed with a,b,c,etc...
