### ISSUE TITLE
Remove width & height

### ISSUE THREAD

**Issue by gelisil** [svg/svgo#1141]
Removing this 2 parameters every image will be responsive in the browser.   
width="10in"
height="13.093749in"
Can we create a specific plugin for this issue?
Or maybe exist one and i don t know  what is the plugin required?

**Comment by strarsis** [comment]
@gelisil: [removeDimensions](https://github.com/svg/svgo/blob/master/plugins/removeDimensions.js) plugin. It is disabled by default, so you have to explicitly enable it.

**Comment by XhmikosR** [comment]
@TrySound this might be invalid being that it should be possible to achieve what the OP is asking with `removeDimensions`
