### ISSUE TITLE
Issue on React App deployment

### ISSUE THREAD

**Issue by Sanyaorg** [svg/svgo#1174]
Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined

**Comment by larsonjj** [comment]
Having the same issue. Looks like v1.3.1 is breaking builds.
CC @GreLI  ^

**Comment by Sanyaorg** [comment]
Temp fix: Just rollback to  "svgo": "1.3.0" (add to package.json file)

**Comment by jsphstls** [comment]
Related:
https://github.com/svg/svgo/issues/1174

**Comment by BrianHVB** [comment]
> Related:
> #1174

@jsphstls  This **is** issue #1174 --- did you mean to link to a different issue?

**Comment by asherstoppard** [comment]
Issue's stemming from https://github.com/svg/svgo/blob/58232a323adc03450211f5e6b5aed025af72224b/lib/svgo.js#L41.

Adding `info = {}` sticky plaster seems to solve the error.

**Comment by montydhanjal** [comment]
> Issue's stemming from
> 
> https://github.com/svg/svgo/blob/58232a323adc03450211f5e6b5aed025af72224b/lib/svgo.js#L41
> 
> Adding `info = {}` sticky plaster seems to solve the error.

`// info.multipassCount = counter;
                info = {}`

This fix does resolve my issue but I am using this as a build-in Create React App feature. As soon as i yarn install, this issue will come back. It's a temporary fix.

**Comment by BrianHVB** [comment]
> > Issue's stemming from
> > https://github.com/svg/svgo/blob/58232a323adc03450211f5e6b5aed025af72224b/lib/svgo.js#L41
> > 
> > Adding `info = {}` sticky plaster seems to solve the error.
> 
> `// info.multipassCount = counter; info = {}`
> 
> This fix does resolve my issue but I am using this as a build-in Create React App feature. As soon as i yarn install, this issue will come back. It's a temporary fix.

you need to pin a specific version ... try
```
yarn remove svgo
yarn add svgo@1.3.0
```

or just manually edit your yarn.lock or package.json file
```

**Comment by johndevedu** [comment]
Can anyone confirm that this fix works? Tried @BrianHVB 's solution
```
yarn remove svgo
yarn add svgo@1.3.0
```
But still getting same error.

**Comment by dshanley** [comment]
@johndevedu I'm still getting the issue -- even with pegging the version to 1.3.0. Looking in node_modules/svgo.js where multipass is referenced, I don't see how this is still generating the error.

**Comment by kykint** [comment]
Same problem while using gulp-svgmin

**Comment by johndevedu** [comment]
Yeah @dshanley looking at the commit for 1.3.0, all that's changed is the README.md and other package dependencies. Thanks for confirming.

**Comment by kykint** [comment]
But with 1.3.0 everything is fine

**Comment by fmolina24** [comment]
For people using yarn add this to your package.json
`"resolutions": {
	  "svgo": "1.3.0"
  }`

**Comment by montydhanjal** [comment]
> For people using yarn add this to your package.json
> `"resolutions": { "svgo": "1.3.0" }`

This resolved my issue. Using CRA. Thanks

**Comment by ievgenk** [comment]
Had to do this with eslint not too long ago. The solution above works thanks!

**Comment by frolad** [comment]
react-svg-loader package is also affected, temporary adding "svgo": "1.30" to the package.json works fine

**Comment by sidharthachatterjee** [comment]
Also seeing this over at https://github.com/gatsbyjs/gatsby

**Comment by rafaeldsousa** [comment]
> > For people using yarn add this to your package.json
> > `"resolutions": { "svgo": "1.3.0" }`
> 
> This resolved my issue. Using CRA. Thanks

Not using yarn, but worked fine for with npm
https://github.com/rogeriochaves/npm-force-resolutions

**Comment by msurguy** [comment]
Seeing this error in Vue / Nuxt.js deployments as well due to CSSNano package using SVGO

**Comment by aaronblondeau** [comment]
To get nuxt builds to work I used the "resolutions" fix from above.  However, instead of using a global version of nuxt, I had to add nuxt as a dependency and run it via yarn so that it too would follow the resolutions and use the older version of svgo

`yarn nuxt build`

**Comment by Cherry** [comment]
I've submitted a PR at https://github.com/svg/svgo/pull/1176 which resolves this issue. 
Until this is merged and released, as others have said, simply pin `svgo` to `1.3.0` or earlier.

**Comment by dazjavier** [comment]
Seeing this at NextJS too. 

> For people using yarn add this to your package.json
> `"resolutions": { "svgo": "1.3.0" }`

This solved the issue though.

**Comment by tichuot** [comment]
remove `svgo` and reinstall `svg@1.3.0` not solved my problem

**Comment by joe223** [comment]
The new version svgo@1.3.1 which released few hours ago cause this problem. Just need to rollback to 1.3.0 and your trouble will be gone.

**Comment by fengerzh** [comment]
> "resolutions": { "svgo": "1.3.0" }

Add this line in `package.json`, then `rm -rf node_modules`, `rm -rf yarn.lock`, then `yarn` to reinstall everything.

**Comment by gengengengengen** [comment]
> > "resolutions": { "svgo": "1.3.0" }
> 
> Add this line in `package.json`, then `rm -rf node_modules`, `rm -rf yarn.lock`, then `yarn` to reinstall everything.

I am using gatsby and met this problem. 
The version of "svgo" is 1.3.0 and works well in my local environment but can't build when deploy to remote server (Cloud Foundry).

**Comment by johnnymillergh** [comment]
Now not only this error happens during React deployment but also happens Vue deployment. Same error message. This is how I solved this issue.

1. Add svgo@1.3.0 in dependencies, package.json
   ```json
   "dependencies": {
     ...
     "svgo": "1.3.0"
   },
   ```

2. Add following statement in package.json

   ```json
   "resolutions": {
     "svgo": "1.3.0"
   }
   ```

3. Done.

Hope this will help you guys who facing this issue as well. 😁

**Comment by namhbnam** [comment]
`"resolutions": {
  "svgo": "1.3.0"
}`
done

**Comment by Gastonite** [comment]
better fix, donot use svgo anymore

**Comment by Gastonite** [comment]
using pnpm, the fix is not a fix, 
so i found a better solution: do not use svgo

**Comment by Gastonite** [comment]
![multipass](https://i.ibb.co/vDxcGx8/1461710295153317889.jpg "Multipass !")

**Comment by rakibtg** [comment]
![BZeYaKO](https://user-images.githubusercontent.com/5412730/67849111-26d4e800-fb30-11e9-8d78-2baced463451.jpg)

**Comment by abdennour** [comment]
Oops! What's a nightmare you did guys 😭
But fixed...😄!
I am DevOps release engineer designing CI/CD of a lot projects. 
Happy it works and thanks for https://github.com/svg/svgo/issues/1174#issuecomment-547658450

**Comment by SecondeJK** [comment]
For Nuxt 2:
pushing svgo down to 1.3.0 via resolutions doesn't result in a build.

Now getting:
`Error: Cannot find module 'css-tree'`
instead.

**Comment by jantimon** [comment]
@SecondeJK you don't have to revert svgo to 1.3.0 anymore - your error is probably unrelated

**Comment by SecondeJK** [comment]
@jantimon thanks - realised it's because I last pulled node modules when it was still a problem. Deleted lock, reinstalled, Nuxt happy with building.

**Comment by kilegalloway** [comment]
https://icetutor.com/question/postcss-svgo-typeerror-cannot-set-property-multipasscount-of-undefined-gatsby/

**Comment by zalmantyrone** [comment]
"resolutions": { "svgo": "1.3.0" }

Add the above to your “package.json” and then rm -rf node_modules to remove “node_modules” and then reinstall “node_modules” again.

This will resolve issue. This issue is related to latest version of postcss-svgo

Full Answer With source code and example at [here](https://icetutor.com/question/postcss-svgo-typeerror-cannot-set-property-multipasscount-of-undefined-gatsby/)
