### ISSUE TITLE
Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined

### ISSUE THREAD

**Issue by happyPanghu** [svg/svgo#1180]
there is bug in 1.3.1 ,but work well in 1.3.0

**Comment by arnorb** [comment]
Same bug as #1179

**Comment by mnlmaier** [comment]
temporary fix provided here: https://github.com/svg/svgo/issues/1174#issuecomment-547760356

**Comment by happyPanghu** [comment]
> there is bug in 1.3.1 ,but work well in 1.3.0

wow~   now  is 1.3.2 ~  fixed!
