### ISSUE TITLE
Optimizing "%s" with SVGO failed with error "%s"

### ISSUE THREAD

**Issue by ylokesh** [svg/svgo#1181]
We are using "gulp-svg-sprite" package where SVGO is one of the sub-dependency. Since last day, while doing the build we are getting following error:

Optimizing "%s" with SVGO failed with error "%s"

Looks like this issue came to surface with latest minor upgrade i.e. 1.3.1

Can you please help us resolving this issue? or suggest an interim resolution.

Package.json
"gulp-svg-sprite": "^1.4.0"

Thanks in advance.

<img width="500" alt="Screenshot 2019-10-30 at 5 02 12 PM" src="https://user-images.githubusercontent.com/3806368/67856551-cf884500-fb3a-11e9-91c0-026263b9bae3.png">

**Comment by eballeste** [comment]
fixed in 1.3.2

**Comment by ylokesh** [comment]
@eballeste Thanks for the update but after updating the version in package.json to 1.3.2, it shows that no matching version found. 

Any suggestions why it is happening?

_**Package.json**_
"svgo":"1.3.2"

**_Error:_**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for svgo@1.3.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'd2-ui-automation'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     /var/go/.npm/_logs/2019-10-30T17_19_35_915Z-debug.log

**Comment by eballeste** [comment]
`npm i svgo:1.3.2`

https://www.npmjs.com/package/svgo

**Comment by ylokesh** [comment]
Same package.json, now tried setting up version to "1.3.0" or "1.3.1" and it worked with both. 
How come it is not working only with "1.3.2". Am i missing anything? Curious.

@eballeste Suggested fix `npm i svgo:1.3.2 `resulted into following error:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "svgo:": svgo:1.3.2

**Comment by ylokesh** [comment]
@eballeste Turned out to be an issue with our nexus repository cache. It's working now. Thanks a lot for your support.

**Comment by Askattaalaibekov** [comment]
same problem  1.5.0
