### ISSUE TITLE
SVGO messes SVGs 

### ISSUE THREAD

**Issue by Hlsgs** [svg/svgo#1183]
I'm using SVGO though "grunt-contrib-imagemin". I've reverted to an earlier package.json and package-lock.json that installs SVGO 1.2.2 and everything is fine, so the regression must have creeped up after that version.

Here is an example before/after that was already optimized multiple times with no issue with versions <= 1.2.2. Now I just ran my build process with 1.3.2 and it got ruined:

Before:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 111.946 75.259"><path id="img" d="M262.946 1229.358H151V1154.1h111.946zm-9.328-65.846h-93.29v37.622l23.322-23.517 27.841 26.018 21.137-18.8 20.99 19.43zm0 51.727l-21.141-18.946-20.844 18.946-28.123-26-23.176 23.37v7.341h93.29v-4.706zm-41.981-23.5a9.407 9.407 0 1 1 9.329-9.412 9.444 9.444 0 0 1-9.329 9.409z" transform="translate(-151 -1154.099)" fill="#fff" fill-rule="evenodd"/></svg>
```

After:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 111.946 75.259"><path id="img" d="M262.946 1229.358H151V1154.1h111.946zm-9.328-65.846h-93.29v37.622l23.322-23.517 27.841 26.018 21.137-18.8 20.99 19.43zm0 51.727l-21.141-18.946-20.844 18.946-28.123-26-23.176 23.37v7.341h93.29v-4.706zm-41.981-23.5a9.407 9.407 0 119.329-9.412 9.444 9.444 0 01-9.329 9.409z" transform="translate(-151 -1154.099)" fill="#fff" fill-rule="evenodd"/></svg>
```

The problem seems to be changing `9.407 0 1 1 9.329-9.412` to `9.407 0 119.329-9.41`

Thank you!

**Comment by GreLI** [comment]
What viewer do you use? It's a valid optimization, introduced in v1.3. Whitespace is optional after `arcto` flags, it's in SVG 1 specification. However, as always, you can turn it off as described in https://github.com/svg/svgo/issues/1137#issuecomment-517738958.

**Comment by Hlsgs** [comment]
You are correct in assuming modern viewers(Firefox, Chrome) view the result properly, but up to date Illustrator outright fails to understand the optimized result(you can check the example I gave). Does Illustator have a non-conformant SVG engine?

Regardless, I've disabled this optimization and everything is fine with my projects, so thank you for pointing me in that direction.
