### ISSUE TITLE
How to use cleanupIDs and removeElementsByAttr in conjunction?

### ISSUE THREAD

**Issue by denchen** [svg/svgo#1192]
I was trying to figure out why my usage of `removeElementsByAttr` wasn't working:

```javascript
const svgo = new SVGO({
  multipass: true,
  plugins: [
    { removeElementsByAttr: { id: ['invisible_box'] } },
  ]
});
```

And then I realized that `cleanupIDs` is by default true. So if I do:

```javascript
const svgo = new SVGO({
  multipass: true,
  plugins: [
    { cleanupIDs: false },
    { removeElementsByAttr: { id: ['invisible_box'] } },
  ]
});
```

Then the SVG elements with id of `invisible_box` get removed, but then none of the `id` attributes get removed since `cleanupIDs` is false. So what is the proper way to both remove elements by ID and then remove all other IDs afterwards?

**Comment by GreLI** [comment]
Plugins are executed in order, so you can change it. However, since [the default order](https://github.com/svg/svgo/blob/master/.svgo.yml) is `cleanupIDs` first , you have to provide a full plugins list, setting `full: true` option. E.g. if add `removeElementsByAttr` to default enabled plugins list:
```js
const svgo = new SVGO({
  full: true,
  plugins: [
    { removeElementsByAttr: { id: ['invisible_box'] } },
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeEditorsNSData',
    'cleanupAttrs',
    'inlineStyles',
    'minifyStyles',
    'convertStyleToAttrs',
    'cleanupIDs',
    'removeUselessDefs',
    'cleanupNumericValues',
    'convertColors',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeViewBox',
    'cleanupEnableBackground',
    'removeHiddenElems',
    'removeEmptyText',
    'convertShapeToPath',
    'convertEllipseToCircle',
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    'convertPathData',
    'convertTransform',
    'removeEmptyAttrs',
    'removeEmptyContainers',
    'mergePaths',
    'removeUnusedNS',
    'sortDefsChildren',
    'removeTitle',
    'removeDesc'
  ]
})
```

**Comment by TrySound** [comment]
Since https://github.com/svg/svgo/releases/tag/v2.4.0 you can put removeElementsByAttr first and then add preset-default. This way you don't need to list all default plugins.
