### ISSUE TITLE
Should SVG 1.2 be supported? Specifically filters like "feDropShadow"

### ISSUE THREAD

**Issue by gdelmas** [svg/svgo#1193]
Hi there,

I noticed filters like "feDropShadow" are removed by the "removeUnknownsAndDefaults" plugin, as it only covers the SVG 1.1 spec.

Is there a reason for only covering 1.1? Should SVG 1.2 be supported?

https://www.w3.org/TR/SVGFilter12
https://www.w3.org/TR/SVG12/

relates to #1045

**Comment by GreLI** [comment]
SVG 1.2 is a dead-end. I doubt it has notable support, or supported at all.

Now, the actual upcoming standard is SVG 2 with corresponding CSS Modules, where some related stuff like transformations and filters were transferred.

**Comment by gdelmas** [comment]
thanks for clarifying. i was not aware that these filters are also defined in SVG 2.

so to rephrase my question: how can filters like "feDropShadow" that are part of the new spec be supported? is there a plan to add them.

i am asking as i was about to add the filter to https://github.com/svg/svgo/blob/master/plugins/_collections.js when i noticed it was not in the SVG 1 spec.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.6.1
