### ISSUE TITLE
removeEmptyContainers should also remove <use xlink:href="# ">

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1194]
svgo -i [Input.svg.txt](https://github.com/svg/svgo/files/3864571/Input.svg.txt) -o [Output.svg.txt](https://github.com/svg/svgo/files/3864574/Output.svg.txt) --multipass

Maybe [removeEmptyContainers should be disabled by default](https://github.com/svg/svgo/issues/569)

removeEmptyContainers removes `<symbol id="f" overflow="visible"/>`, but it does not remove `<use width="100%" height="100%" x="319.19" y="575.56" xlink:href="#f"/>`, hence in combination with cleanupIDs use will refer to another element

## Input
[Input.svg.txt](https://github.com/svg/svgo/files/3864571/Input.svg.txt)
![Inputc](https://user-images.githubusercontent.com/15687581/69161176-0672ca80-0aeb-11ea-97c7-418006f961f1.png)

## Output
[Output.svg.txt](https://github.com/svg/svgo/files/3864574/Output.svg.txt)
![Outputc](https://user-images.githubusercontent.com/15687581/69161191-0bd01500-0aeb-11ea-8f82-27069554743d.png)

## visual Differences:
instead of the space there is a "t"

## Copyright
assuming below threshold of originality

source: https://doi.org/10.1016/j.engstruct.2019.109861 (link will work in near future)

**Comment by johnkenny54** [comment]
It looks like the visual difference is no longer present (fixed by PR #1817, which prevents the no longer valid id from being reused), but the orphaned `<use>` is still present, so this issue is now more or less a duplicate of issue #1765.

**Comment by JoKalliauer** [comment]
confirm fix in version `3.2.0`
