### ISSUE TITLE
Cannot read property 'selectors' of undefined

### ISSUE THREAD

**Issue by PubliAlex** [svg/svgo#1196]
Hello,

I installed svgo and configured as I wish.

Now when I want to clean an SVG, I got the following error : 

`Cannot read property 'selectors' of undefined`

It worked in default configuration, so It's probably due to an option I checked, but I can't remember what is default.

**Comment by GreLI** [comment]
Probably, it's some CSS related plugin.

**Comment by PubliAlex** [comment]
Hello, yes it was related to css plugin. Thank you
