### ISSUE TITLE
var(--x, var(--y)) causes infinite loop with convertStyleToAttrs

### ISSUE THREAD

**Issue by mischnic** [svg/svgo#1198]
Using a CSS custom property as a fallback for another property (see below) seems to cause an infinite loop (`optimize` doesn't return):

Example:
```js
const SVGO = require("svgo");

const x = new SVGO({
	plugins: [
		{
			convertStyleToAttrs: true // works with false
		}
	]
});

x.optimize(
	`<svg>
  <path
    style="fill:var(--spectrum-alert-success-icon-color, var(--spectrum-global-color-green-600));"
    d="M4.5 10a1.023 1.023 0 0 1-.8-.384l-2.488-3a1 1 0 0 1 1.577-1.233L4.5 7.376l4.712-5.991a1 1 0 1 1 1.576 1.23l-5.511 7A.977.977 0 0 1 4.5 10z"
  />
</svg>`
).then(console.log);
```

**Comment by XhmikosR** [comment]
@TrySound have you thought about using csso or another minifier to handle all CSS minifying? It appears that only csso/lib/restructure/prepare/specificity is used right now, which doesn't yield the best possible results and this issue could probably be prevented too.

**Comment by TrySound** [comment]
I think whole csso is used here
https://github.com/svg/svgo/blob/master/plugins/minifyStyles.js

**Comment by XhmikosR** [comment]
Ah, true, missed the plugins folder :)

I guess then, if this issue is reproducible with the latest csso-cli, it should be report upstream.

That being said, I saw some CSS-related issues like https://github.com/svg/svgo/issues/1142 and it made me wonder.

**Comment by TrySound** [comment]
convertStyleToAttrs will be disabled by default in the next release
https://github.com/svg/svgo/pull/1365

**Comment by TrySound** [comment]
https://github.com/svg/svgo/releases/tag/v2.1.0
