### ISSUE TITLE
A hosted API for svgo

### ISSUE THREAD

**Issue by chrisvxd** [svg/svgo#1202]
Hey @GreLI and team! 👋

Just wanted to reach out about funding your work on svgo.

@transitive-bullshit and I are both open source maintainers, and we're exploring new ways to make OSS funding a viable source of income.

We're currently looking at building rate-limited SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

I think svgo would be a great fit, and I'd love to build a SaaS API on top of it. We'd handle the initial dev as well as on going auth, billing and support so you wouldn't have to do anything.

Looking forward to hearing your thoughts! 🙏

**Comment by TrySound** [comment]
Hi. I don't see much sense in this with already existing tools like svgomg
