### ISSUE TITLE
How to use with expo SDK36 ?

### ISSUE THREAD

**Issue by kopax** [svg/svgo#1207]
## How to use with expo web

I am build a react-native application using expo `sdk36` and they advise to use `react-native-svg` in order to use svg within expo.

I went through the expo guide and did `expo install react-native-svg` and read the `react-native-svg` install guide. I add to edit my `app.json` and create `metro.config.js`

## Expected

I expect svg to be important as svg in the web.

## Result

it only import them as react component on iOS and Android

On the web, I have `consol.log(Svg)`:

    /static/media/logo.648cf17b.svg

## Reproduction

```bash
git clone https://github.com/kopax/expo-bug-reports.git
cd expo-bug-reports
git checkout issue-6660
npm i
npm test
npm run web
```

## Other

I have created `webpack.config.js` within my expo project and did:

```bash
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  console.log(JSON.stringify(config.module.rules, null,2));
  return config;
};
```

This is the result of the `console.log`:

```json
[
  {
    "parser": {
      "requireEnsure": false
    }
  },
  {
    "oneOf": [
      {
        "test": {},
        "use": [
          "/home/dka/workspace/test-native/node_modules/html-loader/index.js"
        ],
        "exclude": "/home/dka/workspace/test-native/web"
      },
      {
        "test": {},
        "use": {
          "loader": "/home/dka/workspace/test-native/node_modules/url-loader/dist/cjs.js",
          "options": {
            "limit": 1000,
            "name": "static/media/[name].[hash:8].[ext]"
          }
        }
      },
      {
        "test": {},
        "use": {
          "loader": "/home/dka/workspace/test-native/node_modules/babel-loader/lib/index.js",
          "options": {
            "babelrc": false,
            "configFile": true,
            "cacheCompression": true,
            "cacheDirectory": "/home/dka/workspace/test-native/.expo/web/cache/development/babel-loader",
            "cacheIdentifier": "babel-cache-1-{\"filename\":\"/home/dka/workspace/test-native/foobar.js\",\"cwd\":\"/home/dka/workspace/test-native\",\"sourceFileName\":\"/home/dka/workspace/test-native/foobar.js\",\"babelrc\":false,\"configFile\":false,\"passPerPreset\":false,\"envName\":\"development\",\"root\":\"/home/dka/workspace/test-native\",\"plugins\":[],\"presets\":[{\"dirname\":\"/home/dka/workspace/test-native\",\"file\":{\"request\":\"babel-preset-expo\",\"resolved\":\"/home/dka/workspace/test-native/node_modules/babel-preset-expo/index.js\"}}]}",
            "caller": {
              "bundler": "webpack",
              "platform": "web",
              "mode": "development"
            },
            "sourceType": "unambiguous",
            "root": "/home/dka/workspace/test-native",
            "compact": false
          }
        }
      },
      {
        "test": {},
        "use": [
          {
            "loader": "/home/dka/workspace/test-native/node_modules/url-loader/dist/cjs.js",
            "options": {
              "limit": 50000,
              "name": "./fonts/[name].[ext]"
            }
          }
        ],
        "include": [
          "/home/dka/workspace/test-native",
          "/home/dka/workspace/test-native/node_modules/react-native-vector-icons",
          "/home/dka/workspace/test-native/node_modules/@expo/vector-icons"
        ]
      },
      {
        "test": {},
        "use": [
          "/home/dka/workspace/test-native/node_modules/@expo/webpack-config/node_modules/style-loader/index.js",
          "/home/dka/workspace/test-native/node_modules/css-loader/dist/cjs.js"
        ]
      },
      {
        "loader": "/home/dka/workspace/test-native/node_modules/file-loader/dist/cjs.js",
        "exclude": [
          {},
          {},
          {}
        ],
        "options": {
          "name": "static/media/[name].[hash:8].[ext]"
        }
      }
    ]
  }
]
```

I think it miss `@svgr/webpack`, but I expected it to be configured by default on expo.

I have added a `@svgr/webpack` rules but it still didn't work:

```
  config.module.rules.push({
    test: /\.svg$/,
    use: [
      {
        loader: '@svgr/webpack',
        options: {
          native: true,
        },
      },
    ],
  });
```

## Questions 

- What is the `native: true` options for ? (couldn't find in the doc)
- Is there anything else to configure in order to get proper import

## Answers

> Is it possible for the user of Expo to extend Expo's Webpack config?

Yes, it is possible as described [here](https://docs.expo.io/versions/latest/guides/customizing-webpack/#example)

>  That way you could add the `@svgr/webpack` dependency and configure it.

I have already tried and it does not work at all. (see comment [here](https://github.com/gregberge/svgr/issues/375#issuecomment-570639446))

Basically, this is how my `webpack.config.js` looks like: https://github.com/kopax/expo-bug-reports/blob/issue-6660/webpack.config.js

The whole reproduction (**which is an expo blank project, nothing more**) can be run: 

```bash
git clone https://github.com/kopax/expo-bug-reports.git
cd expo-bug-reports
git checkout issue-6660
npm i 
npm test
npm run web
```

![image](https://user-images.githubusercontent.com/1866564/71748421-c6855e00-2e72-11ea-86db-87dfab07e07f.png)

Without the `webpack.config.js`, at least we can use the `require` return in `<img />`, while with `@svgr/webpack`, we can't (error remains the same)

## 💬 Related issues

- https://github.com/expo/expo/issues/6660
- https://github.com/kristerkari/react-native-svg-transformer/issues/70
- https://github.com/react-native-community/react-native-svg/issues/1235

**Comment by sk-** [comment]
@kopax How is this relevant to `svgo`?

**Comment by kopax** [comment]
It's svgo configuration. Any how it is solved in the appropriate place. Thanks!
