### ISSUE TITLE
Delete paths with fill=none

### ISSUE THREAD

**Issue by runxel** [svg/svgo#1210]
I am using guides (read: paths which have neither fill nor stroke) in Illustrator to align my designs.
Now I want to strip them from the resulting svg.
Could there be a rule which deletes `path`s which have no stroke and their fill color set to `none`?

---

Currently the svg looks like this:
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0h24v24H0z" fill="none"/> <!-- ← this should be gone -->
<path d="…"/>
</svg>
```

**Comment by dynasource** [comment]
same here. How to remove paths with opacity attributes

**Comment by dynasource** [comment]
@runxel, I bypassed it by creating an inline plugin:

```
svgmin({
            full : {}, // required to allow custom plugins (bypasses svgo.yml)
            plugins: [
                {removePath: require('./removePath.js')},
            ],
        })
```

the plugin file contains (in my scenario):
```
'use strict';

exports.type = 'perItem';

exports.fn = function (item, params) {
    var hasOpacityAttr = item.attr('opacity');
    if (hasOpacityAttr) {
        return false;
    }
    return true;
};
```

**Comment by runxel** [comment]
> @runxel, I bypassed it by creating an inline plugin:

Thanks for letting me know! Sounds cool. I don't have sound knowledge of svgo, actually. 😅 
How do I do that? (creating an inline plugin)

**Comment by dynasource** [comment]
yw. Well, in my example I used a separate plugin file, but it also seems possible to use an object.
In you're fill scenario, you could try:
```

plugins: [
                {
                    removePath: {
                        'type': 'perItem',
                        'fn': function (item, params) {
                            var fill = item.attr('fill');

                            return fill  !== 'none';
                        }
                    }
                },
]
```

Also, important here is to use the ```full : {}``` option, otherwise svgo complains about your plugin not be in the defaults.

**Comment by runxel** [comment]
Sadly it's not really well documented.
I just weeded through a bunch of old issues and found that what I want is already doable:
For the [`removeUselessStrokeAndFill` plugin](https://github.com/svg/svgo/blob/master/plugins/removeUselessStrokeAndFill.js) you have to enable **`removeNone`**.
