### ISSUE TITLE
"Non-whitespace before first tag." error

### ISSUE THREAD

**Issue by mahish** [svg/svgo#123]
did $ svgo logo.svg 
got Non-whitespace before first tag

Did not find any info anywhere about this error msg. Can somebody give me a clue? 
Thanks.

**Comment by AndyOGo** [comment]
Same here on SVG's which are run through svgo beforehand.
I double checked to have BOM removed and I check my files with an xml validator.

**Comment by rantiev** [comment]
Heh, it seems i have anything else. 
svg is valid. UTF-8 without bom encoding. No any other svg loaders for fonts. But the error exists.

**Comment by a-x-** [comment]
In my case I realized, that `create-react-app` have already good svg loader inside: svgr

And it's working out of the box:
```jsx
import { ReactComponent as Logo } from './logo.svg';
// or
import logoPath from './logo.svg';
```
