### ISSUE TITLE
Readme mistake

### ISSUE THREAD

**Issue by robole** [svg/svgo#1233]
In the section **Usage > CLI**, the following command:

    $ svgo *.svg

This command appears no longer works. I thought it was a Windows issue as I was getting a "no such file" error as it was the first command I tried with the module!

**Comment by MisterJimson** [comment]
Works for me on macOS

**Comment by HerrZatacke** [comment]
for me it works to run `svgo ./` to optimize all icons (tested on windows powershell, cmd-shell and git-bash)

**Comment by robole** [comment]
Is anyone reviewing issues on this repo?

**Comment by TrySound** [comment]
@robole Yes, windows does not support glob expansion. You need to list all files explicitly or use windows specific tools.
