### ISSUE TITLE
'svgop': svgo compiled with QuickJS into a <2MB standalone commandline app

### ISSUE THREAD

**Issue by twardoch** [svg/svgo#1242]
QuickJS is a new tiny JS interpreter and compiler.

I’ve managed to compile svgo with QuickJS, so the native macOS binary is now 1.9 MB, and does not need node. 

Previous method (pkg) produced 83 MB :) 

https://github.com/twardoch/svgop

**Comment by dr-js** [comment]
Nice idea!

You can also try the webpack output https://unpkg.com/libsvgo/webpack/SVGO.js from https://github.com/dr-js/libsvgo, a re-formatted ES6+ fork of svgo I recently made

**Comment by twardoch** [comment]
Cool, thanks. I'm not much of a JS guy, so my webpacking was rather blind try & err :)

**Comment by SethFalco** [comment]
Pretty cool project, though unfortunately, I'm closing this since it's not a feature request or bug report! ^-^'
Maybe later we should set up the GitHub discussions tab for show and tell. 🤔
