### ISSUE TITLE
Possibility to replace attribute values

### ISSUE THREAD

**Issue by dsebastien** [svg/svgo#1245]
Hello,

First, thanks a ton for this great utility!

I'd like to know if it would be possible to introduce means to replace attribute values through a plugin?

I have received a set of icons from a designer, which include a fill color, which is problematic as I'd prefer to have transparent SVG icons to be able to customize their color more easily (simply using color: #...).

I'm not all that familiar with SVG, so maybe the best is simply to learn more about CSS transformations, but when I compare with Angular Material icons for example, I see that they simply use fill="none", which allows to easily set a color on the icon paths.

So what I'd like to do is something like removeAttributesBySelector allows, but to replace the value of the attributes matching the expression with the provided replacement value.

Does this make any sense? ;-)

**Comment by dsebastien** [comment]
For the time being, I've worked around the issue by removing the fill attribute using removeAttrs and then adding it back to the svg element with addAttributesToSVGElement.

**Comment by TrySound** [comment]
You can write custom plugin

```
const plugin = {
  type: 'visitor',
  name: 'replace-values',
  fn: () => {
    return {
      element: {
        enter: node => {
          if (node.name === 'rect') {
            node.attributes.fill = 'none'
          }
        }
      }
    }
  }
}
```
