### ISSUE TITLE
Convert translateX() and translateY() to translate() when they are in the transform attribute

### ISSUE THREAD

**Issue by juanramoncarceles** [svg/svgo#1250]
Currently _convertStyleToAttrs_ plugin moves the `transform` property values to attributes even if they are `translateX()` and `translateY()` which are not valid there.

After that, _convertTransform_ plugin finds them and removes them (in __transforms.js_ > `transform2js()`), which makes sense since they are not valid.

One solution could be that _convertStyleToAttrs_ skips the `transform` property if it contains either `translateX()` or `translateY()`.

Another solution could be that either _convertStyleToAttrs_ or _convertTransform_ change them from `translateX()` and/or `translateY()` to `translate()`.

**Issue sample:**
Input with a `style` attribute with `translateX()`:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">  
  <line x1="20" y1="10" x2="20" y2="90" style="transform:translateX(75px);stroke:#000;stroke-width:20px;" />
</svg>
```
Output missing the translation:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <line x1="20" x2="20" y1="10" y2="90" stroke="#000" stroke-width="20"/>
</svg>
```

**Comment by TrySound** [comment]
convertStyleToAttrs will be disabled by default in the next release
https://github.com/svg/svgo/pull/1365

**Comment by TrySound** [comment]
https://github.com/svg/svgo/releases/tag/v2.1.0
