### ISSUE TITLE
Feature request: merge <style> tags

### ISSUE THREAD

**Issue by snail123815** [svg/svgo#1253]
As of the new Inkscape 1.0 release, it is found it runs slow or more often hangs with multiple `<style>` tags. Merging all the tags will resolve part of the problem.

Eg.
```xml
<style ... >
stuff { }
</style>
<style ... >
stuff2 { }
</style>
```

Should becomes

```xml
<style ... >
stuff { }
stuff2 { }
</style>
```

It is definitely not necessary to resolve issues for other program, but it seems merging tags can reduce the file size, which meets the goal of SVGO. Also, as far as I know, at least `matplotlab` is producing a lot figures with this problem, which means that this feature will benefit a lot people.

See [https://gitlab.com/inkscape/inkscape/-/issues/504](https://gitlab.com/inkscape/inkscape/-/issues/504) for details on the Inkscape issue.

**Comment by strarsis** [comment]
@snail123815: PR ready for the `mergeStyles` plugin: https://github.com/svg/svgo/pull/1278

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.3.0
