### ISSUE TITLE
Image becomes semi-transparent

### ISSUE THREAD

**Issue by IlyaSemenov** [svg/svgo#1254]
Input file:

<img width="203" alt="Screenshot 2020-05-25 at 20 31 38" src="https://user-images.githubusercontent.com/128121/82817236-d1469b00-9ec6-11ea-8763-219b5555830d.png">

After running:

```bash
yarn svgo -i ping-logo.svg -o ping-logo-o.svg
```

half of the image becomes semi-transparent:

<img width="202" alt="Screenshot 2020-05-25 at 20 31 42" src="https://user-images.githubusercontent.com/128121/82817268-e4f20180-9ec6-11ea-8866-162f52a51e6a.png">

GitHub wouldn't allow me to attach the SVG directly, so I'm attaching the two files (original and optimized) in a zip archive: [logo.zip](https://github.com/svg/svgo/files/4677384/ping-logo.zip)

```
❯ npm ls|grep svgo
│ │ │ ├─┬ postcss-svgo@4.0.2
│ │ │ │ └─┬ svgo@1.3.2
├─┬ svgo-loader@2.2.1
```

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3
