### ISSUE TITLE
Error: postcss-svgo: Error in parsing SVG: Unquoted attribute value

### ISSUE THREAD

**Issue by jafarchoupan** [svg/svgo#1255]
npm run production error : 

`Error: postcss-svgo: Error in parsing SVG: Unquoted attribute value
`
i install svgo :this 1.3.2 version 
and remove node_modules directory and clean cache and remove package-lock.json 
finaly npm install again but have same error yet 
very important please help me !!

**Comment by TrySound** [comment]
Hi @jafarchoupan. Would be helpful to see svg file you pass to svgo.

**Comment by gabor-ottlik-epam** [comment]
I have similar issue. I run the formatter as a cli tool and with the -f option, but when it encounter an svg that has unvalid svg format it throws this error. My problem is that the tool doesn't output the source file where the error has happened.

I get the following output:
```
Processing directory 'src/asset/icon':

Error in parsing SVG: Unquoted attribute value
Line: 16
Column: 21
Char: {
```
Can you advise me how to figure out in which file the error happened?

**Comment by TrySound** [comment]
Hi @gabor-ottlik-epam. I fixed error message. Now file should be also reported. Please check.
