### ISSUE TITLE
Feature request: Remove groups

### ISSUE THREAD

**Issue by jamieburchell** [svg/svgo#1256]
I recently ran an SVG through SVGO and noticed that the optimised version still had two nested g tags surrounding the paths. There were no attributes on these groups and they were safe to remove.

Could the removal of group tags with no attributes be an option?

**Comment by marzepani** [comment]
This should be handled by the [collapseGroups](https://github.com/svg/svgo/blob/master/plugins/collapseGroups.js) plugin.
