### ISSUE TITLE
Feature request: Move fill CSS to attributes

### ISSUE THREAD

**Issue by jamieburchell** [svg/svgo#1257]
Could there be an option to remove classes that only contain a fill and move the fill to the paths as attributes?

For example:

```
<style>
.cls1 { fill: #000; }
</style>
<path class="cls1>
```

Could be represented as this using fewer bytes:

`<path fill="#000">`

For example, I ran an SVG through SVGOMG recently and only one of the classes was removed in this way, the second time another was removed, the third time the third class did not get removed.

**Comment by mondeja** [comment]
You need to set the parameter `onlyMatchedOnce` to `false` in the plugin `inlineStyles`. See [this](https://github.com/svg/svgo/issues/1259) for more info.
