### ISSUE TITLE
inlineStyles not working

### ISSUE THREAD

**Issue by ilabsllc** [svg/svgo#1259]
**sample.svg**

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 100" width="400" height="400">
    <defs>
        <style>
            .rectfill{fill:#377dff}
			.rectfill-2{fill:#aeaeae}
		</style>
	</defs>
	<g opacity=".15">
	<rect x="120" width="100" height="100" rx="15" class="rectfill fill-primary" />
	<rect x="120" width="100" height="100" rx="15" class="rectfill-2 fill-primary" />
	</g>
</svg>
```

If I run svgo --multipass --pretty --enable=inlineStyles -i .\sample.svg -o .\converted-sample.svg

It correctly produces the **converted-sample.svg** as expected

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 100" width="400" height="400">
    <g opacity=".15">
        <rect x="120" width="100" height="100" rx="15" class="fill-primary" fill="#377dff"/>
        <rect x="120" width="100" height="100" rx="15" class="fill-primary" fill="#aeaeae"/>
    </g>
</svg>
```

Now if I try with another one **sample2.svg** with just one difference. I use the same class name on both the elements.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 100" width="400" height="400">
    <defs>
        <style>
            .rectfill{fill:#377dff}
	    .rectfill-2{fill:#aeaeae}
	</style>
	</defs>
	<g opacity=".15">
	<rect x="120" width="100" height="100" rx="15" class="rectfill fill-primary" />
	<rect x="120" width="100" height="100" rx="15" class="rectfill fill-primary" />
	</g>
</svg>
```
Again run svgo --multipass --pretty --enable=inlineStyles -i .\sample2.svg -o .\converted-sample2.svg

It doesn't do anything other than removing unused rectfill-2 class from style section. **converted-sample2.svg**

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 100" width="400" height="400">
    <defs>
        <style>
            .rectfill{fill:#377dff}
        </style>
    </defs>
    <g opacity=".15">
        <rect x="120" width="100" height="100" rx="15" class="rectfill fill-primary"/>
        <rect x="120" width="100" height="100" rx="15" class="rectfill fill-primary"/>
    </g>
</svg>
```

So it seems like if you use the same class on multiple elements it doesn't seem to work. Could you let me know.

**Comment by mondeja** [comment]
This is the expected behaviour: `inlineStyles` plugin has a boolean parameter `onlyMatchedOnce` that is `true` by default. This parameter indicates that only selectors that match once will be inlined.

Try to change the configuration of the plugin in the file at this repository root (`.svgo.yml`) setting `onlyMatchedOnce` to false:

```yml
  - inlineStyles:
      onlyMatchedOnce: false
```

and then run: `node bin/svgo --multipass --pretty --enable=inlineStyles -i .\sample2.svg -o .\converted-sample2.svg`

The output will be:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 100" width="400" height="400">
    <defs>
        <style/>
    </defs>
    <g opacity=".15">
        <rect x="120" width="100" height="100" rx="15" class="fill-primary" fill="#377dff"/>
        <rect x="120" width="100" height="100" rx="15" class="fill-primary" fill="#377dff"/>
    </g>
</svg>
```

**Comment by ilabsllc** [comment]
Okay. I only have the installed version of svgo at /c/Users/{userName}/AppData/Roaming/npm/svgo

So I updated the **.svgo.yml** at /c/Users/{userName}/AppData/Roaming/npm/svgo

```yml
 - removeDoctype
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeXMLNS
  - removeEditorsNSData
  - cleanupAttrs
  - inlineStyles
	onlyMatchedOnce: false
  - minifyStyles
  - convertStyleToAttrs
```
....

It still doesn't seem to take effect.

**Comment by ilabsllc** [comment]
Ah. Found the issue. I was missing a colon after  - inlineStyles in the yml file.
