### ISSUE TITLE
Fails to write to disc

### ISSUE THREAD

**Issue by ghost** [svg/svgo#1262]
@GreLI 
Even i get success message files are not written to disc. 

My example is the same as:
https://github.com/svg/svgo/tree/master/examples

My paths are correct but not sure about the slash direction. I tried other paths no success.
Actually i am trying many different path variations since 2  days.  
Node: v10.19.0

![Screenshot_4](https://user-images.githubusercontent.com/1254613/85157524-44dc8d80-b264-11ea-9573-899640321e30.png)

Do i need to manually write to file? It works if i do but what is the point of destination file option.

![Screenshot_20](https://user-images.githubusercontent.com/1254613/85159152-c8e34500-b265-11ea-9f8e-55d0820f9fe8.png)

**Comment by atilkan** [comment]
This is working. So paths are correct.
I think i don't need to manually write to file. This will cause race condition eventually. 
![Screenshot_20](https://user-images.githubusercontent.com/1254613/85159152-c8e34500-b265-11ea-9f8e-55d0820f9fe8.png)
