### ISSUE TITLE
Error in convertEllipseToCircle

### ISSUE THREAD

**Issue by darsain** [svg/svgo#1264]
I'm getting `Cannot read property 'value' of undefined` error when my gulp-svgmin plugin is processing [this svg file](https://ghostbin.co/paste/y8y6g).

The error comes from `svgo/plugins/convertEllipseToCircle.js:21:31`, which is this line here:

```
var rx = item.attr('rx').value || 0;
```

The only ellipse tag in the file is this one:

```svg
<ellipse
   style="opacity:1;fill:#4f4e57;fill-opacity:1;stroke:none;stroke-width:70;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
   id="path5227"
   cy="500"
   cx="500"
   r="100" />
```

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3
