### ISSUE TITLE
Recursive flag -f doesn't work

### ISSUE THREAD

**Issue by yceballost** [svg/svgo#1269]
Hi guys,

I am using this command to optimize my svg in this structure folder

`svgo -f MY_PATH/FOLDER`

```
folder/
├── foo
│   ├── far
│   │   └── away.svg
│   ├── bar.svg
│   └── cafe.svg
└── car.svg
```

But the svg files inside folders(foo & far) doesn't works with svgo

Thanks

**Comment by DanielVeza** [comment]
I'm also seeing this when trying to put recursive processing into our build scripts.

**Comment by yceballost** [comment]
I tried this command and works too for me! thanks!
