### ISSUE TITLE
How to use removeAttrs to remove xlink:href which could run a Javascript code??

### ISSUE THREAD

**Issue by AravinthAro** [svg/svgo#1283]
Hi I want to optimize my svg code and remove scripts if any. And I found out that we could run Javascript code inside `href` tag and I don't want it to happen in my code. Please help me on how to use removeAttr to remove such Javascript code. Thanks in advance.

This is how my svgo plugin looks like
```
const svgo = new SVGO({
    plugins: [{
      removeAttrs: {attrs: ('xlink:href')},
    }
  ]
  });
```

**Comment by TrySound** [comment]
SVGO is not a security tool. Though uou can implement custom plugin. Something like this.
```js
const removeXlinkHref = {
  name: 'removeXlinkHref',
  type: 'perItem',
  fn: (item) => {
    if (item.hasAttr('xlink:href')) {
      const href = item.getAttr('xlink:href');
      if (/* href is script */) {
        item.removeAttr('xlink:href')
      }
    }
  }
}
```
