### ISSUE TITLE
install without admin-rights

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1284]
I have a bot on Wikimedia Commons for reparing broken svg-images: https://commons.wikimedia.org/wiki/User:SVGWorkaroundBot
It also has a basic webinterface https://svgworkaroundbot.toolforge.org/ for testing-purposes and for manual repair.

It uses scour and svgcleaner, however I was not able to install svgo:
```bash
jkalliau@tools-sgebastion-07:~$ become svgworkaroundbot
tools.svgworkaroundbot@tools-sgebastion-07:~$ npm install -g svgo
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/project/svgworkaroundbot/.npm/_logs/2020-09-13T11_10_28_713Z-debug.log
```

<details>

<summary>/data/project/svgworkaroundbot/.npm/_logs/2020-09-13T11_10_28_713Z-debug.log</summary>

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'svgo' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose npm-session 22e9b57c20dbfee8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/svgo 327ms
8 http fetch GET 200 https://registry.npmjs.org/svgo/-/svgo-1.3.2.tgz 255ms
9 silly pacote tag manifest for svgo@latest fetched in 703ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule svgo@1.3.2 checking installable status
15 http fetch GET 200 https://registry.npmjs.org/chalk 406ms
16 http fetch GET 200 https://registry.npmjs.org/css-select 525ms
17 http fetch GET 200 https://registry.npmjs.org/object.values 523ms
18 http fetch GET 200 https://registry.npmjs.org/coa 535ms
19 http fetch GET 200 https://registry.npmjs.org/css-select-base-adapter 531ms
20 http fetch GET 200 https://registry.npmjs.org/csso 532ms
21 http fetch GET 200 https://registry.npmjs.org/js-yaml 532ms
22 http fetch GET 200 https://registry.npmjs.org/css-tree 584ms
23 http fetch GET 200 https://registry.npmjs.org/sax 592ms
24 http fetch GET 200 https://registry.npmjs.org/mkdirp 596ms
25 http fetch GET 200 https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz 884ms
26 http fetch GET 200 https://registry.npmjs.org/css-select/-/css-select-2.1.0.tgz 885ms
27 http fetch GET 200 https://registry.npmjs.org/object.values/-/object.values-1.1.1.tgz 889ms
28 http fetch GET 200 https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.37.tgz 835ms
29 http fetch GET 200 https://registry.npmjs.org/csso/-/csso-4.0.3.tgz 846ms
30 silly pacote range manifest for chalk@^2.4.1 fetched in 1446ms
31 silly resolveWithNewModule chalk@2.4.2 checking installable status
32 http fetch GET 200 https://registry.npmjs.org/coa/-/coa-2.0.2.tgz 900ms
33 http fetch GET 200 https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.0.tgz 893ms
34 http fetch GET 200 https://registry.npmjs.org/css-select-base-adapter/-/css-select-base-adapter-0.1.1.tgz 896ms
35 http fetch GET 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz 880ms
36 http fetch GET 200 https://registry.npmjs.org/sax/-/sax-1.2.4.tgz 885ms
37 silly pacote range manifest for css-select@^2.0.0 fetched in 1524ms
38 silly resolveWithNewModule css-select@2.1.0 checking installable status
39 silly pacote range manifest for object.values@^1.1.0 fetched in 1529ms
40 silly resolveWithNewModule object.values@1.1.1 checking installable status
41 silly pacote version manifest for css-tree@1.0.0-alpha.37 fetched in 1583ms
42 silly resolveWithNewModule css-tree@1.0.0-alpha.37 checking installable status
43 silly pacote range manifest for csso@^4.0.2 fetched in 1587ms
44 silly resolveWithNewModule csso@4.0.3 checking installable status
45 silly pacote range manifest for coa@^2.0.2 fetched in 1595ms
46 silly resolveWithNewModule coa@2.0.2 checking installable status
47 silly pacote range manifest for js-yaml@^3.13.1 fetched in 1591ms
48 silly resolveWithNewModule js-yaml@3.14.0 checking installable status
49 silly pacote range manifest for css-select-base-adapter@^0.1.1 fetched in 1597ms
50 silly resolveWithNewModule css-select-base-adapter@0.1.1 checking installable status
51 silly pacote range manifest for mkdirp@~0.5.1 fetched in 1593ms
52 silly resolveWithNewModule mkdirp@0.5.5 checking installable status
53 silly pacote range manifest for sax@~1.2.4 fetched in 1594ms
54 silly resolveWithNewModule sax@1.2.4 checking installable status
55 http fetch GET 200 https://registry.npmjs.org/stable 161ms
56 http fetch GET 200 https://registry.npmjs.org/unquote 106ms
57 http fetch GET 200 https://registry.npmjs.org/util.promisify 158ms
58 http fetch GET 200 https://registry.npmjs.org/stable/-/stable-0.1.8.tgz 106ms
59 silly pacote range manifest for stable@^0.1.8 fetched in 349ms
60 silly resolveWithNewModule stable@0.1.8 checking installable status
61 http fetch GET 200 https://registry.npmjs.org/unquote/-/unquote-1.1.1.tgz 163ms
62 http fetch GET 200 https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.1.tgz 119ms
63 silly pacote range manifest for unquote@~1.1.1 fetched in 293ms
64 silly resolveWithNewModule unquote@1.1.1 checking installable status
65 silly pacote range manifest for util.promisify@~1.0.0 fetched in 290ms
66 silly resolveWithNewModule util.promisify@1.0.1 checking installable status
67 http fetch GET 200 https://registry.npmjs.org/ansi-styles 78ms
68 http fetch GET 200 https://registry.npmjs.org/supports-color 81ms
69 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp 90ms
70 http fetch GET 200 https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz 176ms
71 http fetch GET 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz 182ms
72 http fetch GET 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz 116ms
73 silly pacote range manifest for supports-color@^5.3.0 fetched in 288ms
74 silly resolveWithNewModule supports-color@5.5.0 checking installable status
75 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 292ms
76 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
77 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 292ms
78 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
79 http fetch GET 200 https://registry.npmjs.org/color-convert 73ms
80 http fetch GET 200 https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz 33ms
81 silly pacote range manifest for color-convert@^1.9.0 fetched in 119ms
82 silly resolveWithNewModule color-convert@1.9.3 checking installable status
83 http fetch GET 200 https://registry.npmjs.org/color-name 67ms
84 http fetch GET 200 https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz 31ms
85 silly pacote version manifest for color-name@1.1.3 fetched in 111ms
86 silly resolveWithNewModule color-name@1.1.3 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/has-flag 40ms
88 http fetch GET 200 https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz 28ms
89 silly pacote range manifest for has-flag@^3.0.0 fetched in 79ms
90 silly resolveWithNewModule has-flag@3.0.0 checking installable status
91 http fetch GET 200 https://registry.npmjs.org/@types%2fq 85ms
92 http fetch GET 200 https://registry.npmjs.org/q 55ms
93 http fetch GET 200 https://registry.npmjs.org/@types/q/-/q-1.5.4.tgz 84ms
94 http fetch GET 200 https://registry.npmjs.org/q/-/q-1.5.1.tgz 146ms
95 silly pacote range manifest for @types/q@^1.5.1 fetched in 251ms
96 silly resolveWithNewModule @types/q@1.5.4 checking installable status
97 silly pacote range manifest for q@^1.1.2 fetched in 216ms
98 silly resolveWithNewModule q@1.5.1 checking installable status
99 http fetch GET 200 https://registry.npmjs.org/boolbase 107ms
100 http fetch GET 200 https://registry.npmjs.org/nth-check 114ms
101 http fetch GET 200 https://registry.npmjs.org/css-what 185ms
102 http fetch GET 200 https://registry.npmjs.org/domutils 185ms
103 http fetch GET 200 https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz 190ms
104 http fetch GET 200 https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz 192ms
105 silly pacote range manifest for boolbase@^1.0.0 fetched in 319ms
106 silly resolveWithNewModule boolbase@1.0.0 checking installable status
107 http fetch GET 200 https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz 131ms
108 http fetch GET 200 https://registry.npmjs.org/css-what/-/css-what-3.3.0.tgz 133ms
109 silly pacote range manifest for nth-check@^1.0.2 fetched in 327ms
110 silly resolveWithNewModule nth-check@1.0.2 checking installable status
111 silly pacote range manifest for css-what@^3.2.1 fetched in 382ms
112 silly resolveWithNewModule css-what@3.3.0 checking installable status
113 silly pacote range manifest for domutils@^1.7.0 fetched in 386ms
114 silly resolveWithNewModule domutils@1.7.0 checking installable status
115 http fetch GET 200 https://registry.npmjs.org/dom-serializer 35ms
116 http fetch GET 200 https://registry.npmjs.org/domelementtype 93ms
117 http fetch GET 200 https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz 98ms
118 http fetch GET 200 https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz 99ms
119 silly pacote range manifest for dom-serializer@0 fetched in 203ms
120 silly resolveWithNewModule dom-serializer@0.2.2 checking installable status
121 silly pacote range manifest for domelementtype@1 fetched in 207ms
122 silly resolveWithNewModule domelementtype@1.3.1 checking installable status
123 http fetch GET 200 https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz 81ms
124 http fetch GET 200 https://registry.npmjs.org/entities 85ms
125 silly pacote range manifest for domelementtype@^2.0.1 fetched in 101ms
126 silly resolveWithNewModule domelementtype@2.0.1 checking installable status
127 http fetch GET 200 https://registry.npmjs.org/entities/-/entities-2.0.3.tgz 110ms
128 silly pacote range manifest for entities@^2.0.0 fetched in 213ms
129 silly resolveWithNewModule entities@2.0.3 checking installable status
130 http fetch GET 200 https://registry.npmjs.org/mdn-data 90ms
131 http fetch GET 200 https://registry.npmjs.org/source-map 100ms
132 http fetch GET 200 https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.4.tgz 226ms
133 http fetch GET 200 https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz 218ms
134 silly pacote version manifest for mdn-data@2.0.4 fetched in 365ms
135 silly resolveWithNewModule mdn-data@2.0.4 checking installable status
136 silly pacote range manifest for source-map@^0.6.1 fetched in 365ms
137 silly resolveWithNewModule source-map@0.6.1 checking installable status
138 http fetch GET 200 https://registry.npmjs.org/css-tree/-/css-tree-1.0.0-alpha.39.tgz 145ms
139 silly pacote version manifest for css-tree@1.0.0-alpha.39 fetched in 157ms
140 silly resolveWithNewModule css-tree@1.0.0-alpha.39 checking installable status
141 http fetch GET 200 https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.6.tgz 134ms
142 silly pacote version manifest for mdn-data@2.0.6 fetched in 145ms
143 silly resolveWithNewModule mdn-data@2.0.6 checking installable status
144 http fetch GET 200 https://registry.npmjs.org/argparse 46ms
145 http fetch GET 200 https://registry.npmjs.org/esprima 90ms
146 http fetch GET 200 https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz 80ms
147 http fetch GET 200 https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz 96ms
148 silly pacote range manifest for argparse@^1.0.7 fetched in 193ms
149 silly resolveWithNewModule argparse@1.0.10 checking installable status
150 silly pacote range manifest for esprima@^4.0.0 fetched in 200ms
151 silly resolveWithNewModule esprima@4.0.1 checking installable status
152 http fetch GET 200 https://registry.npmjs.org/sprintf-js 26ms
153 http fetch GET 200 https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz 168ms
154 silly pacote range manifest for sprintf-js@~1.0.2 fetched in 205ms
155 silly resolveWithNewModule sprintf-js@1.0.3 checking installable status
156 http fetch GET 200 https://registry.npmjs.org/minimist 90ms
157 http fetch GET 200 https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz 97ms
158 silly pacote range manifest for minimist@^1.2.5 fetched in 198ms
159 silly resolveWithNewModule minimist@1.2.5 checking installable status
160 http fetch GET 200 https://registry.npmjs.org/es-abstract 105ms
161 http fetch GET 200 https://registry.npmjs.org/function-bind 179ms
162 http fetch GET 200 https://registry.npmjs.org/has 180ms
163 http fetch GET 200 https://registry.npmjs.org/define-properties 185ms
164 http fetch GET 200 https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz 422ms
165 http fetch GET 200 https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.6.tgz 438ms
166 http fetch GET 200 https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz 431ms
167 http fetch GET 200 https://registry.npmjs.org/has/-/has-1.0.3.tgz 429ms
168 silly pacote range manifest for define-properties@^1.1.3 fetched in 630ms
169 silly resolveWithNewModule define-properties@1.1.3 checking installable status
170 silly pacote range manifest for es-abstract@^1.17.0-next.1 fetched in 631ms
171 silly resolveWithNewModule es-abstract@1.17.6 checking installable status
172 silly pacote range manifest for function-bind@^1.1.1 fetched in 630ms
173 silly resolveWithNewModule function-bind@1.1.1 checking installable status
174 silly pacote range manifest for has@^1.0.3 fetched in 673ms
175 silly resolveWithNewModule has@1.0.3 checking installable status
176 http fetch GET 200 https://registry.npmjs.org/object-keys 35ms
177 http fetch GET 200 https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz 29ms
178 silly pacote range manifest for object-keys@^1.0.12 fetched in 77ms
179 silly resolveWithNewModule object-keys@1.1.1 checking installable status
180 http fetch GET 200 https://registry.npmjs.org/string.prototype.trimstart 142ms
181 http fetch GET 200 https://registry.npmjs.org/is-regex 145ms
182 http fetch GET 200 https://registry.npmjs.org/object-inspect 146ms
183 http fetch GET 200 https://registry.npmjs.org/es-to-primitive 148ms
184 http fetch GET 200 https://registry.npmjs.org/has-symbols 195ms
185 http fetch GET 200 https://registry.npmjs.org/object.assign 214ms
186 http fetch GET 200 https://registry.npmjs.org/string.prototype.trimend 293ms
187 http fetch GET 200 https://registry.npmjs.org/is-callable 297ms
188 http fetch GET 200 https://registry.npmjs.org/is-regex/-/is-regex-1.1.1.tgz 245ms
189 http fetch GET 200 https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz 244ms
190 http fetch GET 200 https://registry.npmjs.org/object-inspect/-/object-inspect-1.8.0.tgz 258ms
191 http fetch GET 200 https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.1.tgz 263ms
192 http fetch GET 200 https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz 216ms
193 http fetch GET 200 https://registry.npmjs.org/object.assign/-/object.assign-4.1.1.tgz 200ms
194 http fetch GET 200 https://registry.npmjs.org/is-callable/-/is-callable-1.2.1.tgz 198ms
195 silly pacote range manifest for is-regex@^1.1.0 fetched in 499ms
196 silly resolveWithNewModule is-regex@1.1.1 checking installable status
197 http fetch GET 200 https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.1.tgz 203ms
198 silly pacote range manifest for es-to-primitive@^1.2.1 fetched in 503ms
199 silly resolveWithNewModule es-to-primitive@1.2.1 checking installable status
200 silly pacote range manifest for object-inspect@^1.7.0 fetched in 512ms
201 silly resolveWithNewModule object-inspect@1.8.0 checking installable status
202 silly pacote range manifest for string.prototype.trimstart@^1.0.1 fetched in 515ms
203 silly resolveWithNewModule string.prototype.trimstart@1.0.1 checking installable status
204 silly pacote range manifest for has-symbols@^1.0.1 fetched in 522ms
205 silly resolveWithNewModule has-symbols@1.0.1 checking installable status
206 silly pacote range manifest for object.assign@^4.1.0 fetched in 524ms
207 silly resolveWithNewModule object.assign@4.1.1 checking installable status
208 silly pacote range manifest for is-callable@^1.2.0 fetched in 527ms
209 silly resolveWithNewModule is-callable@1.2.1 checking installable status
210 silly pacote range manifest for string.prototype.trimend@^1.0.1 fetched in 527ms
211 silly resolveWithNewModule string.prototype.trimend@1.0.1 checking installable status
212 http fetch GET 200 https://registry.npmjs.org/is-date-object 75ms
213 http fetch GET 200 https://registry.npmjs.org/is-symbol 78ms
214 http fetch GET 200 https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz 27ms
215 http fetch GET 200 https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz 88ms
216 silly pacote range manifest for is-symbol@^1.0.2 fetched in 169ms
217 silly resolveWithNewModule is-symbol@1.0.3 checking installable status
218 silly pacote range manifest for is-date-object@^1.0.1 fetched in 174ms
219 silly resolveWithNewModule is-date-object@1.0.2 checking installable status
220 http fetch GET 200 https://registry.npmjs.org/es-abstract/-/es-abstract-1.18.0-next.0.tgz 305ms
221 silly pacote range manifest for es-abstract@^1.18.0-next.0 fetched in 319ms
222 silly resolveWithNewModule es-abstract@1.18.0-next.0 checking installable status
223 http fetch GET 200 https://registry.npmjs.org/is-negative-zero 112ms
224 http fetch GET 200 https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.0.tgz 29ms
225 silly pacote range manifest for is-negative-zero@^2.0.0 fetched in 156ms
226 silly resolveWithNewModule is-negative-zero@2.0.0 checking installable status
227 http fetch GET 200 https://registry.npmjs.org/object.getownpropertydescriptors 34ms
228 http fetch GET 200 https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.0.tgz 60ms
229 silly pacote range manifest for object.getownpropertydescriptors@^2.1.0 fetched in 105ms
230 silly resolveWithNewModule object.getownpropertydescriptors@2.1.0 checking installable status
231 silly currentTree lib
232 silly idealTree lib
232 silly idealTree └─┬ svgo@1.3.2
232 silly idealTree   ├── @types/q@1.5.4
232 silly idealTree   ├── ansi-styles@3.2.1
232 silly idealTree   ├── argparse@1.0.10
232 silly idealTree   ├── boolbase@1.0.0
232 silly idealTree   ├── chalk@2.4.2
232 silly idealTree   ├── coa@2.0.2
232 silly idealTree   ├── color-convert@1.9.3
232 silly idealTree   ├── color-name@1.1.3
232 silly idealTree   ├── css-select-base-adapter@0.1.1
232 silly idealTree   ├── css-select@2.1.0
232 silly idealTree   ├── css-tree@1.0.0-alpha.37
232 silly idealTree   ├── css-what@3.3.0
232 silly idealTree   ├─┬ csso@4.0.3
232 silly idealTree   │ ├── css-tree@1.0.0-alpha.39
232 silly idealTree   │ └── mdn-data@2.0.6
232 silly idealTree   ├── define-properties@1.1.3
232 silly idealTree   ├─┬ dom-serializer@0.2.2
232 silly idealTree   │ └── domelementtype@2.0.1
232 silly idealTree   ├── domelementtype@1.3.1
232 silly idealTree   ├── domutils@1.7.0
232 silly idealTree   ├── entities@2.0.3
232 silly idealTree   ├── es-abstract@1.17.6
232 silly idealTree   ├── es-to-primitive@1.2.1
232 silly idealTree   ├── escape-string-regexp@1.0.5
232 silly idealTree   ├── esprima@4.0.1
232 silly idealTree   ├── function-bind@1.1.1
232 silly idealTree   ├── has-flag@3.0.0
232 silly idealTree   ├── has-symbols@1.0.1
232 silly idealTree   ├── has@1.0.3
232 silly idealTree   ├── is-callable@1.2.1
232 silly idealTree   ├── is-date-object@1.0.2
232 silly idealTree   ├── is-negative-zero@2.0.0
232 silly idealTree   ├── is-regex@1.1.1
232 silly idealTree   ├── is-symbol@1.0.3
232 silly idealTree   ├── js-yaml@3.14.0
232 silly idealTree   ├── mdn-data@2.0.4
232 silly idealTree   ├── minimist@1.2.5
232 silly idealTree   ├── mkdirp@0.5.5
232 silly idealTree   ├── nth-check@1.0.2
232 silly idealTree   ├── object-inspect@1.8.0
232 silly idealTree   ├── object-keys@1.1.1
232 silly idealTree   ├─┬ object.assign@4.1.1
232 silly idealTree   │ └── es-abstract@1.18.0-next.0
232 silly idealTree   ├── object.getownpropertydescriptors@2.1.0
232 silly idealTree   ├── object.values@1.1.1
232 silly idealTree   ├── q@1.5.1
232 silly idealTree   ├── sax@1.2.4
232 silly idealTree   ├── source-map@0.6.1
232 silly idealTree   ├── sprintf-js@1.0.3
232 silly idealTree   ├── stable@0.1.8
232 silly idealTree   ├── string.prototype.trimend@1.0.1
232 silly idealTree   ├── string.prototype.trimstart@1.0.1
232 silly idealTree   ├── supports-color@5.5.0
232 silly idealTree   ├── unquote@1.1.1
232 silly idealTree   └── util.promisify@1.0.1
233 silly install generateActionsToTake
234 warn checkPermissions Missing write access to /usr/local/lib
235 verbose stack Error: EACCES: permission denied, access '/usr/local/lib'
236 verbose cwd /mnt/nfs/labstore-secondary-tools-project/svgworkaroundbot
237 verbose Linux 4.9.0-8-amd64
238 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "svgo"
239 verbose node v8.11.1
240 verbose npm  v5.8.0
241 error path /usr/local/lib
242 error code EACCES
243 error errno -13
244 error syscall access
245 error Error: EACCES: permission denied, access '/usr/local/lib'
245 error  { Error: EACCES: permission denied, access '/usr/local/lib'
245 error   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib\'',
245 error   errno: -13,
245 error   code: 'EACCES',
245 error   syscall: 'access',
245 error   path: '/usr/local/lib' }
246 error The operation was rejected by your operating system.
246 error It is likely you do not have the permissions to access this file as the current user
246 error
246 error If you believe this might be a permissions issue, please double-check the
246 error permissions of the file and its containing directories, or try running
246 error the command again as root/Administrator (though this is not recommended).
247 verbose exit [ -13, true ]

</details>

**Comment by TrySound** [comment]
I'm sure it's not related to svgo. Something wrong with npm or destination directory rights.
