### ISSUE TITLE
How can I remove unused SVGs?

### ISSUE THREAD

**Issue by theasteve** [svg/svgo#1285]
I'm currently trying to remove unused SVGs from a distributed sprite using `cleanupIDs`, according to the documentation ```remove unused and minify used IDs``` but when I run the gulp task the file size doesn't seem to decrease.

Below is the gulp task i'm runnig.
```
gulp.task('svgs', () => {
  gulp.src(`${PATTERNS_ACCESS}/src/svg/*.svg`)
    .pipe(svgmin())
    .pipe(svgstore({
      inlineSvg: true
    }))
    .pipe(rename('icons.svg'))
    .pipe(gulp.dest('assets/svg/'))
    .pipe(hashFilename({format: HASH_FORMAT}))
    .pipe(gulp.dest('assets/svg/'));

    gulp.src([
      `${DIST}/svg/*.svg`
    ])
    .pipe(svgmin({
       plugins: [{
          cleanupIDs: {
            force: true,
            remove: true,
            minify: true
          }
       }]
    }))
    .pipe(gulp.dest(`${DIST}/svg`));
});
```

**Comment by SethFalco** [comment]
Would you be able to provide an example file to reproduce the issue with?

**Comment by SethFalco** [comment]
I'll close this for now. Still happy to look at this if you're still encountering the problem and willing to provide a minimal reproducible example, though!

Sorry it took so long to get around to this!
