### ISSUE TITLE
feature request:  convert rgba() to color + opacity

### ISSUE THREAD

**Issue by LuisAyuso** [svg/svgo#1294]
Hi there, 

My current development uses svg exported from Adobe Xd in a Qt QML application, usually colors remain black.
I detected that if I replace `fill="rgba(2,133,203,.8)" ` with `fill="#0285cb" fill-opacity="0.8"` colors are correct.
I presume this is part of the svg tiny specification that Qt supports. 

This is the same problem with stroke.

Is it possible to add this feature as part of convertColors or maybe a dedicated plugin? that would be pretty cool.

**Comment by vanillajonathan** [comment]
https://caniuse.com/css-rrggbbaa

<p class="ciu_embed" data-feature="css-rrggbbaa" data-periods="future_1,current,past_1,past_2" data-accessible-colours="false">
		<picture>
			<source type="image/webp" srcset="https://caniuse.bitsofco.de/image/css-rrggbbaa.webp">
			<source type="image/png" srcset="https://caniuse.bitsofco.de/image/css-rrggbbaa.png">
			<img src="https://caniuse.bitsofco.de/image/css-rrggbbaa.jpg" alt="Data on support for the css-rrggbbaa feature across the major browsers from caniuse.com">
		</picture>
	</p>

**Comment by TrySound** [comment]
Hi, browser support is not really a SVGO thing. It only optimizer. But yes, you can write own plugin to solve your problem. I'll be happy to list it in readme. See https://github.com/svg/svgo/pull/1624 for plugin documentation.
