### ISSUE TITLE
Request: Donation alternatives

### ISSUE THREAD

**Issue by Randelung** [svg/svgo#1297]
Hello!

First of all, thank you! You have saved me lots of time and headache with this tool and therefore I wanted to show my appreciation.
I tried donating some money, but PayPal is just shady. First it added a , instead of a . to the amount (which I couldn't change) and casually failed to interpret the amount correctly, adding a factor of 100, and now it's charging 30% of the donation. I don't want to send .10 or 1000.- by mistake and I don't support a 30% fee for not hodling PayPal credit.

Please provide alternatives, I'm sure I'm not the only frustrated donor. :)

Cheers

**Comment by ai** [comment]
OpenCollective or GitHub Sponsors will be great for us

**Comment by TrySound** [comment]
Hi, we created OpenCollective account
https://opencollective.com/svgo

**Comment by ai** [comment]
I became the first contributor 😎

**Comment by TrySound** [comment]
Thanks you @ai!
