### ISSUE TITLE
Incorrect svgo command

### ISSUE THREAD

**Issue by fescobalt** [svg/svgo#1298]
I USE:` { svg: { engine: "svgo", command: [enableCommand, '--multipass'] } }`

But when I put a console.log to **1215** line of /compress-images/index.js I get something like that:
`--enable=removeDimensions,cleanupIDs,removeAttrs,removeViewBox,inlineStyles,collapseGroups,removeTitle,removeMetadata,removeDoctype,cleanupAttrs,--multipass -i ./file-1591896815.svg -o ./file-1591896815.svg`

notice the **comma** (,) 
(cleanupAttrs,--multipass)

**Comment by fescobalt** [comment]
did you mean .join(' ')?

**Comment by TrySound** [comment]
Not sure this is related to svgo
