### ISSUE TITLE
Provide an appimage for svgo

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#1299]
[AppImages](https://en.wikipedia.org/wiki/AppImage) are an easy way of using Software, without installing and without any sudo-rights, it would be a fix of https://github.com/svg/svgo/issues/1284 .

Inkscape for example offers appimages for Linux: https://inkscape.org/de/release/1.0.1/gnulinux/

**Comment by TrySound** [comment]
Have no idea about this. Good idea for separate project, maybe?
