### ISSUE TITLE
Missing prefixClassNames plugin in documentation

### ISSUE THREAD

**Issue by httpiga** [svg/svgo#1303]
Hello, I noticed that a plugin is missing in the main README.md list: [here](https://github.com/svg/svgo/blob/master/plugins/prefixIds.js) a property called `prefixClassNames` is tested, while it is never mentioned in the documentation. 
It works just like as `prefixIds` but for the class names.

I think `prefixClassNames` should be reported in the plugin list so users will be aware of its existence.

**Comment by strarsis** [comment]
@httpiga: Right, `prefixClassNames ` is a setting of the `prefixIds` plugin that allows to selectively let the plugin prefix IDs, classes or both of them.
