### ISSUE TITLE
A way to remove symbols with empty path

### ISSUE THREAD

**Issue by spajak** [svg/svgo#1305]
Below is a symbol that has only one path with empty 'd', `d=""`. Is it possible to remove both, symbol and objects that use it?
```
      <symbol
         overflow="visible"
         id="glyph598-2">
        <path
           style="stroke:none"
           d=""
           id="path491465" />
      </symbol>
```

**Comment by SethFalco** [comment]
Thanks for opening the feature request, sorry it took so long to review it. This has already been resolved and is the default behavior in SVGO v3.0.2.
