### ISSUE TITLE
remove empty tags

### ISSUE THREAD

**Issue by sugoidesune** [svg/svgo#1309]
I assume this would be safe to remove.
from SVGOMG

![image](https://user-images.githubusercontent.com/20317691/101103629-9df96d00-35c9-11eb-8d21-24909fec07a3.png)

**Comment by TrySound** [comment]
Ref https://github.com/svg/svgo/pull/1201

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3
