### ISSUE TITLE
convertShapeToPath does not work

### ISSUE THREAD

**Issue by ECorreia45** [svg/svgo#1313]
here my svg

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
    <defs>
        <style>
            .b{fill:rgba(49,49,49,.8)}
        </style>
    </defs>
    <g transform="translate(-56.348 -47.465)">
        <rect class="b" width="4.513" height="18" rx="1" transform="translate(61.348 50.465)"/>
        <rect class="b" width="4.511" height="18" rx="1" transform="translate(70.848 50.465)"/>
    </g>
</svg>
```

running on this has no effect

**Comment by TrySound** [comment]
Hi @ECorreia45! `rx` and `ry` on rects would produce bigger path so plugin skips such case.

**Comment by oviirup** [comment]
Hello @trysound! I understand the logic behind the current implementation. However, in some specific use cases, I need all shapes to be converted to paths, despite the larger path data.

Would it be possible to add a config option to force conversion of all shapes? This would be very useful for workflows where uniformity of path data is important.

For example, a config might look like:

```js
const plugins = [
  { 
    name: "convertShapeToPath",
    params: { convertArcs: true, force: true }
  }
]
```

Does this sound like a reasonable feature?
