### ISSUE TITLE
Always remove viewBox Attribute?

### ISSUE THREAD

**Issue by LogIN-** [svg/svgo#1314]
Hello,
great tool!

I am having an issue in removing viewBox attribute in my svg file.

Looks like my viewBox doesn't have the same values as <svg> width and hight attributes.
This is because they are defined [like this]( https://cran.r-project.org/web/packages/svglite/vignettes/scaling.html):

Parameter | Value
-- | --
left | 0
top | 0
right | width * 72
bottom | height * 72

By looking at the plugin code I see it is expecting the same values in those tags as in viewBox.
https://github.com/svg/svgo/blob/master/plugins/removeViewBox.js#L40
```js
if (
    nums[0] === '0' &&
    nums[1] === '0' &&
    item.attr('width').value.replace(/px$/, '') === nums[2] && // could use parseFloat too
    item.attr('height').value.replace(/px$/, '') === nums[3]
) {
    item.removeAttr('viewBox');
}
```
Is there any specifics on why is neccecerly to have absolutely the same values there or this check can be removed from plugin?

**Comment by TrySound** [comment]
SVGO is an optimisation tool in the first place. Removing viewBox when its values equal to width/height is an optimisation. In other case it may change/break behaviour.
