### ISSUE TITLE
[Bug]Path compression lost space

### ISSUE THREAD

**Issue by yisibl** [svg/svgo#1317]
Original svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1125">
    <path d="M448.6,997.7c.2,5.6,16.6,9.4,36.5,8.4s35.8-6.2,35.5-11.8a1.7,1.7,0,0,0-.1-.7c-1.5-5.2-17.3-8.6-36.4-7.7s-34.4,5.8-35.5,11.1Z" fill="green" />
</svg>
```

After [svgo](https://github.com/svg/svgo) compression, the spaces are removed, and an error will be reported:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1125">
    <path d="M448.6 997.7c.2 5.6 16.6 9.4 36.5 8.4s35.8-6.2 35.5-11.8a1.7 1.7 0 00-.1-.7c-1.5-5.2-17.3-8.6-36.4-7.7s-34.4 5.8-35.5 11.1z" fill="green" />
</svg>
```

### Use svgcleaner

```svg
<svg viewBox="0 0 750 1125" xmlns="http://www.w3.org/2000/svg">
  <path d="m448.6 997.7c.2 5.6 16.6 9.4 36.5 8.4s35.8-6.2 35.5-11.8a1.7 1.7 0 0 0 -.1-.7c-1.5-5.2-17.3-8.6-36.4-7.7s-34.4 5.8-35.5 11.1z" fill="#008000"/>
</svg>
```

`00-.1` Spaces are required here.

![image](https://user-images.githubusercontent.com/2784308/106470467-75172a80-64db-11eb-80b7-2a2b3a69007a.png)

**Comment by TrySound** [comment]
Hi @yisibl. Where the error is reported? I see no errors or visual differences in chrome and firefox.

**Comment by Jupi007** [comment]
You can see visual problems here: https://github.com/ubuntu/yaru/issues/2630

**Comment by TrySound** [comment]
@Jupi007 I see. Could you help me to find this particular icon?

**Comment by Jupi007** [comment]
In fact almost all icons of the icon theme was bugged using svgo.
For example with **folder-documents-symbolic**:
- source file: https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/places/folder-documents-symbolic.svg
- and exported bugged file: https://github.com/ubuntu/yaru/blob/87a40309aa735adca7e28d54ce5706e5d492e003/icons/Suru/scalable/places/folder-documents-symbolic.svg

But this isn't noticeable directly into the navigator, we was only be able to reproduce that using Ubuntu 18.04 (more recent version seems to use a new SVG parser).

**Comment by TrySound** [comment]
So was it a bug in ubuntu parser?

**Comment by Jupi007** [comment]
I think that the new parser is more permissive with syntax error. But as I'm not a SVG syntax expert I could be wrong.

**Comment by yisibl** [comment]
My understanding is that only the following number starts with - or is the English letter of the next command, can the space be omitted. The browser may have done compatibility processing. We should be consistent with svgcleaner.

**Comment by yisibl** [comment]
In fact, the compressed SVG has a very subtle position change in the browser. Re importing sketch will also have problems. We should ensure good compatibility in non browser environments.

**Comment by yisibl** [comment]
@Jupi007 Can you provide the svg link of this right arrow (>) icon, this icon is simpler and helps svgo test problems.
![image](https://user-images.githubusercontent.com/2784308/108590284-8eeeb380-739d-11eb-8f11-88ac1728bfe9.png)

**Comment by Jupi007** [comment]
Here is the source file: https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/actions/go-next-symbolic.svg

**Comment by yisibl** [comment]
Thanks @Jupi007

@TrySound Through this example, we can also clearly see that there should be a space in the `01-1.825`, The correct one should be `0 1-1.825`.

![image](https://user-images.githubusercontent.com/2784308/108591362-59e55f80-73a3-11eb-867c-5551355d4fcb.png)

**Comment by TrySound** [comment]
Do you want to send a PR @yisibl?

**Comment by yisibl** [comment]
@TrySound I don't know which file to modify. Can you give some guidance?

In addition, are there any plans to introduce correctness tests, like [svgcleaner](https://github.com/RazrFalcon/svgcleaner#correctness).

**Comment by TrySound** [comment]
> I don't know which file to modify. Can you give some guidance?

Me neither to be honest 😄 Maybe _path.js.

> In addition, are there any plans to introduce correctness tests, like svgcleaner.

Good idea. I will look into this.

**Comment by yisibl** [comment]
Thanks, @TrySound 

Update, fsoder replied in https://github.com/w3c/svgwg/issues/827#issuecomment-782601638:

> Those would be the large-arc and sweep flags, which are either 0 or 1 (single character, not a number) so it should be possible to omit spaces there.
[1] https://svgwg.org/svg2-draft/paths.html#PathDataEllipticalArcCommands

I use the Demo in the spec, and omitting blanks cannot display correctly in both Sketch and Adobe Illustrator.

Original file:

```svg
<svg viewBox="0 0 1200 400" xmlns="http://www.w3.org/2000/svg">
  <path d="M300 200 h-150 a150 150 0 1 0 150 -150 z" fill="red" stroke="blue" stroke-width="5" />
</svg>
```

Use svgo:

```svg
<svg viewBox="0 0 1200 400" xmlns="http://www.w3.org/2000/svg">
  <path d="M300 200H150A150 150 0 10300 50z" fill="red" stroke="#00f" stroke-width="5"/>
</svg>
```

So, it seems that we can add an option to control whether to compress the large-arc and sweep flags blank. And in order to compress SVG more safely, this option should be enabled by default. What do you think?

**Comment by TrySound** [comment]
I agree

**Comment by TrySound** [comment]
Will close after release

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3
