### ISSUE TITLE
Version 2.0.0 breaks some files.

### ISSUE THREAD

**Issue by strangedev** [svg/svgo#1333]
Hi :wave:
First of all, thank you for this project.

We recently upgraded from version 1.3.2 to 2.0.0 an are experiencing a bug. I don't really know how to describe this bug, as I'm not well-versed in SVG. The bug visually alters some files drastically. I have prepared a demonstration over at https://github.com/thenativeweb/temp--svgo-bug. When optimizing the input file from this repo, this is the result:

![input](https://user-images.githubusercontent.com/3045979/108353812-d97aff00-71e8-11eb-9f50-c77390da2d45.png)
![output](https://user-images.githubusercontent.com/3045979/108353808-d8e26880-71e8-11eb-9e7f-d44755d14151.png)

Maybe someone with more experience has some idea what the problem might be and if it's something caused by our input file.
I'm sorry we can't really provide more information on this bug, but we thought we should report it anyway.

**Comment by TrySound** [comment]
Thank you for issue! I figured out the problem. Will release fix soon.

**Comment by TrySound** [comment]
Fixed in 2.0.1

**Comment by strangedev** [comment]
Thanks a lot for the swift fix :blush:
