### ISSUE TITLE
Clarify how to use plugins

### ISSUE THREAD

**Issue by anselmbradford** [svg/svgo#1335]
Some things in the docs regarding plugin use is unclear:

- The [default config](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config) link in the docs is a dead link. 
- `has its specific position in the plugins list` is unclear. Does this mean to alphabetize the plugins in the config?

**Comment by TrySound** [comment]
See new docs
https://github.com/svg/svgo/blob/master/README.md
