### ISSUE TITLE
New logo wanted

### ISSUE THREAD

**Issue by TrySound** [svg/svgo#1336]
Current logo might not be very recognisable. We are looking for something refreshing.
If you like svgo and have ideas feel free to share them here.

<img src="https://svg.github.io/svgo-logo.svg" width="300" height="300" alt="logo"/>

**Comment by omgovich** [comment]
Hi! What if we alter the [W3C's SVG logo](https://www.w3.org/2009/08/svg-logos.html) in some way? Super draft sketches:

![svgomgo](https://user-images.githubusercontent.com/206567/108422682-eda21900-7247-11eb-8d95-9300ed9dda3c.png)

**Comment by DerianAndre** [comment]
Hello I'm André, a full-stack designer I recently found this awesome tool.
Although my Idea looks like @omgovich (bottom right-corner), the concept it's the same as the current one but without all the unnecesary stuff so it's an optimization of the logo (wink-wink)

![svgo](https://user-images.githubusercontent.com/8467504/108461199-7b293d00-7237-11eb-9439-360ea188b99b.png)

**Comment by MrSweGyii** [comment]
Thank!Sent from my Huawei phone-------- Original message --------From: André Castillo <notifications@github.com>Date: Fri, Feb 19, 2021, 11:51 AMTo: svg/svgo <svgo@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [svg/svgo] New logo wanted (#1336)

Hello I'm André, a full-stack designer I recently found this awesome tool.

Although my Idea looks like @omgovich (bottom right-corner), the concept it's the same as the current one but without all the unnecesary stuff so it's an optimization of the logo (wink-wink)

**Comment by TrySound** [comment]
Simplified version of current logo looks interesting

**Comment by DerianAndre** [comment]
> Simplified version of current logo looks interesting @DerianAndre 

Thanks!, feel free to give any feedback, I'll do another version later on.

**Comment by deepsweet** [comment]
Looks almost good to me. Technically speaking, it's not really a proper gear as in mechanical gear systems :)

I think we'll also need that icon separately, without leading "SVG" letters, to use it as avatar.

**Comment by DerianAndre** [comment]
@deepsweet of course! 👍🏻
Here is the original logo just optimized and with the gradient too (not the exact one). What do you think?
![SVGO-2](https://user-images.githubusercontent.com/8467504/109385661-bc15f700-78b2-11eb-8538-6f9e4de2245e.png)

**Comment by deepsweet** [comment]
Nice one! Not 100% sure if such gradient is correctly exportable as SVG, but I like it. Could you please also add just a gear icon separately and try to export everything as SVGs?

**Comment by TrySound** [comment]
Less teeth would look cleaner. Maybe make them a bit bigger? Dots inside look chaotic without lines.

**Comment by omgovich** [comment]
Feels like a simpler icon would look better. I mean with fewer amount of teeth and maybe with a simplified inner visual (few bigger dots).

**Comment by DerianAndre** [comment]
![SVGO-3](https://user-images.githubusercontent.com/8467504/109386224-896dfd80-78b6-11eb-8e7e-9de1fec73ffe.png)

**Comment by TrySound** [comment]
Maybe make the wheel a bit thiner? What do you think?

**Comment by DerianAndre** [comment]
You are right, that optic-correction looks better. A few pixels bigger makes a difference.
![SVGO-4](https://user-images.githubusercontent.com/8467504/109386611-faaeb000-78b8-11eb-8028-01256497fe56.png)

**Comment by omgovich** [comment]
Idea (just ignore it if you don't agree): what if we find a free font that looks like Futura? It would make G work better in pair with the O-gear icon. It seems to me that making the characters more "circle-like" (since O is a gear) would make the logo more consistent.
![image](https://user-images.githubusercontent.com/206567/109390882-4008c700-7925-11eb-845b-e829ae8692b7.png)

**Comment by omgovich** [comment]
I love the gradient version BTW. Looks fresh!

**Comment by omgovich** [comment]
BTW2: Awesome work, @DerianAndre! 👏

**Comment by JoKalliauer** [comment]
![https://gitlab.com/inkscape/inbox/uploads/13254c9df383a75f2e76dcd4df054fa6/New.svg](https://gitlab.com/inkscape/inbox/uploads/13254c9df383a75f2e76dcd4df054fa6/New.svg)

Attribution:
-SVG: [Habitator terrae](https://commons.wikimedia.org/wiki/User:Habitator_terrae) License: [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0) ([details](https://commons.wikimedia.org/wiki/File:SVG_Schrift.svg))
-gear: "SVGO project logo by Yegor Bolshakov (http://xizzzy.ru/)" ([source](https://github.com/svg/svgo/issues/1336#issue-811366801))
-wrench: Created in Inkscape, License: below the [Threshold of originality](https://en.wikipedia.org/wiki/Threshold_of_originality)

Trademark-Rights:
-SVG: "SVG" is possible Trademark by W3C (MIT, ERCIM, Keio, Beihang, Beihang).
-gear: might be a Trademark of https://github.com/svg/svgo

**Comment by DerianAndre** [comment]
> Idea (just ignore it if you don't agree): what if we find a free font that looks like Futura? It would make G work better in pair with the O-gear icon. It seems to me that making the characters more "circle-like" (since O is a gear) would make the logo more consistent.
> ![image](https://user-images.githubusercontent.com/206567/109390882-4008c700-7925-11eb-845b-e829ae8692b7.png)

I'll try another font more rounded later! Thanks for the feedback 💯

**Comment by DerianAndre** [comment]
Center one is the original, top font is Cassanet Plus, bottom is Red Hat Display (from Google Fonts is OFL) I think Red Hat looks perfect for this.
![SVGO](https://user-images.githubusercontent.com/8467504/109473580-b34b2f80-7a30-11eb-9bd5-a1531f341b65.png)

**Comment by omgovich** [comment]
The top one doesn't look clean — too much design in the characters IMO. But I like how G works with the gear. That make the logo look neater:
![image](https://user-images.githubusercontent.com/206567/109480088-27ff8780-7a8c-11eb-9b20-6c107c9a4c77.png)

**Comment by DerianAndre** [comment]
@omgovich I agree, fixed.
![SVGO](https://user-images.githubusercontent.com/8467504/109482153-e4306200-7a3a-11eb-8d0b-c2dda3d41631.png)

**Comment by JoKalliauer** [comment]
Since I added my suggested Logo as SVG, it might not be viewed correctly here again as a PNG:
![68747470733a2f2f6769746c61622e636f6d2f696e6b73636170652f696e626f782f75706c6f6164732f31333235346339646633383361373566326537366463643464663035346661362f4e65772e737667](https://user-images.githubusercontent.com/15687581/109482110-e4058600-7a7d-11eb-809a-68df314a8d41.png)

**Comment by TrySound** [comment]
Thank you guys! We like @DerianAndre final result. Could you please send svgs with text and without?

**Comment by DerianAndre** [comment]
> Thank you guys! We like @DerianAndre final result. Could you please send svgs with text and without?

Glad to hear @TrySound 😄 Here are the files, I also included a white version for both logotype and isotype.

[svgo.zip](https://github.com/svg/svgo/files/6061180/svgo.zip)
