### ISSUE TITLE
Running svgo on an invalid svg results in no errors and a truncated input file

### ISSUE THREAD

**Issue by lopopolo** [svg/svgo#1346]
```
$ echo "this text file is not an SVG" > txt_is_not_svg.svg
$ cat txt_is_not_svg.svg 
this text file is not an SVG
$ npx svgo --version
2.0.2
$ npx svgo txt_is_not_svg.svg 

txt_is_not_svg.svg:
Done in 1 ms!
0.028 KiB - 100% = 0 KiB
$ wc -c txt_is_not_svg.svg 
0 txt_is_not_svg.svg
```

This behavior is reproducible with `test.bad.svg` in the test directory of this repository.

**Comment by TrySound** [comment]
Hi! Thanks for reporting. The issue already fixed here and will be released today.
https://github.com/svg/svgo/commit/ea82cc28807a1d77220b9c8bb94ad657f9285e31

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.0.3
