### ISSUE TITLE
proposal: migrate to TypeScript

### ISSUE THREAD

**Issue by 1000ch** [svg/svgo#1355]
As mentioned on https://github.com/svg/svgo/issues/1320#issuecomment-775192021, do we have an actual plan to migrate SVGO codebase to TypeScript? TypeScript is widely adopted by a bunch of OSS as we know, then I feel we can have much more productivity and maintainability by TypeScript-adoption. Specifically, I'd like to suggest SVGO uses TypeScript as a parser with [`--allowjs` option](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options) as the first step until migrating all JavaScript into TypeScript completely.

**Comment by TrySound** [comment]
I personally not a big fan of TS. Though yeah, we could add it with allowjs flag. But not right now.
