### ISSUE TITLE
[BUG] Optimized SVG is different than source Allande coat of arms.svg

### ISSUE THREAD

**Issue by sk-** [svg/svgo#1361]
Using the (wip) integration test tool we identified an issue while optimizing the file `Allande coat of arms.svg` with the default settings.

## SVGO version
2.0.2

## Differences
The crown and the cross lost part of their colors.

## Sources
Original:

[source.svg.txt](https://github.com/svg/svgo/files/6022596/source.svg.txt)

Optimized:

[optimized.svg.txt](https://github.com/svg/svgo/files/6022600/optimized.svg.txt)

## Renders
Here are the two rendered images for comparison:

Original:

![source](https://user-images.githubusercontent.com/911768/108721979-5f58bc00-7501-11eb-9b1b-906f109089ec.png)

Optimized:

![optimized](https://user-images.githubusercontent.com/911768/108721972-5e278f00-7501-11eb-8509-b927b15d65ac.png)

Diff:

![diff](https://user-images.githubusercontent.com/911768/108721965-5c5dcb80-7501-11eb-937e-c5502a1d5905.png)

**Comment by sk-** [comment]
I think this is also solved by #1365 . At least when I disabled that option in SVGOMG I got an equivalent svg.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
