### ISSUE TITLE
[BUG] Optimized SVG is different than source Escudo de Agulo.svg

### ISSUE THREAD

**Issue by sk-** [svg/svgo#1362]
Using the (wip) integration test tool we identified an issue while optimizing the file `Escudo de Agulo.svg` with the default settings.

## SVGO version
2.0.2

## Differences

The dragon is completely broken and also some of its colors changed.
## Sources
Original:

[source.svg.txt](https://github.com/svg/svgo/files/6022627/source.svg.txt)
Optimized:

[optimized.svg.txt](https://github.com/svg/svgo/files/6022626/optimized.svg.txt)
## Renders
Here are the two rendered images for comparison:

Original:

![source](https://user-images.githubusercontent.com/911768/108722601-19e8be80-7502-11eb-8e68-4a4b7e58d1fb.png)

Optimized:

![optimized](https://user-images.githubusercontent.com/911768/108722582-16553780-7502-11eb-8ed8-1f81989ec76f.png)
Diff:

![diff](https://user-images.githubusercontent.com/911768/108722572-13f2dd80-7502-11eb-9798-eaaf31a9a301.png)

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
