### ISSUE TITLE
Add templates for issues and pull requests

### ISSUE THREAD

**Issue by sk-** [svg/svgo#1364]
It'd be great to add templates for issues and pull requests, this should allow us to spend less time and resources triaging issues, as that would prompt users to add all necessary details and it may add automatically labels.

For issues I'd have:
* bug report
* feature request
* plugin request
* question: this should redirect users to StackOverflow and use the tag `svgo` (https://stackoverflow.com/questions/tagged/svgo)

**Comment by TrySound** [comment]
I have no experience with templates. Could you send a PR?

**Comment by sk-** [comment]
Sure, https://github.com/svg/svgo/pull/1367. I grabbed the placeholder templates from Github and adapted them a little bit. Feel free to tweak the sections.
