### ISSUE TITLE
--config option does not handle raw JSON nor fail with incorrect values

### ISSUE THREAD

**Issue by mtancoigne** [svg/svgo#1366]
Hi!

I'm working with the `image_optim` Ruby gem which relies on SVGo to optimize SVGs. I'm [having trouble](https://github.com/toy/image_optim/issues/191) to see how we can switch from v1.3.x to v2, as the gem relies on `--disable` and `--enable`.

`svgo --help` states that `--config` allows to pass raw JSON string, but it seems to do nothing with raw JSON (`svgo -i file.svg -o out.svg --config="{floatPrecision:1}"` produces the same file as if no option was given).

In addition, when `--config` has "invalid" data, it's silently ignored.

Is it intentional ?

**Comment by TrySound** [comment]
Hi!

Both disable/enable flags and config as json string support was removed in v2. I forgot to fix help command.
Fixed the help and error here. Will release tomorrow.
https://github.com/svg/svgo/commit/a855b40ec5d53f3ce3b45213fd4c65bc4dc05347

**Comment by TrySound** [comment]
Is it possible for you to use svg.config.js?

**Comment by mtancoigne** [comment]
Thanks for your quick reply; I'll see if and how we can manage this :)

**Comment by TrySound** [comment]
Fixed error when json string is specified instead of path https://github.com/svg/svgo/releases/tag/v2.1.0
