### ISSUE TITLE
Error while processing some SVGs with version 2.1

### ISSUE THREAD

**Issue by sk-** [svg/svgo#1383]
**Describe the bug**
With the latest release (2.1) some SVGs are no longer being processed. They fail with the error:

```
Error: Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �
File: /tmp/test.svg
    at processSVGData (/node_modules/svgo/lib/svgo/coa.js:290:13)
    at /node_modules/svgo/lib/svgo/coa.js:267:17
    at async Promise.all (index 0)
    at async Command.action (/node_modules/svgo/lib/svgo/coa.js:182:13)
    at async Promise.all (index 0)
```

Note that the file is rendered correctly on Chrome.

**To Reproduce**
Run `svgo` on the attached file.

**Expected behavior**
The file should be optimized correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version: 2.1.0
 - NodeJs Version: 14.4.0
 - OS: MacOS
[issue.svg.txt](https://github.com/svg/svgo/files/6054876/issue.svg.txt)

**Comment by TrySound** [comment]
I see. It's utf-16. Well, v1.3.2 failed in the same way. v2.0.0 didn't failed but produced empty svg.
So it was never actually supported. Is it possible for you to get utf-8?
