### ISSUE TITLE
Make the browser bundle size smaller

### ISSUE THREAD

**Issue by omgovich** [svg/svgo#1390]
**Is your feature request related to a problem? Please describe.**
I noticed that SVGO now provides an official browser bundle, but it costs 825 KB (huge!).
Size matters for everything that intends to work in the browser.
IMO if we want to see the browser version using in the production, we must spend some time to reduce the browser bundle.

**Describe the solution you'd like**
I'm a micro-libraries developer and I have good expertise in bundle size optimizations.
If you agree that investing in the bundle size reducing worth it, I would be glad to create a few PRs reducing the `svgo.browser.js` size. Decided to ask you first before bringing the PRs you might not need. Maybe somebody also wants to help to optimize the browser version, so declaring the problem might involve them as well.

**Comment by TrySound** [comment]
> I noticed that SVGO now provides an official browser bundle, but it costs 825 KB (huge!).

It was 1450kB at first

Size is not a big problem because this package is tooling specific. It's actually much smaller than most of modern apps.
I already digged through bundle size. There is nothing simple you can do for now.

Though I am open for suggestions. Please let's discuss first before spending time on pull requests.

**Comment by omgovich** [comment]
The first thing (the most obvious) that popped out in my mind is the minification enabling by something like `rollup-plugin-terser`. Options:

1. Full minification (`compress: true, mangle: true, comments: false`) — 825 → **403 KB**. We can generate a source-map, so it doesn't make the DX (error handling) worse.
2. In case you want to keep the source readable, we can drop comments  and whitespaces only (preserve variable names, etc) (`compress: false, mangle: false, comments: false`) — 825 → **545 KB**

**Comment by TrySound** [comment]
This is doable. And yeah, keep source readable without maps.

**Comment by omgovich** [comment]
👌 I'll create a small PR once I have time
