### ISSUE TITLE
changes when updating to 2.x in Material-UI

### ISSUE THREAD

**Issue by eps1lon** [svg/svgo#1391]
**Describe the bug**
- plugins needed to be re-ordered to remove empty `<g />` resulting from `removeUselessStrokeAndFill` (specifically `removeUselessStrokeAndFill` has to come before `removeEmptyContainers`
   Edit: Setting `multipass` to `true` does not require re-ordering. Did the default change?
- Some paths have the following diff:
   ```diff
   -0-1.41l-2.83-2.83a.9959.9959 0 00-1.41
   +0-1.41l-2.83-2.83a.9959.9959 0 0 0-1.41
   ```
  This diff has no visible changes (search for `accessalarm` (with `rounded` selected) when [using 1.3.2](https://next--material-ui.netlify.app/components/material-icons/) vs [2.1.0](https://deploy-preview-25122--material-ui.netlify.app/components/material-icons/))

**To Reproduce**
Update svgo to 2.1 and resolve documented breaking changes

**Expected behavior**
Unclear whether this is intended or not. 

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version: 2.1.0 (was 1.3.2)
 - NodeJs Version 12.20.0 (and 10.24.0
 - OS: Ubuntu 20.04.2 LTS
 
**Additional context**
https://github.com/mui-org/material-ui/pull/25122

**Comment by TrySound** [comment]
> Some paths have the following diff. This diff has no visible changes

Not a bug. See https://github.com/svg/svgo/pull/1353

> plugins needed to be re-ordered to remove empty <g /> resulting from removeUselessStrokeAndFill (specifically removeUselessStrokeAndFill has to come before removeEmptyContainers

Might be related to series of fixes which prevents some optimisations in favour of correctness

Please tell if you'll notice any visual regressions.

**Comment by eps1lon** [comment]
[Automated diffing](https://gist.github.com/eps1lon/028adda2db8405d6f300703cc7a4eb66) did not spot any visual changes. If you consider the required `multipass: true` as a regression, feel free to close the issue.

**Comment by TrySound** [comment]
Thanks! Hope soon multipass will not be necessary.
