### ISSUE TITLE
Add `--exclude` option to the CLI script

### ISSUE THREAD

**Issue by Tokimon** [svg/svgo#1392]
**Is your feature request related to a problem? Please describe.**
I run the SVGO recursively on a single folder (`-r -f`), but I have some auto generated SVG files that I for structural purposes have placed in a nested folder in the given folder. However since I know this file is already optimized there is no reason to use resources on parsing it (as well the risk of accidental clearing of the file as it is only symbols), so I would like to exclude them when executing.

I have look in the code (and documentation) and I have not been able to find any way to do this.

**Describe the solution you'd like**
An option to exclude certain files (`--exclude` or `-e`), possibly as regular or glob expression (eg `--exclude "auto/.+\.svg"`)

**Describe alternatives you've considered**
I have considered building my own script that uses the SVGO module that parses the files I need. But that seems redundant, since all other options would be the same and thus a simple exclude in the CLI would be simpler.

**Additional context**
N/A

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.3.0
