### ISSUE TITLE
Space removal for the "arcto" command is not affected by noSpaceAfterFlags 

### ISSUE THREAD

**Issue by NeRdTheNed** [svg/svgo#1403]
**Describe the bug**
When a SVG file containing "arcto" commands ('a' or 'A') is optimised, setting the plugin parameter "noSpaceAfterFlags" to true for relevant plugins does not result in "unnecessary" spaces (required for some programs) being removed from "arcto" commands in the output file. If these spaces do not exist in the input file, they will additionally be added to the output file, which is the opposite of the expected behaviour of noSpaceAfterFlags.

**To Reproduce**
1. Save [this file](https://github.com/svg/svgo/files/6080708/bug.svg.txt) (adapted from a [MDN path example](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths)) and change the extension to .SVG, or copy & save this text as a SVG file:
```svg
<svg viewBox="0 0 325 325" xmlns="http://www.w3.org/2000/svg"><path d="M80 80a45 45 0 0045 45V80z" fill="green"/><path d="M230 80a45 45 0 1045 45V80z" fill="red"/><path d="M80 230a45 45 0 0145 45v-45z" fill="purple"/><path d="M230 230a45 45 0 1145 45v-45z" fill="#00f"/></svg>
```
_(GitHub doesn't let me upload SVGs :/)_
2. Save [this file](https://github.com/svg/svgo/files/6080539/conf.js.txt) and change the extension to .JS, or copy & save this text as a javascript file:
```javascript
const { extendDefaultPlugins } = require('svgo');
module.exports = {
  plugins: extendDefaultPlugins([
    {
      name: 'convertPathData',
      active: true,
      params: {
        noSpaceAfterFlags: true
      }
    },
    {
      name: 'mergePaths',
      active: true,
      params: {
        noSpaceAfterFlags: true
      }
    }
  ])
}
```
_(GitHub doesn't let me upload javascript files either :/)_
3. Run SVGO 2.2.0 on the provided SVG file via the command line, using the provided configuration file (--config conf.js).
4. Observe that the file size is now larger, as SVGO added extra spaces to all "arcto" commands.

**Expected behavior**
I have been attempting to optimise some SVG files for the web. As SVGO 2.2.0 now does not remove spaces in "arcto" commands by default (#1353), I attempted to set the configuration values to what they were previously. I noticed that when I set the parameter noSpaceAfterFlags to true in the relevant plugins, it still did not remove spaces in "arcto" commands. Regardless of what noSpaceAfterFlags was set to, it started adding them to files that did not contain them!

I'm fairly sure that #1387 is actually the cause of this bug: js2path previously called the method cleanupOutData (found in tools.js) to cleanup path data, which had been removing the spaces in "arcto" commands. It looks like the PR removed this call. The new behaviour for "arcto" commands seems to be intentional (as seen here):
https://github.com/svg/svgo/blob/f3a6cf259a645073ec78ce1b88382487439206ee/lib/path.js#L229
but it results in SVGO not respecting noSpaceAfterFlags.

**Desktop (please complete the following information):**
 - SVGO Version: 2.2.0 (the bug was introduced in 2.2.0)
 - NodeJs Version: 7.6.0
 - OS: MacOS Mojave

**Comment by TrySound** [comment]
Fixed in v2.2.1
