### ISSUE TITLE
mergePaths plugin produces broken images

### ISSUE THREAD

**Issue by rarila** [svg/svgo#1422]
**Describe the bug**

Seems like there was some bug introduced in the ``mergePaths`` plugin with v2.

**To Reproduce**

Source SVG (stripped down to just the neccessary elements to show the bug):

```svg
<svg xmlns="http://www.w3.org/2000/svg">
<path d="M420.788 589.92h-46.172l-64.147-129.363c.832 81.583.748 89.443 1.172 129.609H279.18V418.838H325l64.03 128.075c-.324-43.285-.953-91.112-.937-128.32h32.695V589.92z"/>
<path d="M562.468 589.92h-98.672V418.594h98.672v29.765h-62.344v37.618h58.008v29.765h-58.008v44.18h62.344z"/>
</svg>
```

SVGO 2.2.2 with the following configuration:

```svg
{
    "floatPrecision": 0,
    "plugins": [{
            "name": "mergePaths",
            "active": true,
            "params": {
                "collapseRepeated": true,
                "force": false,
                "leadingZero": true,
                "negativeExtraSpace": true,
                "noSpaceAfterFlags": false
            }
        }]
}
```

Results in:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
<path d="M421 590h-46l-64-129c1 82 1 89 1 130H279V419H325l64 128c--43-1-91-1-128h33V590zM562 590h-99V419h99v30h-62v38h58v30h-58v44h62z"/>
</svg>
```

**Expected behavior**

Neither Chrome, Firefox nor Inkscape can display the image correctly (See screenshots).

Validator.nu gives the following error message:

>_Error:_ Bad value ``M421 590h-46l-64-129c1 82 1 89 1 130H279V419H325l64 128c--43-1-91-1-128h33V590zM562 590h-99V419h99v30h-62v38h58v30h-58v44h62z`` for attribute ``d`` on SVG element ``path``: Expected ``x1`` coordinate for ``c`` command but found ``-`` instead (context: ``79V419H325l64 128c--``).

**Screenshots**

Expected result:

![svg ok](https://user-images.githubusercontent.com/5936174/110953848-19488880-8348-11eb-96af-3579c70b4fb7.png)

Broken SVG:

![svg broken](https://user-images.githubusercontent.com/5936174/110953861-1c437900-8348-11eb-8104-a9646fcc7107.png)

**Desktop:**

 - SVGO 2.2.2
 - NodeJs Version 15.11.0

**Comment by TrySound** [comment]
Good catch! Fixed in https://github.com/svg/svgo/commit/3d4adb6b044ff1361a970ea049f90d5626ea9888. Will release soon.

**Comment by rarila** [comment]
@TrySound  Great! – Thanks a lot!

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.3.0
