### ISSUE TITLE
Global floatPrecision cannot be inherited in plugins with default floatPrecision

### ISSUE THREAD

**Issue by jlherren** [svg/svgo#1426]
I can't seem to reopen #1407, but the bug is still not fixed in 2.2.2 unfortunately.  Steps to reproduced are as given in that bug report, with that exact `svgo.config.js` file.

**Comment by TrySound** [comment]
Gotcha. Sorry for wait. Fixed in https://github.com/svg/svgo/commit/7389bcddbfadc49de84203b048199b4a397d656a

Will release soon.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.3.0

**Comment by jlherren** [comment]
Awesome, works now, thank you!
