### ISSUE TITLE
Lint details missing

### ISSUE THREAD

**Issue by strarsis** [svg/svgo#1435]
**Describe the bug**
Currently the lint script lists only the files with linting issues, no further details about the specific lint rule or the line.

**To Reproduce**
1. Introduce a lint error in a file in svgo.
2. Run the lint script (`npm run lint`).
Notice that the lint fails with nonzero exit code and the file path logged, 
but no further indications are made about the lint rule or the exact line.

**Expected behavior**
A detailed lint report so it is easy to fix the linting issues.

**Desktop (please complete the following information):**
 - SVGO Version: master
 - NodeJs Version: v14.16.0
 - OS: WSL 2

**Comment by TrySound** [comment]
Do you mean this? It's prettier error.
```
$ eslint . && prettier --list-different "**/*.js" --ignore-path .gitignore
lib/svgo/jsAPI.js
error Command failed with exit code 1.
```

**Comment by strarsis** [comment]
@TrySound: So the prettier itself has an issue?
Currently the builds for two of my PRs are failing because `npm run lint` fails.
When I invoke `npm run lint` I see the plugin file listed, but not what line or what the linter doesn't like about it.

**Comment by TrySound** [comment]
Not issue. Just format the file with it.

**Comment by TrySound** [comment]
Added "fix" script
