### ISSUE TITLE
error: unknown option '--disable=removeViewBox'

### ISSUE THREAD

**Issue by yceballost** [svg/svgo#1452]
**Describe the bug**
I was using SVGO with github actions and everything works fine but now I don't know why actions is throwing this error

`error: unknown option '--disable=removeViewBox'`

** My commands ** 
- npm install -g svgo (I also test with -i)
- svgo -f icons -r -o icons --disable=removeViewBox
 
Thanks

**Comment by TrySound** [comment]
This feature was removed in v2 https://github.com/svg/svgo/releases/tag/v2.0.0

**Comment by yceballost** [comment]
Oh! thanks, but the readme still appear the property, right? Maybe we need to update the readme.

**Comment by TrySound** [comment]
Could you point me where exactly `--disable` is described?

**Comment by yceballost** [comment]
that's true! my fault, now is everything working! thanks!
