### ISSUE TITLE
Command not found?

### ISSUE THREAD

**Issue by blg002** [svg/svgo#146]
I'm guessing this might be some problem with my permissions/setup but after installing svgo `$ sudo npm install -g svgo` im getting the following:

```
$ svgo -v
-bash: svgo: command not found
```

**Comment by jadchaar** [comment]
I had this issue myself and just added this to my `.zshrc` (or `.bash_profile` if you are using bash): `PATH="$HOME/.npm-packages/bin:$PATH"`.
