### ISSUE TITLE
Add a .svgoignore file to folder

### ISSUE THREAD

**Issue by joao-conde** [svg/svgo#1465]
**Is your feature request related to a problem? Please describe.**
By whatever reason, I might want to skip some directories within my project. 

**Describe the solution you'd like**
Ideally, this could be done by adding a simple `.svgoignore` file, similar to `.gitignore`.

**Describe alternatives you've considered**
1 - Adding the `.svgoignore` in a folder would make it skippable.
2 - Adding a generic `.svgoignore` in the root and specifying skippable paths.

**Comment by TrySound** [comment]
There is `--exclude` flag added in https://github.com/svg/svgo/releases/tag/v2.3.0 to exclude files by regexp. Can it fit your needs?

**Comment by joao-conde** [comment]
I was looking more for something not command-line specified. So at the time I simply run `svgo -r .` which is what I intend for the large codebase, but different components will use certain SVGs and it is rare but possible that I want to ignore its `component/assets/` where the SVGs could be contained for that component.

A simple way would be to create like a `component/assets/.svgoignore` and svgo would skip the analysis.

**Comment by joao-conde** [comment]
If you point me to relevant code that recursively analysis folders, I think I could open a PR with the feature, by simply checking if the directory contains a `.svgoignore` file or something.

**Comment by TrySound** [comment]
I would prefer to add something like `ignore` field to svgo.config.js.

**Comment by joao-conde** [comment]
But then there would be an exhaustive list of paths to svgs to ignore as well. It is still better than the current command-line exclude tho. If what I say is not possible, then that seems a reasonable solution too!
