### ISSUE TITLE
Remove default/initial attributes

### ISSUE THREAD

**Issue by vanillajonathan** [svg/svgo#1469]
Default attributes can be stripped away.

| Attribute | Default value |
|-|-|
| stroke-width | 1
| stroke-linecap | butt
| stroke-linejoin | miter
| stroke-miterlimit | 4
| stroke-dashoffset | 0
| stroke-opacity | 1

### svg
| Attribute | Default value |
|-|-|
| height | 150
| width | 300

### feComposite
| Attribute | Default value |
|-|-|
| k1 | 0
| k2 | 0
| k3 | 0
| k4 | 0
| order | 3
| bias | 0

### feConvolveMatrix
| Attribute | Default value |
|-|-|
| bias | 0
| divisor | 1
| edgeMode | duplicate
| preserveAlpha | false

### feDropShadow
| Attribute | Default value |
|-|-|
| dx | 2
| dy | 2
| stdDeviation | 2

### feFuncR
| Attribute | Default value |
|-|-|
| slope | 1
| intercept | 0
| amplitude | 1
| exponent | 1
| offset | 0

### filter
| Attribute | Default value |
|-|-|
| filterUnits | objectBoundingBox
| x | -10%
| y | -10%
| height | 120%
| width | 120%

**Comment by TrySound** [comment]
This is already done in this plugin https://github.com/svg/svgo/blob/master/plugins/removeUnknownsAndDefaults.js

**Comment by vanillajonathan** [comment]
Oh, I see. My bad. I am not sure it sets the `filterUnits` attribute of the `filter` element.
