### ISSUE TITLE
Paths aren't clipping properly? (not sure what else to call this behavior)

### ISSUE THREAD

**Issue by whaaaley** [svg/svgo#1470]
**Describe the bug**
Paths aren't clipping into the outer box like they should.

![image](https://user-images.githubusercontent.com/7419947/115089939-1a398080-9ed9-11eb-814f-83c87b3118f8.png)

**To Reproduce**

Input:
```svg
<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
  <g>
    <rect fill="none" height="24" width="24"/>
  </g>
  <g>
    <path d="M21,1H3C1.9,1,1,1.9,1,3v18c0,1.1,0.9,2,2,2h18c1.1,0,2-0.9,2-2V3C23,1.9,22.1,1,21,1z M19,19H6.83l1.58,1.58L7,22l-4-4 l4-4l1.41,1.42L6.83,17H17v-4h2V19z M17,10l-1.41-1.42L17.17,7H7v4H5V5h12.17l-1.58-1.58L17,2l4,4L17,10z"/>
  </g>
</svg>
```

Output
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
  <rect fill="none" height="24" width="24"/>
  <path d="M21 1H3c-1.1 0-2 .9-2 2v18c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2zM7 7h10v3l4-4-4-4v3H5v6h2V7zm10 10H7v-3l-4 4 4 4v-3h12v-6h-2v4z"/>
</svg>
```

This is my current config:

```js
module.exports = {
  multipass: true,
  plugins: [
    'cleanupEnableBackground',
    'collapseGroups',
    'convertPathData',
    'mergePaths',
    'removeTitle',
    'removeViewBox',
    'sortAttrs'
  ]
}
```

**Expected behavior**

Desired SVG:
![image](https://user-images.githubusercontent.com/7419947/115089788-b020db80-9ed8-11eb-8f69-44b5ae196409.png)

What I get:
![image](https://user-images.githubusercontent.com/7419947/115089820-c038bb00-9ed8-11eb-9725-fb4476445a49.png)

**Desktop (please complete the following information):**
 - SVGO Version ^2.3.0
 - NodeJs Version v15.14.0
 - OS: Debian 10

**Comment by GreLI** [comment]
Is it real SVGO output? When I run it, I get:
```
<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="#000000">
  <rect width="24" height="24" fill="none"/>
  <path d="M21 1H3c-1.1 0-2 .9-2 2v18c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2zm-2 18H6.83l1.58 1.58L7 22l-4-4 4-4 1.41 1.42L6.83 17H17v-4h2v6zm-2-9-1.41-1.42L17.17 7H7v4H5V5h12.17l-1.58-1.58L17 2l4 4-4 4z"/>
</svg>
```
which differs from your output. In yours path is significantly rewritten (and that is cause of bug).

**Comment by whaaaley** [comment]
@GreLI Yes. SVGO is the only thing I'm using to process SVGs. I'm not sure what else I could have done incorrectly. I used both CLI and https://jakearchibald.github.io/svgomg/ just to be sure and both produced the broken result.

**Comment by GreLI** [comment]
The first example makes sense, since removing `fill-rule` truly leads to bug. However, SVGO never did such a thing, because of possibility of bugs such a kind. I couldn't reproduce an issue with SVGO. All is fine in my runs with v2.3.0 and config that you provided.

**Comment by whaaaley** [comment]
Ahhh, `fill-rule`. I completely missed that. I was stuck on the paths. Thanks for pointing that out!
