### ISSUE TITLE
Style minification removes animation to

### ISSUE THREAD

**Issue by rianbotha** [svg/svgo#1474]
**Describe the bug**
Minifying styles removes the to portion of a CSS animation.

In a first pass of SVGO this:
```
<style>@keyframes plane{0%{transform:translateX(2000px)}100%{transform:translateX(-2000px)}}</style>
```
is converted to: 
```
<style>@keyframes plane{0%{transform:translateX(2000px)}to{transform:translateX(-2000px)}}</style>
```
The `100%` is replaced with `to`.

When svgo is run again the result is:
```
<style>@keyframes plane{0%{transform:translateX(2000px)}</style>
```
The `to` portion of the animation is removed completely.

**To Reproduce**
1. Run svgo on a file with a CSS animation
2. Run svgo again
3. Look at the resulting animation

**Expected behavior**
I expect the second pass of svgo to make no changes to the animation

**Desktop (please complete the following information):**
 - SVGO Version: 2.3.0
 - NodeJs Version: 15.3.0
 - OS: MacOS 11.3

**Comment by SethFalco** [comment]
Thanks for reporting the issue! I actually ran into the same problem in December 2021 and reported an issue as well:

* https://github.com/svg/svgo/issues/1631

This was due to a bug upstream in CSSO and has already been resolved in SVGO v3.
