### ISSUE TITLE
The library is old so I want you to update it.

### ISSUE THREAD

**Issue by famibee** [svg/svgo#1491]
Due to security issues, the library is out of date and I would like you to update it.
セキュリティの問題から、ライブラリが古いので更新して欲しいです。

| Lib | Now | Latest |
|---|---|---|
| css-select | 3.1.2 | 4.1.3 |

https://david-dm.org/svg/svgo

**Comment by AlexSnowLeo** [comment]
Any updates?

**Comment by carboneater** [comment]
I'd say this duplicates #1488 

Some nice folk already submitted #1485 to address that issue.

Maintainer seems AFK though...

**Comment by TrySound** [comment]
Released https://github.com/svg/svgo/releases/tag/v2.3.1
