### ISSUE TITLE
css-what's Denial of Service vulnerabitlity

### ISSUE THREAD

**Issue by mrsegen** [svg/svgo#1496]
**Describe the bug**
Projects that consume svgo (e.g., indirectly, @angular-devkit/build-angular via  css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > css-select > css-what) have a high severity DoS vulnerability due to something that was fixed in version 5.0.1 of css-what. css-select already fixed this in its latest release. Could there be a dependency update to address this?

**To Reproduce**
1. run npm install on an angular 12 project
3. run npm audit

**Expected behavior**
No vulnerability for projects that depend on patched versions of svgo

**Screenshots**
![image](https://user-images.githubusercontent.com/3103203/122781230-9bb4e280-d27d-11eb-8102-fd3da66e1a5a.png)

**Desktop (please complete the following information):**
 - SVGO Version ^2.3.0
 - NodeJs Version 14
 - OS: Windows 10

**Comment by chappjc** [comment]
Appears to be https://github.com/svg/svgo/issues/1496, but I second this.

**Comment by mrsegen** [comment]
@chappjc ah, thanks. Yes, I'll close this.
