### ISSUE TITLE
JSON config files

### ISSUE THREAD

**Issue by mischnic** [svg/svgo#1497]
**Is your feature request related to a problem? Please describe.**
Parcel's caching is most effective when config files are JSON files. The effective (=exported) value of JS config can change arbitrarily meaning that JS config files always have to be treated as "modified" and svgo has to be rerun for every file (even though the user didn't change anything).

For the first config example in the readme, a JSON file would suffice (so a `svgo.config.json`):
```json
{
  "multipass": true,
  "datauri": "enc",
  "js2svg": {
    "indent": 2,
    "pretty": true
  }
}
```

**Describe the solution you'd like**
But for disabling a single plugin, either `extendDefaultPlugins` need to be used, or *all* plugins need to be listed.

```js
const { extendDefaultPlugins } = require('svgo');
module.exports = {
  plugins: extendDefaultPlugins([
    {
      name: 'builtinPluginName',
      active: false
    }
  ])
}
```

What's missing is a way to achieve what `extendDefaultPlugins` does but without needing a JS config file. So for example something along the lines of:

```json
{
  "pluginsOverride": [
    {
      "name": "builtinPluginName",
      "active": false
    }
  ]
}
```

**Additional context**
Trying to avoid having to invent our own svgo config file format for Parcel...

**Comment by TrySound** [comment]
Added preset-default plugin and deprecated extendDefaultPlugins utility here
https://github.com/svg/svgo/pull/1513

**Comment by TrySound** [comment]
Release in https://github.com/svg/svgo/releases/tag/v2.4.0
