### ISSUE TITLE
Custom config supported yaml file 

### ISSUE THREAD

**Issue by LIN727** [svg/svgo#1504]
**Describe the bug**
Custom config file actually supports yaml file but in CLI helper description only .js is supported

**Expected behavior**
Add supporting file types to the description

**Screenshots**
![image](https://user-images.githubusercontent.com/16315216/126463743-04f5a479-6110-457e-8ddf-2f9bd4faebb5.png)

**Desktop (please complete the following information):**
 - SVGO Version 2.3.1
 - NodeJs Version 14.15.4
 - OS: macOS Mojave 10.14.6

**Comment by TrySound** [comment]
No, yaml syntax is not supported since v2. Only js is supported.
