### ISSUE TITLE
svgo.config.js does not load with only svgo installed 

### ISSUE THREAD

**Issue by phatNfqAsia** [svg/svgo#1563]
**Describe the bug**
As I was cloning my code to bulkly generate svg files to jsx files, I install the necessary svgo as devDependencies. But without 
```
		"@svgr/cli": "^5.5.0",
		"@svgr/core": "^5.5.0",
```
It does not respect the svgo.config.js file configuration as mentioned in README and went on optmizing without apply my plugin settings. I find this very confusing because it show such a half-way behavior - still work but not as expected

**Desktop (please complete the following information):**
 - SVGO Version 2.5.0
 - NodeJs Version v14.17.4
 - OS: Ubuntu 20.4

**Comment by TrySound** [comment]
Hi, show you config and the command you run

**Comment by TrySound** [comment]
SVGR uses old svgo version. You can use old config format and svgo.config.json or wait svgr 6.
