### ISSUE TITLE
Add svgo.config.cjs support to support ESM projects

### ISSUE THREAD

**Issue by ai** [svg/svgo#1579]
**Describe the bug**

I have project which we plan to moved to ESM with `"type": "module"` in `package.json`.

But if I will rename `svgo.config.js` to `svgo.config.cjs`, SVGO stopped to see the config.

**Comment by TrySound** [comment]
I was just thinking how to add es modules support. At the moment config is looking only for "svgo.config.js" though you can specify config file via `--config` option.

**Comment by ai** [comment]
Having `.mjs` and `.cjs` config extension is always good for some edge cases.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.7.0
