### ISSUE TITLE
Stopped inlining st* classes?

### ISSUE THREAD

**Issue by waltercruz** [svg/svgo#1589]
**Describe the bug**
SVGO is not inlining st[1-9] classes

**To Reproduce**

1. get this file: https://gist.githubusercontent.com/waltercruz/7bdf372457effd3f304b391b54b3c813/raw/b6460d64874f59b05eb2e5261aeb370a2ab1aec8/instagram.svg
2. compress it with svgo

**Expected behavior**
st1, st2 and st3 classes should be inlined

**Desktop (please complete the following information):**
 - SVGO 2.7.0
 - NodeJs 16.10
 - Mac OS Catalina

**Comment by waltercruz** [comment]
oops, my mistake. Closing!

**Comment by TrySound** [comment]
what was it?

**Comment by waltercruz** [comment]
in the <style> there was 4 classes - st0, st1, st2 and st3. This svg uses only st0 - and it was correctly inlined. In previous versions, the unused classes were deleted, but now the unused classes are kept. It's a different behaviour, but it's not breaking anything!

**Comment by TrySound** [comment]
Actually minifyStyles should remove unused classes. Will take a look later.

**Comment by mahnunchik** [comment]
Hi, I've faced with the same issue with different svg image: https://gist.githubusercontent.com/mahnunchik/23066a318de2956df3c769c87e4e6cbd/raw/e0f246d0e26ce770f3c3adca748a5a454907f8bb/crypto-com-coin-cro-logo.svg

```
<style>
    .st1{fill:url(#SVGID_00000016760000628848746960000000291323288447655331_)}
</style>
```

`st1` class not used and not removed.
