### ISSUE TITLE
Deprecate versions prior to v2.0.0

### ISSUE THREAD

**Issue by ericcornelissen** [svg/svgo#1603]
**Is your feature request related to a problem? Please describe.**

Not so much of a feature request, but just asking if versions prior to v2.0.0 should be deprecated.

I recall seeing a statement from one of the maintainers that older versions won't be updated but I can't remember where I saw that, hence this issue.

**Describe the solution you'd like**

Deprecate versions of this package prior to v2.0.0 if those are no longer supported.

**Describe alternatives you've considered**

Provide some support for version prior to v2.0.0.

**Additional context**

n/a

**Comment by TrySound** [comment]
SVGO < 2.0.0 is deprecated. Thanks!
