### ISSUE TITLE
Export js2svg/parseSvg aka svg2js, or make optimize async

### ISSUE THREAD

**Issue by LeviticusMB** [svg/svgo#1611]
**Is your feature request related to a problem? Please describe.**

I'm using SVGO in a project called [Ghostly](/Divine-Software/ghostly) as an optimizer, but I also have an inline operation that converts URLs into `data:` URLs. 

Fetching a resource and inlining it is an async operation, so I cannot just use a custom plugin. Soo ... I just call svg2js/js2svg manually instead. Which makes each SVGO version bump a pain, because I have to confirm that the hack still works every time.

**Describe the solution you'd like**

1. The best option, for me, would be if optimize() was async and that plugins could be async too.
2. Or, alternatively, I'd like to see the parser and serializer exported as a stable API.

**Comment by TrySound** [comment]
As an option you can run optimize twice
first with custom plugin to collect all links
second to inline already loaded resources

It's a bit less optimal though shouldn't affect performance a lot. I'm still not sure about exposing parser/stringifier as it will require more maintenance cost.

Btw with custom plugins you can use visitor api to not traverse manually
See https://github.com/svg/svgo/blob/master/plugins/sortAttrs.js#L97-L99

**Comment by LeviticusMB** [comment]
Yup, I already [did that](https://github.com/Divine-Software/ghostly/blob/5d70124d7457719444f786c5964b166f5fd55b05/ghostly-engine/src/html-transforms.ts#L403) in my latest release. It works OK so feel free to close this issue if you want.

**Comment by TrySound** [comment]
Please use visitor plugin api. perItem, perItemReverse and full will be removed in svgo v3.

**Comment by LeviticusMB** [comment]
Ah. OK, will migrate.
