### ISSUE TITLE
Attribute quotes are removed, causing XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by williamd5** [svg/svgo#1642]
**Describe the bug**
When the attribute contains no spaces, its quotes are automatically optimised (or at least I do not see a setting to disable this) which causes an XML Parsing error.
![image](https://user-images.githubusercontent.com/66572326/150683659-a558df1a-f77e-46c3-a0b3-ca2d2f2f8160.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the following code:
```js
// input: path to input file
// output: path to output file
const fs = require("fs").promises;
const {optimize} = require("svgo");
    fs.readFile(input, "utf8").then(data => {
        const result = optimize(data, {
            path: input,
            multipass: true,
            floatPrecision: 2,
            plugins: ["cleanupAttrs", "removeDoctype", "removeXMLProcInst", "removeComments", "removeMetadata", "removeTitle", "removeDesc", "removeUselessDefs", "removeEditorsNSData", "removeEmptyAttrs", "removeHiddenElems", "removeEmptyText", "removeEmptyContainers", "removeViewBox",]
        });
        fs.writeFile(output, result.data).then(() => resolve(1)).catch(reject);
    });
}
```
2. Open output file in a browser such as Mozilla
3. See error

**Expected behavior**
Attribute quotes shall not be removed

**Desktop (please complete the following information):**
 - SVGO Version: **`2.8.0`**
 - NodeJs Version: **`16.13.0`**
 - OS: **`Ubuntu 20.04 LTS`**

**Comment by TrySound** [comment]
Hi, which svg do you use as input?

**Comment by williamd5** [comment]
> Hi, which svg do you use as input?

Here are samples for source and output SVGs

#### Source
![icon](https://user-images.githubusercontent.com/66572326/150684105-1d7431a3-25ec-4f3d-abd3-93563c755a40.svg)
#### Output
![icon](https://user-images.githubusercontent.com/66572326/150684108-deeefe35-3a87-411f-ba54-80527375202f.svg)

**Comment by TrySound** [comment]
I just ran your code and all worked as expected. Please check again. Maybe something is missing in reproduction.

**Comment by williamd5** [comment]
> I just ran your code and all worked as expected. Please check again. Maybe something is missing in reproduction.

After more debugging, it seems like the output file is further passed to an HTML minifier (not because of svgo). By disabling the HTML minifier, the svgo output works correctly, therefore this is an issue that has to be resolved internally in our project.
