### ISSUE TITLE
Going from svgo 1.3.2 to 2.8.0, some style info is not removed any more

### ISSUE THREAD

**Issue by gom59** [svg/svgo#1661]
I am not sure if this is a bug, but it looks like one to me?

I have been using an obsolete version of svgo for a while, and recently updated to the latest.
With the legacy version, some style info such as `fill:#000` gets removed (default value), which is the expected behaviour?

But with 2.8.0, a bunch of style info is kept, including the fill field. This whole data chunk gets added  to the output file when going from rev 1 to 2:
`style="opacity:1;vector-effect:none;fill:#000;fill-opacity:1;stroke:none;stroke-width:53.3139801;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:.60194176;paint-order:normal"`

This is simplifying a drawing generated in inkscape. The settings file is using the defaults:
`module.exports = {
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
        },
      },
    },
  ],
};`

The drawing is attached below

**Comment by gom59** [comment]
Attaching the file instead:
![arrowRight](https://user-images.githubusercontent.com/49916817/157768602-a9ab0d50-b94e-4840-9569-4cb089618c89.svg)

**Comment by gom59** [comment]
Enabling the "removeStyleElement" plugin doesn't remove these style parameters for this path:

`
    <path
       inkscape:connector-curvature="0"
       style="opacity:1;vector-effect:none;fill:#000000;fill-opacity:1;stroke:none;stroke-width:53.3139801;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:0.60194176;paint-order:normal"
       d="M 146.55172,11.053879 124.13793,28.516062 103.79472,12.693899 C 97.510438,20.709788 89.902347,28.308238 81.034086,35.232596 72.132068,42.152416 62.365653,48.083675 52.060478,52.983373 L 72.413791,68.81341 49.999999,86.275592 150,88.962084 Z"
       id="path904"
       sodipodi:nodetypes="ccccccccc" />`

I was able to get rid of it using the removeAttrs plugin, configured as in this config.js file:

`
module.exports = {
  plugins: [
    'cleanupAttrs',
    // 'mergeStyles',
    // 'inlineStyles',
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeTitle',
    'removeDesc',
    'removeUselessDefs',
    // 'removeXMLNS', // disabled
    'removeEditorsNSData',
    'removeEmptyAttrs',
    'removeHiddenElems',
    'removeEmptyText',
    'removeEmptyContainers',
    'removeViewBox',
    'cleanupEnableBackground',
    'minifyStyles',
    // 'convertStyleToAttrs', // disabled
    'convertColors',
    'convertPathData',
    'convertTransform',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeUnusedNS',
    // 'prefixIds', // disabled
    'cleanupIDs',
    'cleanupNumericValues',
    // 'cleanupListOfValues', // disabled
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    // 'removeRasterImages', // disabled
    'mergePaths',
    'convertShapeToPath',
    'convertEllipseToCircle',
    // 'sortAttrs', // disabled
    'sortDefsChildren',
    // 'removeDimensions', // disabled
    {
      name: 'removeAttrs',
      params: {
        attrs: '(style)',
      },
    },
    // 'removeAttributesBySelector', // disabled
    // 'removeElementsByAttr', // disabled
    // 'addClassesToSVGElement', // disabled
    // 'addAttributesToSVGElement', // disabled
    // 'removeOffCanvasPaths', // disabled
    // 'removeStyleElement', // disabled
    // 'removeScriptElement', // disabled
    // 'reusePaths', // disabled
  ],
};`

**Comment by XhmikosR** [comment]
If you enable the `convertStyleToAttrs` plugin, it should remove those styles. It's one of those cases where enabling `convertStyleToAttrs` really helps. And this plugin is not enabled by default in svgo >= 2.x hence why you see this effect.

**Comment by SethFalco** [comment]
Indeed, `convertStyleToAttrs` (which will then get optimized out later) would've been perfect for this case.

**`svgo.config.js`**
```js
module.exports = {
  plugins: [
    "convertStyleToAttrs",
    "preset-default"
  ],
};
```

**`optimized.svg`** (92% reduction)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="74.634" height="100"><path d="M21.062 100V76.786L.01 76.768A114.561 114.561 0 0 0 3.205 50C3.195 40.79 2.08 31.79 0 23.196l21.062.018V0l53.572 50Z"/></svg>
```

I'm going to interpret this as another documentation task. We need a more modern getting started and usage guide, with an individual page for each plugin. 🤔 

Especially this issue which dives into a lot of detail, and proposes we document caveats for each plugin, which I think is a great idea:

* https://github.com/svg/svgo/issues/1460

Once I've patched up more of the bugs/tests, I may try to throw something together with Docusaurus later. 🤔
