### ISSUE TITLE
add XSS plugin

### ISSUE THREAD

**Issue by cakeinpanic** [svg/svgo#1665]
Hi, I found out there is no XSS plugin and I'm achieving removal of potential XSS vulnerabilities by combination of other plugins with a bigger config:

*`removeAttrs` with list of all event listeners like `onclick`, `onload` and others
* `removeScriptElement`

I'd be cool to have standalone plugin for this

**Comment by mariusheine** [comment]
Any update on this from one of the maintainers. That would be really cool!

**Comment by SethFalco** [comment]
Hey! Thanks for suggesting this, and sorry for not catching it sooner.
If you read my comment in your PR, you'll see this has been resolved by repurposing the `removeScriptElement` plugin, which will later be renamed.

See: https://github.com/svg/svgo/pull/1664#issuecomment-1793439407
