### ISSUE TITLE
SVGO no long works for me, v.2.8.0, node 16.14.3 - any command prints out 'help' page.

### ISSUE THREAD

**Issue by jjaimealeman** [svg/svgo#1668]
**Describe the bug**
`svgo` no long works for me on CLI.

I run `svgo file.svg -o file.min.svg` and it prints out `help`.
I run `svgo -v` or `svgo --version` and it prints out `htlp`.

screenshots:
![screenshot1](https://i.imgur.com/ANK5x6H.png)
![screenshot2](https://i.imgur.com/Gf2848P.png)

**Expected behavior**
Just expect it to work 😕

**Desktop:**
 - SVGO 2.8.0
 - NodeJs 16.14.0
 - Arch BTW

**Comment by TrySound** [comment]
Hi. Sorry, cannot reproduce this on v16.14.2 on macos
Could you debug what can be the source of the issue?
Starting point is here https://unpkg.com/browse/svgo@2.8.0/bin/svgo

**Comment by jjaimealeman** [comment]
Now sure what the problem was - but uninstall & reinstall fixed it.

![screenshot](https://i.imgur.com/bHy7FX0.png)

👍

_Cheers! Enjoy your weekend!
_
