### ISSUE TITLE
[stable] package is deprecated

### ISSUE THREAD

**Issue by jerryc05** [svg/svgo#1680]
**Is your feature request related to a problem? Please describe.**
when installing `svgo`, an warning occors:
```
WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort...
```

**Describe the solution you'd like**
Remove `stable` package as dep?

**Describe alternatives you've considered** 

**Additional context**
https://www.npmjs.com/package/stable

**Comment by bbzoozoo** [comment]
When will you publish a new version with this fix? Hope it ASAP,  deprecated library is not allowed in our project.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v3.0.0
