### ISSUE TITLE
svgo is not removing some comments

### ISSUE THREAD

**Issue by fabianobonin** [svg/svgo#1686]
If the comment starts with "<!--!" (with a leading !) it is not being removed by "removeComments" plugin.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! foo --><path="..."/></svg>
```
 - SVGO Version 2.8.0

**Comment by danisztls** [comment]
I'm facing he same issue. I guess the extra `!` is the culprit.

**Comment by TrySound** [comment]
This is expected. ! in comments usually used for copyright which should not be removed with minification.
