### ISSUE TITLE
Invalid character entity

### ISSUE THREAD

**Issue by tracker1** [svg/svgo#1695]
**Describe the bug**

Attempting to run Parcel on a project using okta-signin-widget

[Image in question](https://github.com/okta/okta-signin-widget/blob/dfd802db8ac36bca4f5873e16251801afd7b9648/assets/img/appstore/google-play-store.svg)

**Expected behavior**

Expected the project to build without errors.

**Screenshots**
```
parcel build feature/index.html --dist-dir dist
![google-play-store](https://user-images.githubusercontent.com/444316/190267511-71ef83c6-3601-461a-98a0-cbdbed41d3c3.svg)

🚨 Build failed.

@parcel/optimizer-svgo: SvgoParserError: <input>:13:72: Invalid character entity

  11 |  
  12 |  
> 13 | … id="Livello1" xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&nsg…
     |                                                       ^
  14 | …ule:evenodd;clip-rule:evenodd}.st1{fill-rule:evenodd;clip-rule:evenodd;fil…
  15 |  
```

**Desktop (please complete the following information):**
Unsure
 
**Additional context**
Reported the [issue with Parcel](https://github.com/parcel-bundler/parcel/issues/8469) as well.

![google-play-store](https://user-images.githubusercontent.com/444316/190267620-6fc0db4a-4722-426e-88cf-c779ad248e90.svg)

**Comment by mischnic** [comment]
This is a Parcel bug, see https://github.com/parcel-bundler/parcel/issues/8469#issuecomment-1279132032.
