### ISSUE TITLE
[v3.0.0] Could not find declaration files for plugins

### ISSUE THREAD

**Issue by kingyue737** [svg/svgo#1700]
**Describe the bug**
When I build my project depending on `svgo`, `tsc` throws errors like following:
```
error TS7016: Could not find a declaration file for module '../plugins/XXX.js'.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/40021217/197402581-94b81b3e-0156-465b-b61b-5c2cccbe87e0.png)

**Desktop (please complete the following information):**
 - SVGO Version 3.0.0
 - NodeJs Version 16.15.2
 - OS: Windows 11

**Comment by TrySound** [comment]
Hi, looks like you need to have `"allowJs": true,` in compilerOptions to make this work

**Comment by kingyue737** [comment]
`"allowJS": true` doesn't work for me. I need to set `"skipLibCheck": true` to avoid error. Not sure whether it is the correct solution.
Type `PluginOption` cannot be inferred and becomes `any`
![image](https://user-images.githubusercontent.com/40021217/197432066-2f2dc252-663c-476a-8041-d9bab5dde11e.png)

**Comment by ArnaudBarre** [comment]
Do you think it's possible to have typings without enabling JS?
It would be a lot faster for the compiler that would not need to parse all the JS plugins.
I see two possibilities:
- JS files imports typing from manually written TS files
- Change the codebase to TS and generate the types

Would you accept a PR for one of these?

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v3.0.1, thanks for reporting
