### ISSUE TITLE
`cleanupIds` doesn't exist in v3.0.0 browser bundle

### ISSUE THREAD

**Issue by XhmikosR** [svg/svgo#1704]
**Describe the bug**

v3.0.0 release notes mention that `cleanupIDs` is renamed to `cleanupIds`. When using the browser bundle (`svgo.browser.js`), it's still named `cleanupIDs`:

```js
cleanupIDs$1.name = 'cleanupIDs';
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version 3.0.0
 - NodeJs Version 16.18.0
 - OS: Windows
 
**Additional context**

Maybe the dist file was built before the rename happened?

**Comment by TrySound** [comment]
Good catch. Probably prepublishOnly script didn't work

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v3.0.1
