### ISSUE TITLE
[Docs] Inconsistent casing between cleanupIds plugin name and cleanupIDs parameter name

### ISSUE THREAD

**Issue by henriq-88** [svg/svgo#1709]
**Describe the bug**
To preserve the original IDs one is supposed to disable the plugin `cleanupIds` (Pascalcase `Id`). However, in order to disable this plugin, one has to use the parameter named `cleanupIDs` (uppercase `ID`). 

**To Reproduce**
1. Go to the README.md file and look up how to preserve original ids.
2. Check plugin name - `cleanupIds`
3.
```
{
  name: 'preset-default',
  params: {
    overrides: {
      ...
      cleanupIds: false,
      ...
    },
  },
},
```
4. Observe rendered SVGs with custom ids.

**Expected behavior**
The casing between the plugin (`cleanupIds`) and the parameter (`cleanupIDs`) is consistent.

**Desktop (please complete the following information):**
 - SVGO Version 6.5.1
 - NodeJs Version 18.12.0
 - OS: macOS Monterey 12.6
 
**Additional context**
This is not really a bug, but more about improving the documentation.

**Comment by TrySound** [comment]
Hi, could you please point exact places where docs using cleanupIDs? I can't find any.

**Comment by jillmolloy** [comment]
@TrySound I just noticed this also. It's in the [list of built-in plugins](https://github.com/svg/svgo#built-in-plugins) in the ReadMe.

**Comment by TrySound** [comment]
cleanupIds - all is correct, still don't understand the issue
<img width="541" alt="image" src="https://user-images.githubusercontent.com/5635476/203248811-6b78774e-3ecb-4b63-907d-d56f2d702739.png">

**Comment by TrySound** [comment]
Btw the plugin was renamed cleanupIDs -> cleanupIds in https://github.com/svg/svgo/releases/tag/v3.0.0
So it's now consistent with prefixIds.

**Comment by jillmolloy** [comment]
```
{
  "plugins": [
    {
      "name": "preset-default",
      "params": {
        "overrides": {
          "inlineStyles": false
        }
      }
    },
    {
      "name": "cleanupIDs",
      "active": false
    }
  ]
}
```

When I tried using `cleanupIds` as the name under plugins in my config file it did not work. When I changed it to `cleanupIDs` then it did work. I'm using svgo via parcel, which may still be using an older version and maybe what's causing confusion here. 

That's great that there's an update to make these consistent across the board. Thanks!

**Comment by TrySound** [comment]
Yep, sounds like transitive version indeed. You can try o remove svgo from your lockfile and install deps again.

**Comment by SethFalco** [comment]
Indeed, pretty sure this was just an issue with having an old version installed.
The term `cleanupIDs` doesn't even exist in the repo anymore outside our CHANGELOG.

I'm guessing the README was outdated back in November 2021, but today it's fine at least.
