### ISSUE TITLE
Creating a config file and setting decimal precision to 1

### ISSUE THREAD

**Issue by vedranjaic** [svg/svgo#171]
Hello, first of all thank you for this great tool! Second, and kinda newbie question, but how does one create a config file?
I created config.yml file:
```
plugins:

  - cleanupNumericValues
floatPrecision: 1
```
and put it beside my .svg images, and run in terminal:

```
svgo --pretty -i jez.svg -o jez.min.svg --config=config.yml
```
and can't get decimal rounding to 1 point. Am I missing something obvious, or completely missed the point? Can someone point me in the right direction?

**Comment by hayatbiralem** [comment]
Thanks @GreLI, you saved my time. List of all related plugins in my config here:

```js
{
  plugins: [
    {
      cleanupNumericValues: {
        floatPrecision: 1
      }
    },
    {
      convertPathData: {
        floatPrecision: 1
      }
    },
    {
      transformsWithOnePath: {
        floatPrecision: 1
      }
    },
    {
      convertTransform: {
        floatPrecision: 1
      }
    },
    {
      cleanupListOfValues: {
        floatPrecision: 1
      }
    }
  ]
}
```

**Comment by GreLI** [comment]
FYI, there is `--precision` option that does the same added in v.0.5.1. The only exceptions are transforms—because multiplication requires more presision.

**Comment by hayatbiralem** [comment]
Thanks again! Somehow I missed it but also I have trouble with it :(

I try to use global precision param as 2 with [gulp-svgmin](https://github.com/ben-eb/gulp-svgmin) and [gulp-svgo](https://github.com/corneliusio/gulp-svgo) but both uses with default precision 3 in process. My config after your advice is here:

```
{
    precision: 2
}
```

What am I doing wrong?

**Comment by hayatbiralem** [comment]
Actually [default config file](https://github.com/svg/svgo/blob/master/.svgo.yml) has no global precision param, that's interesting.

**Comment by GreLI** [comment]
It's actually `floatPrecision` in config like plugins parameter.

**Comment by hayatbiralem** [comment]
It's alive! Thank you very much for your time :)

**Comment by axe312ger** [comment]
Can you please add this to the readme? Took me a while to find it 🐌
