### ISSUE TITLE
Impossible to disable cleanupIDs plugin

### ISSUE THREAD

**Issue by jimblue** [svg/svgo#1723]
**Describe the bug**
The doc says that **cleanupIDs** is include in Default preset but when I try to disable it, I get the following error :

```bash
You are trying to configure cleanupIDs which is not part of preset-default.
Try to put it before or after, for example

plugins: [
  {
    name: 'preset-default',
  },
  'cleanupIDs'
]
```

**To Reproduce**
Run SVGO with the following config :
```js
module.exports = {
  multipass: true,
  js2svg: {
    indent: 2,
    pretty: true,
  },
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          removeTitle: false,
          removeDesc: false,
          cleanupIDs: false,
          removeViewBox: false,
          removeUnknownsAndDefaults: {
            keepAriaAttrs: true,
            keepRoleAttr: true,
          },
        },
      },
    },
  ],
}
```

**Expected behavior**
As **cleanupIDs** is part of default settings, we should be able to disable it.

**Desktop (please complete the following information):**
 - SVGO Version `3.0.2`
 - NodeJs Version `19.2.0`
 - OS: `macOS 13.0.1`

**Comment by TrySound** [comment]
Please see release notes. cleanupIDs was renamed to cleanupIds
https://github.com/svg/svgo/releases/tag/v3.0.0

**Comment by jimblue** [comment]
Great thank you 🙏🏼
