### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'params')

### ISSUE THREAD

**Issue by davesnx** [svg/svgo#1727]
**Describe the bug**
`plugins: ["collapseGroups", , ]` crashes with a TypeError

```
ib/svgo/plugins.js:21
    const params = { ...plugin.params, ...globalOverrides, ...override };
                               ^

TypeError: Cannot read properties of undefined (reading 'params')
    at invokePlugins (/home/me/monorepo/node_modules/svgo/lib/svgo/plugins.js:21:32)
```

**Desktop (please complete the following information):**
 - SVGO Version 3.0.2
 - NodeJs Version 18.0.0

**Comment by davesnx** [comment]
Wops, my mistake. `["collapseGroups", ,]` breaks.

**Comment by SethFalco** [comment]
Would you be able to provide a full config?
I'm unable to reproduce this with the information in the issue.

**Comment by davesnx** [comment]
When plugins are null, plugin.params was empty and acessing `params` property fails. I believe the bug is still there looking at https://github.com/svg/svgo/blob/main/lib/svgo/plugins.js#L21

**Comment by SethFalco** [comment]
> When plugins are null

I'm testing this on both v3.0.2, and main (b15da27af4832bbe9efbec2bef03eff0c0ed110d), with Node 14, 16, 18 (latest), and 18.0.0 as reported in the initial issue.
Doesn't occur for me when `plugins` is null.

> ```js
>     const params = { ...plugin.params, ...globalOverrides, ...override };
> ```

I don't see an immediate issue with this code. It only iterates when plugins are defined anyway, and when there is a plugin without params, destructuring `null` or `undefined` is valid in Node.js.

However, I see the problem. You probably had a weird configuration.

```js
module.exports = {
  plugins: [
    null
  ]
}
```

I can reproduce it with this, which is an invalid/unsupported configuration. The `plugins` property can be set to `null`, but this tries to add a `null` plugin` in the array.

To avoid issues in future, I'll add a warning whenever this happens and ignore it.

**Comment by davesnx** [comment]
I'm sorry but the bug states perfectly like the following: `plugins: ["collapseGroups", , ]` causes a TypeError. It's a common pattern in JS to filter an array and it produce an array of 3 items but 2 of the are empty.

**Comment by SethFalco** [comment]
> the bug states perfectly like the following: `plugins: ["collapseGroups", , ]`

Ahh, you're right. Honestly, I didn't know this syntax could be used outside destructuring an array, so I thought it was a typo. I should've tested it as-is.

Thanks for clarifying this for me.
