### ISSUE TITLE
There is a bug when it comes to require

### ISSUE THREAD

**Issue by louiss0** [svg/svgo#1741]
**Describe the bug**

I was using a library called astro-icon but this is what I got. As you can see this is a bug that has something to do with this library. 

```
require is not defined
C:\Users\louis\Desktop\web-projects\ui\press-cms-clone\C:\Users\louis\Desktop\web-projects\ui\press-cms-clone\node_modules\.pnpm\svgo@2.8.0\node_modules\svgo\lib\svgo-node.js:3:12
> 3 | const os = require('os');
    |            ^
  4 | const fs = require('fs');
  5 | const { pathToFileURL } = require('url');
  6 | const path = require('path');
ReferenceError: require is not defined
    at /node_modules/.pnpm/svgo@2.8.0/node_modules/svgo/lib/svgo-node.js:1:12
    at instantiateModule (file:///C:/Users/louis/Desktop/web-projects/ui/press-cms-clone/node_modules/.pnpm/vite@3
```

**To Reproduce**
1. Go to [Example Astro icon Project With failed svg  ](https://stackblitz.com/edit/withastro-astro-4vejjq?file=src%2Fpages%2Findex.astro)
3. Scroll down to `<AstroIcon />`
4. See error on the right side of the screen.

**Expected behavior**
I expected Astro Icon to work and make the SVG icon appear but it did not work. 

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version [e.g. 2.0.3]
 - NodeJs Version [e.g 18.12.1]
 - OS: [e.g. Windows]
 
**Additional context**

**Comment by TrySound** [comment]
Hey
I can see the icon on stackblitz. No errors

**Comment by louiss0** [comment]
> Hey I can see the icon on stackblitz. No errors

So do I What do you think happened. I can't belive this. Well I'll close this issue then

**Comment by TrySound** [comment]
This looks like vite is trying to bundle svgo for some reason. Though I don't think this should happen. Maybe some entry point of icon library is not right.
