### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by ainsleyclark** [svg/svgo#1744]
**Describe the bug**
Parsing SVG file throws an error: `Error: SvgoParserError Non-whitespace before first tag.`

**To Reproduce**
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="11.483" height="10.022" viewBox="0 0 11.483 10.022">
  <path id="Path_3905" data-name="Path 3905" d="M0,11.483,4.182,0H5.832l4.19,11.483H8.278L5.019,1.7l-3.3,9.779Z" transform="translate(11.483) rotate(90)" fill="#9a9a9a" opacity="0.599"/>
</svg>
```

Using node:

```typescript
svgo.optimize(file, {
    path: file,
    multipass: true,
} as Config);
```

**Desktop (please complete the following information):**
 - SVGO Version 3.0.2
 - NodeJs Version 18.13.0
 - OS: macOS Arm M1
 
**Additional context**

Steps tried to fix the problem:
- Checked there is no BOM character
- Validated that it's utf-8

**Comment by SethFalco** [comment]
> ```js
> const { optimize } = require('svgo');
> const result = optimize(svgString, {
>   // optional but recommended field
>   path: 'path-to.svg',
>   // all config fields are also available here
>   multipass: true,
> });
> const optimizedSvgString = result.data;
> ```
> 
> — https://github.com/svg/svgo#optimize

The `svgo#optimize` functions take an SVG string for its first parameter, not a file path. You can read the file in with `fs` and pass that along.
