### ISSUE TITLE
Missing optimization: RGB with percent values

### ISSUE THREAD

**Issue by walling** [svg/svgo#175]
I expect the following colors to be converted to a more concise form:

* `rgb(86.27451%,86.666667%,87.058824%)` to `#DCDDDE`
* `rgb(100%,100%,100%)` to `#FFF`
* etc.

This is the SVG output from Cairo (and in turn RSVG library). Right now I'm handling it with a regular expression; not as pretty as it could be:

```javascript
function percentValueToHex(value) {
  var hex = Math.round(value / 100 * 255).toString(16);
  return (hex.length === 2) ? hex : (hex.length === 1) ? '0' + hex : '00';
}

function fixRGBColors(svg) {
  return svg.replace(
    /rgb\(([\d\.]+)%,([\d\.]+)%,([\d\.]+)%\)/g,
    function(_, red, green, blue) {
      return '#' +
        percentValueToHex(red) +
        percentValueToHex(green) +
        percentValueToHex(blue);
    }
  );
}
```

**Comment by GreLI** [comment]
Actually, specification defines only integers in ``rgb()`` function, but done.
