### ISSUE TITLE
Don't encode quotes to entities in <script> and <style>

### ISSUE THREAD

**Issue by Tyriar** [svg/svgo#176]
By default any double quotes `"` withing a `<script>` element are converted to `&quot;`, increasing the size of the resulting file.

**Comment by icek** [comment]
Same for `<style>` element and for single quote `'` which is encoded as `&apos;`

**Comment by MadLittleMods** [comment]
:+1: I have the same <style> mangle:

```
<style>
	.foo {
		fill: url('#som-svg-gradient');
	}
</style>
```

**Comment by shaneparsons** [comment]
+1 this is happening with quotes in a `tspan` as well.
e.g.

**input**
```
<tspan id="height">0'0"</tspan>
```

**output**
```
<tspan id="height">0&amp;apos;0&amp;quot;</tspan>
```

**Comment by jgonera** [comment]
This is messing up text in my SVGs. @shaneparsons did you find a workaround?

**Comment by dphil** [comment]
This was causing issues with single and double quotes in the style element of my svgs. I have not found an svgo-based solution, but a simple workaround that suffices for my case is to run a postprocessing step after svgo to find and replace the encoded quotes:
```
sed -i "s/&apos;/'/g;s/&quot;/\"/g" file.svg
```

**Comment by shaneparsons** [comment]
@jgonera This was a long time ago so it's hard to remember... But I'm pretty sure I just did a find / replace after the processing. e.g.

**find:** `&amp;apos;` **replace:** `'`
**find:** `&amp;quot;` **replace:** `"`

It's not ideal... but my svgs weren't updated often so it wasn't too bad.

**Comment by XhmikosR** [comment]
Confirmed this is still an issue, unfortunately :/ And it can break things as mentioned a couple of comments above.

**Comment by TrySound** [comment]
Which things this break exactly? Looks like browsers interpet html entities as normal characters. Styles and scripts with `&quot;` work fine.

**Comment by TrySound** [comment]
Closing until somebody provide a repro with visual regression
