### ISSUE TITLE
"svgo" seems to be incompatible with "node v20.x".

### ISSUE THREAD

**Issue by stein2nd** [svg/svgo#1774]
**Describe the bug**
I report that I ran "npm install svgo --save-dev" and got the following WARN.:

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.36.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@39.9.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.5.0', npm: '9.8.0' }
npm WARN EBADENGINE }

When I ran "npm install -D eslint eslint-plugin-jsdoc @es-joy/jsdoccomment" individually, no warn showed up.

eslint-plugin-jsdoc: 46.4.5
@es-joy/jsdoccomment: 0.39.4

**To Reproduce**
1. Using Terminal, run "npm install -D svgo".

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SVGO Version: 3.0.2
 - NodeJs Version: 20.5
 - OS: macOS Ventura 13.5
 
**Additional context**

**Comment by TrySound** [comment]
Hello. This package does not rely on those dependencies and have wide range for node. Something to do with npm. Maybe it detects only already installed packages or something.
https://github.com/svg/svgo/blob/main/package.json#L58

**Comment by stein2nd** [comment]
Thanks for the reply.
You are correct.
I should have run the "npm ls xxxxxxxx" command to find out "where the cause is".
