### ISSUE TITLE
`removeViewBox` override is not respected when optimizing

### ISSUE THREAD

**Issue by vaaas** [svg/svgo#1786]
**Describe the bug**

The `removeViewBox` override is not respected when optimizing. This results in viewBox always being stripped even when explicitly configured not to be.

**To Reproduce**

1. Use any SVG with a viewbox.
2. Execute the following code

```typescript
import * as svgo from 'svgo';
import * as fs from 'node:fs';
const code = fs.readFileSync('./your.svg').toString('utf-8')
const result = svgo.optimize(code, {
    plugins: [{
      name: 'preset-default',
      params: {
        overrides: {
          removeViewBox: false,
        }
      }
    }],
});
console.log(result);
```

**Expected behavior**

Viewbox should not be stripped.

**Desktop (please complete the following information):**
 - SVGO Version: `3.0.2`
 - NodeJs Version: `v20.6.1`
 - OS: Arch Linux `Linux 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC`
 
**Additional context**

Viewbox stripping should **not** be the default as it breaks SVG automatic scaling. SVG automatic scaling is the "S" in "SVG" and it's the quintessential feature. At the very least, please respect the 'removeViewBox' override.

**Comment by SethFalco** [comment]
Your exact configuration is working for me. 🤔
Could you test again and share more details, or the actual SVG that produced the issue?

```js
const svgo = require('svgo');
const file = `<svg xmlns="http://www.w3.org/2000/svg" width="11.483" height="10.022" viewBox="0 0 11.483 10.022"></svg>`;

const result = svgo.optimize(file, {
  plugins: [{
    name: 'preset-default',
    params: {
      overrides: {
        removeViewBox: false,
      }
    }
  }],
});

console.log(result.data);

// <svg xmlns="http://www.w3.org/2000/svg" width="11.483" height="10.022" viewBox="0 0 11.483 10.022"/>
```

> Viewbox stripping should not be the default as it breaks SVG automatic scaling. SVG automatic scaling is the "S" in "SVG" and it's the quintessential feature.

Yeah, there's been a lot of debate about this over at [#1128](https://github.com/svg/svgo/issues/1128). ^-^'  
It even netted itself a dedicated spot on our [README](https://github.com/svg/svgo#troubleshooting).

For now, I'm not going to get involved there, but later I will bring up the possibility of keeping `removeViewBox` disabled by default. I'm of the stance that that plugin is breaking SVGs, not optimizing them. It's a nice plugin, just maybe not a nice default.

It was [disabled before](https://github.com/svg/svgo/issues/139), so I don't see why it wouldn't be on the table to do again.  
For some reason, it was then [silently enabled again](https://github.com/svg/svgo/commit/055e303607d53a3d539761d8727d86c03b2e88c1) 3.5 years later, I don't see a discussion or PR about that.

**Comment by vaaas** [comment]
I double checked my file and the problem ended up being in the SVG file. Specifically it declared

`viewbox`

instead of

`viewBox`

(b was lower case)
