### ISSUE TITLE
I've created standalone binaries for SVGO v3.0.2 that don't require Node and runs faster than the Node version.

### ISSUE THREAD

**Issue by fmotion1** [svg/svgo#1789]
I was looking for binaries for SVGO that I could run independent of Node, but couldn't find any that were updated to the latest version (v3.0.2) So I made them using PKG. 

Here is the link: [SVGO-Binaries](https://github.com/fmotion1/SVGO-Binaries)

My repo above includes v3.0.2 of SVGO for both Windows and Linux. No installation required. Just copy the binary somewhere (preferably in a folder included in your PATH environment variable).

**Additional context**
There is another binary compilation hanging around on GitHub if you know where to look, but it's only version 2.8.0. Mine is the latest version of SVGO.

Hoping this helps someone! 

If this is the wrong spot to post this, let me know, and I will move it to the appropriate forum.

**Comment by SethFalco** [comment]
As we have an [**Other ways to use SVGO**](https://github.com/svg/svgo) on our README, normally I'd interpret this as a request to have your project added there.

However, as this is essentially an untrusted binary with no public source/build-steps available, I don't think it's something we (or at least I) can endorse/promote.

Closing this as it's not an issue, just self-promotion, and very dangerous, actually. ^-^'

**Comment by fmotion1** [comment]
I would be happy to post the source and commands used to generate the binary so users can create it themselves from source. I am by no means trying to promote myself. All I did was compile SVGO with [PKG](https://github.com/vercel/pkg). It's very easy to do, and the binary runs a hell of a lot faster than the Node.js native version. The only reason I posted here was so others could benefit. Your sentiment of this being "dangerous" is understood - but a bit misguided. I'll update the repo soon with concrete build steps to... alleviate your fears.

**Comment by pa-0** [comment]
@futuremotiondev  it looks like the link you shared is broken... did you ever end up publishing the code?

**Comment by eartahhj** [comment]
I am also interested in this

**Comment by futuremotiondev** [comment]
Sorry, I never really got around to it...

I didn't realize until later that some of the features of SVGO weren't working properly with the PKG'd binary version. Config files weren't working as expected and some other wonky issues cropped up. I also upgraded my PC and now the native node version runs _extremely_ fast, so I just stuck with the typical install. 

However - if you really want to compile SVGO into an executable, take a look at the new [Single Executable Applications](https://nodejs.org/api/single-executable-applications.html) feature that was just released. It looks really promising and all the documentation is right there in the link.
