### ISSUE TITLE
removeComments Plugin not working as expected.

### ISSUE THREAD

**Issue by fmotion1** [svg/svgo#1811]
**Describe the bug**
I want to remove comments from my SVG files:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
<!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license Copyright 2023 Fonticons, Inc.-->
  <path d="M384 64c17.7 0 32 14.3 32 32v320c0 17.7-14.3 32-32 32H64c-17.7 0-32-14.3-32-32V96c0-17.7 14.3-32 32-32h320zM64 32C28.7 32 0 60.7 0 96v320c0 35.3 28.7 64 64 64h320c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm160 96a128 128 0 1 1 0 256 128 128 0 1 1 0-256zm0 288a160 160 0 1 0 0-320 160 160 0 1 0 0 320zm0-136a24 24 0 1 0 0-48 24 24 0 1 0 0 48z"/>
</svg>
```

The `removeComments` plugin is supposedly enabled by default, but the comments remain after processing. This is what I want to remove:

```svg
<!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license Copyright 2023 Fonticons, Inc.-->
```

**To Reproduce**

1. Create svgo.config.js as outlined:

```js
// svgo.config.js
module.exports = {
    multipass: true,
    js2svg: {
      indent: 2, 
      pretty: true,
    },
    plugins: [  
        { name: 'removeComments' }
    ]
  };
```

2. Run `svgo --config=svgo.config.js "FontAwesome Free 6 Light Album Circle Plus.svg"`
3. Open the resulting SVG and notice that the comment is still present.

**Expected behavior**
All comments to be nuked from the SVG file.

**Desktop (please complete the following information):**
 - SVGO Version 3.0.2
 - NodeJs Version v20.8.0
 - OS: Windows 10 Pro x64 Version 22H2 (Build 19045.3448)
 - 
**Additional context**
Not sure what I'm doing wrong. All I want to do is strip comments.

**Comment by fmotion1** [comment]
**Update:** 

It works if I open `removeComments.js` in `Roaming\nvm\v20.8.0\node_modules\svgo\plugins` and then comment out the conditional: `if (node.value.charAt(0) !== '!')`

I think the problem is, since the comment starts with an `!`, `removeComments` doesn't eliminate it by default. But this is really hackish. I don't want to edit plugin definitions in fear of breaking things. 

Is there a way to do what I need without editing the `removeComments` plugin definition file?

**Comment by SethFalco** [comment]
You aren't doing anything wrong with SVGO.

Unfortunately, the reason for this behavior isn't documented. However, we have test cases explicitly ensuring that comments beginning with `!` are left intact.

As I don't see a practical reason for it, but also want to preserve backward compatibility for now, I'd prefer to leave the default behavior as it is. Instead, I can add a parameter to `removeComments` to preserve comments that match certain patterns. Then you can override it to an empty array or false to disable preserving any comments.

I wanted to this anyway to preserve copyright/license notices anyway… which ironically is exactly what you're trying to remove.

Please refer to the warning I've left here:
https://svgojs.org/docs/plugins/remove-comments/

If you're paying for a Pro license, I think you're good. Keep in mind that if you aren't paying, then removing attribution may be a breach of the Font Awesome and Creative Commons licenses.

If you'd like an immediate solution, you can add a custom plugin for now:

```js
module.exports = {
  multipass: true,
  plugins: [
    {
      name: "customRemoveComments",
      fn: () => {
        return {
          comment: {
            enter: (node, parentNode) => {
              parentNode.children = parentNode.children.filter((child) => child !== node);
            },
          },
        };
      }
    }
  ],
};
```
