### ISSUE TITLE
Including new elements in SVG file

### ISSUE THREAD

**Issue by gtorodelvalle** [svg/svgo#185]
Hi guys,

First off, congrats for this magnificent project ;-)

My name is Germán Toro del Valle (https://github.com/gtorodelvalle/) and I work for Telefónica R&D in the development of Firefox OS (http://www.mozilla.org/en-US/firefox/os/) with Mozilla.

We are currently considering using SVGO to optimize the SVG images used not only in the so called Building Blocks (http://buildingfirefoxos.com/building-blocks/action-menu.html) but also in the core apps we are currently implementing.

To optimize our SVG files we would like to include some content in these files, more concretely:
```html
<defs>
  <style>
    svg>* { display: none; }
    svg>*:target { display: inline; }
  </style>
</defs>
```
as the first child of the <svg> element.

We tried to create a plugin to do it but it seems that SVGO does not currently support this kind of preprocessing so we end up creating a little Node.js app to do it. As a second option, we decided to fork https://github.com/svg/svgo-gui and include this preprocessing directly in the app, you can see it at https://github.com/gtorodelvalle/svgo-gui/tree/add-defs-preprocessing . The changes are as simple as https://github.com/gtorodelvalle/svgo-gui/compare/add-defs-preprocessing?expand=1 ;-)

Another option we have is of course creating Grunt or Gulp tasks to automate this 2 step process, of course.

After all this introduction, our question is: do you plan to include the possibility of inserting content (elements with additional content) in SVGO at some time via the API, probably via an addElement() or addContent() function such as the addAttr() one? :-)

Thank you  very much and congrats once again! ;-)

**Comment by GreLI** [comment]
Hi! Sorry for the late answer, I've missed somehow this issue.
Regarding the question, you're right, there is no such a method. It's not planned in short term, but probably will be added with reworked API. Unfortunately, the latter requires a lot of work, which we don't have enough time for.
