### ISSUE TITLE
Update link to playground

### ISSUE THREAD

**Issue by rdwz** [svg/svgo#1860]
Unfortunately, [`svgomg`](https://jakearchibald.github.io/svgomg/) hasn't been updated for a long time and still uses `svgo v3.0.0`
So I made a fork [`svgomfg`](https://omfg.svg.beauty) featuring the latest `svgo v3.0.4`

**Comment by SethFalco** [comment]
We're actually discussing this with [Jake Archibald](https://github.com/jakearchibald), the maintainer of SVGOMG, to get it up-to-date and resume maintenance!

The playground should be updated to use the latest version of SVGO soon.

Related: https://github.com/svg/svgo.dev/issues/2#issuecomment-1822643241
