### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by mariannekita** [svg/svgo#1921]
**Describe the bug**
I upload an SVG that I want to optimize and after downloading an extra line appears.

**To Reproduce**
I upload an SVG that I want to optimize and after downloading an extra line appears.

**Expected behavior**
Be the same SVG

**Screenshots**
good one
![6x6x1 7cm-16 36x11 2-cm](https://github.com/svg/svgo/assets/130167268/44eeb9ef-f6c6-4f3d-bd00-37ff9bfa6f77)

bad one
![6x6x1 7cm-16 36x11 2-cm](https://github.com/svg/svgo/assets/130167268/5dd7bd6b-895c-473f-a906-2bd201caacee)

![Screenshot 2024-01-02 132213](https://github.com/svg/svgo/assets/130167268/7fdf8f9e-a6d6-4693-bd59-bb95f1b2d0b3)
![Screenshot 2024-01-02 132234](https://github.com/svg/svgo/assets/130167268/97bdc33f-d8f5-4f52-a334-03d3a7cfd9c0)

**Desktop (please complete the following information):**

- SVGO Version [e.g. 3.0.0]
- NodeJs Version [e.g 14.0.4]

**Additional context**
Help setings

**Comment by KTibow** [comment]
The two SVGs you uploaded don't seem to represent the "input" and "output" from SVGO, so it's hard to find the problem.

**Comment by SethFalco** [comment]
>  I upload an SVG that I want to optimize and after downloading an extra line appears.

SVGO is a local tool. Without clear steps to reproduce, we also can't be certain if the issues lies with us, or something the online tool is doing. Some online tools are still using an outdated version of SVGO as well.

Can you clarify what online tool you used to optimize SVG?

**Comment by mariannekita** [comment]
SVGO is a local

**Comment by SethFalco** [comment]
@mariannekita Could you clarify how you optimized the vector, and share the input/output?

If you're unable to, I can close the issue for now, and you're welcome to create another one once you can provide steps to reproduce.
