### ISSUE TITLE
collapseGroups does not move attributes atomically

### ISSUE THREAD

**Issue by johnkenny54** [svg/svgo#1928]
One thing the collapseGroups plugin does is move all attributes from a `<g>` element to its child if it only has a single child. It appears that the code intends this to be an "all or none" move (i.e., if any attributes can't be moved, then no attributes are moved).

As currently implemented, the code will move attributes partially and unpredictably - it moves attributes to the child sequentially until it encounters an attribute that it can't move, then it stops moving attributes. So it is possible that only some attributes are moved, and which ones are moved depends on the order of attributes, which may be changed by other plugins.

This bug is one of the reasons for regression failure of \scalable\devices\media-flash.svg.

SVGO 3.2

**Comment by KTibow** [comment]
I see how this is something that should be fixed, but I don't see how this affects rendering. Can you make a MRE?

**Comment by johnkenny54** [comment]
PR with test case coming shortly.
