### ISSUE TITLE
Option to change props to React Pattern

### ISSUE THREAD

**Issue by supertgo** [svg/svgo#1971]
Is it possible to add a switch that coverts some dom properties to react pattern? Ex: clip-path will be converted to clipPath.

**Comment by KTibow** [comment]
That wouldn't be outputting as SVG. There are projects on GitHub that do this already though.

**Comment by SethFalco** [comment]
As KTibow says, this is out of scope for SVGO in favor of SVGR which has both a CLI and Webpack plugin. It should offer you a better user experience for that use case too.
