### ISSUE TITLE
Unable to install svgo@3.3.1

### ISSUE THREAD

**Issue by gaogaoinvincible** [svg/svgo#2000]
Github release svgo@3.3.1, bug in npm the svgo lastest version is 3.3.0, but 3.3.0 has TypeError: loadConfig is not a function

`pnpm view svgo versions`

[
  '0.0.1-2', '0.0.1-3', '0.0.1', '0.0.2',   '0.0.3', '0.0.4',
  '0.0.5-1', '0.0.5',   '0.0.6', '0.0.7-1', '0.0.7', '0.0.8',
  '0.0.9-1', '0.0.9',   '0.1.0', '0.1.1',   '0.1.2', '0.1.3',
  '0.1.4',   '0.1.5',   '0.1.6', '0.1.7',   '0.1.8', '0.1.9-1',
  '0.1.9',   '0.2.0',   '0.2.1', '0.2.2',   '0.2.3', '0.2.4',
  '0.3.0',   '0.3.1',   '0.3.2', '0.3.3',   '0.3.4', '0.3.5',
  '0.3.6',   '0.3.7',   '0.4.0', '0.4.1',   '0.4.2', '0.4.3',
  '0.4.4',   '0.4.5',   '0.5.0', '0.5.1',   '0.5.2', '0.5.3',
  '0.5.4',   '0.5.5',   '0.5.6', '0.6.0',   '0.6.1', '0.6.2',
  '0.6.3',   '0.6.4',   '0.6.5', '0.6.6',   '0.7.0', '0.7.1',
  '0.7.2',   '1.0.0',   '1.0.1', '1.0.2',   '1.0.3', '1.0.4',
  '1.0.5',   '1.1.0',   '1.1.1', '1.2.0',   '1.2.1', '1.2.2',
  '1.3.0',   '1.3.1',   '1.3.2', '2.0.0',   '2.0.1', '2.0.2',
  '2.0.3',   '2.1.0',   '2.2.0', '2.2.1',   '2.2.2', '2.3.0',
  '2.3.1',   '2.4.0',   '2.5.0', '2.6.0',   '2.6.1', '2.7.0',
  '2.8.0',   '3.0.0',   '3.0.1', '3.0.2',   '3.0.3', '3.0.4',
  '3.0.5',   '3.1.0',   '3.2.0', '3.3.0'
]

**Comment by gaogaoinvincible** [comment]
3.3.0 has TypeError: loadConfig is not a function

**Comment by SethFalco** [comment]
Hey hey! v3.3.0 has just been deprecated, please upgrade to v3.3.2 instead. Breaking changes were accidentally introduced in v3, which have been reverted and slated for SVGO v4.0.0.

Please see the releases tab for more info:
https://github.com/svg/svgo/releases

**Comment by XhmikosR** [comment]
@SethFalco could you maybe push your reverts to a branch along with the tags?

**Comment by SethFalco** [comment]
The tag is already pushed here: https://github.com/svg/svgo/releases/tag/v3.3.2

You can find the commits diff here:
https://github.com/svg/svgo/compare/v3.2.0...v3.3.2

Sorry, I didn't keep the branch around. I deleted it once the release was made. (I didn't actually revert, but rather made a new branch from the v3.2.0 tag and updated the version. I would've preferred to only remove the ESM migration, but that was buried in commits that depended on it.)
