### ISSUE TITLE
Artifacts when optimizing the same image second time

### ISSUE THREAD

**Issue by pasabanov** [svg/svgo#2059]
**Describe the bug**
When using SVGO a second time on the same image, the result contains some symbols appearing in unexpected places.

**To Reproduce**

1. Go to https://commons.wikimedia.org/wiki/File:Location_map_San_Francisco_Bay_Area.svg
2. Click on 'Download'
3. Click on 'Full resolution'
4. Go to downloads folder
5. Execute `svgo Location_map_San_Francisco_Bay_Area.svg`
6. Execute `svgo Location_map_San_Francisco_Bay_Area.svg` a second time
7. Open the image and see some symbols appearing in unexpected places

**Expected behavior**
No artifacts.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/66dbd251-1e91-48ad-b47c-d1a86f9460f0) ![изображение](https://github.com/user-attachments/assets/d59ad300-7dc8-49c7-9f3f-9b7153198e5e)

**Desktop (please complete the following information):**

- SVGO Version 3.0.2
- NodeJs Version 12.22.9
- OS: Linux Mint
- Installation method: Snap package

**Comment by pasabanov** [comment]
I have tested it on the latest version installed through npm: the bug disappears.

**Comment by SethFalco** [comment]
Glad the issue resolved itself from updating! We've fixed _a lot_ of bugs since v3.0.2, so that makes sense.

I'll close this as solved, but feel free to open another issue if anything else comes up.
