### ISSUE TITLE
Export the `Output` type to be directly importable

### ISSUE THREAD

**Issue by joaopalmeiro** [svg/svgo#2074]
Hi! 👋 

**Is your feature request related to a problem? Please describe.**

The `Output` type (the return type of the `optimize()` function) is not currently exported. As a result, this type cannot be directly imported for reuse in scripts/packages, unlike the `Config` type, for example: 

https://github.com/svg/svgo/blob/97d7d00add2643e9b4af016cd34d761a1e044b21/lib/svgo.d.ts#L69-L89

https://github.com/svg/svgo/blob/97d7d00add2643e9b4af016cd34d761a1e044b21/lib/svgo.d.ts#L91-L93

<img width="897" alt="image" src="https://github.com/user-attachments/assets/7c07aab4-b354-494f-ab84-1f13f9bc568a">

**Describe the solution you'd like**

If it makes sense, I would like to be able to import the `Output` type in conjunction with the `Config` type (I use SVGO mostly programmatically):

```ts
import type { Config, Output } from "svgo";
```

If I'm correct, the required change is as follows ([`svgo.d.ts` file](https://github.com/svg/svgo/blob/v4.0.0-rc.1/lib/svgo.d.ts)):

```diff
- type Output = {
+ export type Output = {
  data: string;
};
```

**Current workaround**

```ts
type Output = ReturnType<typeof optimize>
```

**Additional context**

- SVGO version: 4.0.0-rc.1

Let me know what you think and if I can open a PR. Thanks!

**Comment by SethFalco** [comment]
I think that makes sense!

I never ran into this issue as I never had to explicitly import or type a property/function with `Output`, but happy to see this scenario supported. Feel free to open a PR!

**Comment by joaopalmeiro** [comment]
> I think that makes sense!
> 
> I never ran into this issue as I never had to explicitly import or type a property/function with `Output`, but happy to see this scenario supported. Feel free to open a PR, and thanks for reporting the issue!

Thanks! On it.

Just for context, I came across this when putting together several utility functions into this package: https://codeberg.org/joaopalmeiro/svgo-utils
