### ISSUE TITLE
Combine translation transforms, and eliminate if the end result is no translation

### ISSUE THREAD

**Issue by dtrebbien** [svg/svgo#208]
I am using svgo 0.4.4.

In an SVG image that I created with Inkscape 0.48.4 r, the `<g>` element was translated by `translate(0,-924.36218)` and each of the `<path>`s were translated back by `translate(0,924.36218)`:

    <svg
       xmlns:dc="http://purl.org/dc/elements/1.1/"
       xmlns:cc="http://creativecommons.org/ns#"
       xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
       xmlns:svg="http://www.w3.org/2000/svg"
       xmlns="http://www.w3.org/2000/svg"
       xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
       xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
       width="128"
       height="128"
       id="svg2"
       version="1.1"
       inkscape:version="0.48.4 r"
       sodipodi:docname="New document 1">
      <defs
         id="defs4" />
      <g
         inkscape:label="Layer 1"
         inkscape:groupmode="layer"
         id="layer1"
         transform="translate(0,-924.36218)">
        <path
           sodipodi:type="arc"
           style="fill:#008000;stroke:none;stroke-width:4;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:none;fill-opacity:1"
           id="path2987"
           sodipodi:cx="64"
           sodipodi:cy="64"
           sodipodi:rx="56"
           sodipodi:ry="56"
           d="M 120,64 A 56,56 0 1 1 8,64 56,56 0 1 1 120,64 z"
           transform="translate(0,924.36218)" />
      </g>
    </svg>

svgo produced:

    <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">
        <path d="M120 64a56 56 0 1 1-112 0 56 56 0 1 1 112 0z" transform="translate(0 -924.362) translate(0 924.362)" fill="#008000"/>
    </svg>

The translation transforms should be combined, and then eliminated if the end result is no translation, as in this case.

**Comment by GreLI** [comment]
Well, in [v0.5.0](https://github.com/svg/svgo/releases/tag/v0.5.0) svgo doesn't combine transforms, but applies them to paths with ``arc`` command, so it's somewhat better.
