### ISSUE TITLE
CSS variables and media queries have been removed

### ISSUE THREAD

**Issue by ahaoboy** [svg/svgo#2082]
**Describe the bug**
CSS variables and media queries have been removed

**To Reproduce**
```
svgo ./a.svg -o ./b.svg
```

```svg
<svg width="300" height="100">
<style>
@media (prefers-color-scheme: dark) {
    body {
        --text-color: white;
        --background-color: black;
    }
}

@media (prefers-color-scheme: light) {
    body {
        --text-color: black;
        --background-color: white;
    }
}

body {
    color: var(--text-color);
    background-color: var(--background-color);
}

</style>
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" id="helloWorldText">Hello World</text>
</svg>
```

**Expected behavior**
Preserve CSS variables and media queries

**Screenshots**

```
<svg width="300" height="100"><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle">Hello World</text></svg>
```
**Desktop (please complete the following information):**

- SVGO Version 3.3.2
- NodeJs Version 22
- OS: win11

**Additional context**

Similar issues: https://github.com/svg/svgo/issues/1834

**Comment by johnkenny54** [comment]
In the example with this issue, it seems OK to remove the styles because they aren't used (they target the body element, and there is none).

The example file in issue #1834 still doesn't work in SVGO 4. There are a number of related issues which haven't been addressed.

I've been working on a spinoff of SVGO 4 which addresses some of the bugs and performance issues - https://www.npmjs.com/package/svgo-ll - that version handles the file in issue 1834 correctly.

**Comment by ahaoboy** [comment]
Thanks for your help. This reminds me that replacing body with svg can indeed solve the problem in the above example. However, svgo still seems unable to handle css variables and media queries.

```
<svg
  width="100px"
  height="100px"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
>
  <style>
    tspan {
      font-variant-ligatures: none;
      dominant-baseline: central;
      font-variant-ligatures: none;
      white-space: pre;
      font-family: Consolas, Courier New, Monaco;
      font-size: 32px;
    }
    svg {
      color-scheme: light dark;
      background-color: #ffffff;
    }
    svg > text {
      fill: #000000;
    }

    @media (prefers-color-scheme: dark) {
      svg {
        background-color: #181818;
      }
      .black {
        fill: #e5e5e5;
      }
      svg > text {
        fill: #e5e5e5;
      }
    }
  </style>
  <text x="0px" y="16px" width="20px" height="32px"><tspan>hello world</tspan></text>
</svg>

```

**Comment by ahaoboy** [comment]
disbale inlineStyles

```
module.exports = {
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          inlineStyles: false,
        },
      },
    },
  ],
};
```
