### ISSUE TITLE
SVGO removing <missing-glyph> element when <font-face> tag is self closing

### ISSUE THREAD

**Issue by thegoldentoilet** [svg/svgo#226]
I am running into a problem in Chrome where when a SVG is technically malformed according to http://validator.w3.org/check by not having the closing font-face tag.  This causes the missing-glyph element to be deleted out of the optimized SVG. This causes the font to not be recognized by the browser.

**Comment by GreLI** [comment]
Well, it's not a bug. Self-closing tags are perfectly legal in XML, it's more like a Chrome bug.
