### ISSUE TITLE
grunt-svgmin removes id from symbol tag

### ISSUE THREAD

**Issue by Homa** [svg/svgo#232]
I use symbol with id in my svg as it is described in the following link:
http://css-tricks.com/svg-symbol-good-choice-icons/

After magnifications all of my ids are removed from my svg file.

**Comment by kevinSuttle** [comment]
This doesn't work in the `svgo` cli. 
`svgo --cleanupids=false deploy/btn.svg`

Is there an equivalent in `svgo`.

**Comment by GreLI** [comment]
Plugins can be disabled with ``disable`` CLI: ``--disable=cleanupIDs`` as it written in “[How to use](https://github.com/svg/svgo#how-to-use)”.
