### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kevva** [svg/svgo#234]
You really shouldn't throw errors (https://github.com/svg/svgo/blob/master/lib/svgo/svg2js.js#L121) causing modules that consumes this module to break. Make use of callbacks (the right way) instead. What I mean by _i right way_ is that returning errors and actual data inside the same param isn't good practice. Ideally you would return it the "node way" with the error param first and actual stuff after, e.g (err, data, ...).

Currently you are doing it like [this](https://github.com/svg/svgo/blob/master/lib/svgo/svg2js.js#L120) and [this](https://github.com/svg/svgo/blob/master/lib/svgo/svg2js.js#L127). It would be nice if it were done like this instead:

```js
sax.onerror = function (err) {
    this.error = null;

    callback(err);
    return
};

sax.onend = function () {
    callback(null, root);
};
```

**Comment by GreLI** [comment]
Actually, without throwing, ``sax.onend`` will be executed just as ``sax.onerror``, so callback would be executed twice, second time like normal. ``return`` in your example does nothing.
