### ISSUE TITLE
Request: A plugin to convert text to svg paths

### ISSUE THREAD

**Issue by Melaga** [svg/svgo#237]
I was wondering if anyone has an idea on how the text to path works in apps like Illustrator or inkscape? And is it easy to make a plugin for svgo?

**Comment by GreLI** [comment]
It's an editing feature, not an optimization. Also it heavily depends on fonts, you basically need to render them, which is far out of scope.

**Comment by edouard-lopez** [comment]
@Melaga might have a look at [text-to-svg](https://github.com/shrhdk/text-to-svg)

**Comment by renanlecaro** [comment]
Inkscape has an --export-text-to-path option, it saved the day for me (it's quite fast) 
https://inkscape.org/sk/doc/inkscape-man.html
