### ISSUE TITLE
Allow `transformsWithOnePath` plugin to be applied repeatedly until no further changes occur

### ISSUE THREAD

**Issue by premasagar** [svg/svgo#242]
The `transformsWithOnePath` plugin is very useful. It simplifies shapes in a way that I cannot visually notice the change, but the amount of markup and the file size is reduced.

While optimising an image, I noticed that I could re-optimise the same image repeatedly, using `transformsWithOnePath` around 20 times and each time the image would be simplified more. After this many repetitions, the image was not simplified any further.

I was thinking that the plugin could automatically re-optimise images until no further changes occur, to achieve the smallest possible image. I'm not sure if this should be the default behaviour or if it should be available as an optional flag.

**Comment by GreLI** [comment]
There is a ``--multipass`` command-line option where introduced in [v0.5.0](https://github.com/svg/svgo/releases/tag/v0.5.0). I guess it should help.

**Comment by premasagar** [comment]
Yes, thanks. I saw that had been added. Closing....
