### ISSUE TITLE
"open" paths not processed correct by convertPathData

### ISSUE THREAD

**Issue by marcodings** [svg/svgo#255]
With "convertPathData: false" the following path for a letter O is generated which is "hollow" on the inside as its supposed to be

        <path id="path806" d="m 347.119,125.147 c 0,2.115 -0.357,4.229 -1.074,6.344 -0.717,2.115 -1.754,3.969 -3.115,5.564 -1.379,1.648 -3.039,2.971 -4.982,3.965 -1.941,0.994 -4.193,1.492 -6.754,1.492 -2.971,0 -5.385,-0.959 -7.236,-2.877 -1.854,-1.918 -2.779,-4.498 -2.779,-7.742 0,-2.383 0.393,-4.605 1.182,-6.666 0.787,-2.061 1.844,-3.871 3.168,-5.43 1.344,-1.559 3.004,-2.817 4.982,-3.776 1.977,-0.959 4.121,-1.438 6.432,-1.438 3.186,0 5.68,0.973 7.479,2.917 1.799,1.944 2.697,4.493 2.697,7.647 z 
		m -5.478,-1.023 c 0,-2.545 -0.453,-4.453 -1.355,-5.727 -0.904,-1.271 -2.207,-1.908 -3.908,-1.908 -1.486,0 -2.887,0.458 -4.203,1.371 -1.316,0.914 -2.447,2.402 -3.396,4.463 -0.734,1.561 -1.271,3.295 -1.611,5.203 -0.34,1.908 -0.51,3.67 -0.51,5.283 0,2.563 0.441,4.504 1.328,5.82 0.887,1.318 2.225,1.977 4.016,1.977 1.594,0 3.008,-0.502 4.242,-1.506 1.236,-1.004 2.238,-2.277 3.008,-3.818 0.77,-1.506 1.361,-3.23 1.773,-5.176 0.411,-1.943 0.616,-3.937 0.616,-5.982 z" fill="#3b84e7" transform="matrix(3.729 0 0 3.981 -585.996 -357.98)"/>

WITH the "convertPathData" NOT disabled, the following path is outputted

        <path id="path806" d="M708.47 140.274c0 8.42-1.333 16.837-4.006 25.257-2.674 8.422-6.54 15.803-11.617 22.154-5.142 6.56-11.333 11.828-18.58 15.786-7.237 3.957-15.635 5.94-25.185 5.94-11.08 0-20.082-3.818-26.985-11.455-6.913-7.636-10.363-17.908-10.363-30.823 0-9.488 1.466-18.334 4.408-26.54 2.935-8.205 6.877-15.412 11.814-21.62 5.012-6.206 11.202-11.214 18.58-15.032 7.37-3.818 15.367-5.725 23.985-5.725 11.882 0 21.182 3.873 27.89 11.613 6.71 7.74 10.06 17.888 10.06 30.446 z
     m-381.78-19.2c0-10.132-1.69-17.73-5.052-22.8-3.372-5.06-8.23-7.598-14.574-7.598-5.542 0-10.766 1.824-15.674 5.46-4.907 3.638-9.125 9.562-12.664 17.768-2.737 6.215-4.74 13.118-6.008 20.715-1.268 7.595-1.9 14.61-1.9 21.032 0 10.204 1.643 17.932 4.95 23.172 3.31 5.247 8.298 7.87 14.977 7.87 5.944 0 11.218-1.998 15.82-5.995 4.61-4 8.345-9.067 11.217-15.202 2.87-5.996 5.075-12.86 6.61-20.607 1.534-7.735 2.3-15.674 2.3-23.816z" fill="#3b84e7"/>

This show a solid O and and the centerpart that is supposed to be hollow displayed as solid to the left, see image

![14-10-18 16-12-13](https://cloud.githubusercontent.com/assets/3484222/4689882/8d534f12-56d1-11e4-8eb9-53d0301a28b6.jpg)

**Comment by GreLI** [comment]
[v0.5.0](https://github.com/svg/svgo/releases/tag/v0.5.0) should have fixed it. If not, please reopen.
