### ISSUE TITLE
`<path>` isn't visible after minification

### ISSUE THREAD

**Issue by pseudosavant** [svg/svgo#257]
I used SVGO to minify a LinkedIn icon (svg below) and the dot for the "i" was not visible after being processed. Scour was able minify it but the file wasn't quite as small as SVGO.

Here is the content of the pre and post processed files:

### linkedin.svgo.svg
	<svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 144 144" enable-background="new 0 0 568.291 144"><g><path d="M133.688.233H10.972C5.108.233.342 4.88.342 10.61v123.233c0 5.734 4.766 10.39 10.63 10.39h122.716c5.874 0 10.66-4.655 10.66-10.39V10.61c0-5.73-4.786-10.377-10.66-10.377z" fill="#0077b5"/><path d="M21.694 54.218h21.36v68.722h-21.36V54.218zm434.628-34.393c6.828 0 12.377 5.55 12.377 12.38 0 6.837-5.55 12.386-12.378 12.386-6.846 0-12.387-5.548-12.387-12.385 0-6.83 5.542-12.38 12.387-12.38" fill="#fff"/><path d="M56.45 54.218h20.485v9.39h.286c2.853-5.403 9.82-11.1 20.21-11.1 21.628 0 25.62 14.235 25.62 32.737v37.694h-21.343V89.52c0-7.97-.146-18.22-11.1-18.22-11.112 0-12.818 8.68-12.818 17.643v33.996H56.45V54.217z" fill="#fff"/></g></svg>

### linkedin.svg
	<?xml version="1.0" encoding="UTF-8" standalone="no"?>
	

	<svg
	   xmlns:dc="http://purl.org/dc/elements/1.1/"
	   xmlns:cc="http://creativecommons.org/ns#"
	   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	   xmlns:svg="http://www.w3.org/2000/svg"
	   xmlns="http://www.w3.org/2000/svg"
	   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
	   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
	   version="1.1"
	   id="Layer_1"
	   x="0px"
	   y="0px"
	   width="144"
	   height="144"
	   viewBox="0 0 144 144"
	   enable-background="new 0 0 568.291 144"
	   xml:space="preserve"
	   inkscape:version="0.48.5 r10040"
	   sodipodi:docname="linkedin.svg"><metadata
	   id="metadata3057"><rdf:RDF><cc:Work
		   rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
			 rdf:resource="http://purl.org/dc/dcmitype/StillImage" /></cc:Work></rdf:RDF></metadata><defs
	   id="defs3055">
		

			
		</defs><sodipodi:namedview
	   pagecolor="#ffffff"
	   bordercolor="#666666"
	   borderopacity="1"
	   objecttolerance="10"
	   gridtolerance="10"
	   guidetolerance="10"
	   inkscape:pageopacity="0"
	   inkscape:pageshadow="2"
	   inkscape:window-width="1920"
	   inkscape:window-height="1017"
	   id="namedview3053"
	   showgrid="false"
	   inkscape:zoom="5.7638889"
	   inkscape:cx="72.34468"
	   inkscape:cy="71.766953"
	   inkscape:window-x="-8"
	   inkscape:window-y="-8"
	   inkscape:window-maximized="1"
	   inkscape:current-layer="g3027" />
	<g
	   id="g3027"
	   transform="translate(-423.94432,0.23304697)">
				<g
	   id="g3029">
					<g
	   id="g3031">
						
						<g
	   id="g3035">
							
						</g>
						
						
						
						
					</g>
					<path
	   d="M 557.632,0 H 434.916 c -5.864,0 -10.629,4.648 -10.629,10.376 V 133.61 c 0,5.734 4.765,10.39 10.629,10.39 h 122.716 c 5.874,0 10.659,-4.655 10.659,-10.39 V 10.376 C 568.291,4.648 563.506,0 557.632,0 z"
	   id="path3047"
	   inkscape:connector-curvature="0"
	   style="fill:#0077b5" />
					<path
	   d="m 445.638,53.985 h 21.359 v 68.722 H 445.638 V 53.985 z m 10.684,-34.16 c 6.828,0 12.377,5.549 12.377,12.38 0,6.837 -5.549,12.386 -12.377,12.386 -6.846,0 -12.387,-5.549 -12.387,-12.386 10e-4,-6.83 5.542,-12.38 12.387,-12.38"
	   id="path3049"
	   inkscape:connector-curvature="0"
	   style="fill:#ffffff" />
					<path
	   d="m 480.394,53.985 h 20.485 v 9.39 h 0.286 c 2.852,-5.403 9.818,-11.099 20.209,-11.099 21.628,0 25.621,14.234 25.621,32.736 v 37.694 h -21.344 v -33.42 c 0,-7.969 -0.146,-18.22 -11.099,-18.22 -11.113,0 -12.819,8.681 -12.819,17.644 v 33.996 h -21.34 V 53.985 z"
	   id="path3051"
	   inkscape:connector-curvature="0"
	   style="fill:#ffffff" />
				</g>
			</g>
	</svg>

**Comment by christianhaller** [comment]
same here

**Comment by GreLI** [comment]
Closing, because ‘linkedin’ icon is ok in v0.5.0 and other comments don't have essential information.

**Comment by GreLI** [comment]
You should probably check in the new version [v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1).
