### ISSUE TITLE
Can't process folders

### ISSUE THREAD

**Issue by Lomacar** [svg/svgo#259]
I can optimize individual files but if I do something like: `svgo -f ./svg` it just says `C:\current\path\svg:`.

If I do `svgo -f ./svg -o min` it runs through all the files and says it has optimized each one, but there is no output folder and no output files.

I have also tried variations on input and output folder like `svg`, `/svg`, `/svg/`, `./svg/`, and `svg/`. And I have tried back slashes as well. I am using Windows 7 64-bit.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
