### ISSUE TITLE
petal isn't visible/filled after minification

### ISSUE THREAD

**Issue by kaihendry** [svg/svgo#260]
This is probably related to #257 

http://webconverger.org/img/2014/pushing-up-daisies.svg once minified has a missing petal on each of the flowers. I'm using 0.4.4 and I did also try `--disable=cleanupIDs`. Cheers!

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
