### ISSUE TITLE
Create a new element

### ISSUE THREAD

**Issue by raphdg** [svg/svgo#265]
I'm writing a plugin to wrap an existing `<text>` element into a `<g>` that doesn't exist yet.

Say I got this:

```
<text>MyText</text>
```

And I'd like to replace it with:

```
<g>
    <text>MyText</text>
</g>
```

How can I "create" this `<g>` item ?

I assume I should use `exports.type = 'full';` and iterate over the text elements, but I cannot find how to create this `<g>` element to wrap my `<text>` element, and then, putting it in the same position in my svg.

**Comment by GreLI** [comment]
Sorry for late response.
Actually, current [API](https://github.com/svg/svgo/blob/master/lib/svgo/jsAPI.js) isn't supposed to create elements. SVGO is created to remove extra, not to add.

**Comment by GreLI** [comment]
One can workaround by using `constructor` property:
```js
exports.fn = function(item) {
   var elem = new item.constructor({...});
}
```

**Comment by strarsis** [comment]
It is quite easily possible with even the existing/public jsAPI public functions.

This example adds a new style element to SVG as first element:
```js
var jsAPI = require('../lib/svgo/jsAPI');

[...]

    var svgElem  = data.content[0]; // reference to parent element

    var stylesEl = new jsAPI({
      elem:    'style',
      prefix:  '',
      local:   'style',
      content: [{
        text: '/* Test */'
      }]
    }, svgElem); // specify parent element, too, in constructor!

    svgElem.content.unshift(stylesEl); // add as first element to parent element
````
