### ISSUE TITLE
Ampersands doesn't get encoded

### ISSUE THREAD

**Issue by kevva** [svg/svgo#267]
When processing a perfectly valid SVG image with encoded ampersands (`&amp;`) they get replaced with raw ones which makes the image unrenderable.

We had to circumvent this using a regex to replace them https://github.com/imagemin/imagemin-svgo/blob/master/index.js#L37. Would be nice if svgo kept images valid when optimizing.

**Comment by GreLI** [comment]
Actually, they were already encoded, but I've slightly improved it.
