### ISSUE TITLE
Defaults slightly too agressive.

### ISSUE THREAD

**Issue by tomByrer** [svg/svgo#268]
I was testing SVGO for Twitter's twemoji's.  Using a screen shot of in-browser small rendering of over 100 SVG files, I XOR the [before & after of using SVGO via defaults](https://github.com/twitter/twemoji/pull/14#issuecomment-62618628).  I would say they are about 98% the same, which is excellent, and acceptable for many applications.  Even where there is only a single pixel off here & there, I would not worry.  But there are a few places where there is more than a tiny difference.

Should the defaults be a bit more 'safer' please?

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) has been just published. While I haven't seen errors in the v0.5.0, it helped a lot in a development. Thanks again!
