### ISSUE TITLE
Error "Invalid character entity" for any input file

### ISSUE THREAD

**Issue by keithkml** [svg/svgo#272]
Sample input file: https://dl.dropboxusercontent.com/u/49423508/windowpiece-18.svg

This error happens always on every file I've tried.

```
% svgo windowpiece-18.svg
Invalid character entity
```

**Comment by GreLI** [comment]
As a temporary solution I recommend to turn off «Preserve Illustrator Editing Capabilities» and some other advanced options, like including XMP, in Illustrator SVG saving dialog. These options make no sense—any extra will be stripped by svgo anyway.
