### ISSUE TITLE
removeUnknownsAndDefaults breaks image

### ISSUE THREAD

**Issue by booleanbetrayal** [svg/svgo#274]
No other overrides specified, calling through via `gulp-svgmin`. The end result is a completely blank (no visible strokes / fills) output image.

Disabling the `removeUnknownsAndDefaults` plugin fixes the issue. Presumable there's an "unknown unknown" in there somewhere.  =]

Here's a gist with the source image data - https://gist.github.com/booleanbetrayal/fa7b19ed5c4bfc39cb36

Hope this helps!

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.

**Comment by booleanbetrayal** [comment]
just verified! thanks @GreLI !
