### ISSUE TITLE
Silent failure on "Cannot read property 'coords' of undefined"?

### ISSUE THREAD

**Issue by jmhobbs** [svg/svgo#277]
I noticed the error "Fatal error: Cannot read property 'coords' of undefined" when using grunt-svgmin which calls out to svgo.optimize.

I started writing up a test case for that library, when I noticed that svgo itself silently fails on the same file.  No error, no new file created, and the ``<metadata>`` tag I stuck in the file doesn't get removed.

```
jmhobbs@venera:~/replicate ✪ ./node_modules/svgo/bin/svgo editwheelscroll.svg editwheelscroll.min.svg 
jmhobbs@venera:~/replicate ✪ ls
Gruntfile.js		editwheelscroll.svg	node_modules		package.json
jmhobbs@venera:~/replicate ✪ npm list svgo
replicate@1.0.0 /Users/jmhobbs/Desktop/replicate
└── svgo@0.5.0 
jmhobbs@venera:~/replicate ✪ node -v
v0.10.33
```

Here's the run with grunt-svgmin

```
jmhobbs@venera:~/Desktop/replicate ✪ grunt
Running "svgmin:dist" (svgmin) task
Fatal error: Cannot read property 'coords' of undefined
jmhobbs@venera:~/Desktop/replicate ✪ 
```

I'm on OS X, 10.10.1

The SVG passes validation: http://validator.w3.org/check?uri=http%3A%2F%2Fcl.ly%2F1Z2Y3k2o1Q0H%2Feditwheelscroll.svg&charset=%28detect+automatically%29&doctype=Inline&group=0

Example files are here: http://cl.ly/1V26152x3h3v

**Comment by GreLI** [comment]
I guess the reason is in ``<path fill="none" d="z"/>``, it was fixed recently.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.

**Comment by jmhobbs** [comment]
Thanks!
