### ISSUE TITLE
grunt-svgmin: using folder option

### ISSUE THREAD

**Issue by faeron** [svg/svgo#283]
Can anybody tell me to option to process a folder of svg files with the grunt task? Or do I have to specify each file separate a files array?

**Comment by alex-martinez** [comment]
I tried the **/*.svg method, but it doesn't seem to work. 

I'm currently listing the files individually. Please tell me you were you able to get it working.

**Comment by skullcrasher** [comment]
This is waht my files array looks like. It only handles svgs directly in the icons folder (no deeper steps)

    {
        expand: true,
        cwd: 'icons/',
        src: '*.svg',
        dest: 'icons/optimized', 
        ext: '.svg',
        extDot: 'first'
    }

**Comment by LeG3nDz** [comment]
Hi,

What is your config file ? don't work for me :(

**Comment by GreLI** [comment]
@LeG3nDz, you have to write an array of plugins:
```
    plugins: [
        { removeViewBox: false },
        { removeUselessStrokeAndFill: false }
    ]
```

**Comment by LeG3nDz** [comment]
@GreLI Thank you, it's okay :)
