### ISSUE TITLE
--multipass is strange

### ISSUE THREAD

**Issue by H1D** [svg/svgo#284]
As I understand `--multipass` should compress till result incompressible 
![image](https://cloud.githubusercontent.com/assets/697625/5321242/6f42caec-7cca-11e4-99ac-883f71f3a222.png)

Here is the file https://www.dropbox.com/s/epaxeyjsa90ty1f/stepic_logo_christmas_full.svg?dl=1

**Comment by GreLI** [comment]
I've changed the way rounding works, so a lot of minor changes with each pass are gone, thus `--multipass` gives final result in a few passes, just as it should be.

**Comment by GreLI** [comment]
[v0.6.3](https://github.com/svg/svgo/releases/tag/v0.6.3) with the change has been just released.
