### ISSUE TITLE
SVGO breakes this particular file

### ISSUE THREAD

**Issue by H1D** [svg/svgo#285]
After compressing [this](https://www.dropbox.com/s/epaxeyjsa90ty1f/stepic_logo_christmas_full.svg?dl=1) file white color changed to black.

P.S. by compressing I mean running SVGO 20+ time with `--multipass`. See #284

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.

**Comment by H1D** [comment]
:+1:
