### ISSUE TITLE
Not applying optional parameters of rotate()

### ISSUE THREAD

**Issue by romeovs** [svg/svgo#294]
I find that the `convertTransforms` plugin does more harm than good often. For instance, it converts [this](data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%22-100%20-100%20200%20200%22%3E%0D%0A%20%20%20%20%3Cpath%20d%3D%22M12.6%208.6l-3.1-3.2-3.1%203.2-.8-.7%203.9-3.9%203.9%203.9zM9%205h1v10h-1z%22%20transform%3D%22rotate%28-90%209.5%209.5%29%22%20%3E%3C%2Fpath%3E%0D%0A%3C%2Fsvg%3E):

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-100 -100 200 200">
    <path d="M12.6 8.6l-3.1-3.2-3.1 3.2-.8-.7 3.9-3.9 3.9 3.9zM9 5h1v10h-1z" transform="rotate(-90 9.5 9.5)" ></path>
</svg>
```

into [this](data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%22-100%20-100%20200%20200%22%3E%0D%0A%20%20%20%20%3Cpath%20d%3D%22M8.6-12.6L5.4-9.5l3.2%203.1-.7.8L4-9.5l3.9-3.9zm.4%2024.8v-1h10v1z%22%2F%3E%0D%0A%3C%2Fsvg%3E)

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-100 -100 200 200">
    <path d="M8.6-12.6L5.4-9.5l3.2 3.1-.7.8L4-9.5l3.9-3.9zm.4 24.8v-1h10v1z"/>
</svg>
```

This is a complety different image.

I'm guessing the math is off somewhere.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
