### ISSUE TITLE
`removeUnknownsAndDefaults` removes `type` attribute

### ISSUE THREAD

**Issue by laurent-le-graverend** [svg/svgo#297]
`type="translate"` is removed in this example by the plugin `removeUnknownsAndDefaults`.

This causes the animation to don't work on the svg.

```
<?xml version="1.0" encoding="utf-8"?>
<svg ...>
  <g>
    <path d="...">
      <animateTransform attributeName="transform" type="translate" ...></animateTransform>
    </path>
  </g>
</svg>
```

**Comment by GreLI** [comment]
``type="translate"`` is the default value, and thus correctly being removed. Are you sure that it's the real source of problem? Probably it's a bug in your software, or some other reason.

**Comment by khashayar** [comment]
I have the same issue, removing type ruins the way animation works.

**Comment by GreLI** [comment]
Sorry, without an example file there is nothing I can do.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
