### ISSUE TITLE
Merging overlapping paths causes "holes"

### ISSUE THREAD

**Issue by bfred-it** [svg/svgo#298]
Here's the input and output:

![original](https://cloud.githubusercontent.com/assets/1402241/5680526/3292bfe4-97c3-11e4-9232-6a325f1a6d6a.png) ![output](https://cloud.githubusercontent.com/assets/1402241/5680527/32962ba2-97c3-11e4-9e41-9c4a83487b50.png)

[SVGs download](http://cl.ly/ZEsx)

**Comment by GreLI** [comment]
Yeah, it's a known issue with ``mergPaths`` plugin.

**Comment by bfred-it** [comment]
Gotcha. I _solved_ I preventively merged the paths with Illustrator "Unite paths" command (Sketch's has a similar issue)

**Comment by rinatio** [comment]
+1

**Comment by paperboyo** [comment]
+1

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
