### ISSUE TITLE
Allow own attributes

### ISSUE THREAD

**Issue by sateffen** [svg/svgo#301]
Hi there,

in my project I'm using SVG as part of my templates, and want to optimize them with SVGO, but it removes important attributes.

I'm using knockout to bind behaviour to elements, so I'm using the "data-bind=..." attribute, but this gets removed.

Is it possible to configure a list of attributes, that should not get removed?

**Comment by GreLI** [comment]
There is ``removeUnknownsAndDefaults`` which can be disabled, like this:
```
svgo --disable=removeUnknownsAndDefaults -i <input_file> -o <optimized_file>
```

**Comment by sateffen** [comment]
Would this disable all removing?

If yes this would just be not a really cool thing, because other attributes should get removed.

I just think about it, maybe a knockout sensitive plugin would make sense.

Is there a possibility to load plugins from npm modules? Then I would write an external plugin, load it via npm in our CI, connect it with grunt (grunt-svgmin maybe?) and could use it this way.

**Comment by GreLI** [comment]
Yes, this plugin is responsible of removing of all unknown elements and attributes, also it removes attributes with default values.
The list of attributes is in [plugins/_collections.js](//github.com/svg/svgo/blob/master/plugins/_collections.js). You can add there your own.
Probably, it's a good idea not to remove data-* attributes.

**Comment by sateffen** [comment]
Removing data-bind="..." prevents knockout from working correctly^^

With other frameworks you define this binding-attributes by yourself, just like the names. It is a good way starting them with "data-*", but not all people do this. Think about angular or rivets together with SVG. So exluding patterns would be cool, for my case not removing "data-*" would be cool as well.

What do you think about that? Or what are your plans about this?

**Comment by GreLI** [comment]
No short-term plans (I just don't have time), but in long-term yes, it should be done.

**Comment by cibulka** [comment]
Big +1!

**Comment by cibulka** [comment]
+1!

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
