### ISSUE TITLE
Remove software's "signatures"?

### ISSUE THREAD

**Issue by bfred-it** [svg/svgo#302]
OS X app [Sketch](http://bohemiancoding.com/sketch/) saves its useless signature in every exported SVG file.

```svg
<desc>Created with Sketch.</desc>
```

I think it's safe to assume nobody really wants to have that in their minified file. Maybe this should be in the [removeEditorsNSData plugin](https://github.com/svg/svgo/blob/master/plugins/removeEditorsNSData.js). AI and Inkscape seem to only leave a simple comment.

**Comment by bfred-it** [comment]
No?

**Comment by GreLI** [comment]
See the commit, I've added a check and enabled a plugin. Will work in the coming next version.

**Comment by bfred-it** [comment]
Aaah, sorry, I didn't see that in the [CodeHub](https://itunes.apple.com/us/app/codehub-github-for-ios/id707173885?mt=8), I only saw that it was closed

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.

**Comment by bfred-it** [comment]
Thank you!

**Comment by GreLI** [comment]
Though I've forgot to mention it in the list of changes.
