### ISSUE TITLE
Entirely black after --multipass

### ISSUE THREAD

**Issue by GICodeWarrior** [svg/svgo#303]
svgo with the --multipass option breaks this image.

    http://synapticpt.com/wp-content/uploads/2015/01/top-logo.svg

The result is a black outline of the image.

Any ideas what is happening?

**Comment by GreLI** [comment]
I don't see a difference with the current version in the repo. Probably, you should wait for a new version. There was a bug fixed related to multipass, but it isn't released yet.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
