### ISSUE TITLE
Remove attributes with unbound namespaces / Remove invalid attributes

### ISSUE THREAD

**Issue by arteg** [svg/svgo#307]
SVGO now successfully removes Sketch namespaces, elements and attributes https://github.com/svg/svgo/pull/152

But we stumbled upon a case where [our svg file](https://gist.github.com/kizu/898304c5f02d741548e1) had `xmlns:sketch` removed by Illustrator effectively making the whole file invalid.
![](http://i.imgur.com/5075gDJ.png)

We could use some external find and replace tool to remove those attrs, but since SVGO successfully handles removal of all Sketch stuff _together_, it would be great to have a feature to _remove all attributes with undeclared namespaces_. Or maybe even all invalid attributes.

**Comment by GreLI** [comment]
It's an invalid XML, unfortunately. svgo can't process such a file, since parser declines it.
