### ISSUE TITLE
SVGO dies on the image

### ISSUE THREAD

**Issue by iliakan** [svg/svgo#309]
Here's the image:
https://gist.github.com/b9b2f5b7222be4dff803

What I'm doing is:
```
/js/javascript-nodejs
iliakan> svgo -i ~/svg/class-inheritance-array-object.svg -o 1.svg

/js/javascript-nodejs
iliakan> ls 1.svg
ls: 1.svg: No such file or directory
```

**Comment by GreLI** [comment]
That happens because svgo keeps IDs values in an object dictionary, and '__proto__' id rewrites prototype of the internal svg representation, thus breaking svgo work.

**Comment by iliakan** [comment]
Maybe release a new version with this fix?

**Comment by GreLI** [comment]
Yes, the new version is coming. Need to fix some other bugs too.

**Comment by iliakan** [comment]
Okay, looking forward to test it on my svgs :)

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
