### ISSUE TITLE
Api for duplicating element with all it's content

### ISSUE THREAD

**Issue by onlymega** [svg/svgo#311]
Please add the api for duplicating the element with all it's content or simply add a solution to create the svg element from JSON:

exports.fn = function(data, params) {
      return JSON.parse(JSON.stringify(data)); //not working right now
}

**Comment by jakearchibald** [comment]
This would help with SVGOMG, where I keep a clone to avoid having to reparse the SVG per settings change. I'm currently doing really hacky things & the `parentNode` change [broke the hack](https://github.com/jakearchibald/svgomg/blob/master/src/js/svgo-worker/main.js#L66).

I'm happy to create `JsAPI.prototype.clone` for this - any objections @GreLI?

**Comment by GreLI** [comment]
No objections. Pull-requests are welcome.
