### ISSUE TITLE
Group plugins by type so they can be disabled/enabled at once

### ISSUE THREAD

**Issue by bfred-it** [svg/svgo#312]
Sometimes it makes sense to apply non-destructive changes only, so if there was a `--non-destructive` flag or a `nonDestructive` _plugin_ that when enabled, destructive plugins will be disabled and only the whitespace and comments will be removed.

Other plugin groups could follow the same structure

**Comment by GreLI** [comment]
It's hard to say what is non-destructive. Is number rounding is non-destructive enough? Or changing XML structure? If yes what about whitespaces? Either of this is essential for effective optimizing.
I think there could be presets one if which is more careful.

**Comment by bfred-it** [comment]
Non-destructive means that no content and struction should changed, essentially comments, whitespace, doctype, [xml](https://github.com/svg/svgo/blob/master/plugins/removeXMLProcInst.js) — basically the standard behavior of _HTML_ minifiers

**Comment by GreLI** [comment]
An image cannot be optimized and be untouched in same time. Don't touch it with svgo if you don't want changes.

**Comment by bfred-it** [comment]
Do we agree that these two SVGs have the same content but one is lighter?

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<rect x="5.2" y="5.4" fill="#FFFFFF" stroke="#000000" stroke-miterlimit="10" width="28.5" height="28.5"/>
</svg>
```

```svg
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve"><rect x="5.2" y="5.4" fill="#FFFFFF" stroke="#000000" stroke-miterlimit="10" width="28.5" height="28.5"/></svg>
```

No attributes were touched, but by removing comments, doctype and whitespace it was reduced by 43%

I **need** svgo but sometimes I also need the integrity of the minified content to make it interactive or animated

**Comment by GreLI** [comment]
You've changed whitespace (line-breaks) and doctype there, while you've sad that it should not change.

**Comment by bfred-it** [comment]
No, no, there was a misunderstanding. That was an ambiguous phrasing of mine.
I meant to say _**only** comments, whitespace, doctype, xml **should be removed.**_

**Comment by GreLI** [comment]
Ok, this can be a careful preset as I said earlier. But there is no presents currently. Maybe somewhere in future.
