### ISSUE TITLE
In-(SVG-)file setting override

### ISSUE THREAD

**Issue by fregante** [svg/svgo#313]
I happen to use SVGs for animations and HTML clipping, among other things, so I rely on certain elements not being changed. Sometimes I just need the `id`s to be there, other times paths shouldn't be merged, etc. 

In-file settings overrides would help, perhaps:

``` xml
<svg width="14px" height="14px" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" >
    <!-- svgo: -cleanupIDs +removeViewBox -->
    <rect id="to-be-animated" x="0" y="6" width="12" height="3"/>
</svg>
```

For more complex SVGs you could just enable the [`nonDestructive`](https://github.com/svg/svgo/issues/312) plugin like so:

``` xml
<svg width="14px" height="14px" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" >
    <!-- svgo: +nonDestructive -->
    <rect id="to-be-animated" x="0" y="6" width="12" height="3"/>
</svg>
```

**Comment by una** [comment]
:+1: to this feature. It could also be a flag within the tag itself to skip optimization of that particular svg. i.e. an svgo or optimize property:

```
<svg svgo="false" width="14px" height="14px" viewBox="0 0 14 14">
    <rect id="whatever" x="0" y="6" width="12" height="3"/>
</svg>
```

**Comment by GreLI** [comment]
> i.e. an svgo or optimize property:

Sorry, I don't get it.

**Comment by una** [comment]
like in the svg tag: `svgo="false"` <-- because sometimes optimizing SVG's breaks added (hand-coded) functionality. In most cases, I want the majority of my SVG's optimized, but not all of them.

**Comment by GreLI** [comment]
Oh, I didn't noticed it. Why not a comment? Say, right after `<svg>` tag. It could also prevent optimisation of nested svgs for some purpose. (I plan to incorporate them in the host svg document, since sprites are sometimes made in a such way.)

**Comment by bfred-it** [comment]
Yeah I prefer comments inside tags. They don't get lost among other attributes.
