### ISSUE TITLE
Config file does not appear to have any effect

### ISSUE THREAD

**Issue by chrissound** [svg/svgo#315]
It seems regardless of what entries I have in my config file the file size remains the same. And takes pretty much the same amount of time to process.

How could I verify that my config file is being processed correctly?

In addition when I have a comment in my config file the following is output:
```
[3/5.0.7]{1}chris@archdev:~/Utils/svgo-cbas> svgo/bin/svgo -i initial.svg -o simplified.svg --config config.yml

/home/chris/Utils/svgo-cbas/config.yml:2
#  - removeDoctype
^

Done in 7171 ms!
```
Is this a syntax error being reported?

**Comment by GreLI** [comment]
It's been fixed already in the current version in the repo (a2f77ef, see line 130).

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.
