### ISSUE TITLE
Unable to use polygons

### ISSUE THREAD

**Issue by itsjustluck** [svg/svgo#316]
I'm am trying to run a hexagon in the form of a `<polygon/>` element through SVGO using SVGmin for Grunt.

**This is the SVG I am using in the form of hexagon.svg**
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
<polygon points="93,75 49.5,100 6,75 6,25 49.5,0 93,25 "/>
</svg>
```

**This is the console output from the grunt task**
```
grunt
Running "svgmin:dist" (svgmin) task
✔ dist/Untitled-5.svg (saved 288 B 71%)
Fatal error: Cannot read property 'value' of undefined
```
**Removing the polygon produces a .length error**
```
Fatal error: Cannot read property 'length' of undefined
```
This makes sense with no data to read.

**Removing the file allows `<path/>`, `<clipPath/>`, `<circle/>` and  others to run as expected.**

**Comment by GreLI** [comment]
Sorry, but I cannot find what's wrong with svgo.

**Comment by itsjustluck** [comment]
Do you mean that you can't duplicate, or you are unsure of what is causing the issue?

**Comment by GreLI** [comment]
Yeah, it looks good to me, I have no errors, and this error looks odd to me. Does disabling ``convertShapeToPath`` plugin solves the issue?
```
svgo --disable=convertShapeToPath
```
May be you should check your node.js version.

**Comment by GreLI** [comment]
Please, check out if the problem persists in [v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1).

**Comment by TadWohlrapp** [comment]
I get the same error when using @betsydupuis' code, but it works when you add the width and height attributes like this:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 100 100" width="100" height="100" enable-background="new 0 0 100 100" xml:space="preserve">
<polygon points="93,75 49.5,100 6,75 6,25 49.5,0 93,25 "/>
</svg>
```

**Comment by GreLI** [comment]
@TadWohlrapp, I see no errors with the latest SVGO version with or without widht/height.

**Comment by TadWohlrapp** [comment]
@GreLI, you're right. I confused it with https://jakearchibald.github.io/svgomg/ where the error currently occurres. Sorry for the mixup, I might have had too many tabs open at once.
