### ISSUE TITLE
Disabling cleanupIDs still removes id's

### ISSUE THREAD

**Issue by beckdavies** [svg/svgo#318]
I've encountered issues with gulp-svgmin stripping out id's even though I have set `cleanupIDs: false`. 

So, I used the svgo CLI and run
```
svgo --disable=cleanupids email.svg
```
on the following file
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="file-upload" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
	 y="0px" width="16.471px" height="20px" viewBox="0 0 16.471 20" enable-background="new 0 0 16.471 20" xml:space="preserve">
	<path d="M4.706,15.294h7.058V8.235h4.707L8.236,0L0,8.235h4.706V15.294z M0,17.648h16.471V20H0V17.648z"/>
</svg>

```
However, the ids are still being stripped from the svg element.

I am using the most up to date version of svgo, and my version of node is 0.10.26.

**Comment by GreLI** [comment]
I believe it's case-sensitive. I.e you have to write
```
svgo --disable=cleanupIDs email.svg
```

**Comment by beckdavies** [comment]
Thanks, I've just tried your suggestion and the ID's are still being removed. 

I've tested ID's on path as well as svg tags - both are removed.

**Comment by photoart-mtlwebdev** [comment]
Hi,
I'm having the same issue. I'm using it through gulp svgmin wrapper.
I've also tried these 2 formats:
```javascript
.pipe(svgmin({
        plugins: [{
            cleanupIDs: false
        }]
}))

.pipe(svgmin({
        plugins: [{
            cleanupIDs: {
                remove: false
            }
        }]
}))
```

I've also tried to add the ```full: true``` line to the options object with no luck.

**Comment by dbdr** [comment]
I found that disabling the **removeUnknownsAndDefaults** plugin fixes this issue for me (removing the id of the root svg element).

It's not ideal though, because that also disables some desired minification, and the behaviour is definitely not very intuitive.

**Comment by GreLI** [comment]
Oh, I haven't noticed that it was root <svg> tag. I'll look into this. Thanks for the input!

**Comment by GreLI** [comment]
Well, there is a special option to keep SVG id named ‘SVGid’, so it's not a bug, just disable it:
```
  - removeUnknownsAndDefaults:
      SVGid: false
```

**Comment by dbdr** [comment]
Thanks for the info, great if it's possible to do. The naming of the options is still confusing though. Would it be reasonable to make removeUnknownsAndDefaults not touch the SVGid, and move that task to cleanupIDs?

**Comment by GreLI** [comment]
I guess so, but I haven't find out why cleanupIDs doesn't remove it itself. There is no special exception.

**Comment by GreLI** [comment]
I was wrong, ``cleanupIDs`` removes the id, so it's double work, thus removing redundant code.

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with the fix has been just published.

**Comment by kopax** [comment]
Hi, I am trying to keep my IDs, because the CSS and JS customization for my animation are made outside the svg, is that possible ?

**Comment by tansanDOTeth** [comment]
Is there a fix for this? I need to preserve the ID and I already am using `cleanupIDs: false`

**Comment by JumpLink** [comment]
@kopax Yes by disable the `cleanupIds` plugin, see [here how you can disable plugins from the default present](https://svgo.dev/docs/preset-default/#disable-a-plugin). Or by setting the `remove` parameter to `false`, [see here](https://svgo.dev/docs/plugins/cleanup-ids/).
