### ISSUE TITLE
How can I change the default setting?

### ISSUE THREAD

**Issue by ganlanyuan** [svg/svgo#319]
Hello,
Thanks for your great job!
I have a question: which file ( and where is this file ) should I modify to change the default setting?
I install it by 
````
$ [sudo] npm install -g svgo
````

Thanks

**Comment by GreLI** [comment]
Default settings are in [svgo.yml](/svg/svgo/blob/master/.svgo.yml). You may create your own YAML (or JSON) config file to extend the config with ``--config`` command-line key:
```
svgo --config=custom.yml
```

**Comment by ganlanyuan** [comment]
Hi, thanks for your help.

I run 
````
svgo --config=custom.yml
````
on Terminal, but I didn't see this .yml file been created.
I also found `.svgo.yml` in package folder. And I changed 
````
- removeTitle
- removeDesc
````
to 
````
- removeTitle: true
- removeDesc: true
````
but when I run `svgo`, it didn't cleanup the `title` and `desc`.
Do you know why?

Thanks

**Comment by Fuffi** [comment]
I have the same problem, removeTitle and removeDesc do not work

**Comment by Fuffi** [comment]
@ganlanyuan can you try to add --multipass to your command line? It fixed the issue for me!

**Comment by ganlanyuan** [comment]
You mean?
````
svgo --config=custom.yml --multipass
````

**Comment by Fuffi** [comment]
Yes, clearly I added more parameters for input and output files...

More specifically I used --config="custom.yml", with quotes

**Comment by ganlanyuan** [comment]
I still can't get this done.
But thanks a lot!
I can use `svgo -f /Users/path/svg --enable removeTitle --enable removeDesc` manually.

**Comment by Fuffi** [comment]
FYI I also have put all the options in the : false and : true format

**Comment by GreLI** [comment]
Do you have
```
plugins:
```
string at the beginning of your YAML config file?
It's essential for setting plugin parameters.

**Comment by GreLI** [comment]
Check out if the problem persists in [v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1).

**Comment by optimix-designer** [comment]
Hello Lev,
First of all, thaks a lot for this great tool! :)
I tried to implement some custom settings to not disable several features like removing a viewbox. However, my attempts failed. 
I've created a `custom-svgo.yml` file with the following code inside:
```
# Custom settings
# Rewriting some default settings

var config = {
  plugins: [{
    removeViewBox: false,
  }]
}
```
Then I sent the following command:
`svgo --config="/file/location/custom-svgo.yml"`

But it didn't work. Tried to place it in different locations, with and without quotes, with and without '--multipass' option as others suggested – nothing helped :( Each time I get an article how to proper set a query:

![screenshot at apr 29 23-55-18](https://user-images.githubusercontent.com/3405378/39410939-d03a39dc-4c08-11e8-8707-7f047c3b2d36.png)

Can you please help me to figure out what I'm doing wrong? Thank you in advance!

**Comment by GreLI** [comment]
@optimix-designer Config should be an yml or JSON file.
```json
var config = {
```
is obviously none of these. Try for example
```
{
  plugins: [{
    removeViewBox: false,
  }]
}
```

**Comment by swinggraphics** [comment]
What I am trying to do, and what I think others here are trying to do, is change the defaults so that every time svgo is run it uses our settings. Modifying the settings every time with --config is not an option.
