### ISSUE TITLE
SVGO removes fill attribute from mask, produces different image

### ISSUE THREAD

**Issue by tobiastom** [svg/svgo#320]
SVGO seems to remove all `fill` attributes from the `mask` element. As you can see in http://jsbin.com/noroca/2/ this produces some different image. The background is not applied to the mask so the mask is not used for the elements.

With the help of https://jakearchibald.github.io/svgomg/ I was able to find the plugin that removes this attribute: Remove unknowns & defaults.

I tried to find the correct location to add this feature to https://github.com/svg/svgo/blob/master/plugins/removeUnknownsAndDefaults.js but did not find the correct spot. Adding the mask attribute to https://github.com/svg/svgo/blob/64304f3a4d3ca28b244fa7112bc2708138dba62e/plugins/_collections.js#L1387 does not seem to be enough. :)

**Comment by GreLI** [comment]
Yeah, it's been already fixed in #217, that's why you couldn't locate it.

> Adding the mask attribute to _collections.js#L1387 does not seem to be enough. :)

Yes, because it's already there under the 'presentation' group. (That was the fix.)

**Comment by tobiastom** [comment]
Great, thank you for the info. I'll close this one.
