### ISSUE TITLE
Two plugins seem to be buggy

### ISSUE THREAD

**Issue by Fuffi** [svg/svgo#322]
Some of our icons are breaking when enabling these two options: collapseGroups and removeNonInheritableGroupAttrs

Please test it yourselves with this file:
https://gist.github.com/Fuffi/f6e039071d21e3f2f88c

**Comment by GreLI** [comment]
What do you mean by saying “when enabling”? These plugins are enabled by default and I don't see any breaking in v0.5.0

**Comment by Fuffi** [comment]
I use a custom config file that enables everything except for those tu, when I enable them they corrupt the image (the lens disappears making the vector basically in the shape of a rectangle.

I reproduced this problem on two different machines, tomorrow I will double check the versions installed.

**Comment by Fuffi** [comment]
Have you tested the file I linked? It breaks even using svgomg website.

**Comment by GreLI** [comment]
I tried with ``disable={collapseGroups,removeNonInheritableGroupAttrs}`` and this didn't have any effect except slightly increase in file size. Are you using the latest version?

**Comment by GreLI** [comment]
Probably, you've enabled some plugins disabled by default. There is an image manipulation plugin that shouldn't be enabled 'til you are know what are ou doing.

**Comment by Fuffi** [comment]
It works with all options except these two

**Comment by GreLI** [comment]
What do you mean? Can you describe steps which you've done?

**Comment by Fuffi** [comment]
1) Open https://jakearchibald.github.io/svgomg/
2) Upload the file I linked earlier: https://gist.github.com/Fuffi/f6e039071d21e3f2f88c
3) Enable "Remove useless stroke & fill"
4) Notice how part of the original image disappeared

**Comment by Fuffi** [comment]
Second bug:
1) Open https://jakearchibald.github.io/svgomg/
2) Upload the file I linked earlier: https://gist.github.com/Fuffi/f6e039071d21e3f2f88c
3) Enable multipass
4) Enable "Collapse useless groups"
5) Notice how part of the original image disappeared

**Comment by GreLI** [comment]
Ah, it's totally differrent plugin. It's been fixed recently in d3e4f63ae51ca62377b8fd8a1e9adf5781ceee19. Will be in new version soon.

**Comment by GreLI** [comment]
> Second bug:

Don't see any bugs. "Collapse useless groups" is enabled by default as I mention earlier.

**Comment by GreLI** [comment]
> 3) Enable multipass

Multipass also had some fixes.

**Comment by Fuffi** [comment]
Good news, and now you have a couple of good reproduction cases if you wanna test your next release

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) has been just published.
