### ISSUE TITLE
Icons that cannot be optimized (attached files)

### ISSUE THREAD

**Issue by onlymega** [svg/svgo#324]
This two icons cannot be optimized using svgo:
https://dl.dropboxusercontent.com/u/1730358/svgo_issue_15939.svg
https://dl.dropboxusercontent.com/u/1730358/svgo_issue_76248.svg

**Comment by GreLI** [comment]
I don't see any problems with the first image (with car). But the second one quite interesting. Looks like ``<g>`` should be preserved inside ``<switch>`` (useless in this particular image, but whatever).

**Comment by GreLI** [comment]
[v0.5.1](https://github.com/svg/svgo/releases/tag/v0.5.1) with this fix has been just published.
