### ISSUE TITLE
Plugin Request: Strip width and height attributes from rootmost <svg> element

### ISSUE THREAD

**Issue by baloneysandwiches** [svg/svgo#325]
First: thanks, this is *awesome*.

Stripping height and width would be super-useful for responsive design, where you don't want to declare any fixed dimensions, and set dimensions instead using CSS. Note however that nested svgs should keep their explicit dims, because they get calculated within the parent viewBox. So it should just be on the rootmost.

You could call it "responsive.js" or something like that?

**Comment by GreLI** [comment]
Well it has a long history. Initially svgo did something like this, but it was considered bad practice and it can break expectations: e.g. someone might expect icon to have fixed size in CSS background. There is even a pull-request #196, but it needs some checks.

**Comment by baloneysandwiches** [comment]
Thanks, I didn't that. I will comment there.
