### ISSUE TITLE
Plugin Request: nuke classes and nuke ids

### ISSUE THREAD

**Issue by albell** [svg/svgo#326]
For a purpose like svg-as-img, these are often unnecessary cruft. Would be nice to be able to remove entirely.

**Comment by GreLI** [comment]
Well, unused ids are already being stripped. For classes svgo just don't understand CSS in ‘style’ tag, unfortunately.

**Comment by GreLI** [comment]
[`removeAttrs`](https://github.com/svg/svgo/blob/master/plugins/removeAttrs.js) plugin should do the job.
