### ISSUE TITLE
removeHiddenElems breaks SVGOMG example

### ISSUE THREAD

**Issue by jakearchibald** [svg/svgo#333]
http://jakearchibald.github.io/svgomg/test-svgs/car-lite.svg

The number plate and front grill disappear.

I've disabled the plugin by default https://github.com/jakearchibald/svgomg/commit/13b9934ffc6abeea61e437483edca28b72445a41

**Comment by jakearchibald** [comment]
Wow that was fast

**Comment by GreLI** [comment]
Just seen you had errors in svgomg's commits, so I found the error and fixed it. Unfortunately, I forgot about this multiple 'M' data trick in SVG when I made this check.

**Comment by beam2web** [comment]
Hello GreLI,

i drawed a logo with Inkscape and optimized it with the grunt-svgmin plugin. When i set the option removeHiddenElems: true, i missed some lines, but in the original the lines aren´t hidden. Here are my testfiles:

http://beam2web.com/removeHiddenElems/compare.png
http://beam2web.com/removeHiddenElems/before.svg
http://beam2web.com/removeHiddenElems/after.svg

Maybe the trouble comes from the kind of drawing the logo, but i'm not sure, what i should change.

**Comment by GreLI** [comment]
@beam2web, v0.5.2 has been just released–it should be fixed there.
