### ISSUE TITLE
Don't use --precision for 'convertTransform'

### ISSUE THREAD

**Issue by jakearchibald** [svg/svgo#334]
I tried this for SVGOMG, but found that it [broke appearance too much](https://github.com/jakearchibald/svgomg/blob/master/src/js/svgo-worker/main.js#L127). Rounding transforms seems to have a far greater effect than on other properties.

I haven't tried it, but maybe the precision for `convertTransform` could be +1 or +2 of the value passed to `--precision`.

**Comment by GreLI** [comment]
I've made ``transformPrecision`` parameter with default value is 5. Since transformations are multiplying on values, something 5 digits seems to be a good choice to meet 2+3 (or 3+2) usual coordinates digits

**Comment by GreLI** [comment]
I've greatly reworked transformation–it makes sense to split matrix into simple transforms, and deployed in [v0.5.2](/svg/svgo/releases/tag/v0.5.2). Enjoy!
