### ISSUE TITLE
Error in parsing: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by nhusher** [svg/svgo#336]
Running the path merging minifcation step on certain images fail.

*Expected result:* minified svg data.
*Actual result:* `{ error: 'Error in parsing: Cannot read property '0' of undefined' }`

See: https://github.com/svg/svgo/pull/337 for an example image that causes it to fail, and a test case to cause it.

**Comment by GreLI** [comment]
Fixed in ae2981cdea6696124587e9c39906ea90312aaf83.

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
