### ISSUE TITLE
New version of svgo deletes the path node

### ISSUE THREAD

**Issue by anelook** [svg/svgo#339]
After apdating svgo to the latest version we noticed that at least in one scenario we loose a path node in svg after its minimisation. With version of svgo 0.5.0 everything works correctly.

This is an example of svg where for some reason svgo removes the path node:

https://drive.google.com/file/d/0B5-9CLbdcvLNWERwV2d4S2VvNEk/view?usp=sharing

Is there any known reason why this might happen? 

Thanks,
Olena

**Comment by GreLI** [comment]
I don't understand what's the problem. The file you've provided is being optimized correctly (only removing redundant transform).

**Comment by rmaksim** [comment]
same problem with 0.5.1
```
<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13">
  <g transform="translate(0,-1039.3622)">
    <path
       d="m 1,1050.3622 -1,-1 10,-10 1,1 z m -1,-10 1,-1 10,10 -1,1 z"
       style="fill:#f00;" />
  </g>
</svg>
```
optimized into
```
<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13"/>
```
in 0.5.0 it was
```
<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13">
    <path d="M1 11l-1-1L10 0l1 1zM0 1l1-1 10 10-1 1z" fill="#f00"/>
</svg>
```

**Comment by GreLI** [comment]
Yeah, that's one fixed in b3ee51c7bcf20ded13d547f81de37e5cd353c4bd.

**Comment by insane-developer** [comment]
Will it fix same problem with this svg?
`<svg xmlns="http://www.w3.org/2000/svg" width="11" height="15"><path d="M 4,1 2,13 9,13 7,1 4,1 Z"/></svg>`
after svgo 0.5.1:
`<svg xmlns="http://www.w3.org/2000/svg" width="11" height="15"/>`

**Comment by GreLI** [comment]
Yes

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
