### ISSUE TITLE
--datauri=base64 -f dir/ doesn't work

### ISSUE THREAD

**Issue by kirillbunin** [svg/svgo#340]
Unlike inputing a single file, base64 encoding doesn't work for folders.

**Comment by owenhoskins** [comment]
+1

**Comment by GreLI** [comment]
I wonder, how do such base64 file look like?

**Comment by waldyrious** [comment]
@kirillbunin @owenhoskins can you provide more details on what it failing? This seems related to #552, so some commands like the ones there would be very helpful.
