### ISSUE TITLE
My SVG breaks when using the removeHiddenElems plugin

### ISSUE THREAD

**Issue by cooperaj** [svg/svgo#347]
I was using it but at some point recently (I nuked my node_modules folder for the first time in about a month) it stopped. I think it may be this commit: https://github.com/svg/svgo/commit/f651fd8de181c00ba21a023629f47aa22d9d3422

Image here https://gist.github.com/cooperaj/966c6a34ce6d391c74d7

**Comment by GreLI** [comment]
What do you mean by breaking?

**Comment by cooperaj** [comment]
Missing elements. In this case two missing letters (whilst the others are
fine) and a missing laser beam type affair. I’ve since disabled the plugin
and rebuilt so don’t have the broken image around. I can rebuild if you
like but the image linked in the gist above is the one that breaks.

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
