### ISSUE TITLE
missing lines with removeHiddenElems: true

### ISSUE THREAD

**Issue by beam2web** [svg/svgo#348]
Hello GreLI,

i drawed a logo with Inkscape and optimized it with the grunt-svgmin plugin. When i set the option removeHiddenElems: true, i missed some lines, but in the original the lines aren´t hidden. Here are my testfiles:

http://beam2web.com/removeHiddenElems/compare.png
http://beam2web.com/removeHiddenElems/before.svg
http://beam2web.com/removeHiddenElems/after.svg

Maybe the trouble comes from the kind of drawing the logo, but i'm not sure, what i should change.

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
