### ISSUE TITLE
Pattern fills getting removed

### ISSUE THREAD

**Issue by geoffyuen** [svg/svgo#353]
Sample file here: https://github.com/geoffyuen/geoffyuen.github.io/blob/master/test.svg

I batch optimized a bunch of svgs and noticed that pattern fills are being taken out. Is there no support for it?

**Comment by GreLI** [comment]
I guess it's an issue with inherited pattern which has been fixed recently. (Not released yet.)

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
