### ISSUE TITLE
Support buffer?

### ISSUE THREAD

**Issue by stevemao** [svg/svgo#354]
Its faster

**Comment by GreLI** [comment]
Can you explain?

**Comment by stevemao** [comment]
https://github.com/imagemin/imagemin-svgo/blob/master/index.js#L32
The buffer has to be converted to a string.
https://github.com/imagemin/imagemin-svgo/blob/master/index.js#L39
The string has to be converted back to a buffer.

These make things much slower when working with stream. 
https://github.com/creationix/jsonparse/blob/master/jsonparse.js is a streaming JSON parser and it might be a good example of working with streams.

**Comment by GreLI** [comment]
So, you're proposing to make streaming SVG parser or what? BTW, imagemin is a slightly different project.

**Comment by stevemao** [comment]
Yup

**Comment by GreLI** [comment]
There is actually an effort on writing parser–[SVGP](/svg/svgp). By I haven't look closely into it whether it possible to adopt streaming.

**Comment by GreLI** [comment]
Closing since no action can be done by now.
