### ISSUE TITLE
Use idiomatic callback?

### ISSUE THREAD

**Issue by stevemao** [svg/svgo#355]
Its more like a node way

``` js
svgo.optimize(String(file.contents), function (err, data) {
  if (err) {
    // do stuff with err
  }
  // do stuff with data
});
```

**Comment by soswow** [comment]
Or even use promises right away ;-)

**Comment by rpominov** [comment]
Just wondering why it's asynchronous in the first place? :smile:

**Comment by GreLI** [comment]
That's a major change, that will be changed only on rewriting. Anyway it'll be considered then.
