### ISSUE TITLE
cleanupIDs plugin broke my SVGs

### ISSUE THREAD

**Issue by adam-lynch** [svg/svgo#356]
Note: I don't know much about SVGs.

We're using SVGs with `<defs>` and `<use>`s. The IDs in the `<defs>` were minfiied to `a`, `b`, etc. but the references (the  ID in `<use xlink:href="#id">`) wasn't changed to match. It works when the `cleanupIDs` plugin is disabled.

I found this while using [gulp-svgmin](https://github.com/ben-eb/gulp-svgmin),

**Comment by GreLI** [comment]
It's better with provided examples and svgo version. There was such a bug in v0.5.0 which's been fixed in v0.5.1.

**Comment by DamonOehlman** [comment]
I've just seen the same thing with an inkscape SVG :(

Using `--disable=cleanupIDs` provided a cleaned up output that looked as expected.

**Comment by GreLI** [comment]
Could you provide a sample file?

**Comment by DamonOehlman** [comment]
I'll see if I can.  Unfortunately the SVG files that failed are not mine, but let me see if I can create something similar that reproduces the problem...
