### ISSUE TITLE
How to provide options to plugins via command line?

### ISSUE THREAD

**Issue by dhardtke** [svg/svgo#361]
Hey,

I'm trying to use the "prefix" option of the cleanupIDs plugin:
https://github.com/svg/svgo/blob/master/plugins/cleanupIDs.js#L10

Apparently it's not stated anywhere on how to provide options to plugins like this.

How do I do it using a config file?
How do I do it using the command line?

Thanks.

**Comment by GreLI** [comment]
See about [config](/svg/svgo/blob/master/docs/how-it-works/en.md#1-config).

**Comment by GreLI** [comment]
So you need to provide your config in .yml file with content like this:
```(yml)
plugins:
  - cleanupIDs:
      prefix: foo
```
and run svgo with it like
```
svgo --config=yourconfig.yml
```
You can also provide a config in a command line like json:
```
svgo --config='{ "plugins": [ { "cleanupIDs": { "prefix": "foo" } } ] }'
```
Note: ``cleanupIDs`` doesn't work with SVG files containing ``<style>`` or ``<script>`` since svgo can't parse them.

**Comment by LukeStorry** [comment]
This seems to no longer work, has passing in config via command-line strings been deprecated?

**Comment by TrySound** [comment]
Was removed 1.5 years ago
