### ISSUE TITLE
can`t convert Circle and Ellipse

### ISSUE THREAD

**Issue by purplebamboo** [svg/svgo#362]
[ > ] convert some basic shapes to path
https://github.com/svg/svgo/blob/master/plugins/convertShapeToPath.js

i can not find the code to trans shapes like  Circle and Ellipse.

why?

**Comment by GreLI** [comment]
Because svgo it optimizer and generally circles and ellipses are shorter as their own tags. I know the only exception with the transformed (rotated) ellipse
