### ISSUE TITLE
Release v0.5.2

### ISSUE THREAD

**Issue by sateffen** [svg/svgo#363]
Hey there,

I've just got the bug, fixed with b3ee51c7bcf20ded13d547f81de37e5cd353c4bd, so I wanted to create an issue report. But now I see, this is fixed for over 1 month now, but there is no new release yet.

Is it possible to get v0.5.2 out, so the automatic installation of svg "~0.5.0" with NPM leads to a fixed version for our build servers? I think we're not the only team that would be grateful for such bug fix release.

In general I think it's a good idea to provide a faster bugfix-version release (if you follow the semver convention), to help out guys like us with such fixes.

All in all, great work, I love this project!

Cheers

**Comment by GreLI** [comment]
Yeah, I know. It's coming soon.

**Comment by GreLI** [comment]
Done.
