### ISSUE TITLE
What about --dry-run option?

### ISSUE THREAD

**Issue by a-x-** [svg/svgo#364]
Hi, guys,

i want to use svgo in git pre-commit hook, and interrupt commit then immediately fix svg

If exist something like dry-run option, i can compare combed file with source and detect necessity of commit interrupting

Excuse my beginner's English and thank you

**Comment by GreLI** [comment]
Yes, it's known request. I just don't know how to present results. What output it shoud be?

**Comment by a-x-** [comment]
Optimized svg to stdout instead of modifying in place?
Like inverted `sed -i` option.

**Comment by waldyrious** [comment]
alternatively, a diff output option would be nice too

**Comment by waldyrious** [comment]
or even a verbal summary; something like:
- x styles converted to attributes
- y unused IDs removed
- ...
- total bytes saved: z

**Comment by GreLI** [comment]
> Optimized svg to stdout instead of modifying in place, may be?

Well, there is already `--output -` (`-o -`).

**Comment by a-x-** [comment]
Cool, thank you!

`svgo -o - path/to/file.svg`

**Comment by a-x-** [comment]
For @waldyrious:
```sh
diff -y file.svg  <(svgo -o - file.svg)
```

**Comment by waldyrious** [comment]
What about the human-readable summary? That'd be pretty neat.
