### ISSUE TITLE
Interaction removeHiddenElems / convertPathData

### ISSUE THREAD

**Issue by fsalomon** [svg/svgo#365]
I don't know why, but I have to place removeHiddenElems after convertPathData in order to optimize [test.svg](https://files.zenhub.io/555e778dcff2eb104a4c289f) correctly. [faulty.svg](https://files.zenhub.io/555e778dcff2eb104a4c289d)  has been optimized with the default config and some black lines on the umbrella are missing.

[test.yml | Working config file](https://files.zenhub.io/555e778dcff2eb104a4c289e)

**Comment by fsalomon** [comment]
$ svgo --version
    0.5.1

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.
