### ISSUE TITLE
Error merging of paths

### ISSUE THREAD

**Issue by betula** [svg/svgo#366]
I'am use SVGO(5.0.1, all defaults) for SVG in [SVG set file](https://cdn.rawgit.com/icons8/svg-sets/9896b4d4651024569384248180de05a75e458fca/libs/flat-color-icons/1.0.2/flat-color-icons.min.svg) and result has several error on "camcorder_pro", "left_up2", "positive_dynamic", "process", "refresh", "right_up2", "workflow" icons. (Each icon has been optimized separately, before building icon set.)

![Broken SVG set file]
(https://cdn.rawgit.com/icons8/svg-sets/9896b4d4651024569384248180de05a75e458fca/libs/flat-color-icons/1.0.2/flat-color-icons.min.svg)  
[SVG set from original SVG files](https://cdn.rawgit.com/icons8/svg-sets/9896b4d4651024569384248180de05a75e458fca/libs/flat-color-icons/1.0.2/flat-color-icons.svg) (SVG set created only with nodes manipulation without any transformation)

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.

**Comment by betula** [comment]
Thank you very much!
