### ISSUE TITLE
Error optimizing Maki icons

### ISSUE THREAD

**Issue by betula** [svg/svgo#367]
After optimizing (SVGO 5.0.1, all defaults) [Maki](https://github.com/mapbox/maki) icons many of them has been crashed. (Each icon has been optimized separately, before building icon set.)

![](https://cdn.rawgit.com/icons8/svg-sets/f1ae6dcea1f2d9e60575f7715fbbc0f434cb0007/libs/maki/0.4.5/maki-12.min.svg)

[SVG set from original SVG files](https://cdn.rawgit.com/icons8/svg-sets/f1ae6dcea1f2d9e60575f7715fbbc0f434cb0007/libs/maki/0.4.5/maki-12.svg) (SVG set created only with nodes manipulation without any transformation)

**Comment by GreLI** [comment]
[v0.5.2](/svg/svgo/releases/tag/v0.5.2) with the fix has been just released.

**Comment by betula** [comment]
It's awesome! Thank you very much!
