### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by stevemao** [svg/svgo#369]
I can see the cli docs but I can't find the programmatic api docs. Is there any?

**Comment by GreLI** [comment]
No docs, afaik, only [lib/svgo/jsAPI.js](/svg/svgo/blob/master/lib/svgo/jsAPI.js).

**Comment by stevemao** [comment]
Should probably add this link in README if you don't want to put programmatic api in the docs?

**Comment by GreLI** [comment]
Well, there is plans of new architecture of svgo and I find current API not ideal to say the least. So, it's not on the top of priorities.

**Comment by stevemao** [comment]
Sounds good. Thanks for the information @GreLI :D

**Comment by e-cloud** [comment]
The funny thing is, in this repo i can't find out how to config the plugins via programatic API, but I just find out how to use from [here](https://www.npmjs.com/package/gulp-svgmin)
