### ISSUE TITLE
How to run in the browser?

### ISSUE THREAD

**Issue by villanus** [svg/svgo#376]
Is there a way to run this in the browser?
I am trying to remove the viewbox x, y cordinates that illustrator puts in all my svgs, but would rather do it directly in the browser, versus uploading to my Node Sever, processing and then downloading. 

Thanks

**Comment by GreLI** [comment]
Well, there is nice online tool: [SVGOMG](https://jakearchibald.github.io/svgomg/).

**Comment by villanus** [comment]
Thanks!  exactly what I needed.   Does it require node or just any http server?

**Comment by GreLI** [comment]
It just works. I haven't look into it closely, but there is some info in “[about](https://github.com/jakearchibald/svgomg/blob/master/README.md)” section and it's open sourced.

**Comment by villanus** [comment]
I couldnt make it work int he browser so went back to the node version.   I am going to open a different issue, as I cannot get the remove viewbox to do anything.
