### ISSUE TITLE
toFixed not called with value between 0 and 20

### ISSUE THREAD

**Issue by BjornRombaut** [svg/svgo#383]
Hi,

It seems that the toFixed function is called with a value of '-1' which is not between 0 and 20:
https://github.com/svg/svgo/blob/v0.5.2/plugins/convertTransform.js#L307

This is because the default value of the 'degPrecision' is zero:
https://github.com/svg/svgo/blob/v0.5.2/plugins/convertTransform.js#L89

Possible solution might be changing the default value to 1 instead of zero or not lessen the value when calling the toFixed function.

**Comment by GreLI** [comment]
Yeah, thanks, e9d00c5c5704d6a3fad64f17c8e8c838ec273ffc adresses this.

**Comment by swisstofu** [comment]
Hello, I confirm that @GreLI 's commit solves the fix, but doesn't seem to be released yet. when do you think it will be ? thanks

**Comment by cdunlap** [comment]
Yeah this is hosing our build processes as well. We're just not optimizing our SVG files at the moment until this is resolved.

**Comment by teeeg** [comment]
Hey I'm also having this problem -- can you please cut another release with this patch? 

there's no tag for it in npm at the moment. Thanks!

**Comment by GreLI** [comment]
[v0.5.3](/svg/svgo/releases/tag/v0.5.3) with the fix has been just released.

**Comment by swisstofu** [comment]
Works well, thanks.

**Comment by teeeg** [comment]
Thank you!
