### ISSUE TITLE
Make normal output less verbose

### ISSUE THREAD

**Issue by datenreisender** [svg/svgo#384]
During a normal run of svgo it outputs something like

```
/some/directory:

this.svg:
Done in 22 ms!
6.078 KiB - 23.8% = 4.631 KiB

that.svg:
Done in 7 ms!
6.091 KiB - 26.3% = 4.487 KiB
```

During a normal build that output really is not needed, only when I want to now more verbose what is going on.

Enhancement idea: Introduce a `--verbose` option and do the output above only if the option is given. Errors should of course always be output, regardless of the flag.

**Comment by GreLI** [comment]
There was a `--quiet` option was added in #445.
