### ISSUE TITLE
Stripping width & height breaks display of SVG bg-imgs in IE. 

### ISSUE THREAD

**Issue by janaspage** [svg/svgo#385]
If an SVG is specified as the background-image of a DOM element in CSS, and if the SVG doesn't have a width and height in its code (on the SVG tag), the SVG background-image will display at the wrong size (at a really, really small size) in Internet Explorer 9. Unsure about IE10 & 11. 

The SVGO script preserves the viewbox attribute on the SVG element, but that's not enough for IE9. Adjusting the background-size in CSS can compensate, but that causes incorrect sizing on all other browsers.

**Comment by GreLI** [comment]
So, what's the point?

**Comment by janaspage** [comment]
It is unexpected behavior for SVGO to strip width and height from the SVG element, as these are necessary for correct display in Internet Explorer when SVGs are used as background images.

**Comment by GreLI** [comment]
svgo doesn't strip width and height since a long time ago. Have you a recent version?

**Comment by janaspage** [comment]
Aha. You are correct. It was Adobe Illustrator that had stripped them before SVGO was even run. Thank you.
