### ISSUE TITLE
Unknown option: --show-plugins

### ISSUE THREAD

**Issue by janaspage** [svg/svgo#386]
Readme says to run `svgo --show-plugins` to view available plugins to enable/disable. 

Running that results in `Unknown option: --show-plugins`. 

SVGO version 0.5.2

**Comment by GreLI** [comment]
Yes, it has been recently added in #380 after the release of v0.5.2.

**Comment by janaspage** [comment]
![pic 2015-06-14 at 11 09 46](https://cloud.githubusercontent.com/assets/4712441/8149798/0ff42f98-1286-11e5-9288-5ffd358d0175.png)

**Comment by GreLI** [comment]
[v0.5.3](/svg/svgo/releases/tag/v0.5.3) with this option has been just released.

**Comment by janaspage** [comment]
Confirmed. Thank you.
