### ISSUE TITLE
Run multipass until 0% changes

### ISSUE THREAD

**Issue by stevenvachon** [svg/svgo#387]
I'm currently able to consistently run it with `--multipass` multiple times (like 5 or 6) until it finally says that there were 0% savings.

**Comment by GreLI** [comment]
It's already doing so, but just limited to 10 times.

**Comment by stevenvachon** [comment]
It runs multipass a max of 10 times, but not until 0% changes.

**Comment by GreLI** [comment]
Yes, that's the point of the limit. Not to run for too long.

**Comment by stevenvachon** [comment]
Yeah, but is it checking "if 0% change, end", or simply "run 10 times"? I'm having to run multipass multiple times to achieve this. I understand the desire to avoid lagging the system by running it 400 times, but there should at least be an option to run until it technically does not need to be ran again.

**Comment by collinanderson** [comment]
This feature would be nice. I assume it would have to stop eventually, right? :)

I want it "optimized", not just smaller. :)

**Comment by sindresorhus** [comment]
:+1: I always have to manually run it multiple times because it always manages to optimize more even with `--multipass`.

**Comment by GreLI** [comment]
Actually, there is some weird stuff happens, it may give a little profit by the quality decrease. May be a lesser precision option will give you much more.

**Comment by jimlamb** [comment]
How about an optimization level (like optipng) where it runs until it meets a threshold. My biggest concern is that running it a second time shouldn't change the file at all. When you're keeping your SVGs in version control, SVGO is a nice way to normalize them, but not if it modifies the file on every invocation.

**Comment by stevenvachon** [comment]
I don't think that the authors care. It's been 7 months.

**Comment by stevenvachon** [comment]
Has this been fixed?

**Comment by GreLI** [comment]
Wouldn't fix.

**Comment by stevenvachon** [comment]
Not a good decision, in my opinion (as well as others).

**Comment by GreLI** [comment]
It'd just spend time for nothing. Ideally, there should be no changes after few iterations, but there are some rounding issues. It's not an optimization, just a picture little worse. If it's ok to you just decrease precision.

**Comment by stevenvachon** [comment]
Ok. Is there an issue created for correcting the rounding issues? With that fixed, it'd nullify our thoughts on needing this issue's feature.

**Comment by GreLI** [comment]
Only in my but head :smiley:.

**Comment by stevenvachon** [comment]
Ah, then I've created an issue for it. Not that I think you'll forget, but we need a place to nag :wink:
