### ISSUE TITLE
Error for rotation SVG path

### ISSUE THREAD

**Issue by betula** [svg/svgo#392]
Origin SVG path:
M12 10h16a2 5 0 0 1 2 5v10a2 5 0 0 1-2 5H12a2 5 0 0 1-2-5V15a2 5 0 0 1 2-5z
Using: 
transform: rotate(1)
Result for native browser rotation:
![Native rotation](https://monosnap.com/file/xhqvOD5HhRfMDe2zb8JgBZGFH8w4wV.png)
Result path for optimized transformation:
M11.824 10.208l15.997.28a2 5 1 0 1 1.914 5.033l-.175 10a2 5 1 0 1-2.088 4.964l-15.997-.28a2 5 1 0 1-1.913-5.033l.175-9.998a2 5 1 0 1 2.087-4.964z
Result in browser:
![Optimized rotation](https://monosnap.com/file/NywLMKnTZoVpVhmXamapaiGDUDiVve.png)

Environment:
os x 10.9.5
Chrome 43.0.2357.124 (64-bit)

**Comment by betula** [comment]
Sorry, I added stroke after the transformation, but it is not correct.
Everything works fine paths with stroke not apply transformation.
Thank you for a great tool!

**Comment by GreLI** [comment]
That's because of ending `z`. Looks like a browser bug in rendering.
