### ISSUE TITLE
svgo 0.5.3 failing silently

### ISSUE THREAD

**Issue by jedrichards** [svg/svgo#394]
This SVG file [here](https://gist.githubusercontent.com/jedrichards/093f32739c40e4fa1a1d/raw/f121ea0f1290c47fad4d4e4ab8219010209ee36a/icons.svg) fails to optimise using the latest version of svgo 0.5.3.

Just running the simplest possible command,

```
svgo icons.svg
```

Fails to optimise the file, yet also produces no error messages.

The exact same file works fine on svgo 0.5.0 so there's been some sort of regression maybe?

Since 0.5.0 > 0.5.3 is just a semver patch number increase this caused our build process to upgrade the module, but since no errors are produced it means we've been serving unoptimised svg spritesheets to production for some time :O

Thanks!

**Comment by GreLI** [comment]
Curios that you can workaround this by optimizing one time with disabled `convertTransform` or `convertPathData` and then it'll be processed normally.
