### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by liukanghui** [svg/svgo#395]
I've noticed that this project doesn't do any sanitization to the inputted svg—i.e. if someone throws a ```<script>``` tag in the ```<svg></svg>``` it won't be stripped.

If I'm using the node module version of this project, where users input their own svgs which other users can later load in their browser, are there security vulnerabilities? My guess would be yes, since a user could just add a ```</svg>``` into the evaluated textarea and then put any script they wanted in after that.

**Comment by GreLI** [comment]
Well, svgo isn't a security tool. You can write a plugin that removes script tags.
