### ISSUE TITLE
Resize SVG to Optimize File Size

### ISSUE THREAD

**Issue by philbar** [svg/svgo#398]
There is opportunity to reduce file size by using a smart resize feature.

Below are 2 scenarios that are simplifications. Imagine this applying to paths with 100s of anchors; the file savings could be huge!

I'm not sure how to execute this feature other than a script that multiplies everything by a number (10 in scenario 1) and seeing if the file size is smaller than the original, then run it again until all the file size doesn't get smaller.

## Scenario 1 - Decimal Location
Adjust size in multiples of ten to reduce unnecessary zeros after decimals.

Before

    <svg viewBox="0 0 0.0000001 0.0000001" width="100" height="100">
      <rect width="0.0000001" height="0.0000001"/>
    </svg>
After:

    <svg viewBox="0 0 1 1" width="100" height="100">
      <rect width="1" height="1"/>
    </svg>

## Scenario 2 - Common Multiple
Adjust size in intervals (in this case multiples of 2) to reduce unnecessary numbers.
Before:

    <svg viewBox="0 0 1.5 1.5" width="150" height="150">
      <rect width="1.5" height="1.5"/>
    </svg>
After:

    <svg viewBox="0 0 3 3" width="150" height="150">
      <rect width="3" height="3"/>
    </svg>

**Comment by GreLI** [comment]
See #293
