### ISSUE TITLE
request - plugin to remove <style> and <g> wrapper

### ISSUE THREAD

**Issue by m5o** [svg/svgo#399]
First of all, thank you of this wonderful piece of software! :sparkles: 

Currently I use svgo to optimize a set of various svg files. 
I've noticed some of them still have `<style type="text/css">` blocks and `<g id="foo">` wrapper after processing with svgo. I tried all possible combinations, played with [SVGOMG](https://jakearchibald.github.io/svgomg/) but couldn't manage to get these pieces removed.

The SVG's were created with _Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)_ as you see in the samples. The path btw is a simple circle for demo purposes.

**raw svg**
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="1024px"
	 height="1024px" viewBox="0 0 1024 1024" style="enable-background:new 0 0 1024 1024;" xml:space="preserve">
<style type="text/css">
	.st0{display:none;}
</style>
<g id="_x31_6px_Grid" class="st0">
</g>
<g id="debit">
	<path id="debit_1_" d="M-0.088 512c0-141.5 114.5-256 256-256 141.438 0 256 114.5 256 256s-114.562 256-256 256C114.413 768-0.088 653.5-0.088 512z"/>
</g>
</svg>
```

**optimized svgo output**

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024">
  <style>
    .st0{display:none;}
  </style>
  <g id="debit">
    <path id="debit_1_" d="M-0.088 512c0-141.5 114.5-256 256-256 141.438 0 256 114.5 256 256s-114.562 256-256 256C114.413 768-0.088 653.5-0.088 512z" />
  </g>
</svg>
```

In the optimized svg output you see the unnecessary `  <style>.st0{display:none;}</style>` block as well as the ` <g id="debit">` wrapper. Is there a way to get these blocks removed by any current plugin. Or could this be a possible request for a feature plugin.

**expected optimized output**

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024">
  <path d="M-0.088 512c0-141.5 114.5-256 256-256 141.438 0 256 114.5 256 256s-114.562 256-256 256C114.413 768-0.088 653.5-0.088 512z" />
</svg>
```

**Comment by GreLI** [comment]
Unfortunately, svgo now doesn't parse `style` tags and thus it's not supported. svgo can't understand the meaning of stylesheets for now. Of course this is subject to work on in future.

Regarding empty `g`, it should be removed in the second run or with `--multipass` comand-line option. Again, with the current architecture there are always cases in which plugins runned one by one aren't fully efficient, and there are plans for improvement. But it requires a lot of coding, so it'll be done not soon.

**Comment by stephanedemotte** [comment]
+1 quick export to svg from photoshop CC add style,

It could be cool to remove it :)

**Comment by evenfrost** [comment]
:+1: Came here right for this. Would be nice to have option to remove redundant tags like `<style>`.

**Comment by GreLI** [comment]
Actually, it was done recently in #427.

**Comment by ianmcgregor** [comment]
I also have a use case where I need to copy the contents of CSS classes in <style> blocks outputted by Illustrator/Photoshop into attributes to make them work with SVG Symbol sprite sheets.

The plugin @GreLI mentions (convertStyleToAttrs #427) makes it a lot easier, but there is still a manual step of copying the classes in the <style> blocks into style attributes.

Would it make sense if there was a separate plugin for this or for it to be rolled into convertStyleToAttrs or as part of the proposed 'remove <style>' plugin?

**Comment by ianmcgregor** [comment]
I also have a use case where I need to copy the contents of CSS classes in `<style>` blocks outputted by Illustrator/Photoshop into attributes to make them work with SVG Symbol sprite sheets.

The plugin @GreLI mentions (convertStyleToAttrs #427) makes it a lot easier, but there is still a manual step of copying the classes in the `<style>` blocks into style attributes.

Would it make sense if there was a separate plugin for this or for it to be rolled into convertStyleToAttrs or as part of the proposed 'remove `<style>`' plugin?

**Comment by GreLI** [comment]
It needs a CSS parser which svgo doesn't have yet.

**Comment by rachelnabors** [comment]
Also came here for this.

**Comment by m5o** [comment]
@GreLI Thank you for your answer. 

Do you also have some infos about the unnecessary `<g id="foo">` wrapper?

**Comment by GreLI** [comment]
@m5o, it's the same story. Normally, `cleanupIds` wipes unused ids and than empty group is collapsed. But since there is `<style>` element, `cleanupIds` can't tell anymore that id is unused.
