### ISSUE TITLE
svg fonts are destroyed by svgo

### ISSUE THREAD

**Issue by olegskl** [svg/svgo#404]
Is it possible to use svgo for fonts? I've tried to run version 0.5.3 on OpenSans.svg and it transformed the following:

    <?xml version="1.0" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <metadata></metadata>
    <defs>
    <font id="open_sansbold" horiz-adv-x="1169" >
    <font-face units-per-em="2048" ascent="1638" descent="-410" />
    <missing-glyph horiz-adv-x="532" />
    <glyph horiz-adv-x="0" />
    <glyph unicode="&#xd;" horiz-adv-x="1044" />
    <glyph unicode=" "  horiz-adv-x="532" />
    ...
    etc.

Into this:

    <svg xmlns="http://www.w3.org/2000/svg"/>

**Comment by snorripall** [comment]
Was having the same problems via image-webpack-loader. 

You might want to set removeUselessDefs to false. 

Webpack config
```
{ test: /\.(jpe?g|png|gif|svg)$/, loader: 'file!image-webpack?{ svgo: { plugins: [ { removeUselessDefs: false } ] } }' }
```

**Comment by GreLI** [comment]
Have you tried disabling `removeUselessDefs`?

**Comment by miksago** [comment]
@GreLI we (@snorripall and myself) did that and our iconmoon fonts work — it's because all the content of svg fonts is in `<defs>`.

**Comment by olegskl** [comment]
Seems to be working with `removeUselessDefs: false`.

**Comment by HoBi** [comment]
How can I use 'removeUselessDefs: false' in console? I normally do something like:

`$ svgo -f ../path/to/svg/image.svg -o ../path/to/svg/image.min.svg`

**Comment by GreLI** [comment]
```
svgo --disable=removeUselessDefs
```

**Comment by bespired** [comment]
So not so useless after all.
