### ISSUE TITLE
convert shape to path - add circle, ellipse

### ISSUE THREAD

**Issue by onlymega** [svg/svgo#406]
See working example here: https://github.com/mailzwj/sstp/blob/master/svg-shape-to-path.js

**Comment by GreLI** [comment]
Circle and ellipse hasn't been added because they're have less bytes in a form of `circle` and `ellipse` tags instead of `path`.

**Comment by onlymega** [comment]
But when there are a lot of circles it is better to convert them to path and merge. You can add ellipse and shapes conversion and and add a flag for those who want convert them.

**Comment by GreLI** [comment]
It may be so, but there is no such a logic for now. It requires sophisticated algo that doesn't fit in current design. May be in future, when there'll be much better architecture (it's in early planning stage).

**Comment by qbaty** [comment]
Agree to @onlymega , I try to use js to draw svg instead of use svg as image. 
I want my svg is all made by Paths, not circle or ellipse.

**Comment by SnooHD** [comment]
@onlymega would also like to see this implemented.
Maybe as an optional argument which is off by default?

**Comment by GreLI** [comment]
Such an option was added in v1.0.0.
