### ISSUE TITLE
Can SVGO remove the xmlns attribute?

### ISSUE THREAD

**Issue by drw158** [svg/svgo#409]
For example, this svg:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
<path d="M22 16h-4V8c0-1.105-.895-2-2-2H8V2H6v4H2v2h4v8c0 1.105.895 2 2 2h8v4h2v-4h4v-2zM8 16V8h8v8H8z"/>
<path fill="none" d="M0 0h24v24H0z"/>
</svg>
```

would be converted to:

```svg
<svg viewBox="0 0 24 24">
<path d="M22 16h-4V8c0-1.105-.895-2-2-2H8V2H6v4H2v2h4v8c0 1.105.895 2 2 2h8v4h2v-4h4v-2zM8 16V8h8v8H8z"/>
<path fill="none" d="M0 0h24v24H0z"/>
</svg>
```

I tried looking through the documentation and couldn't find anything about the xmlns attribute. Thanks in advance.

**Comment by waldyrious** [comment]
Ironically, the `xmlns` attribute is the *only* thing required to produce a valid svg file. See https://github.com/mathiasbynens/small/blob/master/svg.svg?short_path=5fda422 (or try validating the second code snippet as SVG in http:///validator.nu)

**Comment by drw158** [comment]
Thank you! I'll leave the attribute in.

**Comment by GreLI** [comment]
You can write a [simple plugin](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#3-plugins). When there are several SVGs inlined in HTML there is no real need to keep `xmlns` in each one.
