### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by TrySound** [svg/svgo#410]
Replace please colors with [chalk](https://github.com/chalk/chalk). It more safe, because do not modify prototypes.

**Comment by GreLI** [comment]
There is nothing bad in modifying prototypes in controlled environments (e.g. not in browsers). And I see nothing worthy in creating extra dependency for the functionality that's already present.

**Comment by oyeanuj** [comment]
@GreLI Can we revisit this? Colors also doesn't play well with Webpack (https://github.com/Marak/colors.js/issues/137), and given that it hasn't been updated in 2 years, seems unlikely.

**Comment by GreLI** [comment]
SVGO doesn't use webpack as for now. I see no point to revisit it. It just works.
