### ISSUE TITLE
Path is removed completely with new validation regex

### ISSUE THREAD

**Issue by cdl** [svg/svgo#413]
As of `v0.5.4`/`v0.5.5`, the path of the below SVG is invalidated due to the new regex (created to fix #405), and the `<path>` is removed completely.

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" viewBox="0 0 21 21">
<path class="st2" d="M10.77.45c-.19-.2-.51-.2-.7 0l-9.69 9.7c-.19.19-.19.51 0 .71l9.73 9.74c.19.19.51.19.7-.01l1.24-1.31c.19-.2.18-.52-.01-.72l-7.7-7.71c-.19-.19-.19-.51 0-.71l7.7-7.7c.19-.19.2-.51 0-.71l-1.27-1.28z" id="icon-backarrow"/>
</svg>
```

This happened as of `v0.5.4`/`v0.5.5` due to [this commit](https://github.com/svg/svgo/commit/8ec45b7251c71d171597a8bc97cb609f918ac686). [Old regex](http://rubular.com/r/3HIdyQVfHc) validated the path fine (used in `v0.5.3`), but the [new regex](http://rubular.com/r/r55OTzrrFS) doesn't.

**Comment by GreLI** [comment]
extra dot in `(?![\de.])`, my bad
