### ISSUE TITLE
Plugin to optimize path data by removing small details

### ISSUE THREAD

**Issue by behdad** [svg/svgo#414]
See for example:

  http://bost.ocks.org/mike/simplify/
  http://stackoverflow.com/questions/13730062/simplifying-svg-path-strings-by-reducing-number-of-nodes

We need to be smarter with curves.

I need this, to optimize flag SVGs in https://github.com/behdad/region-flags/tree/master/svg
Currently some of the flags are over 200kb.   That's a bit on the excessive side. :)

cc @jamesgk

**Comment by GreLI** [comment]
See #411

**Comment by behdad** [comment]
Awesome.  Lets follow up there.
