### ISSUE TITLE
Path distortion

### ISSUE THREAD

**Issue by silverwind** [svg/svgo#415]
I'm seeing path distortion in the upper left and lower right of the following image, using the default settings:

````svg
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><path d="M384 128h-69c24 16 46.5 44.5 53.5 64h15c32.5 0 64 32 64 64s-32.5 64-64 64h-96c-31.5 0-64-32-64-64 0-11.5 3.5-22.5 9-32h-68.5c-2.5 10.5-4 21-4 32 0 64 63.5 128 127.5 128s32.5 0 96.5 0 128-64 128-128-64-128-128-128zM143.5 320h-15c-32.5 0-64-32-64-64s32.5-64 64-64h96c31.5 0 64 32 64 64 0 11.5-3.5 22.5-9 32h68.5c2.5-10.5 4-21 4-32 0-64-63.5-128-127.5-128s-32.5 0-96.5 0-128 64-128 128 64 128 128 128h69c-24-16-46.5-44.5-53.5-64z"/></svg>
````

Original:
![screen shot 2015-08-19 at 10 05 09 pm](https://cloud.githubusercontent.com/assets/115237/9367567/6eb4277e-46be-11e5-9f11-e27629d0e833.png)
Optimized:
![screen shot 2015-08-19 at 10 05 17 pm](https://cloud.githubusercontent.com/assets/115237/9367569/6ef10d2e-46be-11e5-9cfa-01bbf96dd0da.png)

**Comment by GreLI** [comment]
Well,
```
plugins:
  - convertPathData:
      straightCurves: false
```
helps with such an issue.

**Comment by GreLI** [comment]
[v0.6.0](https://github.com/svg/svgo/releases/tag/v0.6.0) with the fix have been just released.

**Comment by silverwind** [comment]
Awesome, thanks!
