### ISSUE TITLE
Remove useless wrapping tags

### ISSUE THREAD

**Issue by nt1m** [svg/svgo#419]
If a g tag only has one child, apply the styles and attributes on the child then remove the <g> tag.

**Comment by nathanuphoff** [comment]
Furthermore, change translate="transform(10,10)"  to x="10" y="10" (shorter). And better yet, (optionally) inline styles to style="properties:here" which is in anmost any case the shorter syntax. Cheers.

**Comment by GreLI** [comment]
`x` and `y` work only on limited set of tags. `style=` adds 6 bytes by itself and can be compensated also by more than 6 rules which is rare, actually.

**Comment by nathanuphoff** [comment]
Actually four is the threshold after which style becomes the more efficient option. Not worth it I would say: http://d.pr/i/1jB6A

I did not know about the x and y’s limitations in that regard. Thanks.

**Comment by nt1m** [comment]
@nathanuphoff I think the W3C recommends inline attributes instead of inline styles. In fact, some CSS properties act differently than their SVG equivalents (transforms for example).

**Comment by nathanuphoff** [comment]
@nt1m Clear. I’m pretty fresh to svg outside Sketch.app until some things annoyed me and I had to take a look below the surface. Consider me a newbie to the matter. It’s like learning html all over again, including all the quirks.

**Comment by GreLI** [comment]
Regarding the subject, `collapseGroups` plugin already does the job. Sometimes it can be missed because group is empty after later executed plugins, but the second run will optimize that. There's `--multipass` to run multiple times (10 times or until there's nothing can be optimized).
