### ISSUE TITLE
Plugin request: Remove style tags

### ISSUE THREAD

**Issue by betsydupuis** [svg/svgo#425]
Illustrator is including a base64 of fonts during an scripted export in a style tag. A plugin  for that would be helpful.

<style type="text/css">
<![CDATA[
@font-face{font-family:'SourceSansPro-Regular';src:url("data:;base64,\

**Comment by GreLI** [comment]
It's not that difficult, but obviously should be disabled by default.

**Comment by itsjustluck** [comment]
I can try to work on it this weekend and submit pull request. Would that help?

**Comment by GreLI** [comment]
It would be nice.

**Comment by itsjustluck** [comment]
I have a commit ready to make a pull request. Should I create the request to the 'next' branch?

**Comment by GreLI** [comment]
No, it's far for completion.

**Comment by GreLI** [comment]
Why you've closed it?

**Comment by itsjustluck** [comment]
I wasn't sure which branch to go to. So, I make the request to master?

**Comment by GreLI** [comment]
Yep

**Comment by itsjustluck** [comment]
Thanks for the merge, that was kind of a quick fix for my problem, but I could see where this might be a pain point for others in the future it they still want the rest of the styles. 

For my purposes, I'm just building a single color sprite, so the fewer attributes and styles the better.

When using scripts to export SVGs, I couldn't get illustrator to stop exporting that base 64 font. I tried making an action to outline fonts and change other export settings. 

What are your thoughts?

**Comment by GreLI** [comment]
Sorry, I can't say anything

**Comment by itsjustluck** [comment]
I can do some research on this and get back to you.

**Comment by GreLI** [comment]
Closed, due to #427
