### ISSUE TITLE
Default options should not strip existing Creator/Rights/Licence metadata

### ISSUE THREAD

**Issue by scruss** [svg/svgo#431]
I know most SVG editors leave in blank and useless metadata, but stripping Creator/Rights/Licence information by default makes this a cracking tool, not an optimizer.

**Comment by GreLI** [comment]
Removing comments doesn't remove rights for the image. If a license doesn't allow removing legal info, then the user must preserve it, e.g. by disabling appropriate plugins. But usually there is nonsense stuff like “generated by our awesome editor” which worth nothing.

Do you have a reliable way of detecting such a legal information? We'd like to see a pull-request.

**Comment by scruss** [comment]
I'm not a javascript programmer, so a pull request is unlikely. Any RDF section that would ultimately resolve to a non-empty string should be preserved. RDF isn't just comments; it's provenance. While removing it doesn't remove rights, it makes the job of proving rights harder for the creator.

**Comment by GreLI** [comment]
Sorry, it contradicts the purpose of optimization which is in priority here. That's why I'm asking for technical details. SVGO is a tool and it's assumed that user knows how to use it.

**Comment by thiakil** [comment]
Please provide an example metadata section and I might be able to look into it.

Although, agreed that this is really a user issue. Calling it a cracking tool is fear mongering... You could call Notepad a cracking tool by that definition. The creator would likely have original files that would easily prove their rights.

**Comment by scruss** [comment]
Thanks! I put a small file with example metadata here: http://scruss.com/wordpress/wp-content/uploads/2015/10/kite.svg

One unrelated thing I've noticed (with 0.5.6) and this particular example file is that the output is massively scaled up. The original is ~ 9 mm wide, but it ends roughly 9½ m wide when run through svgo.

**Comment by thiakil** [comment]
So, by default, the removeMetadata plugin is enabled. This quite obviously will remove the whole metadata section - something I can guarantee most other image optimisers will do.

My personal opinion is that this is your responsibility to disable. ``` --disable=removeMetadata```
IANAL, but from my studies I know that the absence of licence info does not affect copyright claims, so the default option is unlikely to be changed.

Therein also lies another issue; what metadata to save, what to get rid of? What metadata does this program add, what does that program add?

The scaling issue: this appears to be a quirk with how your image is saved; width and height are in mm, but the DPI info is inside an Inkscape XMLNS, something I doubt SVGo understands. Nothing but Inkscape would be able to convert that properly.

**Comment by GreLI** [comment]
Well, may be it'll be considered with the new architecture implementation, but for now `--disable=removeMetadata` is the best option to keep legal info.

**Comment by strarsis** [comment]
I have to bump this because today I wanted to use some Font Awesome SVGs which require attribution specifically in the source code of the SVG file.
