### ISSUE TITLE
Don't convert '<' or '>'

### ISSUE THREAD

**Issue by shaneparsons** [svg/svgo#434]
I have php tags in my svg, for dynamic colouring reasons, and svgo destroys my php tags by converting the `<` and `>` to `&lt;` and `&gt;`

I've looked to see if there was a setting to disable this "functionality", but there doesn't seem to be.

**Comment by shaneparsons** [comment]
Any ideas?

**Comment by GreLI** [comment]
No ideas, sorry.

**Comment by thiakil** [comment]
If you really want to have PHP tags in an SVG file, you will need to run it through some kind of preprocessor before it hits svgo, as your file is invalid.

A better approach would likely be not running SVG as PHP on your server; use XML valid placeholders instead and process in separate PHP script. That would allow you to use vanilla svgo on the command line.

**Comment by shaneparsons** [comment]
Yeaa it took some reworking but I ended up just swapping out the php with classes and using php on the other end
