### ISSUE TITLE
Add option 'Remove hidden layer elements'

### ISSUE THREAD

**Issue by s10wen** [svg/svgo#437]
https://github.com/jakearchibald/svgomg/issues/32

**Comment by GreLI** [comment]
As far as I understand your request, you want to parse styles. SVGO cannot parse styles for now, only the `style` attribute.

**Comment by strarsis** [comment]
Native CSS support has been added with https://github.com/svg/svgo/pull/592.

**Comment by GreLI** [comment]
SVGO v1.0.0 with the plugin by @strarsis has been released.
