### ISSUE TITLE
IDs not cleanup

### ISSUE THREAD

**Issue by vruzin** [svg/svgo#438]
Example
```
<svg id="Слой_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1125 52.7"><style>.st0{fill:none;stroke:#77787B;stroke-width:4;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;}</style><path id="XMLID_2_" class="st0" d="M1123 1.7V11c0 13.3-8.7 21.7-22 21.7H585c-11.1 0-20.4 7.5-23.1 17.7-2.8-10.2-12.1-17.7-23.1-17.7H28C14.7 32.7 2 24.3 2 11V1.7"/></svg>
```

It's after Optimizing

Why is ids not cleanup?

======
Код вверху. IDs не удаляются. Почему?

**Comment by GreLI** [comment]
svgo doesn't parse \<style\>, so it can't say whether the is is used.

=====
svgo не умеет парсить отдельные стили, поэтому не знает, используется ли id.

**Comment by vruzin** [comment]
Может в CleanupIDs стоит сделать опцию "all:true/false" чтоб удалять все ID?
Они редко используются.Иконки, например, маленькие картинки где ID вообще не нужны.

Про <style>. Думаю стоит сделать опцию "Style" с опциями:
* Удалить
* Оставить как есть
* Сжать (Оптимизировать)
* Вынести в отдельный файл (указать его). Это будет супер удобно при работе с большим числом иконок. В них удобно выносить стили в один файл, потому что они имеют одни и те же значения стилей. и плодить стили от иконки к иконке нет смысла.

**Comment by GreLI** [comment]
На самом деле, как раз в недавнем пулл-реквесте #427 сделали плагин для удаления `<style>`, но он ещё не попал в релиз.
