### ISSUE TITLE
convert shape to paths needs to close path for polygon.

### ISSUE THREAD

**Issue by ccorcos** [svg/svgo#441]
Here's a simple star:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="30px" height="30px" viewBox="0 0 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <!-- Generator: Sketch 3.3.3 (12072) - http://www.bohemiancoding.com/sketch -->
    <title>star</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <g id="star" sketch:type="MSArtboardGroup" fill="#000000">
            <polygon id="Star-1" sketch:type="MSShapeGroup" points="15 21.5699379 7.35879172 26.5172209 9.70267424 17.7212055 2.63626529 11.9827791 11.7260726 11.4938256 15 3 18.2739274 11.4938256 27.3637347 11.9827791 20.2973258 17.7212055 22.6412083 26.5172209 "></polygon>
        </g>
    </g>
</svg>
```

But the path isnt closed when its converted:

```
<path fill-rule="evenodd" d="M15 21.57l-7.64 4.947 2.343-8.796-7.067-5.736 9.09-.49L15 3l3.274 8.494 9.09.49-7.067 5.737 2.344 8.798 Z"></path>
```

it needs a z at the end

**Comment by ccorcos** [comment]
Seems like it should always be a closed path if its a polygon:

https://github.com/svg/svgo/blob/master/plugins/convertShapeToPath.js#L90

**Comment by ccorcos** [comment]
Also, this isn't stopping the conversion:       {  convertShapeToPath: false },

**Comment by GreLI** [comment]
Actually there is no need in closing if you have no stroke. It's absolutely same.

**Comment by ccorcos** [comment]
Without the Z

```
<html>
<body>
  <style type="text/css">
    svg {
      fill: red;
      stroke: blue;
    }
  </style>
  <svg>
    <path fill-rule="evenodd" d="M15 21.57l-7.64 4.947 2.343-8.796-7.067-5.736 9.09-.49L15 3l3.274 8.494 9.09.49-7.067 5.737 2.344 8.798 "></path>
  </svg>
</body>
</html>
```

![screen shot 2015-10-12 at 10 36 10 am](https://cloud.githubusercontent.com/assets/1794527/10434230/27c8f464-70cd-11e5-90fa-9b6c50e24e32.png)

With the Z

```
<html>
<body>
  <style type="text/css">
    svg {
      fill: red;
      stroke: blue;
    }
  </style>
  <svg>
    <path fill-rule="evenodd" d="M15 21.57l-7.64 4.947 2.343-8.796-7.067-5.736 9.09-.49L15 3l3.274 8.494 9.09.49-7.067 5.737 2.344 8.798 Z"></path>
  </svg>
</body>
</html>
```

![screen shot 2015-10-12 at 10 36 28 am](https://cloud.githubusercontent.com/assets/1794527/10434243/371d6c6a-70cd-11e5-95f4-173b0a22416e.png)

**Comment by GreLI** [comment]
Ah, you have stroke in styles. Yes, svgo can't parse styles for now.

**Comment by ccorcos** [comment]
the styles aren't within the SVG file. its within the html page. at the top is the SVG file thats input. The first example in the last comment is the compiled version. And the second is what I think it should be, with the Z appended.

**Comment by ccorcos** [comment]
All polygons are closed. Thats my point.

**Comment by GreLI** [comment]
Yeah, but svgo can't know about it. Consider tuning the configuration.

**Comment by ccorcos** [comment]
Thats my point about this line:

https://github.com/svg/svgo/blob/master/plugins/convertShapeToPath.js#L90

I think closePath should always be true for polygons.

**Comment by GreLI** [comment]
[v0.6.0](https://github.com/svg/svgo/releases/tag/v0.6.0) with the fix have been just released.
