### ISSUE TITLE
SVG stroke thinned 

### ISSUE THREAD

**Issue by plonko** [svg/svgo#443]
Hullo, before I disable each SVG plugin one by one, I thought I'd check if anyone has come across the SVG compressor translating stroke badly? It seems to make it too thin. 
Here are the before and after
https://gist.github.com/sebastianthomas/f68fc465c63b26bc3bae
https://gist.github.com/sebastianthomas/79e80064145be1b03ab5

This is my current gulp task:
```
gulp.task('images', function() {
  return gulp.src('src/images/**/*')
    .pipe($.imagemin({
      svgoPlugins: [{
        convertPathData: false,
        removeUselessStrokeAndFill: false
      }]
    }))
    .pipe(gulp.dest('build/images'));
});
```
As per: https://www.npmjs.com/package/generator-gulp-less-jade
Which is using `"gulp-imagemin": "^1.0.1"`, so maybe that's just a really old version.. 

Any ideas? Thanks!

**Comment by GreLI** [comment]
You know, I couldn't reproduce the case with and without these plugins in any version of 0.5 in command line. `stroke-width` is correctly preserved by svgo.

**Comment by GreLI** [comment]
U
