### ISSUE TITLE
gulp svgo plugin svg optimisation

### ISSUE THREAD

**Issue by jolution** [svg/svgo#444]
Dear Developers,
ill like that gulp Plugin and write my first plugin for SVG optimisation.
But my problem is that i cannot bring it to my gulp.

Ill override the "addClassesToSVGElement" file and than it works, but wanne have my own file - maybe for github.
I am very new to this. Ill read the manual here:
https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md
but it doesnt work, do you have any glue ?

Thanks very much!
Sorry for my bad english.

**Comment by GreLI** [comment]
Well, when you have your own file, you need to add to the plugins list in config. Also, if it's disabled by default (`exports.active = false`), you have to set it to true.
