### ISSUE TITLE
SVG appareance is changed with the plugin moveElemsAttrsToGroup.

### ISSUE THREAD

**Issue by cduez** [svg/svgo#446]
With `svgo` version 0.5.6. Using the `moveElemsAttrsToGroup` plugin on a svg 'hide' some text entries node. (The node is here but we can't see the content)

Here is my test config:

````
full: true
plugins:
  - moveElemsAttrsToGroup
````

The cmd:
````
svgo --pretty --config=config.yml meeting_canvas_pretty.svg
````

The plugin move a `translate` attributes (You can easily see this on the node with id `g150`) from a group to another one. But this seems to change the result of the svg.

This as probably nothing to do with the issue but the result file size is bigger than the original. (74 vs 78 ko)

[Original File (jsfiddle link)](http://jsfiddle.net/b2hpr7pb/)
[Result File (jsfiddle link)](http://jsfiddle.net/9q5bmqps/)

(click on run to see the svg :eyes: )

**Comment by GreLI** [comment]
Another `clip-path` issue. Thanks for reporting!

**Comment by GreLI** [comment]
[v0.6.0](https://github.com/svg/svgo/releases/tag/v0.6.0) with the fix have been just released.
