### ISSUE TITLE
Testing plugin with params

### ISSUE THREAD

**Issue by strarsis** [svg/svgo#449]
In ./test/plugins/ svg "diffs" can be placed with @@@ as separator.
The plugin is tested automatically.
But how can I add tests with different options passed to the plugin?
Can I add "annotations" for the options to the svg test file?

Thank you and 
With best regards

**Comment by GreLI** [comment]
You can place JSON like parameters after the second separator. See for example [test/plugins/removeAttrs.01.svg](https://raw.githubusercontent.com/svg/svgo/master/test/plugins/removeAttrs.01.svg).
