### ISSUE TITLE
Add an option to configure indentation with --pretty argument

### ISSUE THREAD

**Issue by nt1m** [svg/svgo#450]

**Comment by waldyrious** [comment]
Yes, please! :+1:

**Comment by jaydenseric** [comment]
+1 we work with 2 spaces, not 4.

**Comment by GreLI** [comment]
Duplicates #424.

**Comment by jaydenseric** [comment]
@GreLI #242 is about changing the hardcoded indentation value (to 2 spaces from 4), not making indentation configurable as with this issue/suggestion.

Ultimately I would like to see configurable `--pretty` indentation via a CLI argument, defaulting to `.editorconfig` and finally falling back to 2 spaces. See https://github.com/svg/svgo/issues/507.

**Comment by GreLI** [comment]
Hardcoded indentation isn't an option ofc.
