### ISSUE TITLE
Specify --pretty Option In Node Module Usage

### ISSUE THREAD

**Issue by tay1orjones** [svg/svgo#452]
I can't find a way to use the `--pretty` option when using it as a node module. I see how you can pass in config values, but to my knowledge that only works for plugins, not built-in functionality like `--pretty` or `--datauri`

Maybe I'm missing something easy and small. Any help?

**Comment by GreLI** [comment]
I guess this should work:
```
js2svg:
  pretty: true
```
This is not obvious, yes.

**Comment by GreLI** [comment]
I guess, I answered your question. For data:uri there is related issue #340.

**Comment by bentaly** [comment]
@GreLI  How would you set this in node?
using the standard:
```
const SVGO = require('./node_modules/svgo');
const svgo = new SVGO({
    plugins: [...
```

**Comment by bentaly** [comment]
Never mind, I worked it out, it's:

```
const svgo = new SVGO({
    plugins: [
        { cleanupAttrs: true },
        ...
    ],
    js2svg: { pretty: true } 
});
```
