### ISSUE TITLE
Error in plugin minifyStyles.js for .svg from CorelDraw

### ISSUE THREAD

**Issue by ne3Vubeki** [svg/svgo#456]
```
svgo\plugins\minifyStyles.js:47
            if(styleCss.length > 0) {
                       ^
TypeError: Cannot read property 'length' of undefined
```
Ошибка возникает при наличие в svg такой конструкции:

```
<defs>
  <style type="text/css">
   <![CDATA[
    .fil0 {fill:#B3B3B3}
    .fil1 {fill:white}
   ]]>
  </style>
 </defs>
```

соответственно CLI тоже вылетает без ошибки

**Comment by dishs** [comment]
I can confirm the same error happening with the addition of this plugin.  We are wrapping our style content with CDATA, which breaks the plugin and causes build errors:

<style><![CDATA[
	.st0{fill:#FF7900;}
	.st1{fill:#FFFFFF;}
]]></style>

Taken from the standard .... http://www.w3.org/TR/SVG/styling.html
```Note how the CSS style sheet is placed within a CDATA construct (i.e., <![CDATA[ ... ]]>). Placing internal CSS style sheets within CDATA blocks is sometimes necessary since CSS style sheets can include characters, such as ">", which conflict with XML parsers. Even if a given style sheet does not use characters that conflict with XML parsing, it is highly recommended that internal style sheets be placed inside CDATA blocks.```
