### ISSUE TITLE
Document how to use config files

### ISSUE THREAD

**Issue by gajus** [svg/svgo#457]
Program API shows `--config=CONFIG : Config file to extend or replace default` can be used to configure `svgo` program. But there is no example of the config file in the docs.

**Comment by gajus** [comment]
Found it. https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config

**Comment by GreLI** [comment]
Yeah, not the best location.

**Comment by GreLI** [comment]
It has to be YAML or JSON file.
