### ISSUE TITLE
error : infinite loop while processing mergePaths plugin.

### ISSUE THREAD

**Issue by matbech** [svg/svgo#459]
I'm calling svgo with the following option:
--multipass --disable=convertTransform

For this particular .svg the result is a file with all the markup aside from svg element removed:
https://gist.github.com/matbech/0629e2ab460af94f9339

**Comment by GreLI** [comment]
Wow! It's the type of error that shouldn't occur.

**Comment by GreLI** [comment]
Your error is due to `transform="translate(.5-89.26)"`. SVG syntax doesn't allow omitting the separator between numbers in transform functions. Did you use SVG Cleaner or such?

**Comment by matbech** [comment]
That was most likely the case. Thank you for pointing it out.

**Comment by GreLI** [comment]
Just released v0.6.1 which should work well now.
