### ISSUE TITLE
convertTransform plugin removes gradient

### ISSUE THREAD

**Issue by matbech** [svg/svgo#460]
I'm not sure if this is by intention, but the convertTransform plugin removes the gradient transformations:
Gist with before and after:
https://gist.github.com/matbech/541687f496976fa23b9e

The relevant markup:
Before:
`gradientTransform="matrix(.8738 0 0-.8738-112.82 718.94)"`

After
`gradientTransform="scale(NaN NaN)"`

**Comment by GreLI** [comment]
SVG syntax doesn't allow absence of space before minus sign in transformation. Where did you get such a file?

**Comment by matbech** [comment]
Adobe Illustrator 19, latest build (SVG Export plugin)

**Comment by GreLI** [comment]
It requires rewriting of transform attribute parser, which is not that trivial or somewhat prioritized task.

**Comment by GreLI** [comment]
Made it so in v0.6.1. No more errors, yay!
