### ISSUE TITLE
No output since 0.6.0

### ISSUE THREAD

**Issue by mcfly83** [svg/svgo#461]
Since updating to 0.6.0 svgo seems to ignore some of my svg files. When executing something like "svgo test.svg test.min.svg" there's no output at all. Optimizing still works with other files, but I can see no pattern here. When reverting to 0.5.6 everything works fine again.
Is there any debug option to figure out what goes wrong?

**Comment by GreLI** [comment]
It's likely some error. Could you provide a sample file?

**Comment by mcfly83** [comment]
This is one of the files that fail with v0.6.0: http://dropcanvas.com/d2vq6

**Comment by GreLI** [comment]
It's `CDATA` in `<style>`, same as #456.
