### ISSUE TITLE
multiple files, whole directories?

### ISSUE THREAD

**Issue by v3nt** [svg/svgo#463]
Is it possible to process more than one file? If so how can it be done?  Or how about whole directories?

this doesn't seem to work...
 files: {  
                'dist/wonkhe-main-logo.svg':'assets/img/wonkhe-main-logo.svg',
                'dist/wonkhe-site-icons.svg':'assets/img/wonkhe-site-icons.svg'
            }

**Comment by GreLI** [comment]
Pull requests are always welcome :wink:.

**Comment by pauldraper** [comment]
Being able to process multiple files at the same time would be a real time saver.

**Comment by TrySound** [comment]
According to docs multiple files already supported.
https://github.com/svg/svgo#cli
