### ISSUE TITLE
CLI silently fails when config is malformed

### ISSUE THREAD

**Issue by bdkjones** [svg/svgo#466]
I was attempting to pass JSON for the `config` option because JSON is much easier to create/parse than yml. Before I found the example in #361, I tried passing this:

```
{
	"full":true,
	"plugins": {
		"removeDoctype":true,
		"removeXMLProcInst":true,
		"removeComments":true
	}
}
```

SVGO silently failed. Nothing was returned by the CLI: no error message, no warnings, etc. That should probably not be the case. If SVGO doesn't like the config file, it should tell you so.

**Comment by GreLI** [comment]
[0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with some improvements is out.

**Comment by bdkjones** [comment]
Thanks!
