### ISSUE TITLE
svgo and feGaussianBlur

### ISSUE THREAD

**Issue by Flackus** [svg/svgo#467]
Not sure if this isn't by design, but:

```
$ cat newbuilding-header.svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"><filter id="blur"><feGaussianBlur stdDeviation="15" /></filter></svg>
$ svgo newbuilding-header.svg
Done in 88 ms!
0.121 KiB - 66.9% = 0.04 KiB
$ cat newbuilding-header.svg
<svg xmlns="http://www.w3.org/2000/svg"/>
$ svgo --version
0.6.1
```

This is a common trick (http://stackoverflow.com/a/12025098/530394) to emulate `filter: blur` in Firefox <35.

I'm sure there is a rationale behind this behaviour, but can it be disabled by enabling one of the plugins?

**Comment by GreLI** [comment]
Filter is not used, that's why it's being removed. Disable `removeUselessDefs` plugin to prevent this.

**Comment by Flackus** [comment]
Thanks :+1: 
It was rather obvious :flushed:
