### ISSUE TITLE
removeAttrs examples don't work as intended

### ISSUE THREAD

**Issue by jasmussen** [svg/svgo#469]
I'm using `svgmin` with the `svgo` plugin `removeAttrs`.

The [documentation](https://github.com/svg/svgo/blob/master/plugins/removeAttrs.js) seems to suggest that this should work:

```
plugins: [
	{ removeAttrs: 'fill' },
	{ removeViewBox: false },
	{ removeEmptyAttrs: false }
]
```

But for some reason the script doesn't run at all when it's formatted like that. It works if I format it like this:

```
plugins: [
	{ removeAttrs: { attrs: ['fill'] } },
	{ removeViewBox: false },
	{ removeEmptyAttrs: false }
]
```

Am I reading the documentation wrong, or is there an issue in the script? In case of the former, it might be good to include the above working example verbatim. 

Thanks! Love svgo!

**Comment by GreLI** [comment]
There is `attrs` option, that you forgot. E.g. not
```js
plugins: [
    { removeAttrs: 'fill' },
...
```
but
```js
plugins: [
    { removeAttrs: { attrs: 'fill' } },
...
```

**Comment by jasmussen** [comment]
Correct. And like I mentioned, it works when I write `{ removeAttrs: { attrs: 'fill' } }`, but that's not mentioned in the documentation anywhere. May I offer a PR to update the documentation? Right now ` { removeAttrs: 'fill' },` doesn't work at all, though that's what seems to be the suggested use.

**Comment by GreLI** [comment]
I didn't noticed where is the error, but if you found it, it would be nice of you to make PR.

**Comment by jasmussen** [comment]
Tried making a PR, but seems I don't have permissions to push PRs. In any case, the change to the documentation is very small. Here's an updated file:

https://cloudup.com/czB43eIAPOH
