### ISSUE TITLE
requirejs / browserify support would be really nice

### ISSUE THREAD

**Issue by wauwau0977** [svg/svgo#470]
I know this has been discussed before and you didn't like it, but I would also be interested to have a requirejs / browserify support. 

For a single page application built with gulp and browserify the plugins are not included. I guess the problem araises in Config, where the plugins are loaded with a parameter, which browserify is blind for... 

EXTEND({}, require('../../plugins/' + item));

I would love to see a dedicated Config that supports loading with browserify. 

Last and absolutely not least: The library you wrote, is just amazing! Good work, go on :-)

**Comment by GreLI** [comment]
See #614.
