### ISSUE TITLE
Include line number in parse errors

### ISSUE THREAD

**Issue by sindresorhus** [svg/svgo#482]
Would be useful if parse errors included line number (column too if possible).

It's currently hard to debug errors in large SVG files as there's no indication of where the parse error is.

-

https://github.com/sindresorhus/grunt-svgmin/blob/0a71db372f1e77fbc5d565e60310fdc18a8af061/tasks/svgmin.js#L20

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) now shows parser error. Enjoy!
