### ISSUE TITLE
convertPathData produces wrong stroke width

### ISSUE THREAD

**Issue by tuomassalo** [svg/svgo#483]
Here's a screenshot what happens to the attached .svg file when I run `svgo` with default options:

![svgo-bug](https://cloud.githubusercontent.com/assets/189964/12224284/5e26d8fe-b7f5-11e5-846e-a2f5dc5cf5c1.png)

Note that the text is not `<text>`, just paths.

If I disable `convertPathData`, everything is ok. I assume the problem has something to do with the `scale` transform in the paths. There is no stroke width specified, but scaling should affect the default, too.

The original file has items such as:

    <path d="..." id="H" transform="scale(.00098)"/>

[Here's the original and minified SVG file.](https://github.com/svg/svgo/files/85196/svg-files.zip)

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with the fix is out.
