### ISSUE TITLE
cleanupIDs prefixes mask ids but not path/group ids

### ISSUE THREAD

**Issue by mxdubois** [svg/svgo#484]
Hi, I'm using gulp-svgmin, which uses svgo, and when I run an svg through `cleanupIDs` with the `prefix` option, it prefixes the `id`s on `mask` elements, but not the `id`s on `path` or `g` elements. I've attached an example of input and output. 

I'd really appreciate a fix. Let me know if there's anyway I can help debug it.

svgo version: `0.5.6`
gulp-svgmin version: `1.2.0`
node version: `0.12.7`

options (passed to gulp-svgmin):

```
           // where `filename` is `"browser"` for the attached example file. 
            {
              mergePaths: false,
              cleanupIDs: {
                  prefix: filename + '-',
                  remove: false,
                  minify: true,
              },
            }
```

[svgo-cleanup-ids-bug-example.zip](https://github.com/svg/svgo/files/86666/svgo-cleanup-ids-bug-example.zip)

**Comment by GreLI** [comment]
It seems, that you have provided wrong config. `plugins` in config is an array of objects which define every plugin separately. E.g.:
```js
{
    plugins: [
        { mergePaths: false },
        {
            cleanupIDs: {
                prefix: filename + '-',
                remove: false,
                minify: true,
            }
        }
    ]
}
```

**Comment by GreLI** [comment]
However, I don't exactly know how gulp-svgmin works with config.
