### ISSUE TITLE
Consider moving lib/svgo/js2svg.js lib/svgo/svg2js.js to svgp

### ISSUE THREAD

**Issue by marionebl** [svg/svgo#485]
I'd love to see js2svg and svg2js exposed as API, ideally as own module. As far as I can see this has been done with some work on [svgp](https://github.com/svg/svgp), although it seems to have stalled. This would yield the possibility to enable other offspring, say a type of `svglint`.

I'd be interested in helping to get this off the ground, if this is seen as the way forward for svgo.

**Comment by GreLI** [comment]
Yeah, it of course planned to do so and rewrite svgo architecture completely. However, it requires a bunch of work, and I don't like API in svgp in the current state.

**Comment by marionebl** [comment]
If you outline the work that is planned for svgp i'd be more than happy to help!

**Comment by GreLI** [comment]
It's not the current problem but certainly will be considered when (and if) there'll be a rewrite.
