### ISSUE TITLE
Feature Request: scale to rounded numbers

### ISSUE THREAD

**Issue by atk** [svg/svgo#488]
See https://medium.com/@larsenwork/598815d74f9c for reference - the author saved a lot of space by scaling the SVG paths up until he had round numbers (with a loss of n% accuracy) and increasing the scale of the viewBox accordingly.

It should be possible to automate this process.

**Comment by paperboyo** [comment]
Related/duplicate of https://github.com/svg/svgo/issues/293.

**Comment by GreLI** [comment]
Yep, it is.
