### ISSUE TITLE
Style removal loses properties

### ISSUE THREAD

**Issue by aleixpol** [svg/svgo#489]
I've found that the optimization process has some issues when converting the style. We've experienced this issue in a couple of places.

Here's an example: http://quickgit.kde.org/?p=plasma-framework.git&a=blob&h=29e74c0f31838fc123fc4a30eddd9d4d7acd61b1&f=src%2Fdesktoptheme%2Fbreeze%2Fwidgets%2Ftasks.svgz&o=plain

When optimizing this one, some components will apply the following change:
```
-    <g
-       id="west-hover-center"
-       transform="matrix(1.0370294,0,0,-0.84615385,70.814663,74.469231)">
-      <rect
-         y="4.0999999"
-         x="5"
-         height="13"
-         width="27"
-         id="rect4957-0-5-7-4-4"
-         style="opacity:0.3;fill:currentColor;fill-opacity:1;stroke:none"
-         class="ColorScheme-Highlight" />
-    </g>
```
into
```
+        <g id="west-hover-center">
+            <path id="rect4957-0-5-7-4-4" class="ColorScheme-Highlight" opacity=".3" fill="currentColor" d="M76 79h28V68H76z"/>
+        </g>
```

With these changes, we lose the fill: currentColor property, leaving the element color-less.

Passing `--disable=convertStyleToAttrs` fixes the issue.

**Comment by GreLI** [comment]
I see `fill="currentColor"` (right after `opacity=".3"`) in your example as well as in the test file.

**Comment by aleixpol** [comment]
You are right, my assessment was wrong. Nevertheless, the representation is still different:

![](http://i.imgur.com/cOS0OW5.png)

**Comment by GreLI** [comment]
Well, SVGO doesn't support embedded styles in SVG for now.

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with the fix is out.
