### ISSUE TITLE
convertPathData.js messes up with gradients

### ISSUE THREAD

**Issue by aleixpol** [svg/svgo#490]
Optimized version of [1] doesn't show gradients.
An inspection using inkscape, shows the gradient vector far away from where it should be.

Passing `--disable=convertPathData` displays as expected.

[1] http://quickgit.kde.org/?p=plasma-framework.git&a=blob&h=21776986ff19cd9ce6ad35ccec2dca9f43547e20&f=src%2Fdesktoptheme%2Fbreeze%2Ftranslucent%2Fdialogs%2Fbackground.svgz&o=plain

**Comment by GreLI** [comment]
Actually, I don't see a difference in any browser.

**Comment by aleixpol** [comment]
Correct, this is only happens after I pass `--disable=convertStyleToAttrs`, that I need to enable to ensure #489 doesn't affect.

**Comment by GreLI** [comment]
Doesn't reproduce after fixing #489.
