### ISSUE TITLE
Calculate viewbox

### ISSUE THREAD

**Issue by iskiselev** [svg/svgo#491]
Is it possible to calculate viewbox similar to getBBox() with SVGO, if it not exists in svg input file and write it back?

**Comment by GreLI** [comment]
Well, there is some implementation for `path` in [plugins/transformsWithOnePath.js](https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js). However, it works only with relative commands (turn off `utilizeAbsolute` in `plugins/convertPathData.js`). For other basic shapes I believe implementation is trivial.

But write it back to where? If you mean `viewBox` attribute it has default value `0 0 width height`.

**Comment by ArmorDarks** [comment]
Just for a note, that question seems to be relative to https://github.com/svg/svgo/issues/548
