### ISSUE TITLE
Empty combined SVG

### ISSUE THREAD

**Issue by markorosic** [svg/svgo#492]
While building my site with Foundation 6 which uses imagemin plugin I noticed that my svg-defs.svg file was broken. I have used [svgstore](https://github.com/w0rm/gulp-svgstore) to create the file in question.

The source file:
`<svg xmlns="http://www.w3.org/2000/svg"><symbol viewBox="0 0 28.6 36" id="shape-mr-symbol"><title>mr-symbol</title><path d="M1.4 13.3c1.3 2.2 2.8 4.2 4.5 6.1.1.2 1.3.2 1.2.1C6 15.7 4.7 12.1 5.3 8.1l-1.2.3c2.3 2.6 3.5 5.8 4.5 9.1 0 .1 1.2-.3 1.2-.6-.5-5.3-1.6-13 3.3-16.6l-.9.4c4.9 10.9.6 23.9 0 35.3l1.1-.7c-1.8-4.8-.5-10.9.6-15.8S19 1.3 26 7.3c5.3 4.6-4.1 9.7-7.8 10.9-5.6 1.7-11.9 3.4-17.7 3.1L0 22.6c2.1 0 4.1-.6 6.1-1 2.7-.5 5.7.2 8.3 1.1 4.5 1.5 8.3 5.9 9.6 10.3l.4-1.3c-.7.3-1.4.4-2.1.3-.3-1.3.1-2.1 1.2-2.4 1.2-.7 2.8-1 4.2-1.5.2-.1 1-.8.9-.8-2.6.1-6.5.7-7.5 3.6-.8 2.3 1 2.6 3 2.2.3-.1.4-1.1.4-1.3-1.2-4.1-4.1-7.2-7.7-9.5-2.3-1.4-4.9-1.9-7.5-2.1-3-.3-5.8 1-8.8 1-.3 0-.5 1.3-.4 1.3 5.1.3 9.7-1.3 14.6-2.3 2.9-.6 5.7-1.4 8.2-3C26.4 15 30.7 8.7 26 5.7c-4.3-2.8-8.8 2.5-10.4 5.8-2.1 4.4-3.1 9.5-3.8 14.3-.4 3.2-.8 7 .4 10.2 0 .1 1.1-.5 1.1-.7.7-11.3 4.9-24.4.1-35.3-.1-.2-.8.3-.9.4-5.3 3.9-4.4 11.3-3.9 17.1l1.2-.6c-1-3.3-2.2-6.3-4.5-8.9-.1-.1-1.2.1-1.2.4-.6 3.9.5 7.3 1.8 11 .4 0 .8.1 1.2.1-1.9-1.7-3.6-3.6-5-5.7-.1-.2-.9-.9-.7-.5z"/></symbol><symbol viewBox="12 -12 48 48" id="shape-point-current"><title>point-current</title><circle id="point-current-outer" fill="currentColor" class="point-current-outer" cx="36" cy="12" r="18"/><circle id="point-current-iner" class="point-current-iner" cx="36" cy="12" r="12"/></symbol><symbol viewBox="12 -12 48 48" id="shape-point"><title>point</title><circle class="st0" cx="36" cy="12" r="12"/></symbol></svg>`

Resulting file: `<svg xmlns="http://www.w3.org/2000/svg">`

**Comment by kevinlaw91** [comment]
The problem is SVGO doesn't keep unused symbol in file. Try disable ```cleanupIDs``` plugin and try again.

**Comment by markorosic** [comment]
Thanks, it did the trick.
