### ISSUE TITLE
Rounding not work on polygon object if convertShapeToPath plugin was disabled

### ISSUE THREAD

**Issue by kevinlaw91** [svg/svgo#493]
When **```convertShapeToPath```** plugin was disabled, SVGO did not perform rounding for points in ```<polygon>``` objects.

I guess this is because the polygon object doesn't get converted to ```<path>```, then the plugin ```convertPathData``` failed to pick it up.

Is ```convertShapeToPath``` required for all kind of floating point rounding? It should be clarified at homepage to reduce confusion.

**Comment by GreLI** [comment]
Actually, there is [/plugins/cleanupNumericValues.js](https://github.com/svg/svgo/blob/master/plugins/cleanupNumericValues.js), but it doesn't process `points`, yes. I guess, it's good place for enhancing.

**Comment by kevinlaw91** [comment]
Yes this is important. This is affecting not just ```points```, but other attributes like ```viewBox``` too.

**Comment by kevinlaw91** [comment]
Unable to reproduce this any more. Closing this.
