### ISSUE TITLE
Ability to add custom plugins

### ISSUE THREAD

**Issue by supercodepoet** [svg/svgo#495]
Looking through the code I did not find a way to add a custom plugin without wrapping the svgo command in my own command line tool. I tried to use a YAML config file and JSON config file but the parser never saw my fn: declaration as a JS function. Is there a way to easily tell svgo here is my custom plugin JS file?

Thanks

**Comment by GreLI** [comment]
Well, the plugin should be in a `plugins` folder of SVGO and has to be listed in `plugins` option. That's how it works for now.
