### ISSUE TITLE
Compound circle is being inverted

### ISSUE THREAD

**Issue by skmasq** [svg/svgo#496]
When minifying SVGs the compound circle with cross inside is being inverted and leaves only cross visible.

I'm using:

- SVGO version: `0.6.0`

- grunt-svgmin version: `3.1.2`

Following plugins are disabled (should I disable any other?):

```javascript
svgmin: {
        options: {
            plugins: [
                {
                    removeViewBox: false
                }, {
                    removeUselessStrokeAndFill: false
                }
            ]
        }
}
```

Original SVG [https://gist.github.com/skmasq/c7a18a91da3f17458f8d](url) (File is compatible with Illustrator)
Minified using SVGO [https://gist.github.com/skmasq/524f1ede47c1b4bfc23a](url)

**Comment by skmasq** [comment]
Fixed issue adding: `{convertPathData: false}`

**Comment by GreLI** [comment]
Definitely a bug in v0.6.1 which is already fixed.

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with the fix is out.
