### ISSUE TITLE
convertPathData looses paths

### ISSUE THREAD

**Issue by darkv** [svg/svgo#498]
I am having a problem optimizing a specific SVG. As seen in the screenshot in the lower image part there are two paths (read circles) missing:

![loosing elements](https://cloud.githubusercontent.com/assets/582546/13006746/57f00d20-d18b-11e5-8da1-9d5eee0c04e3.png)

When disabling the _convertPathData_ plugin the result is correct. See the attached zip file for before/after SVG files.

[icons.zip](https://github.com/svg/svgo/files/127976/icons.zip)

**Comment by GreLI** [comment]
Fixed along with #477.

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with the fix is out.

**Comment by darkv** [comment]
Cool, thanks!
