### ISSUE TITLE
Please consider using static declaration of plugin dependencies.

### ISSUE THREAD

**Issue by MeoMix** [svg/svgo#504]
Hey there,

We're working on getting JSPM's CSS loader all hooked up into PostCSS plugins. We would like to (easily) use CSSNano as our CSS minification plugin. CSSNano has a dependency on svgo.

Currently, JSPM does not have support for dynamic require statements (see here: https://github.com/jspm/registry/issues/221). As such, [this bit of code](https://github.com/svg/svgo/blob/master/lib/svgo/config.js#L99) is causing us some headache (discussed here: https://github.com/MeoMix/jspm-loader-css/pull/2)

It's possible to workaround this issue in a couple of ways. More than likely I'll end up forking svgo, creating static requires, and overriding the dependency, but that's not ideal nor very maintainable.

I can appreciate the appeal of using dynamic require statements, but I'd be very happy if you'd consider replacing it with the alternative.

Thanks

**Comment by GreLI** [comment]
What are dynamic declaration and how it differs from static? How would you use plugins in that case&

**Comment by MeoMix** [comment]
Hey,

Thanks for the response.

Essentially, instead of dynamically building a string which points to an unknown-until-runtime location in the `plugins` folder, all plugins which could potentially be needed should be required upfront and then only worked upon if needed.

I might be able to provide a PR at some point, but need to do some reading to make sure it works as expected. I'll end up doing that on my own fork hopefully sometime this week.

Talking to @guybedford about the issue he said:

> @MeoMix dynamic CommonJS requires are not supported because they are sync and the browser is async. Typically for these plugin patterns you want to ensure the module is already loaded by creating an async layer around it. Eg how we handle Babel plugin loading in the system-babel plugin, by first System.import'ing the plugins ourselves, then running Babel.

You can see that file here: https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js

**Comment by GreLI** [comment]
See #614
