### ISSUE TITLE
Different result on file with converted text outlines on Mac and Windows

### ISSUE THREAD

**Issue by terje** [svg/svgo#506]
Hi,

We are having a problem with an SVG file minified with gulp-svg-min. The minified version of the file changes between running it on a Mac and running it on Windows. Not exactly sure what information is relevant here so please ask if you are wondering anything.

The file in question is here: http://pastebin.com/LY9NHtcx

We are running svgmin like this:

```
gulp.task('imgMin', function() {
  gulp.src(staticPath + '/images/*.svg')
    .pipe(svgmin())
    .pipe(gulp.dest(staticPath));
});
```

We have other SVG files that don't show this behaviour. What is common among the two files that do exhibit this behaviour is that they both have text converted to outlines. None of the other files have this. All our SVG files are created with Sketch on a Mac.

It's a bit hard to see exactly what is different between them, but they show up as changed in Git and there is more than just line endings changed. I see at least a couple different numbers in the SVG.

**Comment by GreLI** [comment]
Hmm, I see no problems when I'm passing this file through svgo.

**Comment by terje** [comment]
Ok, give me a couple days and I'll set up a reduced test for you.

-- 
Terje

**Comment by GreLI** [comment]
It would be nice of you.

**Comment by terje** [comment]
Sorry, I am unable to reproduce it outside of our bigger project now. Test case here: https://github.com/terje/svgo-bug-reduction

Feel free to close this issue, I will reopen or submit another if I am able to reproduce it.

**Comment by GreLI** [comment]
Still couldn't reproduce. However, v0.6.2 is out and there are some fixes that may help.
