### ISSUE TITLE
--pretty should respect .editorconfig

### ISSUE THREAD

**Issue by jaydenseric** [svg/svgo#507]
As a suggestion, `--pretty` should respect [`.editorconfig`](http://editorconfig.org) for formatting, particularly in regards to indentation.

`.editorconfig` is a centralized place to configure encoding and formatting for all text files in a repo, so you don't have to separately configure tools.

Often, I will `--pretty` optimize files and then open them in Atom to make manual edits. Atom conveniently respects my established SVG formatting config but SVGO doesn't, resulting in inconsistent formatting.

A benefit to respecting the config, other members from the team can jump in and start optimizing without having to ask anyone about the formatting. I don't trust everyone to laboriously follow up SVGO optimizations with manual reformatting to conform to our standards.

Ideally there would also be formatting options for the CLI that would take precedent, like how ESLint works.

**Comment by GreLI** [comment]
FYI, there is new option `--indent` added in 0.6.4 which allows to set number of spaces to `--pretty`.

**Comment by TrySound** [comment]
Editorconfig look less popular these days. Wouldn't like to increase package size with editorconfig dependencies.
