### ISSUE TITLE
Correct "precision issues"

### ISSUE THREAD

**Issue by stevenvachon** [svg/svgo#508]
I cannot say exactly what they are, but they are referenced in #387

**Comment by GreLI** [comment]
Done. It seems that «smart» rounding brought odd results sometimes, so I make it to apply only when the rounding is needed. So, in subsequent passes in `--multipass` already rounded numbers will not be modified further.

**Comment by GreLI** [comment]
[v0.6.3](https://github.com/svg/svgo/releases/tag/v0.6.3) with the fix has been just released.
