### ISSUE TITLE
List of safe options

### ISSUE THREAD

**Issue by jt3k** [svg/svgo#509]
Когда обрабатываем большое кол-во файлов при помощи SVGO то иногда получаем испорченный результат. (сломанные иконки)

Подскажите список безопасных опций, которые не влияют на результат.

----

When processed a large number of files using SVGO we sometimes get spoiled result. (broken icons)

Tell me the list of safe options that do not affect the result.

[](https://github.com/CSSSR/csssr-project-template/issues/112)

**Comment by GreLI** [comment]
Да все плагины что-то делают, и в этом плане небезопасны :smiley:. Но опаснее те, что делают что-то более сложное. Вообще я стараюсь все баги чинить (и многое уже починино), так что если что-то реально портится, лучше про это сообщать.

Из последнего, что было исправлено, но ещё на выпущено в релиз: превращение в дуги в `convertPathData` #477 и некорректные переносы трансформаций, если есть маски, в `moveElemsAttrsToGroup`. Также ещё сильное округление может дать погрешности в случаях с дугами, но это редкость в «дикой природе» SVG.

**Comment by jt3k** [comment]
Спасибо за ответ :+1: 
Я тогда пофлудю в ишьюсы если наберу достаточное количество проблемных файлов.

**Comment by cronfy** [comment]
У меня картинку ломает правило `convertStyleToAttrs`. В Chrome показывается просто белая страница вместо картинки (хотя просмотрщик картинок нормально ее отображает).

Вот картинка 

[arrow.zip](https://github.com/svg/svgo/files/1239475/arrow.zip)

**Comment by cronfy** [comment]
Та же картинка в IE11 неправильно позиционируется как background, если включена опция removeDimensions.

А был ли в итоге составлен список безопасных опций? Может, уже наработана какая-то практика?
