### ISSUE TITLE
Improve error handling for plugins

### ISSUE THREAD

**Issue by daniellmb** [svg/svgo#510]
When I recently tried to optimize an SVG file I got the following completely useless error.

![screen shot 2016-03-04 at 11 15 48 am](https://cloud.githubusercontent.com/assets/108018/13537599/919ab55a-e1fa-11e5-8939-93af76f60af3.png)

Currently, the plugins are run like this:

``` javascript
/**
 * Plugins engine.
 *
 * @module plugins
 *
 * @param {Object} data input data
 * @param {Object} plugins plugins object from config
 * @return {Object} output data
 */
module.exports = function(data, plugins) {

    plugins.forEach(function(group) {

        switch(group[0].type) {
            case 'perItem':
                data = perItem(data, group);
                break;
            case 'perItemReverse':
                data = perItem(data, group, true);
                break;
            case 'full':
                data = full(data, group);
                break;
        }

    });

    return data;

};
```

I propose wrapping the code with a try catch block and log useful information about failures. Perhaps something like this:

``` javascript
/**
 * Plugins engine.
 *
 * @module plugins
 *
 * @param {Object} data input data
 * @param {Object} plugins plugins object from config
 * @return {Object} output data
 */
module.exports = function(data, plugins) {

    plugins.forEach(function(group) {
        try {
          switch(group[0].type) {
            case 'perItem':
              data = perItem(data, group);
              break;
            case 'perItemReverse':
              data = perItem(data, group, true);
              break;
            case 'full':
              data = full(data, group);
              break;
          }
        } catch(err) {
          // log error and continue processing other plugins.
          console.warn('Warning: Plugin', group[0].name + ' failed!', group[0].description,
                       '\n', err.message,
                       '\n', err.stack);
        }
    });

    return data;

};
```

This would provide two enhancements. First it would display useful information for debugging/reporting issues. Secondly is would allow the process to continue and gracefully ignore failing plugins as shown below.

![screen shot 2016-03-04 at 11 23 11 am](https://cloud.githubusercontent.com/assets/108018/13537771/938acaa2-e1fb-11e5-9022-ebbf5d2c1c2d.png)

Using this information I was able to quickly find the problem in the convert colors plugin #511.

If this error handling change seems like a useful addition I can create a pull request.

**Comment by GreLI** [comment]
Nice idea, but `group[0]` isn't the actual name of the current plugin. Each group can contain several plugins, so it's a bit more complicated then that.

**Comment by daniellmb** [comment]
Right, this was more pseudo code to get the idea across...

**Comment by TrySound** [comment]
I am covering the whole project with strict tsdoc which should eliminate such errors. If such error happens anyway we can actually see the plugin in stack trace. Skipping failed plugin may work even worse because ast may be corrupted and produce invalid svg. Better explicitly disable the plugin in your config.
