### ISSUE TITLE
Convert colors plugin plugin throws error for uppercase color names

### ISSUE THREAD

**Issue by daniellmb** [svg/svgo#511]
The issue is caused because the code does a lowercase check if the color exists, but then doesn't lowercase the value when it's looked up. So an uppercase color name such as `Black` breaks the plugin.

```javascript
// Convert color name keyword to long hex
if (params.names2hex && val.toLowerCase() in collections.colorsNames) {
  val = collections.colorsNames[val];
}
```

Something like the following would resolve it:

```javascript
// Convert color name keyword to long hex
if (params.names2hex && val.toLowerCase() in collections.colorsNames) {
  val = collections.colorsNames[val.toLowerCase()];
}
```

Found using error handling improvements #510

**Comment by GreLI** [comment]
Thanks for catching this!

**Comment by GreLI** [comment]
[v0.6.2](https://github.com/svg/svgo/releases/tag/v0.6.2) with the fix is out.

**Comment by daniellmb** [comment]
:+1:
