### ISSUE TITLE
What about embiding visual diff utility in svgo for after opt verification?

### ISSUE THREAD

**Issue by a-x-** [svg/svgo#512]
Run diff on source rendered svg and resulted rendered svg After optimization.
Cancel next dangerous optimization step if diff failed
Repeat iteration opt --> diff
Return proof lossless optimized svg

Cool?

**Comment by GreLI** [comment]
Perhaps, but rendering is a heavy optimization, and it also requires heavy dependencies. Also, it doesn't guarantee that image isn't worse, since SVG rendering depends on scale. If it's not sufficient enough then some small details can be loosen. Again, too large scale still is heavy.

**Comment by a-x-** [comment]
there isn't happy in the world :) есть ещё мысль
just run special gemini cases on website with optimized icons with high sensitivity settings (targets on icons)
It 'll be check in `real world` 

Let's automate this (svgo running than run gemini on automaticaly generated icon test cases)

**Comment by GreLI** [comment]
I believe it goes beyond the scope of SVGO. It can a script or whatever.
