### ISSUE TITLE
svgo --show-plugins ordering

### ISSUE THREAD

**Issue by Pomax** [svg/svgo#514]
Calling `svgo --show-plugins` currently returns the list of available plugins in a seemingly random order; in order for users to quickly find the plugin they need, it would be great if this list was `sort()`ed alphabetically.

**Comment by GreLI** [comment]
Well, actually it's the order in which they're being applied.

**Comment by GreLI** [comment]
Not sure it's the best solution, but probably it's a little less messy indeed.

**Comment by GreLI** [comment]
Done in 57dc9aedc4a39325a22125d258d668b156e56812.
