### ISSUE TITLE
Passing --disable=convertStyleToAttrs corrupts files

### ISSUE THREAD

**Issue by aleixpol** [svg/svgo#515]
I've been testing it on the Breeze icons.

Example of svg file that breaks:
https://quickgit.kde.org/?p=breeze-icons.git&a=blob&h=3dd55bcaa991d5d159b88a9ad6aba243afcfbdd7&f=icons%2Fapps%2F32%2Fpreferences-desktop-emoticons.svg&o=plain

**Comment by GreLI** [comment]
It wasn't expected, that someone will keep properties in `style`.

**Comment by GreLI** [comment]
[v0.6.3](https://github.com/svg/svgo/releases/tag/v0.6.3) with the fix has been just released.
