### ISSUE TITLE
RemoveAttrs plugins matches only tags name

### ISSUE THREAD

**Issue by fr-ench** [svg/svgo#516]
Currently, I cannot use removeAttrs plugin with RegExp that match or exclude certain classes, or smth specific other then tag name. Would be really useful to be able to somehow exclude from rule certain svg  files.

I'd like to use smth like this:
'removeAttrs': {
  attrs: '._path(?!._class="filled").*:fill'
}

**Comment by GreLI** [comment]
Technically, it's quite complicated and since the plugin is a byproduct by a third-party committer it's unlikely that someone will improve it.

**Comment by TrySound** [comment]
You can use custom plugin
```js
const plugin = {
  type: 'visitor',
  name: 'remove-my-attrs',
  fn: () => {
    return {
      element: {
        enter: node => {
          if (node.name === 'path') {
            if (node.attributes.class.split(/\s+/).includes('filled')) {
              delete node.attributes.fill
            }
          }
        }
      }
    }
  }
}
```
