### ISSUE TITLE
The file contains data of an unknown image type

### ISSUE THREAD

**Issue by Torkiliuz** [svg/svgo#519]
I am getting the message in the title when processing a folder where there are webfont.svg-files, example:  
**OpenSans-BoldItalic-webfont.svg: The file contains data of an unknown image type**

Is this because it isn't exactly an image, or do you have any information as to why this might occur? If you need any more information just ask me, and I'll try my best :)

**Comment by GreLI** [comment]
Sorry, I've missed the issue. It's a complicated topic. See discussion about file type detection in #306.
