### ISSUE TITLE
Preserved spaces in text/tspan should not be trimmed

### ISSUE THREAD

**Issue by shaneparsons** [svg/svgo#522]
I'm having an issue very similar to #299 with the most recent version and it's causing me some serious issues.

The only difference is I'm using `white-space:pre` styling as well, so if there's no fix to stop the white-space removal directly, maybe you can make a rule specifically for elements with the `white-space:pre` styling?

Here's an example:

**Input**

```
<text>
  <tspan style="white-space:pre">key: value  |  key: value</tspan>
</text>
```

**Output**

```
<text>
  <tspan style="white-space:pre">key: value | key: value</tspan>
</text>
```

**Comment by shaneparsons** [comment]
It behaves the same with the "proper" SVG 1.1 method as well, i.e. `xml:space='preserve'`.

**Comment by GreLI** [comment]
Unfortunately, it's parsing time issue and thus quite complicated at the moment to solve.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
