### ISSUE TITLE
Move attrs to parent group only works when there is more than 1 path in group

### ISSUE THREAD

**Issue by dottodot** [svg/svgo#524]
I have several groups with paths that all contain attrs and to get as I want I have to set `Collapse Unless groups` to false (so the id on the group). When I select `move attr to parent group` it adds the fill (but not stroke) to the parent group of the first group but on the rest of the groups the fill attr remains on the paths.

**Comment by GreLI** [comment]
Sorry, I don't fully understand your issue. Could you provide some more details and examples?

**Comment by dottodot** [comment]
OK so my svg from AI is like below (path values have been remove to keep it easy to folllow

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" baseProfile="tiny" id="template" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 600 300" xml:space="preserve">
  <g id="background">
    <path fill="#FFFFFF" stroke="#000000" d=""/>
  </g>
  <g id="undershorts">
    <path fill="#FFFFFF" />
    <path fill="#FFFFFF" stroke="#000000"/>
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="shortsTrim">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="waist">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="thirdColor">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="secondColor">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="mainColor">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
  <g id="bottomTrim">
    <path fill="#FFFFFF" stroke="#000000"/>
  </g>
</svg>
```
I make clean ids false so the groups keep there ids, make collaspe unless groups false, then select `Move attrs to parent group` which results in the following.

```
<svg baseProfile="tiny" id="template" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 300">
  <g id="background">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="undershorts" fill="#FFF" stroke="#000">
    <path />
    <path />
    <path />
  </g>
  <g id="shortsTrim">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="waist">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="thirdColor">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="secondColor">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="mainColor">
    <path fill="#FFF" stroke="#000" />
  </g>
  <g id="bottomTrim">
    <path fill="#FFF" stroke="#000" />
  </g>
</svg>

```
As you can see the fill attr has moved to the group for the undershorts group but on all the other paths within groups they remain on the path. So it seems that it only works if the group contains more than 1 path

**Comment by GreLI** [comment]
Ah, I understand now. `plugins/moveElemsAttrsToGroup.js` is moving attributes only of there is more than one element. I guess, because there is no profit in moving attributes if there is only one element. Probably, it's best not to move them, because if that group is empty it can be removed. So, it works as expected.
