### ISSUE TITLE
<script> inside SVG

### ISSUE THREAD

**Issue by ethanmay** [svg/svgo#527]
Hi there,

I am using Iconic svg icons, which have "smart" svgs that contain `<script>` tags inside them. I need help figuring out which setting to disable. I have pasted the code below.

``` html
<script class="iconic-api" type="application/ecmascript">
//<![CDATA[
var iconicApis=window._Iconic?window._Iconic.smartIconApis:{};iconicApis["account"]=iconicApis["account"]||function(t){var i=function(i){t.setAttribute("data-state",i);var e,n=t.querySelectorAll(".iconic-account-login"),o=t.querySelectorAll(".iconic-account-logout");if("logout"===i){for(e=0;e<n.length;e++)n[e].setAttribute("display","none");for(e=0;e<o.length;e++)o[e].setAttribute("display","inline")}else{for(e=0;e<n.length;e++)n[e].setAttribute("display","inline");for(e=0;e<o.length;e++)o[e].setAttribute("display","none")}},e=function(){var e=t.getAttribute("data-state");e&&i(e)};return{update:e,setState:i}};
//]]>
</script>
```

The offending code seems to come in here: `e&&i(e)`. When the .svgs are minified, that code is converted to `e&amp;&amp;i(e)`.

Thank you very much for any help you can provide!

**Comment by GreLI** [comment]
Are you using latest SVGO version? I couldn't reproduce this behavior. Have you tried removing `//` comments before `<![CDATA[` since they're totally useless?

**Comment by ethanmay** [comment]
Thanks for the quick reply. I did try removing those `//` and unfortunately it made no difference. I am gulp-imagemin, so it's possible that this is not an issue related to SVGO. Gulp-imagemin includes `imagemin-svgo@4.2.1`, which includes `svgo@0.6.3 `. So it does appear to be the latest version. If it makes a difference, the `<script>` tag I mentioned above is located right before the closing `</svg>` tag.

**Comment by hellol11** [comment]
The comments are not useless. When you use the `<script>` tag, 2 different parsers are working at the same time: the XML parser, and the JavaScript parser. Because the JavaScript parser is active, we need to hide the cdata sections from the JavaScript parser.

**Comment by GreLI** [comment]
As I said I can't reproduce this behavior and CDATA sections are preserved as is. Please provide a reduced test case if you can reproduce the behavior.
