### ISSUE TITLE
optimization breaks embedded css

### ISSUE THREAD

**Issue by ben-page** [svg/svgo#531]
Converting tags type (like changing `rect` to `path`), can break embedded CSS. For example: 
**Original File**

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
     width="10cm" height="5cm" viewBox="0 0 1000 500">
  <defs>
    <style type="text/css"><![CDATA[
      rect {
        fill: red;
        stroke: blue;
        stroke-width: 3
      }
    ]]></style>
  </defs>
  <rect x="200" y="100" width="600" height="300"/>
</svg>
```

**Optimized File**

```
<svg xmlns="http://www.w3.org/2000/svg" width="10cm" height="5cm" viewBox="0 0 1000 500">
    <defs>
        <style>
            rect{fill:red;stroke:#00f;stroke-width:3}
        </style>
    </defs>
    <path d="M200 100h600v300H200z"/>
</svg>
```

In this file the original `rect` has been changed to a `path`, consequently the style is not applied.

**Screen Shot**
![capture1](https://cloud.githubusercontent.com/assets/744035/14329291/5e351e2e-fc00-11e5-9805-409267b796ee.png)

**Comment by ben-page** [comment]
Thinking on this, I don't think the optimization should be turned off if there is are embedded styles defined for tags. Or at least not by default, an config option would be nice.

However, a warning (on the command line, when optimizing) would be very helpful. With [reworkss](https://github.com/reworkcss/css) is should be pretty easy to parse the CSS and identify if there are problematic styles defined.

**Comment by GreLI** [comment]
Actually, a lot of optimizations can break embedded styles since there can be any selector. It's a known issue that svgo doesn't understand css—parsing and applying it is a complex thing to implement.
