### ISSUE TITLE
Broken image after optimization

### ISSUE THREAD

**Issue by lipis** [svg/svgo#532]
When I'm trying to optimize this flag: https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/tj.svg I'm getting this as a result: https://dl.dropboxusercontent.com/u/15234/tj-svgo.svg

**Comment by GreLI** [comment]
Thanks for reporting! Just another issue about passing transform and having references.

**Comment by lipis** [comment]
Awesome! 💯

**Comment by GreLI** [comment]
v0.6.6 with the fix is out.
