### ISSUE TITLE
Broken image after optimization : Namespace prefix i on pgfRef is not defined

### ISSUE THREAD

**Issue by abarre** [svg/svgo#533]
I have this image that is generated by Adobe Illustrator with the option "preserve illustrator editing capabilities" : https://gist.github.com/abarre/21a60e4277bde17d7807af4ba1edebb4 (input.svg)

After optimizing with SVGO, the image is corrupted : https://gist.github.com/abarre/21a60e4277bde17d7807af4ba1edebb4 (output-broker.svg)

The error is `error on line 10 at column 113: Namespace prefix i on pgfRef is not defined`

If I remove this part, it works : 
```svg
<foreignObject requiredExtensions="http://ns.adobe.com/AdobeIllustrator/10.0/" x="0" y="0" width="1" height="1"><i:pgfRef xlink:href="#adobe_illustrator_pgf"></i:pgfRef></foreignObject>
```

Note : Problem seens on svgo 0.6.3

**Comment by abarre** [comment]
Detail of the problem : https://commons.wikimedia.org/wiki/User:Quibik/Cleaning_up_SVG_files_manually

**Comment by GreLI** [comment]
v0.6.6 with the fix is out.

**Comment by abarre** [comment]
Thank you for your fix.
