### ISSUE TITLE
Add option to specify header

### ISSUE THREAD

**Issue by nt1m** [svg/svgo#535]
Some SVGs require a license header, it'd be nice if svgo could automate the process of adding one if specified.

**Comment by GreLI** [comment]
Could you provide some information about what format it should be?

**Comment by nt1m** [comment]
@GreLI 

An example:

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 62" width="132" height="62">
....
</svg>

A parameter that accepts a string or a text file to append as header would fit my needs.

**Comment by GreLI** [comment]
Well, you can write a plugin for that. However, there is no sign that the comment is a license to preserve it. Like an exclamation mark in JS (`/*! some license text */`).

**Comment by nt1m** [comment]
@GreLI I'd be fine with having to regenerate the header every time SVGs are cleaned. The exclamation point is a good idea though.
