### ISSUE TITLE
Fatal error: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by visualcookie** [svg/svgo#536]
Hi,

I recently got this error while trying to compile 120+ SVGs. SVGO closes after 40+ with an error.

**Comment by GreLI** [comment]
Probably, there is some error on processing one of those files. Could you find the erroneous file and report about it?

**Comment by visualcookie** [comment]
Nope, it was not in the logs, sadly.

**Comment by GreLI** [comment]
Probably reduce it to the file by binary search?

**Comment by GreLI** [comment]
Can't do anything without data. Probably there is some invalid content.
