### ISSUE TITLE
Wrong matrix decomposition on convertTransform

### ISSUE THREAD

**Issue by ghetolay** [svg/svgo#541]
I have an element with a transform set as follow : 

```
 matrix( 0.49234309  -0.87040122   -0.87040122   -0.49234309   96.139654   286.1997 )
```

and using svgo with convertTransform enabled breaks the transform. Problem come from the function responsible of the matrix decomposition ( `matrixToTransform()` ). 

The _wrong_ output from `matrixToTransform()` is : 

```
rotate( -60.505  293.42  60.682 )
```

Unfortunately the matrix output was generated by a software so I don't know what's the real composition of it.

**Comment by GreLI** [comment]
Actually, the current result is `scale(1 -1) rotate(60.505 293.421 -60.682)` which is right. There were related fixes, probably, you've used not the latest version of svgo.

**Comment by ghetolay** [comment]
Well, my issue was submitted 6 month ago.
I can confirm it works now with the latest version `0.7.1`.

Thank You.
