### ISSUE TITLE
animate disappearing with removeUnknownsAndDefaults

### ISSUE THREAD

**Issue by maxstarkenburg** [svg/svgo#544]
When using just the removeUnknownsAndDefaults option, some of my &lt;animate&gt;s are disappearing. Perhaps it's just the ones with attributeName="offset". For example:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100">
  <linearGradient id="g1" gradientUnits="userSpaceOnUse" x2="100" y2="100">
    <stop offset="0" stop-color="#f00"/>
    <stop offset="0" stop-color="#0f0">
      <animate attributeName="offset" dur="800ms" to="1"/>
    </stop>
    <stop offset="1" stop-color="#00f"/>
  </linearGradient>
  <rect width="100" height="100" fill="url(#g1)"/>
</svg>
```

the &lt;animate&gt; disappears. In another SVG of mine, however, the attributeName="stop-opacity" ones survive. My apologies if I'm misunderstanding that this is somehow intended behavior, or is actually being caused by svgomg (whose developer didn't get back to me).

**Comment by GreLI** [comment]
That was an error data. Fixed.
