### ISSUE TITLE
scale does not change viewBox?

### ISSUE THREAD

**Issue by hh9527** [svg/svgo#547]
I need to scale all svg icons to 40x40 with transformsWithOnePath plugin, this works. but viewBox is not changed. How can i do this? 

original:

``` xml
<svg width="16" height="16" viewBox="0 0 16 16">
  <path d="..." /> 
</svg>
```

result expected:

``` xml
<svg width="40" height="40" viewBox="0 0 40 40">
  <path d="..." /> 
</svg>
```

but i got:

``` xml
<svg width="40" height="40" viewBox="0 0 16 16">
  <path d="..." /> 
</svg>
```

**Comment by GreLI** [comment]
Yeah it [seems so](https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js#L218). No `viewBox` amending. You can remove it with `removeViewBox` plugin though :wink:.
