### ISSUE TITLE
Option to resize the viewbox to fit the svg content

### ISSUE THREAD

**Issue by ivancuric** [svg/svgo#548]
Would something like this be possible? If you look at the octicons on github, they are cropped to fit the artwork bounds.
I know that illustrator and inkscape have these options, but I was wondering if such a task could be automated using npm scripts.

**Comment by GreLI** [comment]
It's totally possible. Actually ‘[transformsWithOnePath](https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js)’ plugin computes BBox of the path (but for scaling). You need only to translate and resize the image (can be done jusy by amending `viewBox`). However, the plugin supports only relative coordinates commands (e.g. “l” but not “L”) and the task itself is not a SVGOs purpose.

**Comment by ivancuric** [comment]
Yea, it's not really in SVGOs domain. What would be the best way to go about the problem in your opinion?

**Comment by GreLI** [comment]
Developing own SVGO plugin is totally fine I think.

**Comment by ivancuric** [comment]
I'll try. Still trying to understand how this all works :) Could use some help.

**Comment by GreLI** [comment]
General information is in “[How it works](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md)” doc.

**Comment by ArmorDarks** [comment]
That would be nice addition :+1: 

I agree it's indeed seems to be a bit out of scope for svgo, however, from another perspective, it can be named as kind of optimization too.

**Comment by AndreyKozlov1984** [comment]
There is a https://github.com/cncf/svg-autocrop project which does exactly this. It is used a lot in a cloud native computer foundation projects like landscape.cncf.io to automatically crop all svg files via calculating an ideal viewbox.

**Comment by glennosss** [comment]
Another option: https://github.com/glennosss/svgo-autocrop

**Comment by xamgore** [comment]
I've rewritten those two into https://github.com/xamgore/svgo-autocrop — SVGO v4 support and no browser installation.
