### ISSUE TITLE
Test svgo for images of mathematical formulae

### ISSUE THREAD

**Issue by physikerwelt** [svg/svgo#549]
We tried to use svgo for SVG images displaying of mathematical formulae generated by MathJax. 
While this leads go good results in many cases, it fails for at least one [case](https://github.com/mathjax/MathJax-node/issues/235).
Thus, we need to understand in which cases svgo guarantees to keep the spatial alignment of the glyphs used in the formulae and in which cases, this cannot be guaranteed.

_Disclaimer: I'm aware that SVGs are not a good format for mathematical formulae and MathML should be used instead. However, the svg fallback images are required at the moment since not all browsers support MathML reasonably well._

**Comment by GreLI** [comment]
Quite a bug! Thanks for reporting!
