### ISSUE TITLE
Groups with data-bind get removed

### ISSUE THREAD

**Issue by sateffen** [svg/svgo#550]
Hey,

didn't see this issue, I hope it's no duplicate: The option "collapseGroups" removes group-elements, which contain a `data-bind`. So my code

```
<g data-bind="...">
<rect ... data-bind="..." />
</g>
```

Gets reduced to `<rect ... data-bind="..." />` and the important group is gone.

I know about the intention to merge down the attributes down to the single element, but this doesn't work in this case (and will never work, because the group data-bind will generate new child elements).

Is there a way to remove the empty `<g>` elements, but every group with at least one attribute is remained (or at least the ones with data-\* attributes)? Maybe there is and I don't get the option?

**Comment by GreLI** [comment]
Thanks for reporting, that was a nasty bug!
