### ISSUE TITLE
SVGO new logo

### ISSUE THREAD

**Issue by cjdowner** [svg/svgo#554]
We're going to be using SVGO in a project of ours, we were planning on showing the logo.

As a designer, I'm aching to make a couple of improvements. Would anyone mind? I plan on keeping the same general shape, colours, and concept. Just refresh the style a little bit.

**Comment by GreLI** [comment]
Personally, I think that SVGO needs a brand new modern logo. I doubt that current one is well-known.

**Comment by deepsweet** [comment]
👍
