### ISSUE TITLE
Remove xmlns:xlink

### ISSUE THREAD

**Issue by iamdriz** [svg/svgo#557]
How do I remove: `xmlns:xlink="http://www.w3.org/1999/xlink"` from the SVG?

As using: `{removeAttrs: { attrs: ['svg:xmlns', 'svg:xmlns:xlink'] }},` doesn't work... only the `xmlns` is removed.

**Comment by GreLI** [comment]
Why not `xmlns:xlink`? What do you mean by “only the `xmlns` is removed”?

**Comment by kevinSuttle** [comment]
Was wondering about the same thing.

**Comment by iamdriz** [comment]
@GreLI @kevinSuttle Because the `:` is used by this script as an element search it conflicts with attributes that have `:` in them. So for example I want to remove the attribute: `xmlns:xlink` from the `svg` element but because it sees that `:` it tries to remove `xlink` from the `xmls` element which doesn't exist. That make sense?

**Comment by GreLI** [comment]
No. What did you have? What did you do? And what did you get in result? My guess is that you should run SVGO with `{removeAttrs: { attrs: ['xmlns:xlink'] }},` in config.

**Comment by iamdriz** [comment]
@GreLI That causes it to try and remove an `xlink` attribute from an `<xmlns>` element (which doesn't exist!). The problem is that the `:` colon is used as a prefix to choose which element to apply the search and in this case the attribute itself contains the prefix so confuses SVGO.

**Comment by GreLI** [comment]
Got it. The plugin API isn't that good really. Any ideas or suggestions?

**Comment by anaibol** [comment]
`removeAttrs: {attrs: '(stroke|xmlns)'},` works

**Comment by kevinSuttle** [comment]
I wonder if you can escape the : or maybe process them as template literals with backticks.

**Comment by joscha** [comment]
Found this thread because I had the same problem when transforming an SVG to vdom calls.
The following plugin removes all namespaced attributes:

```js
    {
      removePrefixedAttributes: {
        type: 'perItem',
        fn: (item) => {
          item.eachAttr((attr) => {
            if (attr.prefix && attr.local) {
              item.removeAttr(attr.name);
            }
          });
        },
      },
    }
```

**Comment by ChenYCL** [comment]
same issues , what the solution is ?

**Comment by ManAnRuck** [comment]
is it a new issue in a new version? I've got the same issue :/

**Comment by tom-rigelblu** [comment]
> Found this thread because I had the same problem when transforming an SVG to vdom calls. The following plugin removes all namespaced attributes:
> 
> ```js
>     {
>       removePrefixedAttributes: {
>         type: 'perItem',
>         fn: (item) => {
>           item.eachAttr((attr) => {
>             if (attr.prefix && attr.local) {
>               item.removeAttr(attr.name);
>             }
>           });
>         },
>       },
>     }
> ```

Thanks! Looks like the general solution is use a dot in place of the colon
```js
 {
      name: 'removeAttrs',
      params: {
        attrs: ['fill', 'xml.space'],
      },
    },
```

**Comment by dink** [comment]
Just had the same issue and found a simple solution. This should also work for any elements that may contain a `:` colon. You need to set a different `elemSeparator` such as `?` for example. Then make sure that new separator is present here again `attrs: '*?(...)`

```js
    {
      name: 'removeAttrs',
      params: {
        elemSeparator: "?",
        attrs: '*?(aria-labelledby|xmlns:xlink)',
      }
    }
```

Hope that helps.
