### ISSUE TITLE
Unknown argument error

### ISSUE THREAD

**Issue by lifeiscontent** [svg/svgo#560]
I'm trying to use this comment with svgo `find img -name "*.svg" | xargs svgo`

and it is giving me an `Unknown argument: img/centers/icons/peace-of-mind.svg` error.

is there something I'm misunderstanding here or is this a bug of svgo?

**Comment by lifeiscontent** [comment]
I also tried `svgo -f img/**`

and `svgo -f img/**/*.svg` but no luck

**Comment by GreLI** [comment]
`svgo` accepts only two filenames — one for input and one for output. So, `xargs` isn't suitable for bunch of files. You need to use `for` loop or folder syntax that is `svgo -f img` (without `**`).

**Comment by marcopashkov** [comment]
My workaround: `find . | grep "\.svg$" | xargs -Iz -n 1 -P <number of CPUs> svgo z`. The `-n 1` argument tells xargs to only use one file at a time. With `-P` you can run it in parallel.

**Comment by lifeiscontent** [comment]
@marcopashkov this is awesome, thanks
