### ISSUE TITLE
Breaks SVG view in GNOME image viewer

### ISSUE THREAD

**Issue by rugk** [svg/svgo#566]
Example file: https://cdn.rawgit.com/PrivateBin/assets/96208cd24ca1c5d2dbf819fe3f101a34b58dc800/images/preview/icon.svg

Now minify it and you get this file with ~1,9KB:
https://gist.github.com/rugk/cd91d31eb7871f2f129ab158f93c60a7

In browsers this looks gode, but in the GNOME image viewer of LMDE it looks broken:
![brokensvg](https://cloud.githubusercontent.com/assets/11966684/16946642/e97cb8a6-4daa-11e6-831f-4d847b3ac86c.png)

GNOME image viewer version:
![gnomeversion 3.10.1](https://cloud.githubusercontent.com/assets/11966684/16946762/7e37ca8a-4dab-11e6-963c-c3fa54ee7564.png)

SVGO used with [atom-svgo](https://github.com/1000ch/atom-svgo) (uses SVGO v0.6.6).

**Comment by derhuerst** [comment]
Can you give an example, with both the SVG you optimized and which plugins were enabled?

**Comment by rugk** [comment]
See edit...

**Comment by GreLI** [comment]
I guess, GNOME viewer is somewhat broken. IIRC, colleague of mine has encountered the problem as well.

**Comment by rugk** [comment]
Okay, that's good to hear (as it means the SVG is valid).

If it is already a known bug: Is there a bug report for this opened in the GNOME issue tracker somewhere?

**Comment by GreLI** [comment]
Not I'm aware of.

**Comment by rugk** [comment]
Okay, reported: https://bugzilla.gnome.org/show_bug.cgi?id=769052
