### ISSUE TITLE
Destroys SVG Fonts

### ISSUE THREAD

**Issue by andrewcharnley** [svg/svgo#567]
Any of the SVG font files within;

https://github.com/igaro/app/tree/master/src/cp/cdn/fonts

**Comment by GreLI** [comment]
Have you disabled `removeUselessDefs` plugin? It removes non-referenced `<defs>` like fonts.

**Comment by andrewcharnley** [comment]
Not done a thing, shouldn't this plugin be disabled by default then?

**Comment by GreLI** [comment]
Nope, SVG fonts aren't usual images and, frankly, obsolete by now. I'd strongly recommend using modern font formats like WOFF. All modern and widespread browsers support it, often with additional font features, while SVG fonts even don't have base things like kerning. It's just a set of glyphs outline.

**Comment by andrewcharnley** [comment]
I'm using otf, woff etc, the svg is a fallback for older browsers. 

I still thing the role of svgo should be to clean and not destroy. ;)
