### ISSUE TITLE
Remove empty containers should be disabled by default

### ISSUE THREAD

**Issue by maksad** [svg/svgo#569]
`removeEmptyContainers` is handy plugin, but it might a bit tricky to enable it by default. One issue could be "empty pattern" container. According to `removeEmptyContainers` it is empty, but in fact it serves as holder that can be filled by `css`. Here is an actual example:

**Unminified file:**
[plunker for the svg demonstration](https://plnkr.co/edit/YoXcSKgbJsbNdW92oeub?p=preview)

<img width="295" alt="screen shot 2016-07-25 at 12 34 41" src="https://cloud.githubusercontent.com/assets/4527650/17093706/3e926602-5264-11e6-882e-8bd0284efae9.png">

**Minified with `removeEmptyContainers`:** 
[plunker for the svg demonstration](https://plnkr.co/edit/ZNYys3Z9IzOtQGYMCmvm?p=preview)
<img width="289" alt="screen shot 2016-07-25 at 12 34 45" src="https://cloud.githubusercontent.com/assets/4527650/17093697/3421d2fc-5264-11e6-9ac8-c11b038c661d.png">

**Minified without `removeEmptyContainers`:**
[plunker for the svg demonstration](https://plnkr.co/edit/swbAEk4mxVWPaB56R607?p=preview)

<img width="295" alt="screen shot 2016-07-25 at 12 34 41" src="https://cloud.githubusercontent.com/assets/4527650/17093706/3e926602-5264-11e6-882e-8bd0284efae9.png">

As you may have noticed the:
```
  <pattern  id="SVGID_2_" xlink:href="#_x3F__yellow" patternTransform="matrix(0.7175 0 0 0.7175 -1968.5363 -1723.4424)">
  </pattern>
```
is considered empty and therefore removed.

**Comment by GreLI** [comment]
Have you tried it in latest version? Work fine for me in 0.6.6.

**Comment by maksad** [comment]
You are right. seems that the versions above `^0.6.0` solves this issue. 👍
