### ISSUE TITLE
issue with syntax calling removeStylement  on svg file 

### ISSUE THREAD

**Issue by myselfgaurav** [svg/svgo#573]
i wrote below command but it did not work , please help me with correct syntax

`svgo removeStylement  1.svg 2.svg`

**Comment by GreLI** [comment]
See [How to use](https://github.com/svg/svgo#how-to-use) (or cli output) about basic usage and [config](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config) about configuring plugins. The config is passed by `--config` command line option.

**Comment by GreLI** [comment]
To be clear. SVGO runs like this:
```
svgo
