### ISSUE TITLE
doesn't work with mock-fs

### ISSUE THREAD

**Issue by awinogradov** [svg/svgo#574]
If you try to use SVGO as nodejs module in tests, where you have mock-fs for any targets you will see this error:

```
ENOENT, no such file or directory '/Users/username/Sources/project/node_modules/svgo/lib/svgo/../../.svgo.yml'
 at Binding.<anonymous> (/Users/username/Sources/project/node_modules/mock-fs/lib/binding.js:353:15)
 at maybeCallback (/Users/username/Sources/project/node_modules/mock-fs/lib/binding.js:43:17)
 at Binding.open (/Users/username/Sources/project/node_modules/mock-fs/lib/binding.js:327:10)
 at Object.fs.openSync (/Users/username/Sources/project/node_modules/mock-fs/node/fs-6.3.0.js:598:18)
 at Object.fs.readFileSync (/Users/username/Sources/project/node_modules/mock-fs/node/fs-6.3.0.js:466:33)
 at Object.readFileSync (/Users/username/Sources/project/node_modules/mock-fs/lib/index.js:59:31)
 at module.exports (/Users/username/Sources/project/node_modules/svgo/lib/svgo/config.js:31:48)
 at new module.exports (/Users/username/Sources/project/node_modules/svgo/lib/svgo.js:21:19)
 at Object.exports.html (/Users/username/Sources/project/src/lib/compilers/index.js:45:16)
 at Promise.resolve.then.screen (/Users/username/Sources/project/src/submodule/screen/actions/index.js:43:37)
 at process._tickCallback (internal/process/next_tick.js:103:7)
```

node `v6.2.1`
npm `3.9.3`
svgo `0.6.6`

**Comment by GreLI** [comment]
SVGO fails to read the default config.

**Comment by awinogradov** [comment]
yep

**Comment by GreLI** [comment]
So what the point of the issue?

**Comment by awinogradov** [comment]
So, svgo doesn't work if u try to use it with mock-fs. I think it's necessary in general and for me, because many users use mock-fs in tests. Now I can't use svgo and I need to find another tool, but I don't want to do it. I like svgo and I think u can solve this problem. I think problem can be in yml parser, but I'm not sure.

**Comment by derhuerst** [comment]
@awinogradov have you manually confirmed the file exists?

**Comment by GreLI** [comment]
It's not yml parser, it's [svgo/lib/svgo/config.js](/svg/svgo/blob/1162dac878a36bfe317040283b4777c62ab600ea/lib/svgo/config.js#L31) as stack trace says. It tries to read the default config file as I said above.

**Comment by derhuerst** [comment]
> It's not yml parser, it's svgo/lib/svgo/config.js:31:48 as stack trace says. It tries to read the default config file as I said above.

Yeah, but why can't it read `.svgo.yml`? Is that because of `mock-fs` or because of something else?

**Comment by awinogradov** [comment]
@derhuerst I'm absolutely sure. I've made example for exception demo https://github.com/awinogradov/svgo-ex. You can repeat it:

``` bash
git clone git@github.com:awinogradov/svgo-ex.git
npm i
node .
```

**Comment by derhuerst** [comment]
Your example doesn't seem to "copy" the files into the mock fs:

```js
const mock = require('mock-fs');
const SVGO = require('svgo');

mock({[process.cwd()]: mock.directory()});

const svgo = new SVGO();
```

Also, svgo loads the yaml file relative to the *current file*, not to the current working directory. This looks like it might be another reason it fails.

**Comment by awinogradov** [comment]
U can do any operations with mock-fs. SVGO fails anyway :(

**Comment by derhuerst** [comment]
@awinogradov 

I think this issue isn't related to SVGO.

You first have to tell mock-fs which files should be available in the mocked fs. The following code fails (even though it doesn't even use SVGO):

```js
'use strict'

const mock = require('mock-fs')
const fs = require('fs')
const path = require('path')

mock({[process.cwd()]: mock.directory()});

fs.readFileSync(path.join(__dirname, 'package.json'))
```

**Comment by awinogradov** [comment]
@derhuerst yep. I'm going to mock-fs issues)

**Comment by awinogradov** [comment]
https://github.com/tschaub/mock-fs/issues/158

**Comment by blade254353074** [comment]
@adamdicarlo 

It might be caused by .yarnclean file.
This file include `.*.yml`, when you yarn install, match files will be ignore.

**Comment by blade254353074** [comment]
https://yarnpkg.com/en/docs/cli/clean

**Comment by athlite** [comment]
To get rid of this problem temporarily, edit  ./node_modules/svgo/lib/svgo/config.js
Line 31, set defaults var:
defaults = { plugins: [] }
