### ISSUE TITLE
removeUselessStrokeAndFill is not stable in our environment

### ISSUE THREAD

**Issue by zdila** [svg/svgo#575]
We are using svgo with [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader) to compile our webapp. Compilation produces client assets and server assets. The same source SVG file gets minified to two different versions on client and server.

The problem has been removed by setting `{ "removeUselessStrokeAndFill": false }`. There are no other settings (using defaults).

Please see [files.zip](https://github.com/svg/svgo/files/422986/files.zip) which contains 3 files - two with hashed names are minified version of the third file.

Please, where could be the problem?

**Comment by GreLI** [comment]
Well, I don't see any difference in browser. The only difference in hashed files is that the first element
```svg
<path fill="#FFF" fill-opacity="0" d="M-10-10h155v60H-10z"/>
```
is converted by `removeUselessStrokeAndFill` to
```svg
<path fill="none" d="M-10-10h155v60H-10z"/>
```
So what the problem? Is there one?

**Comment by zdila** [comment]
The problem is that two different results were produced with the same arguments. I'll do some more testing and inform you if I find some more details.
