### ISSUE TITLE
use json as config

### ISSUE THREAD

**Issue by pixelass** [svg/svgo#578]
Since`yml` is not as well known as`JSON` and also opens a lot more potential issues I think it would be nice to offer an option to define config in a JSON file instead.

IMHO the yml syntax is irritating and results in issues e.g. #558

**Comment by derhuerst** [comment]
I think JS files are the most straightforward, since you can put inline functions etc.

**Comment by pixelass** [comment]
@derhuerst I don't disagree ;)

JSON is the main format for a lot of tools (.eslintrc, .babelrc ...) hence the suggestion.

IMHO `js` and `json` are better than `yml`  at least when working in a node environment

**Comment by GreLI** [comment]
Actually, one can pass a json file as a config.

**Comment by rtxrulez** [comment]
@GreLI Or can you give an example of json config ?

**Comment by GreLI** [comment]
It's same as YML just in JSON.
```json
{
  "plugins": [
    "removeDoctype",
    "removeXMLProcInst",
    "removeComments",
    "removeMetadata"
  ]
}
```

**Comment by zahidlabs** [comment]
> It's same as YML just in JSON.
> 
> ```json
> {
>   "plugins": [
>     "removeDoctype",
>     "removeXMLProcInst",
>     "removeComments",
>     "removeMetadata"
>   ]
> }
> ```

How to pass plugin parameters like, 
  removeViewBox: false
  removeXMLNS: false

**Comment by GreLI** [comment]
@zahidlabs see readme, like:
```
    {
      name: 'removeViewBox',
      active: false
    }
```
API was reworked in SVGO 2.
