### ISSUE TITLE
Synchronous version of SVGO::optimize

### ISSUE THREAD

**Issue by MaKleSoft** [svg/svgo#580]
Would be nice. Just saying...

**Comment by derhuerst** [comment]
Since the core of SVGO is inherently asynchronous, that would be difficult to pull of.

If you tell me how you want to use it, I'd be glad to help you.

**Comment by MaKleSoft** [comment]
I'm integrating the optimizer into another tool that until now is working synchronously. I was just hoping adding a synchronous method would be possible without too much hassle so I didn't have to change my api 😊 other than this is exactly what I was looking for! Thanks for the quick answer, I guess I'll close the issue now.

**Comment by derhuerst** [comment]
> I'm integrating the optimizer into another tool that until now is working synchronously. I was just hoping adding a synchronous method would be possible without too much hassle so I didn't have to change my api

This is by definition impossible. Since JavaScript runtimes execute blocks until they finish (without pausing and switching to another context), you can not possible "wait" synchronously for another asynchronous context.

**Comment by MaKleSoft** [comment]
I know... I was just thinking many packages (including the core node
packages) have synchronous as well asynchronous versions of most functions
so maybe your dependecies offer that choice, too.

**Comment by derhuerst** [comment]
SVGO relies on at least one async library ([sax](https://github.com/isaacs/sax-js#readme)).

**Comment by MaKleSoft** [comment]
@derhuerst I see. Anyway, thanks so much for the clarification!
