### ISSUE TITLE
add dimensions from viewbox attribute

### ISSUE THREAD

**Issue by fr-olivier** [svg/svgo#581]
Hello,

Is it possible to add dimensions as attributes from viewbox values? If not, how can I write my own plugin to do it? I wrote one, put it in plugins/ and .svgo.yaml, but nothing changes. I use it through gulp-svgmin though, I don't know if that makes a difference.

Thanks in advance for your help,
François

**Comment by GreLI** [comment]
IIRC, there is no such a plugin currently,

**Comment by GreLI** [comment]
To use a plugin you have to put a plugin into svgo `plugins` directory and then add it through a config. Alternately, you can pass it as a function in a JSON config (as were discussed in #564).
