### ISSUE TITLE
Allow sync usage

### ISSUE THREAD

**Issue by ArmorDarks** [svg/svgo#584]
It would be great if async usage would be optional

So far forceful usage of async in SVGO causes a lot of pain in libraries, which can't handle natively async calls. For example, some templates language doesn't play well with it at all.

Any chances for optional sync implementation?

**Comment by ArmorDarks** [comment]
I see that some efforts have been made here https://github.com/svg/svgo/issues/580, though, they didn't succeed.

**Comment by GreLI** [comment]
I'm afraid the only option use it sync is to wait for execution in command prompt.

**Comment by ArmorDarks** [comment]
`<irony>`10 out of 10 solution`</irony>`

**Comment by yvele** [comment]
It's maybe a bit ugly but here is a hack using [deasync](https://github.com/abbr/deasync)

```js
import SVGO from "svgo";
import deasync from "deasync";

function svgoOptimizeSync(svgo, content) {
  let res;
  svgo.optimize(content, result => res = result);
  deasync.loopWhile(() => !res);
  return res;
}
```

**Comment by ArmorDarks** [comment]
@yvele Thanks for additional solution. Unfortunately, it implies additional dependency or a hack, which we'd like to avoid.

I think the real issue here is that SVGO _does not use promises_ and instead relies on callback. Otherwise it would be very easy to do with `async function`. But as right of now, we're forced to use `deascyn`-like hacks, or use some means to promisify SVGO, which, I'd say, isn't ok on 2017.

Though, I don't want to insult developers. SVGO is great library and it saved us like a ton of kbs and time.

**Comment by GreLI** [comment]
SVGO has appeared when there was no promises.

**Comment by ArmorDarks** [comment]
Yeap, I know.

**Comment by GreLI** [comment]
`SVGO.optimize()` now returns `Promise` in v1.0.0.
