### ISSUE TITLE
How do you disable removal of whitespace

### ISSUE THREAD

**Issue by axelson** [svg/svgo#585]
I'd like to run all of the optimizations except for removing white-space (for readability on large SVG files) but I can't figure out how to do this. I though that `svgo --disable cleanupAttrs test.svg` would work, but whitespace is still removed. Is whitespace removed in a different plugin?

**Comment by GreLI** [comment]
Whitespace is removed during parsing and there is no way to preserve it. There is option `--pretty` to format output svg.

**Comment by axelson** [comment]
Cool, thanks! That works.
