### ISSUE TITLE
Replace linked PNG SVG with embedded PNG

### ISSUE THREAD

**Issue by lolobosse** [svg/svgo#590]
Hi there,

I got the use case today that we used linked SVG (SVG with PNG linked to it) and I wanted to pack everything in the SVG. I do not think it is currently possible with the lib but I wrote a small script for it. I'd be glad to include it in the lib if it helps 😄  

Could it be an interesting feature for SVGO?

To summary: you have a folder with PNGs and one SVG which refers to all these PNGs and SVGO compresses everything in a big optimised SVG with Base64 Strings instead of links (which makes it easier for web 😉 👍 )

**Comment by paulocoghi** [comment]
Also, there are cases where is strictly important to preserve linked images. It's up to you, when importing your PNGs in your design tool, to decide if your imported image will be linked or embedded.

**Comment by lolobosse** [comment]
@paulocoghi Yeah of course, I wanted to give it as an option only (not to force the user to use embedded images).

The use case was that I wanted really small pictures so I took my PNGs and minified them, then I minified my SVGs and I wanted to put them back together not to create 2 HTTP Requests.

But ok, I can understand that this could be out of scope 😄 👍

**Comment by paulocoghi** [comment]
@lolobosse Now I understand you better! And, now, I think this would be interesting :smiley:

**Comment by paulocoghi** [comment]
For automation purposes, +1

**Comment by lolobosse** [comment]
Cool, I just need to learn how the lib is structured. 😆 

Let's see what I can get done in the next days. 🚀

**Comment by GreLI** [comment]
Feel free to write a plugin if you want.
