### ISSUE TITLE
Preserved spaces in text/tspan should not be consolidated

### ISSUE THREAD

**Issue by MacX19** [svg/svgo#591]
I'm having an issue very similar to #522 with the most recent version and all plugins disabled.
Input:

```
<text xml:space="preserve">
   <tspan>E   X   A   M   P   L   E</tspan>
</text>
```

Output:

```
<text xml:space="preserve">
   <tspan>E X A M P L E</tspan>
</text>
```

**Comment by GreLI** [comment]
I don't think there is any. I think it's a parse-time issue.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
