### ISSUE TITLE
cleanupIDs.js:123 for (var ID of referencesIDs)

### ISSUE THREAD

**Issue by alentsch** [svg/svgo#593]
svgo 0.7.0 fails with the following error message on my Ubuntu 14.04.2 installation:
```
$ svgo bsb.svg 

/usr/local/lib/node_modules/svgo/plugins/cleanupIDs.js:123
    for (var ID of referencesIDs) {
                ^^
```
Usage/help shows properly when calling svgo without arguments.
Installation was done with "npm install -g svgo"
I tried with two different files, one created with Inkscape and the other from https://en.wikipedia.org/wiki/Scalable_Vector_Graphics - same error.

Please advise what I can do :-)

**Comment by GreLI** [comment]
SVGO requires Node.js 0.12 or higher. Unfortunately, Ubuntu has outdated version of Node.js, so you have to upgrade it. See https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions for instructions.

**Comment by alentsch** [comment]
Thank you GreLI, this solved my problem!!!

**Comment by GreLI** [comment]
You're welcome.
