### ISSUE TITLE
If you provide the --indent the --pretty flag could be omitted

### ISSUE THREAD

**Issue by lipis** [svg/svgo#596]
I think we could skip writing explicitly the the `--pretty` when `--indent=4` is used..

```
svgo --pretty --indent=4 foo.svg
```

Thas is also very clear that the intention is to prettify the file with 4 spaces

```
svgo --indent=4 foo.svg
```

**Comment by Nejik** [comment]
I suppose it is bad idea, because it will break code like this

js2svg : { 
    pretty: config.isDevelopment,
    indent: 2 
}

**Comment by GreLI** [comment]
What about doing so only in command line?
