### ISSUE TITLE
scale / mirror / shift (transform) plugin

### ISSUE THREAD

**Issue by puzrin** [svg/svgo#60]
Sometime it's useful to add transformation for source images. For example, when you attach svgs from external project via git submodule, but wish to fit image size for your needs.

That can be outlier for SVGO, but looks convenient - just one more section in config, instead of separate tools.

PS. That can be strange, but i don't know good SVG transform utility. We use kludge with raphael & phantomjs.

**Comment by GreLI** [comment]
Well, there is ``transformsWithOnePath`` plugin. Also, check up great [Snap.svg](http://snapsvg.io/).

**Comment by puzrin** [comment]
@GreLI that plugin was done by [my request](https://github.com/svg/svgo/blob/master/plugins/transformsWithOnePath.js#L4) and is not as flexible, as suggested in this ticket. Snapsvg also is not related to this ticket anyhow.

Anyway, there is [svgpath](https://github.com/fontello/svgpath) to do this job.
