### ISSUE TITLE
transformsWithOnePath doesn't include arc instructions to calculate bounds

### ISSUE THREAD

**Issue by bummzack** [svg/svgo#600]
If a path contains elliptical arc curves ("A" or "a" SVG instruction), these segments won't be used to calculate the real path bounds. This leads to incorrect vcenter results and probably also to wrong scaling.

**Comment by GreLI** [comment]
:disappointed:

**Comment by bummzack** [comment]
@TrySound Has this been fixed or are you just closing old issues?

**Comment by TrySound** [comment]
transformsWithOnePath no longer exist. I can reopen the issue if you would give me svg to reproduce the problem.

**Comment by bummzack** [comment]
Ah I see. No problem in keeping this issue closed if it's no longer applicable.
Thanks for clearing that up.
