### ISSUE TITLE
Requiring node v0.12

### ISSUE THREAD

**Issue by leifdalan** [svg/svgo#602]
Requiring a different Node engine should be considering a breaking change. An environment where this package worked without issue and now has an issue should be considered a major version upgrade.

Please republish the latest release as a major, not minor release.

**Comment by usirin** [comment]
This broke our builds. `css-loader` uses `cssnano` uses `postcss-svgo` uses `svgo`. And we did not even changed the version of `css-loader` as we are using strict version numbers[*](https://github.com/koding/koding/blob/master/client/package.json#L122)

Not sure what is the best solution.

**Comment by GreLI** [comment]
Versions below 0 don't follow semver. Why not just use modern environment? Node 0.10 is waaay outdated and buggy.

**Comment by GreLI** [comment]
Btw, Node 0.10 will be officially completely unsupported in 10 days.

**Comment by pmwisdom** [comment]
@GreLI Some of us are not afforded the opportunity to use .12+. A build server I am required to use is locked in at .10 for instance. A change from .10 for a lot of people is just not feasible whereas bumping this package by a major release so that we can be stuck in our archaic ways would not require much effort.

**Comment by ben-eb** [comment]
What is blocking svgo's usage of semver at this point? Bumping to v1.0.0 would be a very welcome change as modules like https://github.com/ben-eb/gulp-svgmin, https://github.com/ben-eb/metalsmith-svgo & https://github.com/ben-eb/postcss-svgo (and a ton of others) could benefit from new features without requiring manual version bumps.

It's been 4 years since the initial release, after all. 😄

**Comment by deepsweet** [comment]
@GreLI so let's use semver? every breaking change is a major bump (positive integers are still free), every new feature is a minor and every fix is a patch. well, 4 years ago this was not so popular :) v1.0.0 FTW.

**Comment by palmerj3** [comment]
Yep broke our builds too

**Comment by GreLI** [comment]
@deepsweet, was thinking about it too. I think yeah, it's mature enough. Most bugs fixed, but what disturbs me is that SVGO still doesn't understand CSS.

**Comment by deepsweet** [comment]
@GreLI supporting CSS in its basic form could be v1.1 or whatever minor version bump if it doesn't break backward compatibility or something. so imo it's time for 1.0 for sure.

**Comment by GreLI** [comment]
@deepsweet right.

**Comment by orbiteleven** [comment]
Ditto. We don't have the ability to upgrade our Node version yet. Builds for ANYONE using Node 0.10.x and css-loader are broken now.

**Comment by usirin** [comment]
Guys, how hard can it be to make another release and fix 0.10.x users' problems as well?

**Comment by deepsweet** [comment]
btw why all your builds are broken if there was a minor version bump while a major number is still zero?

> Major version zero (0.y.z) is for initial development. Anything may change at any time.
http://semver.org/

this is why we have that special behaviour of `^`-range:

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice.
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

so you had to use something like `"svgo": "^0.6.6"` to follow semver from your side. so... have you been using `*` or `0.x`?

it's a different kind of question why there is still no `svgo@1.0.0`.

**Comment by deepsweet** [comment]
in other words: dropping Node.js 0.10 was a breaking change for sure, no doubt about it. but it's totally allowed to make that only with minor version number while major one is zero.

**Comment by leifdalan** [comment]
It looks like at least for my build, it is due to `postcss-svgo`'s recent version bump:

https://github.com/ben-eb/postcss-svgo/commit/12c10e7ae173fb5c0a3c730d61d5592d2fc154cb

**Comment by deepsweet** [comment]
greenkeeper has been working hard :) builds are so green now.

@GreLI could you please revert a part of commits prior to Node.js version dropping, then publish `0.7.1` (this will fix builds), then apply "breaking changes" again and publush it as `1.0.0`? it seems like we still have to do something regardless the semver discussion.

**Comment by deepsweet** [comment]
but greenkeeper could bump it again for you guys. or for your dependencies. and if your dependency maintainer will not bump a major version of that dependency too then things will become bad again.

**Comment by usirin** [comment]
> btw why all your builds are broken if there was a minor version bump while a major number is still zero?

Problem of `npm` maybe, I haven't upgraded our `css-loader` dependency at all, and it was a fixed version (e.g doesn't include any wildchar `^`, `~`, `*`, or you name it), but still got this problem and i fixed it with forking `css-loader` to use a working version of `postcss-svgo`.

Basically what i did was removing `cssnano` dependency of `css-loader`.

Here is the result: https://github.com/usirin/css-loader/commit/f1e39932ff71cc316a328bbf786e3b22a5ce937c

**Comment by GreLI** [comment]
@deepsweet, yep, will do.

**Comment by GreLI** [comment]
Well, v0.7.1 with the fix has been just released.
