### ISSUE TITLE
How to: pass params to custom plugin

### ISSUE THREAD

**Issue by joscha** [svg/svgo#604]
If I have my own plugin, like:
```js
exports.type = 'perItem';
exports.active = true;
exports.description = 'calls back when it finds a color fill';

exports.params = {
  allowedValues: ['currentColor', 'none', 'inherit'],
  callback: console.log.bind(console), // eslint-disable-line no-console
};

exports.fn = function callbackOnDefinedFill(item, params) {
  var fill; // eslint-disable-line no-var
  if (item.hasAttr('fill')) {
    fill = item.attr('fill').value;
    if (fill && params.allowedValues.indexOf(fill) === -1) {
      params.callback(fill);
    }
  }
};
```

how can I pass a parameter (the callback) at runtime in a clean way?
Currently I am doing this:
```js
const callbackOnDefinedFill = require('./callbackOnDefinedFill');

module.exports = (fillCallback) => {
  // TODO find out how to pass this to an SVGO plugin at runtime
  callbackOnDefinedFill.params.callback = fillCallback;
  const svgo = new SVGO({
    plugins: [
      {
        callbackOnDefinedFill,
      },
      // ...
```

but that doesn't seem to be too sane - ideally I would pull in the plugin but not alter the class instance itself, but only the plugin that I actually pass to the SVGO object. I can't find how to do this in the docs - any hints?

**Comment by GreLI** [comment]
I guess this should work:
```js
const svgo = new SVGO({
    plugins: [
      {
        callbackOnDefinedFill: {
            allowedValues: ['currentColor', 'none', 'inherit'],
            callback: /* pass your callback here */
        },
      }
    ]
})

```

**Comment by joscha** [comment]
@GreLI this works only for built-in plugins - how do I load/add my custom one with a predefined name like `callbackOnDefinedFill`?

**Comment by GreLI** [comment]
There is no difference of defining custom and predefined plugin. I've skipped part before `const` in my example—it's same as yours.

**Comment by joscha** [comment]
mine is es6 short notation, which makes it a:
```
{
  callbackOnDefinedFill: callbackOnDefinedFill
}
```
meaning that the key is a string `'callbackOnDefinedFill'` and the value is the plugin object.

Yours is only a string key with a JSON object. The plugin is not part of the equation any more and hence can not be picked up unless I tell SVGO somehow that behind the name `'callbackOnDefinedFill'` there is the plugin `callbackOnDefinedFill` - and I am not sure how.

**Comment by GreLI** [comment]
That object contains params that are passed to the plugin.

**Comment by joscha** [comment]
Your sample has a defined key in the JSON object. How does svgo know where to get the according plugin code?

**Comment by GreLI** [comment]
It's being passed through `fn` option.

**Comment by joscha** [comment]
@GreLI Yes, sure, but your code:

```js
const svgo = new SVGO({
    plugins: [
      callbackOnDefinedFill: {
        allowedValues: ['currentColor', 'none', 'inherit'],
        callback: /* pass your callback here */
      }
    ]
})
```

does not pass the plugin in anywhere - apart from the `plugins` array not even taking a named key like that. If I assume you meant:

```js
const svgo = new SVGO({
    plugins: [
    {
      callbackOnDefinedFill: {
        allowedValues: ['currentColor', 'none', 'inherit'],
        callback: /* pass your callback here */
      }
    }
    ]
})
```

which would be allowed by SVGO, it still would just be a plain JSON object with a key named 'callbackOnDefinedFill`, but the plugin has not been loaded.

**Comment by joscha** [comment]
I suppose

```js
const callbackOnDefinedFill = require('./callbackOnDefinedFill');
const svgo = new SVGO({
    plugins: [
    {
      callbackOnDefinedFill: Object.assign({}, callbackOnDefinedFill, {
        callback: /* pass your callback here */
      })
    }
    ]
});
```

would work without altering the required plugin, I think I was just hoping for something like:
```js
const callbackOnDefinedFill = require('./callbackOnDefinedFill');
const svgo = new SVGO({
    plugins: [
    {
      callbackOnDefinedFill: { callback: /* pass your callback here */ }
    }
    ]
});
svgo.registerPlugin('callbackOnDefinedFill', callbackOnDefinedFill);
```

or similar.

**Comment by GreLI** [comment]
> Yes, sure, but your code:… does not pass the plugin in anywhere

Yep, forgot it.

I'm afraid there is no another way.

**Comment by joscha** [comment]
OK, I will just use `Object.assign` for now then, thank you @GreLI!
