### ISSUE TITLE
svgo deletes everything but a single svg element?

### ISSUE THREAD

**Issue by nachtfunke** [svg/svgo#605]
I am using the grunt-svgmin 4.0.0 plugin to compress my svg sprites, and for some reason, when I compress only certain files, it deletes everything but a single `<svg />`.

I have no Idea what is happening and how I can fix it. I have tried using different options or using no options whatsoever, and it all workes for some files, but for certain it doesn't. Could it have something to do with my svg files?

**Comment by GreLI** [comment]
Perhaps, you have some misconfiguration. E.g. someone thoughtlessly enables all plugins, most of which are destructive and used for their very own purpose.

Maybe you have not SVG pictures, but some sort of sprite/image library where all elements are hidden and used elsewhere. Such elements are removed by default by plugins like `removeUselessDefs`. In such a case it must be disabled (see `--disable` option or configuration settings).

**Comment by nachtfunke** [comment]
Thanks! In the Grunt Task I defined `removeUselessDefs: true`, and with svg-store I applied a class `hidden`to the svg-element, it seems as if in some cases that led to that problem.
