### ISSUE TITLE
Access `createContentItem` from within plugin

### ISSUE THREAD

**Issue by joscha** [svg/svgo#606]
I have a plugin that uses `.createContentItem` - I expected `this` to be the `SVGO` object instance, but it is not. As a workaround I create an additional SVGO instance in the plugin itself, but I think ideally the `fn` function would be bound to the SVGO instance it runs on. Any reason this is currently not done?

**Comment by GreLI** [comment]
Well, SVGO is for optimizing, thus creating items condraticts its purpose. It was exposed for external usage.

You can workaround by using `constructor` property:
```js
exports.fn = function(item) {
   var elem = new item.constructor({...});
}
```

Also there is `clone` method (used by SVGOMG).

**Comment by joscha** [comment]
ah, great, that works, thanks! I have an optimization step that makes an SVG accessible (it creates an `aria-labelledby` attribute and adds a `<title>` and `<description>` element. Not necessarily a performance optimization, but still an optimization in a sense.
