### ISSUE TITLE
Replace coa dependency with licensed equivalent

### ISSUE THREAD

**Issue by shyndman** [svg/svgo#609]
I was wondering if you were open to me rewriting the argument parsing logic using a library other than coa? It's unlicensed, which makes using it in our (Google's) tooling impossible. I have opened an issue on their repo (veged/coa#64), but it doesn't seem likely to be resolved quickly based on their level of activity.

Ideally I'd like to depend on a library that already exists in your transitive dependencies, like argparse.

What do you think?

**Comment by GreLI** [comment]
Well, [package.json](https://github.com/veged/coa/blob/master/package.json) there says it has MIT license.

**Comment by TrySound** [comment]
Replaced coa with commander
