### ISSUE TITLE
linear gradient in symbol (FF)

### ISSUE THREAD

**Issue by Muskos** [svg/svgo#615]
Did you see this bug on FF?
http://stackoverflow.com/questions/24806913/how-can-i-refer-to-an-internal-gradient-definition-inside-an-svg-sprite-symbol
Have you some options or issue for this?

**Comment by GreLI** [comment]
No, I didn't encountered it.

Is it actual? Firefox is gradually updating including graphical stuff like this.

**Comment by Muskos** [comment]
It's actual.
You can try:
http://codepen.io/Muskos/pen/dpjvvj bad
http://codepen.io/Muskos/pen/WGaGmN good

**Comment by Stenvdb** [comment]
Would love an option to fix this as well. This is fixable by moving the linear gradient outside the symbol element. See: https://stackoverflow.com/questions/12867704/svg-linear-gradient-does-not-work-in-firefox#answer-12871215

Any ideas?

**Comment by strarsis** [comment]
@Muskos, @Stenvdb: Could this be related?: https://github.com/svg/svgo/pull/733

**Comment by SethFalco** [comment]
It looks like this has been resolved in Firefox, so there's no need for us to address this now.
