### ISSUE TITLE
SVG parse error does not result in non zero exit code

### ISSUE THREAD

**Issue by engina** [svg/svgo#618]
When svgo encounters a SVG parse error, it does not exit with an error code. 

```
bash-4.3$ svgo test.svg --multipass -o - --datauri=unenc && echo ok
Error in parsing SVG: Non-whitespace before first tag.
Line: 0
Column: 1
Char: d
ok
```

**Comment by bdkjones** [comment]
+1. 

I just wasted a lot of time trying to figure out what was going on before I realized SVGO incorrectly returns `0` when the option parsing fails. Any chance this can be addressed soon?

**Comment by slakkenhuis** [comment]
I had a similar issue happening when the input file didn't exist.

```
svgo test.svg && echo $?
Error: no such file or directory 'test.svg'.
0
```

I'm not at all familiar with the current codebase or even node.js in general, but it seems an easy fix: https://stackoverflow.com/questions/5266152/how-to-exit-in-node-js — is there a reason why this shouldn't be done? :)

**Comment by GreLI** [comment]
There are exit codes were added in v1.0.0.
