### ISSUE TITLE
support for multiple inputs

### ISSUE THREAD

**Issue by mdesantis** [svg/svgo#62]
something like this: `svgo *.svg` ;-)

**Comment by shooftie** [comment]
Is recursive folders an option? Something glob-ish like `svgo -f img\svg\**\*.svg`?

**Comment by evenfrost** [comment]
Looking forward to this as well.

**Comment by GreLI** [comment]
It's a major change, so it would likely be in a brand new svgo version. Unfortunately, it will not be soon.

**Comment by eknkc** [comment]
BTW, for recursive stuff you can just do;

```sh
find . -name "*.svg" -type f -exec svgo '{}' \;
```

Would be great if it was built in though :)

**Comment by stefanjudis** [comment]
For copying over the svg files first we ended up an extended version using this in npm scripts.

```
"optimizeSvg": "cp -R assets/Yves/wib/img/svg/ src/Pyz/Yves/Application/Theme/wib/svg && find src/Pyz/Yves/Application/Theme/wib/svg -name '*.svg' -type f -exec svgo {}  \\;",
```

Just to share another solution. :)

**Comment by pdehaan** [comment]
Similarly, support for multiple input folders would be great:

```sh
✗ $(npm bin)/svgo --folder=addon/webextension/icons --folder=static/img -q
Unknown option: --folder
```

It works great with a single `--folder` argument, but really dislikes me trying to pass multiple folders.

**Comment by TrySound** [comment]
According to docs multiple files already supported.
https://github.com/svg/svgo#cli
