### ISSUE TITLE
Document plugins usage programmatically

### ISSUE THREAD

**Issue by niftylettuce** [svg/svgo#620]
I had to look in GitHub issues to see how others were able to pass plugins for programmatic usage. Maybe you could add another example to examples folder showing plugins usage.

```js
{
    plugins: [
        { mergePaths: false },
        {
            cleanupIDs: {
                prefix: filename + '-',
                remove: false,
                minify: true,
            }
        }
    ]
}
```

**Comment by GreLI** [comment]
Have you more concrete suggestions?

**Comment by emkayy** [comment]
I've got a similar question ...
**How do you enable plug-ins via command line?**
Everything I tried didn't work
I'm particularly interested in 
- **removeAttrs**
- removeTitle
- cleanupIDs
- collapseGroups
- removeStyleElement
- mergePaths

What I'm trying to do is cleaing up Illustrator asset SVGs as good as possible.
However, I couldn't find any examples online.
Maybe you could add some more examples for the plug-ins to the documentation?

**Comment by davidtheclark** [comment]
@GreLI: I'd like to help here by writing some documentation about how to use SVG via Node. Right now there's an example — I think we could have a Markdown document that explains the example and also explains how to pass plugins. Are you interested in this?

**Comment by GreLI** [comment]
Yep, any commitment is welcome.
