### ISSUE TITLE
CLI: SVGO silently fails if output directory does not exist

### ISSUE THREAD

**Issue by bdkjones** [svg/svgo#621]
### The Problem:
If you use the CLI to provide an output path for the optimized file, but the folder where that output file is to be created does not exist, SVGO will exit normally (code 0) but no output is created.

### Expected Result:
1. SVGO should create the folder where the output file is to be written if that folder does not exist.
2. If creation of that folder fails, SVGO should exit with a `non-zero` code; it should NOT indicate success.

### Actual Result:
SVGO fails to create an output file, then exits normally so the user can't tell anything went wrong.

**Comment by bdkjones** [comment]
This one is related to #618.

**Comment by TrySound** [comment]
Looks like this is fixed already
