### ISSUE TITLE
no such file or directory .svgo.yml

### ISSUE THREAD

**Issue by bonesoul** [svg/svgo#622]
Warning: Error: ENOENT: no such file or directory, open 'F:\Source\node_modules\svgo\.svgo.yml'

getting the error when installed with yarn package manager.

**Comment by GreLI** [comment]
`svgo/lib/svgo/config.js` [reeds](https://github.com/svg/svgo/blob/master/lib/svgo/config.js#L31) `${__dirname}/../../.svgo.yml`, so the target file should be `svgo/.svgo.yml`. It seems like something went wrong.

**Comment by chrisvfritz** [comment]
I noticed this with problem with Yarn after someone had run `yarn clean`. Deleting the `.yarnclean` file, deleting `node_modules`, then re-running `yarn` fixed it.

**Comment by pcwa-ahendricks** [comment]
Confirming @chrisvfritz fix.  Thanks.

**Comment by aap82** [comment]
@chrisvfritz confirming as well.  thank you kindly.

**Comment by teonik** [comment]
@chrisvfritz Confirmed! I faced this issue unexpectedly when trying to use css-loader with webpack....

**Comment by valotvince** [comment]
@chrisvfritz Thanks !

**Comment by brandondurham** [comment]
For whatever reason this fix doesn’t work for me.

**Comment by damassi** [comment]
Is there a way that we can make this library more compatible with Yarn so that this fix is not needed?

**Comment by zrrtcs** [comment]
There's an open issue regarding `*.yml` files in `.yarnclean` at yarnpkg/yarn#2276

**Comment by khzaw** [comment]
@chrisvfritz Worked for me, too. Thanks!

**Comment by matthieusb** [comment]
Thanks for the fix @chrisvfritz ! Just saved me a lot of trouble.

**Comment by pearman** [comment]
Thanks @chrisvfritz and @zrrtcs. Removing `*.yml` and ` .*.yml` (and any other entries that should not be deleted) from my `.yarnclean` file fixed my issues.

**Comment by bytedaring** [comment]
@chrisvfritz  Thanks！

**Comment by jochemjanssens** [comment]
@chrisvfritz  Thanks!

**Comment by tommueller** [comment]
@chrisvfritz Thanks!

**Comment by LaravelMonster** [comment]
@chrisvfritz Thanks!

**Comment by jasonmerry** [comment]
Thanks :)

**Comment by soulomoon** [comment]
@chrisvfritz  Thanks, some here

**Comment by lili21** [comment]
Thanks , saved my life.

**Comment by soulomoon** [comment]
Thank you!

**Comment by soulomoon** [comment]
@chrisvfritz  Thank you!

**Comment by LinusBorg** [comment]
Thanks @chrisvfritz ;)

**Comment by LinusBorg** [comment]
@chrisvfritz Thanks! ;)

**Comment by joneslloyd** [comment]
@chrisvfritz Cheers!

**Comment by Cecilxx** [comment]
@chrisvfritz thanks

**Comment by dcifuen** [comment]
Instead of deleting the whole `.yarclean` file or removing the lines `*.yml` and .`*.yml`, you can add a new line in your `.yarclean` to ignore this specific file: `!svgo/.svgo.yml`

**Comment by brandondurham** [comment]
@dcifuen Worked like a charm. Thanks!

**Comment by junen0511** [comment]
@chrisvfritz Thanks!

**Comment by disarticulate** [comment]
still doin whatever it's doin. Fix above worked.

**Comment by jeantimex** [comment]
@chrisvfritz Thanks a lot!

**Comment by chrisvfritz** [comment]
@pcwa-ahendricks @aap82 @teonik @valotvince @khzaw @matthieusb @pearman @bytedaring @jochemjanssens @tommueller @LaravelMonster @soulomoon @LinusBorg @joneslloyd @Cecilxx @brandondurham @junen0511 @disarticulate @jeantimex 

Don't thank me. Thank `git diff HEAD^..HEAD`.

![Batman Grapple Away](https://media.giphy.com/media/l0NwBAQfhHKohJwIM/giphy.gif)

But seriously, please just add a reaction. 😅  I've unsubscribed from this thread so many times, but every mention subscribes me again.

**Comment by crisu83** [comment]
@dcifuen your fix worked perfectly, thanks! 👍

**Comment by ownmaster** [comment]
Sometimes `svgo` can be referenced by other installed modules, in such case you need to change @dcifuen suggestion to `!.svgo.yml` - it will ignore `.svgo.yml` in all subfolders.

**Comment by iamazik** [comment]
I'm trying to use the SVGO with the https://github.com/nklayman/vue-cli-plugin-electron-builder and experiencing the `/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/../../.svgo.yml` issue. I can confirm that I don't have a `.yarnclean` file, nor `yarn` is cleaning anything as I verified it by manually checking the `/node_modules/svgo/svgo.yml` file and it's there. Anyone got any idea?
