### ISSUE TITLE
Option to pass the name of the svg being processed as a param into a plugin

### ISSUE THREAD

**Issue by harrisjose** [svg/svgo#623]
Is there any way to pass in the filename of the current svg into a plugin ?

The reason why i need this is because a lot of our svgs are exported from illustrator and have style tags with class names like `.st0 {} .st1 {}`. This causes a issues when we use a lot of svgs in a single page, as the styles get overriden.

An easy way to solve this would be to replace a class like `.st0` to `.svgName0`..which is why i need the file name. I'd also appreciate other ideas on solving this.

**Comment by bomberstudios** [comment]
+1. I recently added an auto prefixing feature for `defs` to https://github.com/BohemianCoding/svgo-compressor, based on the SVG filename, and was considering sending a pull request to make it "native" to SVGO.

**Comment by harrisjose** [comment]
Even though I mostly don't have this issue these days ( we just started using attributes or inline styles when exporting svgs ), I'd still love to see this being natively supported in svgo.

**Comment by strarsis** [comment]
PR: https://github.com/svg/svgo/pull/700

**Comment by bomberstudios** [comment]
👏👏👏👏

**Comment by harrisjose** [comment]
Closing this since prefixIds plugin by @strarsis takes care of what I was originally trying to achieve.
