### ISSUE TITLE
multipass and precision

### ISSUE THREAD

**Issue by kellerkichel** [svg/svgo#631]
Hi, I need some help with the multipass and precision command in grunt:
There are any way to use multipass and precision options?

I tryed:

```
svgmin: {
  options: {
    multipass: true,
    precision: 2,
    plugins: [{
        removeViewBox: true
    }]
  },
  dist: {
    files: [{
      expand: true,
      cwd: 'svg/',
      src: ['**/*.svg', '!**/*.min.svg'],
      dest: 'svg/',
      ext: '.min.svg',
      extDot: 'last'
    }]
  }
} 
```
without sucess... any tips?

Reference: https://github.com/sindresorhus/grunt-svgmin/issues/55

**Comment by romuloinnocencio** [comment]
Hum, I think this is really usefull. 
If i use _tinypng.com_, the svg gets smaller, but if i use svgmin at grunt, gets bigger than tinypng.

There's a way to set Multipass and Precision on it?
