### ISSUE TITLE
convertStyleToAttrs working?

### ISSUE THREAD

**Issue by nicothin** [svg/svgo#632]
I make `svgo --enable convertStyleToAttrs -f . -o ./opt` , 
but to see the output folder files tagged with `style` and` class` at `paths`
what am I doing wrong? ))

**Comment by elrumordelaluz** [comment]
@nicothin`convertStyleToAttrs` plugin converts the `style` attribute form each node, not the classes referenced from `<style>` ~  [Example](https://github.com/svg/svgo/blob/master/plugins/convertStyleToAttrs.js#L34-L51)

**Comment by strarsis** [comment]
Using the inlineStyles plugin before convertStyleToAttrs plugin would make this possible, see related PR https://github.com/svg/svgo/pull/592 .
