### ISSUE TITLE
white space / xml:space="preserve" (on <tspan/>)

### ISSUE THREAD

**Issue by strarsis** [svg/svgo#634]
A SVG exported from an Illustrator document (Illustrator CC 2017) 
uses the `xml:space="preserve"` attribute on a `tspan`-element.

svgo plugin `removeUnknownsAndDefaults` removes this attribute.
This results in a visual change, the extra white space that is intentionally there isn't shown anymore.
Chrome, Firefox and Internet Explorer 11 show no whitespaces anymore.

In [plugins/_collections.js](https://github.com/svg/svgo/blob/master/plugins/_collections.js#L108) which is used by the plugin 
it seems that `xml:space="preserve"` is assumed to be the default value.
```js
exports.attrsGroupsDefaults = {
    core: {'xml:space': 'preserve'},
````
Apparently it isn't, because setting it explicitly for 
the `tspan`-element as in the original SVG restores the original visual effect.

Edit: The svgo core (not a plugin) seems to remove whitespace that comes before the text. 
The text content of the elements in svgo AST already got the whitespace before the text stripped.

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
