### ISSUE TITLE
collapseGroups: Side effect with <image/> (Illustrator)

### ISSUE THREAD

**Issue by strarsis** [svg/svgo#635]
A SVG exported from an Illustrator document (Illustrator CC 2017) uses `<image/>` elements.
Each `<image/>` element is inside a `<g></g>` element with a `clip-path` property by css class.

When the collapseGroups plugins collapse the group, 
the `<image/>` element inside gets the `clip-path` of that group assigned.
This results in the `<image/>` elements not being visible anymore 
(its dimensions + position is still there according to Chrome Developer Tools, but it is not actually shown).

**Comment by TrySound** [comment]
Would be good to have a reproduction. Probably lost already.
