### ISSUE TITLE
How to pass param to plugin through CLI

### ISSUE THREAD

**Issue by jkelstrup** [svg/svgo#636]
I can't seem to figure out how to pass a param to a plugin when using the command line.

Specifically I want to tell `convertColors` to set `currentColor` to `true`.

The only way I found to do this is to create a config-file. But I'm hoping that there's a simpler inline-way of doing it?

**Comment by elrumordelaluz** [comment]
@jkelstrup looking at the `coa` code seems that there's a way to pass a _config_ String `JSON` formatted. Something like (tested and it works for me):
```
svgo -i test.svg -o test-out.svg --config '{ "plugins": [ { "convertColors": { "currentColor": true } }] }'
````

I think could be added into CLI helps.

**Comment by jkelstrup** [comment]
Thanks a lot @elrumordelaluz ! This might not be the prettiest of CLI-interactions, but it does exactly what I was looking for!

I'm gonna close this issue. If others could find it useful to see this improved, I think a new issue should be opened for that.

**Comment by elrumordelaluz** [comment]
yes @jkelstrup, absolutely agree about
> might not be the prettiest

and

> new issue should be opened for that.

**Comment by evilPaprika** [comment]
@elrumordelaluz 
Inlined json config is no longer suppored in svgo@2. What should i do?

**Comment by TrySound** [comment]
@evilPaprika Use svgo.config.js
