### ISSUE TITLE
Deleting empty text

### ISSUE THREAD

**Issue by erikdubois** [svg/svgo#639]
I have had great use of your script. This is my last challenge. Some of the icons have a lot of code like this. Can I do something with your script to get rid of this?
![problem](https://cloud.githubusercontent.com/assets/10594806/21561653/bea6abc8-ce6f-11e6-99d1-f72429674445.jpg)

<text x="729.64" y="231.36">
  
 </text>
 <text x="1310.91" y="151.36">
  
 </text>
 <text x="239.33" y="-29.9">
  
 </text>
 <text x="1337.38" y="-246.37">
  
 </text>
 <text x="1918.65" y="-326.38">
  
 </text>
 <text x="1529.53" y="-798.78">
  
 </text>
 <text x="2110.79" y="-878.78">
  
 </text>
 <text x="277.99" y="535.94">
  
 </text>

**Comment by elrumordelaluz** [comment]
@erikdubois [`removeEmptyText`](https://github.com/svg/svgo/blob/master/plugins/removeEmptyText.js) (_active_ by default) didn't work for you?

**Comment by erikdubois** [comment]
close for now - Upon next cleaning cycle I will get back to you if this is still relevant
