### ISSUE TITLE
GUI app submission for README

### ISSUE THREAD

**Issue by thomasjbradley** [svg/svgo#642]
I created a GUI app that uses SVGO internally after noticing SVGO-GUI isn’t maintained anymore.

[**Spritebot**](https://github.com/thomasjbradley/spritebot)

It does optimization as well as prettification of code. I was inspired by SVGO-GUI & SVGOMG.
The new features that it adds over those two apps are: batch processing, which SVGOMG doesn’t do & the ability to generate SVG sprite sheets for use with the SVG `<use>` tag.

I’d like to submit it for inclusion in the README—can I create a pull request?

**Comment by jadchaar** [comment]
Just used the tool--very nice! Well done!
