### ISSUE TITLE
root SVG ID gets removed

### ISSUE THREAD

**Issue by koraysels** [svg/svgo#643]
how can i prevent the SVG id attribute from being removed ?? (i am usin imagemin with svgo plugin..) 

the following options do not work: 

```
 svgoPlugins: [{removeViewBox: false, SVGid: true}],
```

```
 svgoPlugins: [{removeViewBox: false, cleanUpIDs : false}],
```

**Comment by GreLI** [comment]
With CLI `--disable=cleanupIDs` should work. What about imagemin I'd suggest to ask its authors. Try to spell it as `cleanupIDs` for starting point.

**Comment by koraysels** [comment]
I tried spelling it ``cleanupIDs`` to no avail.. looks like the options do not pass on to the actual imagemin process...

**Comment by meze** [comment]
Found in google, worked for me:  `svgoPlugins: [{removeViewBox: false}, {cleanUpIDs: false}]`

**Comment by XhmikosR** [comment]
@TrySound maybe this can be closed too?
