### ISSUE TITLE
Possible optimization: Remove elements that are out of viewport

### ISSUE THREAD

**Issue by kornelski** [svg/svgo#647]
I've found a *huge* file that is bloated by a base64-encoded embedded `<image>`, *which isn't even visible*, because its `x` position is outside of the viewport.

https://github.com/alecive/FlatWoken/blob/fd7d026fcbf455d42dc87aa9e43d44bfc4013cf4/FlatWoken/scalable/apps/bad-piggies.svg

**Comment by GreLI** [comment]
Well, that's nice, but in SVG 2 images will not be cropped by default :(. But yeah, it's possible.

**Comment by pwichmann** [comment]
So, is this still unsolved?

**Comment by GreLI** [comment]
You can make a PR if you wish. PRs are always welcome.

**Comment by pwichmann** [comment]
I would make a PR if I knew how to solve the problem.

**Comment by GreLI** [comment]
Well, basically you need to check if the element axis-aligned bounding box (AABB) is outside of [viewBox](https://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute). Computing AABB is somewhat trivial for basic shapes, and is done for paths inside `intersects` function [in plugins/path.js](https://github.com/svg/svgo/blob/4495a34f55560b2bc05cf837ba9dd01ca20cd479/plugins/_path.js#L601). The only caveat could be a stroke (specifically [stroke miter](https://www.w3.org/TR/SVG/painting.html#StrokeProperties)), but it can be handled later, in further iteration.

**Comment by DavidBruchmann** [comment]
It can't always be assumed that scenes outside the viewport are not used.
Depending on animations scenes are moved around and get visible when moved
inside the viewport.
Therefore a general solution is not possible and any cropping has to be
optional and/or define-able for each object.
Also a threshold could be defined for this purpose, assume you've a layer
for light-effects that is far away from the viewport but still has some
impact on the image in the viewport, depending on a threshold the hole
layer could be rendered or omitted.

**Comment by GreLI** [comment]
SVGO does many manipulations that can break such scenarios, but 99% images are simple and it's ok to make such operations. Usually there are stop conditions like having an ID (cleanupIDs removes unused) or animation.

**Comment by pwichmann** [comment]
Thanks @GreLI !
In my case, I only deal with static images (no animations).

**Comment by briantbutton** [comment]
FWIW, I am looking for an application that does this.  Only this.  I deal with map files and have not found an editor that will handle them.

The search continues . . .

**Comment by nikkwong** [comment]
I will pay someone to solve this issue. Looking at the code and it is perplexing; maybe someone knows SVGO API better than I; kindly contact me and name your price.

**Comment by nikkwong** [comment]
Ha, looks like it's my lucky day and this feature at some point was implemented into SVGO. 

https://github.com/svg/svgo/blob/master/plugins/removeOffCanvasPaths.js
