### ISSUE TITLE
Need a Node config example

### ISSUE THREAD

**Issue by wuz** [svg/svgo#653]
The [node module example](https://github.com/svg/svgo/blob/master/examples/test.js) has the line `/*{ custom config object }*/`, but there is no reference to what the config object should look like. Could we get an example of that?

**Comment by GreLI** [comment]
Well, it's same is [in docs](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config), just in a form of JSON.

**Comment by nikparo** [comment]
Here's part of one of mine. I use `full: true`, behaviour may be different with it off.

```javascript
var svgo_config = {
    full: true,
    multipass: false,
    js2svg: {
        pretty: true,
        indent: '  '
    },
    plugins: [
        { removeEditorsNSData: {
            additionalNamespaces: ['http://www.figma.com/figma/ns']}
        },
        { removeDesc: {removeAny: true} },
        // 'removeTitle', // This doesn't actually enable disabled by default plugins
        { removeTitle: {} }, // pass it an argument to enable
        'removeComments', // does enable default plugins. (using { full: true } )
        'removeMetadata',
    ]
};
var svgo = new SVGO(svgo_config);
```

**Comment by Tofandel** [comment]
Having to look into the issues to understand how to configure for nodejs... This needs to be added in the doc

**Comment by TrySound** [comment]
See changes in v2 https://github.com/svg/svgo/releases/tag/v2.0.0
Better docs are coming
