### ISSUE TITLE
Possible issue with font files

### ISSUE THREAD

**Issue by tmpfs** [svg/svgo#656]
I just noticed that `svgo` is taking a font file and removing *all* information from the file.

To verify this I just installed the latest version from npm and ran `svgo` on the file `PTSans-Regular.svg` which I cannot attach to this issue (no svg support).

I end up with a file that contains just six bytes (`<svg/>`).

```
svgo src/font/PTSans-Regular.svg test.min.svg && cat test.min.svg

Done in 496 ms!
392.396 KiB - 100% = 0.006 KiB

<svg/>
```

Any idea what I need to do to fix this issue?

**Comment by GreLI** [comment]
Probably, it's being cleaned by `removeUselessDefs`. It removes all non-used referenced, which is an entire content of a font file. You just need to disable it.

However, in general I don't recommend using SVG fonts—they're deprecated, have no actual use and pretty limited.

**Comment by tmpfs** [comment]
Thanks for the info :) Closing as not an issue.
