### ISSUE TITLE
Option to namespace all IDs

### ISSUE THREAD

**Issue by premasagar** [svg/svgo#66]
e.g. `--namespace="myapp-"`

This may be too niche, but anyway I'll share, in case there is a wider use fo this.

I'm experimenting with loading SVG files into a document (not via an SVG `<image>` element, but by importing them from iframes). When they are all in the same document, there can be id collisions. Unfortunately, SVG links for clip-paths, gradients, etc all require IDs to be used. It'd be handy to be able to supply a namespace prefix that will be applied to all elements with IDs, and any other elements, CSS or event references that link to them.

This is potentially fraught, since there may be a `<script>` inside the SVG that references the IDs. (Maybe I just talked myself out of it - anyway, it'd be useful for my purposes!).

**Comment by GreLI** [comment]
Actually, it was done in #202 with prefix option in ``cleanupIDs``.
