### ISSUE TITLE
Fill attribute being removed from SVG?

### ISSUE THREAD

**Issue by ProdigySim** [svg/svgo#661]
Hi, I have the following basic SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <polygon fill="#000000" fill-rule="evenodd" points="5 8 5 4 3 4 3 10 13 10 13 8" transform="rotate(-45 8 7)"/>
</svg>
```

If I run it through svgo with default options, it turns into this:

```
$ node_modules/.bin/svgo  --pretty -o - default-color.svg 
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6.586 9.828L3.757 7 2.343 8.414l4.243 4.243 7.07-7.071-1.413-1.414z"/>
</svg>
```

Note that the `<polygon>` is now a path, and the `fill=` attribute is gone. I would like to keep the `fill=` attribute.

I've tried adding `--disable removeUselessStrokeAndFill` but I still get the same result. Which plugin is responsible for the `fill=` attribute being removed?

**Comment by nikparo** [comment]
Try:

    svgo --pretty --disable=convertColors -o - default-color.svg

**Comment by GreLI** [comment]
`fill="#000000"` is the default color value (figures are being filled by black by default), so it's being removed as redundant. This is done by `removeUnknownsAndDefaults` plugin.
