### ISSUE TITLE
transformsWithOnePath not work because of the wrong order in `.svgo.yml` 

### ISSUE THREAD

**Issue by sunshiner** [svg/svgo#665]
I want to resize below svg with `gulp-svgmin`

```

<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <title>angle-down</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <polyline id="angle-down" points="1 7 11.9838122 17.9119161 23 7.03215231"></polyline>
    </g>
</svg>

```

`fulpfile.js` config

```

gulp.task('svg', function () {
    return gulp
        .src('./test/*.svg')
        .pipe(svgmin({
            plugins: [
                {
                    transformsWithOnePath: {
                        width: 1000,
                        height: 1000,
                    }
                }]
        }))
        .pipe(gulp.dest('res'));
});

```

It didn't work unless i delete the title and desc in the svg file. Then I read the source code and i find there has a condition in the `transformsWithOnePath` plugin code.

```

if (item.isElem('svg') &&
            item.content.length === 1 &&
            item.content[0].isElem('path')
        ) {

}

```

 I realized that the problem is because of the default plugin list which defined in the `.svgo.yml`, so i change the file to make sure the `transformsWithOnePath` after the `removeDesc` and `removeTitle` , and it did work.

so i suggest  adjust the `.svgo.yml` file to make sure `transformsWithOnePath` plugin can work well.

**Comment by GreLI** [comment]
`transformsWithOnePath` is working only when there is only one path, what is described by its name. Actually, it's an obsolete plugin out of scope of SVGO, so I'm going to remove it.
