### ISSUE TITLE
Stop attributes = "0" from being removed

### ISSUE THREAD

**Issue by petebarr** [svg/svgo#667]
Hi I can't see if there's a SVGO plugin which I can use to stop attributes which ="0" from being removed. e.g. x="0". An error is thrown in dev tools when trying to animate that attribute. Is there one/parameter to stop this from happening?

**Comment by GreLI** [comment]
Well, `x="0"` is a default value and thus removed by `removeUnknownsAndDefaults` plugin.

**Comment by petebarr** [comment]
Thanks for the heads up! :-)
