### ISSUE TITLE
convertPathData plugin declares unused params

### ISSUE THREAD

**Issue by alexjlockwood** [svg/svgo#668]
For example, it looks like the applyTransformsStroked param is never used, so it probably shouldn't be declared:

https://github.com/svg/svgo/blob/master/plugins/convertPathData.js#L11

(At least it is never used inside the file... not sure if it is possible for it to be used elsewhere as well.).

There are a couple other params that aren't used as well.

**Comment by GreLI** [comment]
Nope, it's being used [in _path.js](https://github.com/svg/svgo/blob/a55dc255c25f4d72a4d209e5b1c880e7a83141b2/plugins/_path.js#L191). This is not an issue.
