### ISSUE TITLE
Bad behavior on a cubic curve path

### ISSUE THREAD

**Issue by caub** [svg/svgo#669]
First svg is the original, second and third are generated from svgo current master branch, and last one from 
[browser](https://github.com/svg/svgo/pull/633) branch

Last 3 are similar, and have this weird unwanted black arc shape.

The test/browser.html script is in [browser](https://github.com/svg/svgo/pull/633) pull request branch

![image](https://cloud.githubusercontent.com/assets/3134574/23333960/69284f50-fb95-11e6-854e-6cb4155d3edd.png)

### The first path triggers the issue:
![image](https://cloud.githubusercontent.com/assets/3134574/23334110/794642d6-fb98-11e6-9c70-4536230159f9.png)

left original svg: 
```
<svg viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg"><g><path d="M4.635,4.039c0.015,-0.039 0.031,-0.078 0.047,-0.117c0.039,-0.092 0.081,-0.182 0.126,-0.271c0.125,-0.247 0.268,-0.485 0.428,-0.712c0.274,-0.39 0.596,-0.747 0.958,-1.058c0.302,-0.26 0.633,-0.487 0.984,-0.675c0.292,-0.157 0.598,-0.287 0.914,-0.391c0.3,-0.098 0.608,-0.172 0.919,-0.223c0.225,-0.037 0.451,-0.063 0.678,-0.076c0.092,-0.005 0.185,-0.008 0.277,-0.009c0.045,-0.001 0.045,-0.001 0.09,0c0.073,0 0.146,0.002 0.219,0.006c0.167,0.008 0.333,0.024 0.498,0.05c0.404,0.062 0.799,0.179 1.168,0.357c0.19,0.091 0.372,0.198 0.544,0.319c0.112,0.079 0.22,0.163 0.323,0.252c0.515,0.447 0.911,1.019 1.189,1.638c0.087,0.192 0.162,0.389 0.226,0.59c0.024,0.079 0.047,0.157 0.068,0.237c0.01,0.041 0.02,0.083 0.029,0.125c0.004,0.011 0.004,0.011 0.008,0.023c0.032,0.098 0.049,0.2 0.062,0.302c0.014,0.117 0.023,0.236 0.028,0.354c0.008,0.173 0.009,0.346 0.007,0.52c-0.003,0.186 -0.011,0.372 -0.022,0.558c-0.021,0.33 -0.053,0.66 -0.097,0.987c-0.044,0.331 -0.1,0.66 -0.17,0.987c-0.062,0.29 -0.135,0.577 -0.223,0.86c-0.013,0.042 -0.027,0.085 -0.041,0.127c0.064,0.163 0.115,0.33 0.15,0.502c0.043,0.209 0.063,0.423 0.055,0.636c-0.008,0.21 -0.042,0.419 -0.102,0.621c-0.024,0.083 -0.051,0.165 -0.086,0.244c-0.027,0.063 -0.372,0.453 -0.504,0.59c-0.002,0.033 -0.005,0.066 -0.008,0.098c-0.025,0.26 -0.069,0.518 -0.142,0.768c-0.106,0.361 -0.274,0.713 -0.541,0.982c-0.037,0.038 -0.076,0.073 -0.116,0.107c-0.059,0.048 -0.121,0.093 -0.186,0.133c-0.067,0.041 -0.138,0.077 -0.211,0.107c-0.053,0.022 -0.108,0.042 -0.163,0.058c-0.12,0.036 -0.244,0.058 -0.368,0.068c-0.052,0.046 -0.119,0.105 -0.126,0.11c-0.086,0.055 -0.173,0.107 -0.262,0.155c-0.077,0.042 -0.155,0.082 -0.234,0.118c-0.39,0.18 -0.818,0.298 -1.25,0.28c-0.061,-0.003 -0.121,-0.008 -0.181,-0.016c-0.085,-0.011 -0.169,-0.028 -0.252,-0.05c-0.118,-0.032 -0.233,-0.076 -0.342,-0.129c-0.177,-0.088 -0.34,-0.202 -0.487,-0.334c-0.068,-0.062 -0.133,-0.127 -0.195,-0.196c-0.126,-0.015 -0.317,-0.035 -0.352,-0.047c-0.158,-0.053 -0.309,-0.126 -0.448,-0.218c-0.1,-0.067 -0.194,-0.143 -0.28,-0.228c-0.063,-0.062 -0.121,-0.128 -0.175,-0.198c-0.036,-0.048 -0.071,-0.098 -0.103,-0.149c-0.239,-0.38 -0.349,-0.826 -0.386,-1.269c-0.005,-0.056 -0.008,-0.112 -0.011,-0.168c-0.305,0.124 -0.85,0.348 -0.973,0.373c-0.072,0.015 -0.145,0.028 -0.217,0.038c-0.096,0.015 -0.193,0.025 -0.29,0.033c-0.136,0.011 -0.273,0.017 -0.41,0.018c-0.13,0.001 -0.26,-0.003 -0.389,-0.009c-0.112,-0.006 -0.224,-0.014 -0.335,-0.031c-0.181,-0.027 -0.359,-0.073 -0.53,-0.14c-0.123,-0.048 -0.242,-0.106 -0.355,-0.175c-0.077,-0.048 -0.153,-0.1 -0.224,-0.156c-0.054,-0.042 -0.106,-0.086 -0.156,-0.133c-0.359,-0.333 -0.612,-0.766 -0.784,-1.221c-0.029,-0.078 -0.056,-0.157 -0.08,-0.236c-0.046,-0.146 -0.083,-0.294 -0.114,-0.443c-0.011,-0.057 -0.021,-0.114 -0.03,-0.171c-0.006,-0.036 -0.011,-0.073 -0.015,-0.11c-0.001,-0.008 -0.003,-0.016 -0.005,-0.024c-0.022,-0.118 -0.036,-0.237 -0.046,-0.357c-0.012,-0.142 -0.017,-0.285 -0.015,-0.427c0.005,-0.507 0.088,-1.015 0.255,-1.494c0.12,-0.345 0.284,-0.675 0.488,-0.978c0.22,-0.327 0.485,-0.622 0.783,-0.879c0.123,-0.106 0.251,-0.207 0.384,-0.299c0.239,-0.166 0.496,-0.307 0.769,-0.408c0.117,-0.043 0.236,-0.078 0.358,-0.106Z" style="fill:#433231;"/></g></svg>
```
(on the right, processed by SVGO)

### Shrinking more I get: 
![image](https://cloud.githubusercontent.com/assets/3134574/23334299/040e5fea-fb9c-11e6-9902-0f9991bac1f7.png)
on the left: 
`<svg viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg"><g><path d="M4.635,4.039c0.515,0.447 0.911,1.019 1.189,1.638c0.087,0.192 0.162,0.389 0.226,0.59c0.024,0.079 0.047,0.157 0.068,0.237c0.01,0.041 0.02,0.083 0.029,0.125c0.004,0.011 0.004,0.011 0.008,0.023c0.008,0.173 0.009,0.346 0.007,0.52c-0.021,0.33 -0.053,0.66 -0.097,0.987c-0.044,0.331 -0.1,0.66 -0.17,0.987c-0.062,0.29 -0.135,0.577 -0.223,0.86c-0.013,0.042 -0.027,0.085 -0.041,0.127c0.064,0.163 0.115,0.33 0.15,0.502c0.043,0.209 0.063,0.423 0.055,0.636c-0.008,0.21 -0.042,0.419 -0.102,0.621Z" style="fill:#433231;"/></g></svg>`

SVGO output on the right:
`<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M4.63 4.04a4.72 4.72 0 0 1 1.52 2.59 2.52 2.52 0 0 1-.41 5.26z" fill="#433231"></path></svg>`

**Comment by GreLI** [comment]
Cannot reproduce on v0.7.2.

**Comment by GreLI** [comment]
Ok, reproduced with `--precision 2`.

**Comment by shrpne** [comment]
Optimization curve to arc returns the wrong result. 
I got wrong large-arc-flag in the arc `a4.98 4.98 0 1 0-3.38 8.66`, it should be `a4.98 4.98 0 0 0-3.38 8.66`
Tested with svgo 1.0.5 with precision 2, however precision 3 returns fine result.


Initial path
d="M20,9 C26.085938,9 31,13.914062 31,20 C31,22.679688 30.046876,25.125 28.46875,27.03125 C27.609376,24.59375 25.75,22.632812 23.375,21.664062 C24.367188,20.75 25,19.445312 25,18 C25,15.25 22.75,13 20,13 C17.25,13 15,15.25 15,18 C15,19.445312 15.632812,20.75 16.625,21.664062 C14.25,22.632812 12.398438,24.59375 11.539062,27.03125 C9.953126,25.125 9,22.679688 9,20  C9,13.914062 13.914062,9 20,9 Z " 

Optimization output
d="M20 9a10.99 10.99 0 0 1 8.47 18.03 9.04 9.04 0 0 0-5.1-5.37A4.98 4.98 0 0 0 20 13a4.98 4.98 0 **1** 0-3.38 8.66 9.03 9.03 0 0 0-5.08 5.37A10.99 10.99 0 0 1 20 9z"

Expected output
d="M20 9a10.99 10.99 0 0 1 8.47 18.03 9.04 9.04 0 0 0-5.1-5.37A4.98 4.98 0 0 0 20 13a4.98 4.98 0 **0** 0-3.38 8.66 9.03 9.03 0 0 0-5.08 5.37A10.99 10.99 0 0 1 20 9z"

Maybe these issues are related to it:
#822, #842

**Comment by TrySound** [comment]
Cannot reproduce. Probably fixed.
