### ISSUE TITLE
Crop an image

### ISSUE THREAD

**Issue by premasagar** [svg/svgo#67]
This could be achieved in the original graphics program, but I find I often have a SVG files that have surplus whitespace around them and I want them trimmed, so that I have more flexibility in their display.

Currently, the way I manually achieve this is by pasting in the SVG to a new document in [SVG Edit](https://svg-edit.googlecode.com/svn/trunk/editor/svg-editor.html), then group all the elements, align them to top and bottom, then ungroup them again and copy the generated output. This avoids unnecessary translate transforms and recalculates all the correct coordinates.

No worries if this is beyond the scope of SVGO, but it would be handy.

**Comment by GreLI** [comment]
Not sure what you are asking for, but svgo writes output in compact form by default. This happens because the input file is translated to internal representation and then it serialized back in XML. There is ``--pretty`` command-line option, if one wants to pretty-printed output format.

**Comment by premasagar** [comment]
I didn't explain it so clearly. It wasn't about the XML output. The request was for an option to crop an image such that any visual whitespace outside of the shapes in the image is removed. The dimensions of the image will be smaller. This would be done by changing the path/point/x/y coordinates and not by applying an overall transform the elements.

It's not really a file optimization feature. It's an image manipulation feature.

**Comment by GreLI** [comment]
Not sure that svgo should do image editing (except simple cases with manipulations which done anyway). But probably in future it will crop path elements outside viewport.

**Comment by paperboyo** [comment]
> But probably in future it will crop path elements outside viewport.

Hi,

That, along with removing elements that are invisible/hidden behing opaque elements, would be heaven indeed!

Thanks for all your great work, @GreLI!

Regards
Mateusz

**Comment by scottyu2012** [comment]
Yes +1 for this feature!

**Comment by peterjaap** [comment]
+1

**Comment by onlymega** [comment]
+1

**Comment by AW-UC** [comment]
+1 would be great!

**Comment by SebT** [comment]
+1 this would be awesome for people using svgo to generate icon fonts

**Comment by davidgoli** [comment]
+1

**Comment by ricardobeat** [comment]
+1. This would be the desired behaviour to produce SVG sprites. If there is whitespace around the paths (viewport > actual path area) it's a bit cumbersome to declare image sizes since you have to account for this inner padding.

**Comment by nOji** [comment]
+1

**Comment by AGresvig** [comment]
+1

**Comment by berkaey** [comment]
+1

**Comment by niftylettuce** [comment]
+1

**Comment by GreLI** [comment]
> But probably in future it will crop path elements outside viewport.

Seems like it wouldn't. In SVG 2 “SVG root and foreignObject are no longer overflow:hidden in User Agent style sheet.” (as per [Changes](https://www.w3.org/TR/2016/CR-SVG2-20160915/changes.html#rendering) section).

Also, I don't think SVGO will crop an image since it's not an image editing tool. However, there is a `transformsWithOnePath` plugin that can do it. It works only for one path and only with relative coordinates (set `utilizeAbsolute: false` option to `convertPathData`).
