### ISSUE TITLE
removeXMLProcInst breaks file mime type detection

### ISSUE THREAD

**Issue by posgarou** [svg/svgo#675]
## Problem

Removing the xml processing instruction breaks mime type detection using `file`.  I've tested this with both:

- file-5.22 on Debian 8 (jessie)
- file-5.04 on OSX 10.11.6

A number of other programs depend on file's mime type detection to avoid mime type spoofing.  (In my case, I ran across it with the ruby gem Paperclip.)

## Steps to reproduce

Using svgo 0.7.2 and node v6.9.5:

```
$ curl https://upload.wikimedia.org/wikipedia/commons/5/57/Swimming.svg\?download -o swimming.svg
$ file -b --mime swimming.svg
image/svg+xml; charset=us-ascii

$ svgo swimming.svg -o swimming-opt.svg
$ file -b --mime swimming-opt.svg
text/html; charset=us-ascii

$ svgo swimming.svg -o swimming-opt-with-xml.svg --disable=removeXMLProcInst
$ file -b --mime swimming-opt-with-xml.svg
image/svg+xml; charset=us-ascii
```

## Suggested resolution

Make `removeXMLProcInst` a non-default option.

**Comment by GreLI** [comment]
See #306. MIME-detection is broken, use correct tools for your tasks.
