### ISSUE TITLE
Question: Using multiple plugins via command line tool

### ISSUE THREAD

**Issue by mrmohtas** [svg/svgo#677]
I'm trying to run a few plugins over a folder of svgs and none of them are working. Can you enable more than one plugin at a time via the CLI?

Example command:
`svgo -f INPUT -o OUTPUT -p 1 --enable='removeTitle, removeDesc, removeDimensions'`

**Comment by mrmohtas** [comment]
After some investigation I've found out the way to use multiple plugins

`svgo -f INPUT -o OUTPUT -p 1 --enable=removeTitle --enable=removeDesc --enable=removeDimensions`

Not the best way to do it and not documented...

**Comment by mrmohtas** [comment]
Failing silently isn't helpful either

*ECHO*

**Comment by GreLI** [comment]
Well, that's a standard command-line syntax. In bash you can use curly brackets like
```
svgo --enable={removeTitle,removeDesc,removeDimensions}
```
Can't say about other terminals.

**Comment by jmwebservices** [comment]
This came up in Google while searching how to set multiple plugins via a single option. I am on Windows so curly brackets expansion didn't work for me. I have [PR](https://github.com/svg/svgo/pull/1019) for this feature.

**Comment by Pomax** [comment]
Probably worth reopening as a documentation uddate issue, to make sure the docs mention to use multiple `--enable=...` instructions if you need cross-platform funcationality (which, let's be fair: in the Node ecosystem, everyone needs).
