### ISSUE TITLE
minifyStyles doesn‘t remove unused style

### ISSUE THREAD

**Issue by ianchadwick** [svg/svgo#679]
I'm trying to minify an svg I think is from Illustrator which contains lots of unused style classes but minifyStyles doesn't actually remove them... is this expected?

```
<style type="text/css">
	.st0{fill:#64798A;}
	.st1{fill:#FCD462;}
...
</style>
```

After it's just removed the spaces/new lines.

Thanks!

**Comment by GreLI** [comment]
Yep, SVGO can't parse styles for now. That would bring a significant code complication. There is an effort in #592, though I doubt in its performance.

**Comment by lahmatiy** [comment]
@GreLI but it does, not directly but via CSSO.
@ianchadwick By default minifyStyles should remove unused styles based on usage data. There are few exceptions:
- SVG contains `<script>` element
- some elements have an `on*` attribute (event handler)
If something from the list is found in SVG, minifyStyles decides that style removal is unsafe. You can force removal by setting `usage.force` option to `true` (see [example](https://raw.githubusercontent.com/svg/svgo/master/test/plugins/minifyStyles.09.svg)).
I admit a problem with minifyStyles. Let me know if you found cause of the problem.

**Comment by lahmatiy** [comment]
I understood the problem. Unused styles removal feature were introduced in PR #640. But it's not released yet.
@GreLI When are you planning publish a new version?

**Comment by ianchadwick** [comment]
@lahmatiy thanks for the extra info.

Neithier of those exceptions are true for the SVG i'm attempting to minify. 

Here's what I've tried:

`svgo 1.svg 1.min.svg --pretty --enable=minifyStyles --config '{"plugins":[{"minifyStyles":{"usage":{"force":true}}}]}'`

Here are the before and after shots.

Before: [Fat file](http://pastebin.com/raw/6Znrpmp0)
After: [Minified(ish)](http://pastebin.com/raw/F1p6q2we)

The SVG only needs 9/10 of the first classes the rest are not used.

@GreLI If by performance you mean speed of conversion this is a complete non issue for me. I'd much rather spend 1 minute making a file 90% smaller than extra ms & bandwidth on every single request :)

Thanks!

**Comment by lahmatiy** [comment]
@ianchadwick Do you use version from npm or github master? Version on npm hasn't unused style removal feature. Wait for upcoming release or try version from master.

> If by performance you mean speed of conversion this is a complete non issue for me.

I guess @GreLI misunderstood you, because mentioned issued #592 doesn't relate to your problem.

**Comment by ianchadwick** [comment]
@lahmatiy npm... just tried from master and it's working as expected. Thank you!!!
