### ISSUE TITLE
Feature Req: Add Option to export groups as separate indipendent svg files

### ISSUE THREAD

**Issue by Emasoft** [svg/svgo#681]
Feature Req: Add Option to export groups as separate indipendent svg files

Rationale: Almost all artists draw their svg icons in a single svg document, so they can make global modifications or just compare on the same layout the various icon styles. 
It is a bother and a waste of time to have to save each icon separatedly after every update to such master svg file.
A very useful feature of svgo would then be the option to load an svg and export all groups (only those that are children of the root node, of course) as separate svg files.

The requisites are:

1 - The name of each exported svg file should be the group id.
2 - The coordinates should be transformed to be relative to the group bounding box (similar to the inkscape option 'resize the page to fit selected elements')
3 - The viewport and the viewBox of each svg should also be generated to fit the group bounding box
4 - Each svg should carry the definitions of the original file that it needs and discards the others
5 - All the resulting svg files should be valid svg v1.1 files, and when viewed in browsers they should have the exact size of the original group bounding box, only translated to 0,0

**Comment by GreLI** [comment]
Unfortunately, it's an image editing request, not optimizing one, so it's out of scope.
