### ISSUE TITLE
Prevent SVG aria attributes from being removed

### ISSUE THREAD

**Issue by MrFirthy** [svg/svgo#684]
Is it possible with any combination of settings to prevent `aria-*` attributes from being remove from the `<svg>` tag when optimising? 

I have tried all options that seem relevant to this but have had no luck so far:
```
.pipe($.svgo({
    addAttributesToSVGElement: true,
    removeUnknownsAndDefaults: false,
    cleanupAttrs: false,
    removeEmptyAttrs: false
}))
```

This is quite important as the `aria-labelledby` and `aria-describedby` attributes allow screen readers to interpret the content of inline SVG's.

**Comment by GreLI** [comment]
I believe they're removed by `removeUnknownsAndDefaults` as unknowns. But your config is set incorrect, it should be an array of plugins.

**Comment by davidtheclark** [comment]
@GreLI I see [this line](https://github.com/svg/svgo/blob/a2a0a1ef3fc51cc5dae25ae85125ecf5fb90b897/plugins/removeUnknownsAndDefaults.js#L108) where data-* attributes are ignored. I could add a similar condition for aria-* attributes. *Or* I could add an aria attribute group to https://github.com/svg/svgo/blob/a2a0a1ef3fc51cc5dae25ae85125ecf5fb90b897/plugins/_collections.js#L21 with the list here: https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def. Which do you think would be the better option?

**Comment by GreLI** [comment]
I think aria-* attributes is ok. But unlike data-*, it should be an option. Editors may insert this attributes as well as other garbage attributes (e.g. with label like “Shape 1”), so it should be kept only for those who really need it and set certain preference.

**Comment by davidtheclark** [comment]
> I think aria-* attributes is ok. But unlike data-*, it should be an option.

@GreLI: This plan sounds good. I can try to get a PR up soon.
