### ISSUE TITLE
run svgo in lint-staged

### ISSUE THREAD

**Issue by BrRenat** [svg/svgo#689]
I have error when start `"*.svg": "imgmin"` in lint-staged. Only if more than one svg file has been uncommitted.

Running tasks for *.svg
→ Unknown argument: ~\mySvgFolder\attention.svg

**Comment by GreLI** [comment]
SVGO has syntax
```
svgo <input-file> <outputfile>
```

**Comment by BrRenat** [comment]
`
"scripts": {
    "imgmin": "svgo -f mySvgFolder",
}
`
Ok, if my syntax wrong. How i should add svgo task to lint-staged?

**Comment by BrRenat** [comment]
I wrote that the error appears only if more than one svg file has been uncommitted. With one svg file everything works.
