### ISSUE TITLE
How do parse all *.svg files in a directory recursively?

### ISSUE THREAD

**Issue by lipis** [svg/svgo#690]
If I have the following structure:

```
/path/to/svg/
├── foo
│   ├── far
│   │   └── away.svg
│   ├── bar.svg
│   └── cafe.svg
└── car.svg
```

- `svgo -f /path/to/svg/` fixes only the `car.svg`
- `svgo -f /path/to/svg/*` fixes all the files in `foo` directory but not `car.svg` and not the `far` folder

So the question is.. what's the best way to scan all the `*.svg` recursively in a folder?

**Comment by waldyrious** [comment]
In the spirit of Unix philosophy, I'd be inclined to propose using `find` for locating the files, and `svgo` for processing them. Something like `find /path/to/svg/ -name *.svg -exec svgo {} \;`.

That said, given that the `-f`option already exists, it could be argued that it makes sense to extend it to process folders recursively.

**Comment by lipis** [comment]
Yes that will work only in Unix systems..and if I want to use it inside the package.json as a script it won't fly on every platform.. the `-f` should be fixes to support all.

Or maybe even something like that

- `svgo /path/to/svg/**/*.svg` would parse all the files recursively inside that match the `*.svg` extension.
- `svgo /path/to/svg/*.svg` only in the root of that folder without going deeper and only the `*.svg` files.

**Comment by DavidBruchmann** [comment]
No clue how the possibilities are with installed git-bash in windows, there are some linux-commands like grep and find available too. Should be possible to combine that but add another dependency ...
I know this is probably not the way to go but just thought about it.

**Comment by lipis** [comment]
We all know the workarounds guys... let's just fix it! The question was mostly on how to do it without workarounds and if not possible.. it's a feature request.

**Comment by caub** [comment]
how is this related to svgo?

**Comment by lipis** [comment]
It is realted to svgo because svgo supports `-f`

**Comment by caub** [comment]
so if you're motivated, extend this https://github.com/svg/svgo/blob/master/lib/svgo/coa.js#L49 with a -rf option (r for recursive) and paste the code above to get all .svg's

**Comment by lipis** [comment]
Thanks a lot @caub for the advice man.. I didn't know that I was aloud to make my own PRs..

**Comment by caub** [comment]
you're very aloud to

**Comment by lipis** [comment]
Thanks again man..! I'll keep that in mind..

**Comment by mnpenner** [comment]
I would like to see this built-in to SVGO too, but in the mean-time, here's a workaround that runs SVGO in parallel:

```sh
find resources/icons -type f -name '*.svg' -print0 | xargs -0 -n 1 -P 6 $(NM)/svgo
```

**Comment by mnpenner** [comment]
Thanks for adding this feature. Could you tag this release please? @justrhysism

**Comment by mnpenner** [comment]
Actually the output is a little weird. It says

> No SVG files have been found.

...even though it did find all my icons. I guess it didn't find any in the root dir.

```
node_modules/.bin/svgo -r resources/icons
Processing directory 'resources/icons':

Processing directory '/mnt/c/Users/Mark/PhpstormProjects/myproject/resources/icons/fa':

Processing directory '/mnt/c/Users/Mark/PhpstormProjects/myproject/resources/icons/ion':

Processing directory '/mnt/c/Users/Mark/PhpstormProjects/myproject/resources/icons/misc':

No SVG files have been found.
asterisk.svg:
Done in 14 ms!
0.497 KiB - 0% = 0.497 KiB

android-calendar.svg:
Done in 6 ms!
0.316 KiB - 0% = 0.316 KiB

account.svg:
Done in 9 ms!
0.948 KiB - 0% = 0.948 KiB

...
```

**Comment by averyvery** [comment]
Excited about this change, does it seem like it'll be in a release soon?

**Comment by ranuss** [comment]
When will this be released?

**Comment by iafiawik** [comment]
Agree. This would be a much appreciated feature. 🙂

**Comment by keithws** [comment]
Is this dead? Will this ever be released?

**Comment by michtoen** [comment]
I did not find it written elsewhere, but today it is simple, also on windows

svgo -o /PATH/TO/OUTPUT/DIR/ -f /PATH/TO/INTPUT/DIR/ -i *.svg

will also create the output if it did not exits.

**Comment by Pomax** [comment]
This is now part of the "with files" documentation in the https://github.com/svg/svgo#usage section.

**Comment by bashjs** [comment]
-f and -r both still don't work with paths like `packages/**/static/next/icons`
Possible workaround: `svgo $(echo packages/**/static/next/icons) -r`

**Comment by Pomax** [comment]
Those aren't paths, those are [globs](https://en.wikipedia.org/wiki/Glob_(programming)) - many tools don't support globs.
