### ISSUE TITLE
run svgo in lint-staged

### ISSUE THREAD

**Issue by BrRenat** [svg/svgo#691]
I have error when start `"*.svg": "imgmin"` in lint-staged. Only if more than one svg file has been uncommitted.
`"scripts": { "imgmin": "svgo -f mySvgFolder", }`

How i should add svgo task to lint-staged?
Error appears only if more than one svg file has been uncommitted. With one svg file everything works.

Running tasks for *.svg
→ Unknown argument: ~\mySvgFolder\attention.svg

**Comment by ai** [comment]
@GreLI this question is important for my project too

**Comment by GreLI** [comment]
There is no lint option as for now.

**Comment by ai** [comment]
@GreLI nope, we didn’t ask about lint option. We said that current CLI API doesn’t allow you to use `svgo` with `lint-staged`.

**Comment by ai** [comment]
`lint-staged` is a tool to run any CLI on changed and staged files. The best practice is to use it with ESLint and Stylelint. But linters is not only one way.

For example, you can use `lint-staged` to sort your CSS properties on commit. Or to unify JS syntax with prettier.

Or, to minify new or changed SVG with `svgo`.

So we use `lint-staged` not for linting. But to minify SVG in pre-commit hook.

**Comment by ai** [comment]
`lint-staged` is very popular right now. For example, create-react-app uses it.

**Comment by ai** [comment]
CLI problem:

`lint-staged` runs `command file1 file2`. So of I will change `a.svg` it will execute `svgo a.svg`. But by some reason svgo will not work as ESLint, Stylelint, postcss-sorting or prettier. By some reason, `svgo` will not see `a.svg` and falls with:

```
Running tasks for *.svg
→ Unknown argument: a.svg
```

**Comment by ai** [comment]
@GreLI is it a error? And how I can integrate SVGO with lint-staged in this case?

**Comment by BrRenat** [comment]
I note that if one file is changed, everything is ok. I think we have error because if more than one file they detected like svgo options and we have Unknown argument.

**Comment by GreLI** [comment]
Ah, I get it. Currently SVGO has syntax
```
svgo <input> <output>
```
Thus meaning that first file is treated as input, second as output and all other as options. But I wanna change it and now is a good moment for this.

**Comment by dmitrika** [comment]
Was also surprized, that I cannot combine svgo and lint-staged.

@GreLI Great, that you wanna change it, maybe you can give a hint, where to start, that I could help.

**Comment by superfunkminister** [comment]
+1

**Comment by ApacheEx** [comment]
yay, it works well: 🥇 
```json
"public/**/*.svg": [
  "svgo",
  "git add"
],
```
