### ISSUE TITLE
CLI: Choose if pretty indentation uses tabs or spaces

### ISSUE THREAD

**Issue by JohaWeber** [svg/svgo#699]
It drives me pretty crazy that I do not have an option for that via CLI.
I know that there is a never ending discussion about it. But until the point where no editor gives the option to choose from those two options anymore (which perhaps will never be the case), it would be nice to have this option to pass it to the CLI-tool.

**Comment by GreLI** [comment]
Actually, you can a string value to `indent` (`indent: '\t'`), but through config only. E.g.
```yml
js2svg:
  pretty: true
  indent: "\t"
```
or 
```bash
$ svgo --pretty --config='{ "js2svg": { "indent": "\t" } }'
```

**Comment by JohaWeber** [comment]
Thx, for the info - tried this on windows with powershell:

`svgo -f  \\network\path\to\icon\folder --pretty --config='{ "js2svg": { "indent": "\t" } }'`

and get the error:

```
Error: Couldn't parse config JSON.
SyntaxError: Unexpected token j in JSON at position 2
```

Although without the `--config` flag an with a `--indent=2` (e.g.) it works.

**Comment by Crissov** [comment]
If file size optimization is the primary goal of this project, either `indent:1` or `indent:'\t'` should be the default.

**Comment by TrySound** [comment]
Indent can be set via CLI
