### ISSUE TITLE
Shape disappearing from SVG file after being optimized

### ISSUE THREAD

**Issue by gustavnikolaj** [svg/svgo#701]
The following SVG file:

```svg
<svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    width="69.964px"
    height="11.535px"
    viewBox="0 0 69.964 11.535"
    enable-background="new 0 0 69.964 11.535"
    xml:space="preserve"
>
    <g>
        <path
            fill="#ffffff"
            d="M32.988,8.093c-0.587,0-1.062,0.478-1.062,1.06c0,0.586,0.475,1.059,1.062,1.059c0.584,0,1.058-0.473,1.058-1.059C34.045,8.57,33.572,8.093,32.988,8.093z"
        />
    </g>
</svg>
```

Results in the following SVG when being run through `svgo -i file.svg`:

![screenshot from 2017-04-07 16-02-46](https://cloud.githubusercontent.com/assets/1371503/24803476/a9330a82-1bab-11e7-945a-61309a4362b5.png)

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="69.964" height="11.535" viewBox="0 0 69.964 11.535"><path fill="#fff" d="M32.988 8.093a1.06 1.06 0 1 0 0 0z"/></svg>
```

If I run it through `svgo -p 4 -i file.svg` instead, I get similar to original output (with no loss of the shape):

![dot](https://cloud.githubusercontent.com/assets/1371503/24803477/a9355698-1bab-11e7-97aa-78f65144c72a.png)

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="69.964" height="11.535" viewBox="0 0 69.964 11.535"><path fill="#fff" d="M32.988 8.093c-.587 0-1.062.478-1.062 1.06 0 .586.475 1.059 1.062 1.059.584 0 1.058-.473 1.058-1.059-.001-.583-.474-1.06-1.058-1.06z"/></svg>
```

Before version 0.6.0 (latest being 0.5.6) svgo would not mangle the shape without explicitly setting the precision argument to something higher than the default. I can tell that some [changes have happened](https://github.com/svg/svgo/compare/v0.5.6...v0.6.0) in between `0.5.6` and `0.6.0` with relation to the precision argument. I admittedly don't understand the full consequence by the changes, but it worries me that the default options on the CLI tool is not lossless but will actually do destructive optimizations to the image.

---

The original SVG is similar to the second image example, but there's no background color on it, so I added the green one to make the changes more obvious.

**Comment by GreLI** [comment]
Hmm, there should be two arcs making a circle. Something went wrong there.

**Comment by gustavnikolaj** [comment]
@GreLI Sorry, I didn't quite understand if you refer to something going wrong in svgo or in my original svg :smile:

**Comment by gustavnikolaj** [comment]
@GreLI ping :-) Do you need anything for me, or is this a bug in svgo which you have all the information necessary to dig into?

**Comment by GreLI** [comment]
Sorry, haven't dig into it yet, rather busy lately.

**Comment by gustavnikolaj** [comment]
I was about to complain about the rather abrupt closing of this issue...

But I went on to verify if this bug is still there, and I am happy to report that the latest version (2.2.0) will not mangle the circle.

**Comment by TrySound** [comment]
Oops, sorry. Forgot to write that I could not reproduce this issue 😅
