### ISSUE TITLE
svgo breaks path data

### ISSUE THREAD

**Issue by herrernst** [svg/svgo#706]
Input:
`<path d="M44.618,51.066c5.232,0,9.475-4.242,9.475-9.477c0-3.279-1.666-6.168-4.199-7.869
	c-0.15-5.101-4.324-9.191-9.461-9.191c-3.547,0-6.633,1.951-8.258,4.836c-0.699-0.389-1.492-0.629-2.35-0.629
	c-2.644,0-4.785,2.107-4.863,4.732c-2.76,1.658-4.611,4.67-4.611,8.121c0,5.234,4.242,9.477,9.475,9.477H44.618z"/>
`
![screen shot 2017-04-11 at 18 58 40](https://cloud.githubusercontent.com/assets/20795/24920880/27add708-1ee9-11e7-90c2-1ac2176af195.png)

Output:
`<path d="M44.618 51.066c5.232 0 9.475-4.242 9.475-9.477a9.462 9.462 0 0 0-4.199-7.869 9.468 9.468 0 1 0-17.719-4.355 4.809 4.809 0 0 0-2.35-.629 4.87 4.87 0 0 0-4.863 4.732c-2.76 1.658-4.611 4.67-4.611 8.121 0 5.234 4.242 9.477 9.475 9.477h14.792z"/>`
![screen shot 2017-04-11 at 18 59 29](https://cloud.githubusercontent.com/assets/20795/24920904/4387fada-1ee9-11e7-8bda-601b36ba0e21.png)
(notice the higher top part)

(using 0.7.2)

**Comment by TrySound** [comment]
Cannot reproduce in latest version
