### ISSUE TITLE
NPM plugins are different from Github plugins

### ISSUE THREAD

**Issue by madysondesigns** [svg/svgo#710]
I'm trying to use `cleanupIDs` with the `preserve` param. I could not get it to work until I finally looked at a diff of the two plugin files and saw that the NPM provided version does not support `preserve`, even though both versions are listed `0.7.2`. 

If you look at [the diff](https://www.diffchecker.com/EqBSLulD) (NPM installed plugin on the left, Github plugin on the right), there is quite a big difference. 

Is there a planned time to release the newer plugin to the official NPM repository?

**Comment by elrumordelaluz** [comment]
I think the lib published in `npm` is the same as [last release](https://github.com/svg/svgo/releases/tag/v0.7.2) branch, not `master`.

Try comparing this [file](https://github.com/svg/svgo/blob/v0.7.2/plugins/cleanupIDs.js).

**Comment by swhinnem** [comment]
Yes, that's what I assume is happening. 

My question was is there a release schedule or a way to request a new release?

**Comment by elrumordelaluz** [comment]
don't know about the releases timing, but why not to use the `master`branch?

**Comment by swhinnem** [comment]
I can and am currently, but I would rather lock to an official version to keep any unanticipated future changes from breaking my current workflow.
