### ISSUE TITLE
Line converted to path incorrectly.

### ISSUE THREAD

**Issue by hellopovi** [svg/svgo#711]
Code:
``` svg
          <svg width="12" height="12">
            <line stroke-dasharray="4, 3" x1="0" y1="4" x2="12" y2="4"></line>
          </svg>
```
Output:
``` svg
<svg width="12" height="12">
<path d="M0 4h12"></path
</svg>
```
Result:
<img width="212" alt="screen shot 2017-05-01 at 15 12 00" src="https://cloud.githubusercontent.com/assets/3407144/25580349/97ebb796-2e80-11e7-8d43-3a4d48cf9263.png">

Expected result:
<img width="215" alt="screen shot 2017-05-01 at 15 13 32" src="https://cloud.githubusercontent.com/assets/3407144/25580374/c37859be-2e80-11e7-9da7-8e2c1c90fbfa.png">

**Comment by GreLI** [comment]
That cannot be output from SVGO since SVGO never creates classes.

**Comment by hellopovi** [comment]
I forgot to remove the classes from the output. Fixing that.

**Comment by GreLI** [comment]
That's `removeUselessStrokeAndFill` plugin removing `stroke-dasharray` since there is no `stroke` and thus attribute is useless. Disable it if you want to preserve the attribute..
