### ISSUE TITLE
Delete items outside the viewbox

### ISSUE THREAD

**Issue by logolab** [svg/svgo#713]
This looks like an amazing library!

The SVGs I am working with are 'contaminated' by elements hidden by being **outside** the viewbox.
I am, therefore, looking for a solution to delete all SVG elements outside the viewbox. Is there such a solution? Would svgo help with this problem?

Many thanks!

**Comment by paperboyo** [comment]
Duplicate/related: https://github.com/svg/svgo/issues/647, https://github.com/svg/svgo/issues/67

**Comment by GreLI** [comment]
Closing as duplicate.
