### ISSUE TITLE
results end up being different

### ISSUE THREAD

**Issue by bcardarella** [svg/svgo#715]
We've noticed that our SVGs change shape a bit after using svgo. Are there suggestions on how to mitigate this?

**Comment by bcardarella** [comment]
> There could be also some bugs, despite I'm trying to eliminate them. If you find some, please submit an issue.

Happy to! How should we submit these bugs? Are you interested in getting the actual SVGs?

**Comment by GreLI** [comment]
Just submit an issue with bug description. Like what did you do, what is your SVG and what is broken. It would be fine if you can narrow down the issue to certain part of the image and probably certain plugin (it can be a combination of plugins).
