### ISSUE TITLE
Npm module without promise

### ISSUE THREAD

**Issue by Minoga** [svg/svgo#716]
There is promise in example https://github.com/svg/svgo/blob/master/examples/test.js . But when i load npm module svgo i get 0.7.2 version with callback.

**Comment by GreLI** [comment]
That change hasn't get to release yet.

**Comment by greybax** [comment]
So how is it works in current version?

**Comment by GreLI** [comment]
As it stated in a version before: https://github.com/svg/svgo/commit/8429ffb53ca298ecb2bda96dd58327d115e91b40

**Comment by lifeiscontent** [comment]
@GreLI when will the new version release??

**Comment by GreLI** [comment]
When it'd be done. There are some things to manage yet, but hopefully it'll help in future.

**Comment by lifeiscontent** [comment]
@GreLI is there a milestone or timeline?

**Comment by caub** [comment]
it's quite confusing, the npm module is version 0.7.2 and .optimize is callback-based

master branch here is 0.7.2 and has the promise api

so we should probably have a 0.8.0 or any non-minor version change

**Comment by g0t4** [comment]
Also, the callback API is non-standard, both errors and results are passed back in the first argument:
```if (this.config.error) return callback(this.config);```
and later on 
```callback(svgjs);```

**Comment by GreLI** [comment]
SVGO v1.0.0 with a promise has been released.
