### ISSUE TITLE
new plugin addTitle which defaults to the file name

### ISSUE THREAD

**Issue by Crissov** [svg/svgo#718]
The contents of the `title` element is shown in tab or window titles in browsers, just like for HTML documents. That's usually more useful than putting their full URL there. I'd therefore like to suggest a new plugin that lets the user add a title to the SVG file, which would default to one automatically generated from the file name.

**Comment by GreLI** [comment]
It has nothing to do with optimization. But it's not hard to do a plugin for yourself, thanks to plugin system.

**Comment by Crissov** [comment]
Optimization is about readability, so I think it's in scope.

Anyway, why are you closing the issue &ndash; if I wrote a PR would you decline it?

**Comment by GreLI** [comment]
No, the primary task here is reducing file size. I'm sorry if the “O” in SVGO let you think other way.

Yeah, I will not accept a PR to prevent bloating.

**Comment by TrySound** [comment]
Better create empty children array in element definition

**Comment by ljani** [comment]
@TrySound: Thanks for the hint. However, I thought [`JSAPI` took care of that](https://github.com/svg/svgo/blob/1b88baa123d9878c5b7de5bdc5350e1d7160cf35/lib/svgo/jsAPI.js#L69) and thus I'm relying on it?

**Comment by TrySound** [comment]
Its gonna be removed in v3. Better write nodes explicitly

**Comment by songkeys** [comment]
@ljani Thank you for the script.

Also, if you want this in v3:

```js
const svgoAddTitle = {
	name: "addTitle",
	type: "visitor",
	active: true,
	fn: (ast, params, { path: svgPath } = {}) => {
		return {
			element: {
				enter: (node, parentNode) => {
					const isRoot = node.name === "svg" && parentNode.type === "root";
					if (isRoot && svgPath) {
						const hasTitle = node.children.some(
							(child) => child.type === "element" && child.name === "title",
						);
						if (!hasTitle) {
							const filename = path.parse(svgPath).name;
							const title = {
								type: "element",
								name: "title",
								attributes: {},
								children: [],
							};
							Object.defineProperty(title, "parentNode", {
								writable: true,
								value: node,
							});
							const text = {
								type: "text",
								value: filename,
								attributes: {},
								children: [],
							};
							Object.defineProperty(text, "parentNode", {
								writable: true,
								value: title,
							});
							title.children.push(text);
							node.children.unshift(title);
						}
					}
				},
			},
		};
	},
};
```
