### ISSUE TITLE
Inverse of convertShapeToPath plugin

### ISSUE THREAD

**Issue by Crissov** [svg/svgo#719]
[`convertShapeToPath`](https://github.com/svg/svgo/blob/master/plugins/convertShapeToPath.js) turns semantic elements into more compact `<path>` elements. I wish there was also the opposite which would make editing by hand simpler.

**Comment by GreLI** [comment]
That's an image edition option which is highly optional and doesn't has something with optimization, so it's out of scope of SVGO.

Also, `<path>` element is more powerful then simple shapes counterparts. But you can do it for yourself if you want. Here are some docs about: https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md

**Comment by Crissov** [comment]
Making an SVG easier to edit is an aspect of optimization, which is not the same as minification.

**Comment by GreLI** [comment]
As I said in other issue, we're optimizing file size here. Otherwize the goal would be quite vague.
