### ISSUE TITLE
pngcrush embedded PNG files

### ISSUE THREAD

**Issue by kaihendry** [svg/svgo#72]
I noticed my particular SVG has PNG files embedded in it. Could these be detected and pngcrushed?
http://pmt.sourceforge.net/

That's IFF pngcrush was detected on the system, which I have :}

**Comment by GreLI** [comment]
Compressing PNGs is a very complex topic. There are a lot of tools, many of them aren't cross-platform. pngcrush isn't a best one. Also, it can be time consuming depending on compression method (e.g. zopfli to optimize deflate compression isn't a fast algorithm).

I believe there should be a modular structure that allows to connect external compressors, but as for now SVGO is far from that.

As for CSSO—it's already included, so I'm closing this.
