### ISSUE TITLE
Let cleanupIDs keep non-automatic IDs

### ISSUE THREAD

**Issue by Crissov** [svg/svgo#720]
I'd like [`cleanupIDs`](https://github.com/svg/svgo/blob/master/plugins/cleanupIDs.js) to keep IDs unchanged if they are semantic, i.e. carefully applied manually by the author instead of systematically stupid by an image editor. The latter are usually of the form `([a-z]+)(\d+)` where $1 usually matches the element type, e.g. `g` or `path` or just its initial letter.

**Comment by GreLI** [comment]
I'm afraid that's a highly speculative and not that demanded.

**Comment by Crissov** [comment]
Please at least keep removing unused IDs and renaming used IDs separate then.
