### ISSUE TITLE
Support external plugins

### ISSUE THREAD

**Issue by alex3165** [svg/svgo#722]
I have used svgo on a nodejs project and I couldn't find a way to define a plugin from outside of svgo module so I had to fork the library to add my own plugins. Am I missing something or is svgo plugins designed this way on purpose?

**Comment by GreLI** [comment]
You're right, currently, there is no design to connect external plugin. How do you think such an API would look like?

**Comment by alex3165** [comment]
Hum, maybe the less disruptive approach would be to have something like this:
```
const svgo = new SVGO({
    definePlugins: [
        renameAttrsToCamelCase: {
          type: "perItem",
          active: true,
          description: 'Convert attributes names to camelCase',
          params: {},
          fn: (item, params) => {
            // Blabla my logic here 
          }
        }
    ],
    usePlugins: [
        'removeComments',
        'removeMetadata'
    ]
});
```

I can work on a PR if you are happy with that.

**Comment by GreLI** [comment]
Speaking of this, if I reading [lib/svgo/config.js](/svg/svgo/blob/master/lib/svgo/config.js) correctly, you can pass plugins as functions with config like this. (Haven't tried it really.)
```
{
    plugins: [
        {
            myPlugin: {
                name: 'myPlugin',
                params: {},
                fn: function(data) { /*...*/ }
            }
        }
    ]
}
```

**Comment by strarsis** [comment]
It may be a nice solution to use [liftoff](https://github.com/js-cli/js-liftoff) as basis for plugin loading.

**Comment by tiptronic** [comment]
@Enchiridion Thanks for pointing that out. However, if I copy/paste your code (or create a even more simpler/empty plugin) in a `config.js` file, I am getting:

`YAMLException: missed comma between flow collection entries at line 8, column 38:
     ...    fn          : function(item) {`

Any idea?
btw. I am on a Mac (10.14.4)
