### ISSUE TITLE
Sync-ify? Await result? Lost tbh.

### ISSUE THREAD

**Issue by ivancuric** [svg/svgo#723]
Since I'm using svgo as a step in a rather crude way due to tech constraints (https://github.com/sindresorhus/gulp-template), returning values would be a godsend.

Here's a snippet of what I have so far:
```js
const optimizeSvg = svgString => {
  const svgo = new SVGO();

  let optimizedSvgString;
  svgo.optimize(svgString, output => (optimizedSvgString = output.data));
  // async problem
  return optimizedSvgString;
};

```
Trouble is, of course, that complex SVG graphics take some time to parse and `optimized` ends up being `undefined` in some cases.

Would `async/await` help here? If so, any ideas on how to manage it?

**Comment by GreLI** [comment]
Use callbacks instead of sync return. Async/await should help when the promisified version will be released. (Or you can promisify it yourself.)

**Comment by ivancuric** [comment]
Thanks for the prompt reply!

I should maybe post this to stackoverflow instead of clogging up the repo, but gonna try it anyway :)

Thing is, the template engine expects a static data object. I managed to "fool" it by using a getter:
```js
const tpl = {
  get data() {
    return {
      md: markdownToHtml,
      svg: getSvg,
    };
  },
};
```
which is then used as `.pipe(template(tpl.data))` in the gulp pipeline. The caller looks like this:
```js
const getSvg = (filename, uriEncode) => {
  const svgString = fs.readFileSync(`${path.src.svg}${filename}.svg`, 'utf-8');
  return optimizeSvg(svgString, uriEncode);
};
```
So in the end I need a string return value in the `tpl.data(filename)` call.
If you have any ideas I'd be extremely grateful!

**Comment by strarsis** [comment]
Relevant PR for imagemin-svgo: https://github.com/imagemin/imagemin-svgo/pull/27

**Comment by TrySound** [comment]
API is now synchronous
