### ISSUE TITLE
Json configuration is ignored in CLI

### ISSUE THREAD

**Issue by ameesme** [svg/svgo#724]
`svgo --config=svgo_config.json -i src/glyphs/black_add_document.svg -o -`

The command should read a file from the source-folder, read the config and output it to stdout.

My configuration file is as follows;
```
{
    "plugins": [
        "removeComments",
        "removeMetadata",
        "removeTitle",
        "mergePaths"
    ]
}
```

However, the output file still contains a title and multiple paths. Even when I feed it a malformed JSON, no error is shown.

Running version 0.7.2.

**Comment by posixpascal** [comment]
I had problems with svgo as well, downgraded to 0.6.1 – still not working.
I'm now on svgo 0.5.1 and it works. 

Latest version didnt even recognize `--enable` cli options.

**Comment by strarsis** [comment]
@posixpascal: I can enable a plugin using e.g. `enable=chainFilters`, maybe the `=` is required for it to work.

**Comment by ameesme** [comment]
@strarsis Seems like a weird syntax. Is this a standard?

**Comment by strarsis** [comment]
@ameesme: https://github.com/svg/svgo#cli
Maybe the arguments parser is not flexible enough?
svgo uses [coa](https://www.npmjs.com/package/coa) for CLI.

**Comment by elrumordelaluz** [comment]
Seems work well in `svgo@^1.0.0`
