### ISSUE TITLE
Insufficient documentation for removeUselessStrokeAndFill

### ISSUE THREAD

**Issue by peternowell** [svg/svgo#727]
I've read through the removeUselessStrokeAndFill.js plugin as best I can, and I haven't been able to figure out exactly when it's useful. There's absolutely zero documentation or specific examples of what this optimization targets.
Again, I've tried tons of SVGs that seem like they should work with that optimization, but there's never any effect. I'm using it through SVGOMG.

Does anybody have a demo or two of an SVG that is actually affected by removeUselessStrokeAndFill? @deepsweet @GreLI @kt3k @caub — it looks like you guys contributed to this one.

I'm teaching a course tonight that goes over SVGO and I need to figure out this answer! :)

**Comment by caub** [comment]
SVGOMG is probably outdated

see test/plugins/removeUselessStrokeAndFill* to see what it could do

note: we should rename those files without .svg extension, it doesn't make sense and can't be seen easily on GH

**Comment by peternowell** [comment]
Thank you so much, @caub! I didn't know about that whole folder of test SVGs. Those examples seem to have cleared up my confusion.

**Comment by SethFalco** [comment]
Thanks for reporting the issue!

SVGO now has documentation hosted on svgo.dev, you can read more about it here:
https://svgo.dev/docs/plugins/remove-useless-stroke-and-fill/

Contributions to improve our documentation is welcome.
