### ISSUE TITLE
Docs vs config

### ISSUE THREAD

**Issue by stephan-v** [svg/svgo#731]
I am wondering why the docs state that plugins like `removeDimensions` state that it is disabled by default, yet when I look at the default configuration is it clearly there in the plugins list:

https://github.com/svg/svgo/blob/master/.svgo.yml

Are the plugins in the default not the plugins that get executed by default or is the documentation wrong on this?

**Comment by strarsis** [comment]
@stephan-v: Just ran into this in a PR for a new plugin. The .svgo.yml states the _available_ plugins and their specific _order_. Whether a plugin as enabled by default (="active") is controlled in plugin file, e.g. https://github.com/svg/svgo/blob/master/plugins/minifyStyles.js#L5 .

**Comment by TrySound** [comment]
New version has more clear variables naming
