### ISSUE TITLE
enabling cleanupIDs won't let convertPathData apply transformations

### ISSUE THREAD

**Issue by geolauf** [svg/svgo#736]
Dear all,

I have an input svg file that I wan to clean creating new paths applying the transformations and I don't want to loose my ids.
When I enable the convertPathData plugin alone, transformations are applied but the ids disapear:
svgo -i input.svg -p 2  --enable=convertPathData -o output.svg
When I disable the cleanupIDs plugin, the transformations are not applied anymore.
svgo -i input.svg -p 2  --enable=convertPathData --disable=cleanupIDs -o output.svg

example of path:
'<path transform="translate(6234.90295410156 1772.95837402344) scale(100)"  id="region:1:Barbuda" d="M -61.999862670898438 -16.999860763549748 L -62.000137329101563 -16.999860763549748 -62.000137329101563 -17.000139236450138 -61.999862670898438 -17.000139236450138 Z M -61.852085113525334 -17.642915725707951 L -61.848194122314453 -17.629861831665096 -61.849582672119084 -17.62208366394043 Z M -61.846248626708928 -17.609304428100586 L -61.825416564941406 -17.64708328247076 -61.830139160156193 -17.681528091430721 -61.862083435058537 -17.695140838623104 -61.844581604003906 -17.729583740234432 -61.743194580078125 -17.643472671508903 -61.730972290039006 -17.54486083984375 -61.7620849609375 -17.557361602783203 -61.766803741455021 -17.543193817138786 -61.821804046630859 -17.591806411743107 -61.859027862548771 -17.580972671508789 Z M -61.834861755371094 -17.671806335449332 L -61.834304809570313 -17.665418624877987 -61.836807250976506 -17.667360305786133 Z M -61.862640380859375 -17.682916641235465 L -61.878471374511719 -17.699028015136776 -61.852359771728459 -17.645416259765625 -61.886528015136719 -17.696805953979435 -61.869304656982422 -17.71624946594244 Z/>" 	

Somebody has already faced this issue and would like to share a tip?

Thank you in advance,
Best

**Comment by elrumordelaluz** [comment]
Could you pleas share the `output` you obtain and what you expected?

I'm trying with your example (input.svg):
```
<svg>
  <path
    transform="translate(6234.90295410156 1772.95837402344) scale(100)"
    id="region:1:Barbuda"
    d="M -61.999862670898438 -16.999860763549748 L -62.000137329101563 -16.999860763549748 -62.000137329101563 -17.000139236450138 -61.999862670898438 -17.000139236450138 Z M -61.852085113525334 -17.642915725707951 L -61.848194122314453 -17.629861831665096 -61.849582672119084 -17.62208366394043 Z M -61.846248626708928 -17.609304428100586 L -61.825416564941406 -17.64708328247076 -61.830139160156193 -17.681528091430721 -61.862083435058537 -17.695140838623104 -61.844581604003906 -17.729583740234432 -61.743194580078125 -17.643472671508903 -61.730972290039006 -17.54486083984375 -61.7620849609375 -17.557361602783203 -61.766803741455021 -17.543193817138786 -61.821804046630859 -17.591806411743107 -61.859027862548771 -17.580972671508789 Z M -61.834861755371094 -17.671806335449332 L -61.834304809570313 -17.665418624877987 -61.836807250976506 -17.667360305786133 Z M -61.862640380859375 -17.682916641235465 L -61.878471374511719 -17.699028015136776 -61.852359771728459 -17.645416259765625 -61.886528015136719 -17.696805953979435 -61.869304656982422 -17.71624946594244 Z"
  />
</svg>
```

running `svgo -i input.svg -p 2 --enable=convertPathData --disable=cleanupIDs -o output.svg --pretty`

the result (output.svg) is:

```
<svg>
    <path 
      transform="matrix(100 0 0 100 6234.9 1772.96)" 
      id="region:1:Barbuda" 
      d="M-62-17zm.15-.64v.01zm0 .03l.02-.04v-.03l-.03-.02.02-.03.1.09v.1l-.02-.02v.02l-.06-.05h-.04zm.02-.06zm-.03-.01l-.02-.02.03.05-.04-.05.02-.02z"/>
</svg>

```

**Comment by geolauf** [comment]
Thank you @elrumordelaluz, it worked using the command line you provided :)

**Comment by macrozone** [comment]
@geolauf i have the exact same issue, but @elrumordelaluz does not solve it as you see in his comment. The transform is still there
