### ISSUE TITLE
conditionally squash #RRGGBB to #RGB?

### ISSUE THREAD

**Issue by jdischler** [svg/svgo#74]
I love this tool but unless I'm missing an option, sometimes a given conversion to #RGB from #RRGGBB loses enough precision on that colour that it now looks wrong.  I would think it might be helpful to have an option to only optimize a colour when the compressed format is sufficiently close to the original.  I guess it could be done as some kind of error tolerance...if the resulting error is too high, output the uncompressed #RRGGBB color?

**Comment by GreLI** [comment]
It was eventually made, I guest [``convertColors``](/svg/svgo/blob/master/plugins/convertColors.js) plugins now fully satisfies this request.
