### ISSUE TITLE
How to delete data-* attr?

### ISSUE THREAD

**Issue by Artkoch** [svg/svgo#744]
I get 
> Warning: Unknown prop `dataName` on <g> tag. Remove this prop from the element
How to delete data-* attr?

**Comment by elrumordelaluz** [comment]
Where are you getting this _warning_? Seems from react, that accept data-attributes not camelCased.

However you could use [removeAttrs plugin](https://github.com/svg/svgo/blob/master/plugins/removeAttrs.js) to remove specific attrs. Is super flexible since accept regexp.

**Comment by GreLI** [comment]
Thanks to @elrumordelaluz for the comprehensive answer. It really doesn't seem like related to SVGO.
