### ISSUE TITLE
Breaks some of the earlier optimised images.

### ISSUE THREAD

**Issue by nashokin** [svg/svgo#745]
Some of the images optimised before are broken after running this plugin on them. Files before and after are attached.
[Archive.zip](https://github.com/svg/svgo/files/1096751/Archive.zip)

**Comment by GreLI** [comment]
In your archive there is an extra `</svg>` at the end, but I cannot reproduce such a thing with SVGO.

**Comment by nashokin** [comment]
Thanks. Yes, it's been fixed along the way, can't reproduce it anymore either.

**Comment by nashokin** [comment]
Actually still breaks files. Archive attached.
[svgo.zip](https://github.com/svg/svgo/files/1144324/svgo.zip)

**Comment by JoshyPHP** [comment]
The `geelongadvertiser-original.svg` file gets minified correctly on my local svgo 0.7.2 running on Node.js v8.1.2.

**Comment by nashokin** [comment]
I does minify it when I call `svgo geelongadvertiser.svg geelongadvertiser.min.svg`

We use automation using imagemin. I already logged and iisue with imagemin and have been referred here. No one wants to take responsibility.

The code is pretty basic, which runs in a loop:
`imagemin([srcPath + file + '/*.svg'], assetsPath + file, {use: [imageminSvgo({plugins: [{removeViewBox: false}]})]}).then(() => {
			console.log('Svg images optimized');
		});`

Can you see anything wrong here?

**Comment by JoshyPHP** [comment]
If the issue is reproducible with imagemin but not reproducible with svgo then you should ask the imagemin maintainers to give it a second look.

**Comment by nashokin** [comment]
https://github.com/imagemin/imagemin-svgo/issues/28

**Comment by kevva** [comment]
Well, you're running `imagemin-svgo` with `removeViewBox: false` and just `svgo` without it. Can you try `svgo --enable="removeViewBox" geelongadvertiser.svg geelongadvertiser.min.svg`?

**Comment by nashokin** [comment]
I agree and it works. Can this be an issue with `imagemin` itself?

**Comment by kevva** [comment]
Nope, works fine. Here are the images [test.zip](https://github.com/svg/svgo/files/1147016/test.zip) with the following code:

```js
imagemin(['geelongadvertiser.svg'], __dirname, {
	use: [
		imageminSvgo({
			plugins: [
				{removeViewBox: false}
			]
		})
	]
});
```

It's probably something wrong with your code, although I don't have time to look at that. Probably better to ask on StackOverflow.

**Comment by nashokin** [comment]
no, it doesn't.

can you provide the actual js script file that you ran?

and which node version are you on?

**Comment by kevva** [comment]
There you go: [test.zip](https://github.com/svg/svgo/files/1147074/test.zip). Feel free to close @GreLI.

**Comment by nashokin** [comment]
Try this: 
[better test.zip](https://github.com/svg/svgo/files/1147197/better.test.zip)
`npm install`
`npm run compile`

node v 7.10

after goto 'public' folder and BAR-349

normally, but not always it works 1st time, but not 2nd or 3rd it, geelong svg is broken

I'd say it's not happy to run alongside 'ncp'

and yes, your basic example works; close it as I feel resistance in resolving this

but, I'd still blame 'imagemin-svgo' as it works perfectly well with 'imagemin-jpegtran' and 'imagemin-optipng' AND 'imagemin-gifsicle'

**Comment by kevva** [comment]
> and yes, your basic example works; close it as I feel resistance in resolving this

That's just how you solve problems in programming. If a function works, it *works*. If it's breaking in in your code, then you have to debug to see what's wrong. This isn't a support forum, if you can't provide an isolated test that proves that either `svgo` or `imagemin` is broken, then it's nothing we can do.

And by looking at your code in the archive you provided, I think you need to learn the basics of async programming before

**Comment by nashokin** [comment]
Ok, thanks for letting me know, if these are the rules, these are the rules.

In my defence I have 3 other modules in the same logic, that work just fine with my code, can easily be the other way around and this is just an upset bold statement.

Many functions work in isolation, it's when putting them all together gets obvious who is the winner.

**Comment by kevva** [comment]
FYI: You can't do async operations in a regular `.forEach` and expect stuff to work smoothly. Either use https://github.com/sindresorhus/each-async or `Promise.all(files.map(x => doStuff()))`.
