### ISSUE TITLE
Bad sweep flag when converting curve to arc

### ISSUE THREAD

**Issue by JoshyPHP** [svg/svgo#754]
I tracked it down to [line 337 of the convertPathData plugin](https://github.com/svg/svgo/blob/bc3c8a6e38d8c356e633a408d55f7f6fa0d202b1/plugins/convertPathData.js#L337). Removing that line fixes this issue and does not make any test fail but I don't know what that line really does so it may very well not be a proper fix.

Tested on current master (0.7.2) with the following:

Original
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -6 36 30">
    <path d="M0 0c-.191.142-.457.13-.635-.029-.177-.16-.217-.424-.094-.628z" fill="#888"/>
</svg>
```
Expected
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -6 36 30">
    <path d="M0 0a.5.5 0 0 1-.729-.657z" fill="#888"/>
</svg>
```
Actual
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -6 36 30">
    <path d="M0 0a.5.5 0 1 1-.729-.657z" fill="#888"/>
</svg>
```

**Comment by GreLI** [comment]
I believe it's been addressed by #752. Correct me if I'm wrong.
