### ISSUE TITLE
Sort <defs> for better compression

### ISSUE THREAD

**Issue by davidleston** [svg/svgo#761]
Better gzip compression can be achieved by sorting the children of <defs>.

Take the svgoomg demo:
https://github.com/jakearchibald/svgomg/blob/8dc58d63d7bad5bd70d86112f4db7dc510ea9c8d/src/test-svgs/car-lite.svg

Fully optimized and gzipped it's 3,493 bytes.
The suggested additional optimization and gzipped produces 3,484 bytes, saving 9 bytes.

**Comment by GreLI** [comment]
SVGO v1.3.0 with the plugin is released.
