### ISSUE TITLE
Suggestion: Change colors slightly so they can be shorter

### ISSUE THREAD

**Issue by davidleston** [svg/svgo#763]
Similar to how cleanupNumericValues' option to reduce float precision: configure how much colors are allowed to change in order to be shorted.

Currently `#333333` is converted to `#333`. A configured value of `1` would replace `#323333` and `#333433` with `#333`. Would also implement detecting distance to [short color names](https://github.com/svg/svgo/blob/d0a511fc376b07c0a5874387f7b64f57691c73f8/plugins/_collections.js#L2492).

I'd be happy to create a PR if this sounds like something that'd be accepted. Would you like this as a new plugin or a part of convertColors plugin? Also, any suggestions on the name of the parameter to configure and a default value?

**Comment by GreLI** [comment]
Nice idea! `convertColors ` would be nice place for the optimization. Perhaps, a good name would be something like ‘convertClose’.

The only thing I'm considering is what the threshold value. 0x10? 0.01%? An option value?
