### ISSUE TITLE
hasChild()

### ISSUE THREAD

**Issue by Crissov** [svg/svgo#770]
The jsAPI can check the AST for attributes with `hasAttr()`. For a plugin I'm writing, I'd need to know whether the node has a specific child. If I understand correctly, I can insert a child node (at the top) with `spliceContent(0, 0, newElems)`, but I don't want to add it if another child node of the same type already exists.

(`spliceContent()` is not documented in [docs/how-it-works/en.md](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md), but I found it in [lib/svgo/jsAPI.js](https://github.com/svg/svgo/blob/master/lib/svgo/jsAPI.js).)

**Comment by GreLI** [comment]
There is no API for adding elements, so yeah, I guess it's the only way within API. Feel free to add an API method, if you like or going to make a PR.

(You can just `.shift()` since it's an usual array under hood, but it's deprecated, not guaranteed etc...)

**Comment by strarsis** [comment]
@Crissov: Could this be helpful?: https://github.com/svg/svgo/blob/master/lib/svgo/css-select-adapter.js#L26

**Comment by Crissov** [comment]
Possibly, thanks. I'm currently busy with other stuff, though.
