### ISSUE TITLE
Multiple files CLI

### ISSUE THREAD

**Issue by ai** [svg/svgo#773]
`lint-staged` is very useful with `svgo` (it will send to svgo` any new or changed SVG).

But `lint-staged` pass all file names in single command `TOOL FILE1 FILE2 FILE3`.

`svgo` falls in this case. Also when you change only two files `lint-staged` called it with `svgo one.svg two.svg` which even broke uncommit files :(.

@GreLI do we have any solution for this? If not. just give me CLI API — I will send PR.

**Comment by GreLI** [comment]
Actually, I'm working on it right now.

**Comment by GreLI** [comment]
JFYI, for now current CLI API is
```
svgo <input-file> <output-file>
```
(and I want to change that.)

**Comment by killbillsbor** [comment]
Hi, @GreLI!

Any progress on this issue? `lint-staged` and `svgo` are a great couple, but it's annoying to commit not more than one SVG file per commit.

Thanks!

**Comment by asottile** [comment]
I took a stab at this in #786, people are reaching for the same things for [pre-commit](http://pre-commit.com/)

**Comment by GreLI** [comment]
Finally, It has been done it in e3ddf1d96ab88beb9f496a122dee6ebcb4a0c907.
