### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by jbergstroem** [svg/svgo#774]
Since there's been a lot of important commits (for the ecosystem, such as promises) since the last release in January, perhaps it's time to tag a new release?

**Comment by GreLI** [comment]
Yet there are some things to finish not completed.

**Comment by fatfisz** [comment]
Is there a checklist somewhere?

I looked at an example with promises and it turns out the latest release still has callbacks, so I'd be interested in helping with getting the new version shipped.

**Comment by ydaniv** [comment]
@GreLI please share with us what you have, there hasn't been any progress for a very long time.
You can commit work in progress to a new branch, so we can view and try to help.
This is the meaning of "open" in open source (:

**Comment by GreLI** [comment]
Well, at most I was busy [making `svgo *.svg` possible](https://github.com/svg/svgo/commit/e3ddf1d96ab88beb9f496a122dee6ebcb4a0c907). It's done, I just to tweak and cleanup the plugins, fix some dumb things and release.

**Comment by codysherman** [comment]
Any idea of a timeline on when the release is expected? Will it be in 2017? Need dat recursive folder feature HNNNNGGGG. Awesome work by the way!

**Comment by jbergstroem** [comment]
@GreLI we all appreciate your work. I think it might be time to put new features on shelf and make sure we avoid breaking for the community that is dependent on things like promises, then keep working on those said features.

**Comment by GreLI** [comment]
> Need dat recursive folder feature HNNNNGGGG. Awesome work by the way!

Unfortunately it has lost in that commit. :disappointed: It's hard to make it properly in a async way.

**Comment by strarsis** [comment]
@GreLI: Yes, a new release to npm would be great! 
I have sometimes strange issues with other modules using svgo (imagemin-svgo).

**Comment by JackNUMBER** [comment]
Same here, gulp-svgmin has some issues and we need inlineStyles back :)

**Comment by strarsis** [comment]
`svgo` version `1.0.0` comes with Promise based API, you have to update plugins/adapters that for svgo.

(svgo-loader: https://github.com/rpominov/svgo-loader/pull/17,
imagemin-svgo: https://github.com/imagemin/imagemin-svgo/pull/27)

**Comment by fatfisz** [comment]
Yay! Thanks a lot for the release, great work :)

**Comment by bradleyayers** [comment]
I believe this can be closed now.

**Comment by GreLI** [comment]
Yeah, thanks for reminder.
