### ISSUE TITLE
Document the configuration options

### ISSUE THREAD

**Issue by jeremyabel** [svg/svgo#775]
I'm trying to use this in a browser-based application, and the example I'm looking at has a few options set, but I have no idea what any of them do. I've spent the past 15 minutes digging thru the existing issues to see if anyone has posted anything on this, but I didn't find anything. 

Things like:
- what does the "full" setting do?
- what does the "multipass" setting do?
- what other options are there, and what do they do?

**Comment by GreLI** [comment]
1. “full” means, that you write exhaustive list of plugins and standard set of plugins will not be applied. Without it config (any plugin setting) extends the default set.
2. Plugins are running in order, and some plugins are best to run after others. Some plugins are best to run after each other in different order or even several times. “Multipass” do the latter. It runs plugins several times until there is no change, capped by 10 times.
3. There are different options: plugins—that do certain optimization and settings (e.g. “precision” sets number of floating part digits).
