### ISSUE TITLE
Error with adjacent <svg>s

### ISSUE THREAD

**Issue by elrumordelaluz** [svg/svgo#782]
Since [sax](https://github.com/isaacs/sax-js/) is set in [`strict` mode](https://github.com/svg/svgo/blob/master/lib/svgo/svg2js.js#L8), `svgo` throws an Error with adjacent `<svg/>` but in some cases:

```js
const str = `
<svg viewBox="0 0 64 64">
  <line x1="5" y1="5" x2="10" y2="10" stroke="#000" stroke-width="2"/>
</svg>
<svg viewBox="0 0 64 64">
  <line x1="5" y1="5" x2="10" y2="10" stroke="#000" stroke-width="2"/>
</svg>
`
svgo.optimize(str, ({ data }) => console.log(data))
```

The code above works as expected logging this
```
<svg viewBox="0 0 64 64"><path stroke="#000" stroke-width="2" d="M5 5l5 5"/></svg><svg viewBox="0 0 64 64"><path stroke="#000" stroke-width="2" d="M5 5l5 5"/></svg>
```

But it I have for example a `<title/>` tag in one of the `<svg/>`s will fail:
```js
const str = `
<svg viewBox="0 0 64 64">
  <line x1="5" y1="5" x2="10" y2="10" stroke="#000" stroke-width="2"/>
</svg>
<svg viewBox="0 0 64 64">
  <title>Hello</title>
  <line x1="5" y1="5" x2="10" y2="10" stroke="#000" stroke-width="2"/>
</svg>
`
svgo.optimize(str, r => console.log(r))
```

```
{ error: 'Error in parsing SVG: Text data outside of root node.\nLine: 5\nColumn: 10\nChar: H' }
```

The condition where `sax(strict)` throws is [here](https://github.com/isaacs/sax-js/blob/master/lib/sax.js#L1034-L1036) since, `closedRoot` is `true` after the first `svg` is closed.

Probably is the right behaviour.
But maybe for `svgo`, in case could not parse adjacent `<svg/>`s should throws in both cases.

Let me know if is an issue most related to `sax` so continue analysing in this direction.

**Comment by GreLI** [comment]
sax in non-strict mode isn't good for XML's like SVGs. E.g. it doesn't preserve character case. XML files can have only one root tag, so your example is syntactically invalid. So, you need to have another approach. Some options may be wrapping it with `<svg>` tag temporary, or using symbols or similar tags. At last, you can optimize SVGs just one by one.

**Comment by elrumordelaluz** [comment]
Yep, thanks @GreLI I am doing a _workaround_ wrapping the `<svg/>`s into a temp `<root>` tag.

The point that push me to open the _Issue_ is that the `xml` syntax with errors pass in one case an not in the other (the 2 examples I post before), since both are syntactically wron, right?

**Comment by GreLI** [comment]
Yeah. However there are cases, when tags outside root tag are legal, e.g. a comment.
```xml
<svg>
...
</svg>
<!-- some comment here -->
```
So we have what we have.
