### ISSUE TITLE
'svgop' released. Compiled binary executables of svgo for macOS and Windows

### ISSUE THREAD

**Issue by twardoch** [svg/svgo#783]
Hi all, 

I’ve spent the last night on preparing compiled binary executable packages of svgo for macOS and Windows which can be run without Nodejs installed. The result is at: 

* https://github.com/twardoch/svgop

I used [`pkg`](https://www.npmjs.com/package/pkg) to prepare the distributables. `pkg` choked on two things: 

* some aspects of `coa.js` (so I ended up not using it but just hardcoding some parameters), 
* the dynamic loading of plugins (the `require('../../plugins/' + name)` thing), so I ended up hardcoding the list of plugins and using portions of the [rejected PR 614](https://github.com/svg/svgo/pull/614/) by @joeldenning. 

Also: I don’t know shit about JS (really) and about Node and about packaging, so I ended up with a very hacky [`Makefile`](https://github.com/twardoch/svgop/blob/master/Makefile) which hacks it all together. :) But it works! 

I’d still prefer if svgo plugin loading was rewritten upstream in a way that doesn’t make `pkg` (and `Jspm` and possibly other environments) choke. The current method is not nice. 

Patches, pull requests or comments on https://github.com/twardoch/svgop are most welcome.

**Comment by twardoch** [comment]
(I also briefly thought on taking on https://github.com/svg/svgo/issues/411 but realized that I’m far too slow with writing JS. But anyone else is most welcome to tackle that one! :) ).

**Comment by douglasmiranda** [comment]
This tool (svgo) is the best so far!

Would be awesome a official binary release.

---

I saw a reference here too https://github.com/svg/svgo/issues/777#issuecomment-326388634 but no answer, some official member could clarify here if there's interest to release standalone executables.

**Comment by twardoch** [comment]
I've managed to compile svgo with QuickJS, so the native macOS binary is now 1.9 MB. Previous method (pkg) produced 83 MB :) 

https://github.com/twardoch/svgop

**Comment by TrySound** [comment]
Great! Check the new version https://github.com/svg/svgo/releases/tag/v2.0.0
Dynamic plugins loading is removed. Though config is still loaded this way.
