### ISSUE TITLE
Color changes unexpectedly!

### ISSUE THREAD

**Issue by TheYahya** [svg/svgo#785]
Why after compressing any `svg` file, all colors become same color?! so svgo doesn't support multi-color svg files.

**Comment by JoshyPHP** [comment]
You should post a link to the original SVG file and maybe the optimized file.

**Comment by TheYahya** [comment]
It's the [original file](http://svgshare.com/i/2vs.svg) and the optimized version is [here](http://svgshare.com/i/2v2.svg).

**Comment by GreLI** [comment]
It's because of CSS styles. SVGO doesn't support them.
