### ISSUE TITLE
`role` attribute being removed

### ISSUE THREAD

**Issue by MatthewHerbst** [svg/svgo#787]
When I run svgo with default options, it removes the `role` attribute from within the `svg` tag. However, having the [`role="img"`](https://www.w3.org/TR/wai-aria/roles#img) attribute is recommended good practice for helping make SVGs accessible:

https://www.w3.org/TR/svg-aam-1.0/
https://developer.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/

I assume the thing causing this is that `role` is not specified in the [`_collections`](https://github.com/svg/svgo/blob/master/plugins/_collections.js) file. Before I make a PR for that, I wanted to see if this was ok, or if there was something I'm missing?

**Comment by GreLI** [comment]
I guess it should be highly optional due to very marginal case. It's useless when you use SVG as an image or a background.

**Comment by MatthewHerbst** [comment]
@GreLI My use case is that I have a bunch of icons as SVGs, and while each icon has meaning (as I note in the `title` and `desc` fields, supported by an `aria-labelledby="titleId  descId"`), the things that compose them do not, so by giving the SVG an `role="img"`, I'm instructing browsers not to traverse the SVG's child elements, and thus to not add them into the accessibility tree, since they on  their own have no semantic meaning. (At least, that's my understanding of what adding the `role="img"` is doing.)

Considering the developer has to explicitly add it, is there any harm in simply allowing it, so long as the value for the `role` is valid (and not the default option)?

**Comment by GreLI** [comment]
At now SVGO doesn't know anything about `role` and `aria-*`, except `keepAriaAttrs` option was added recently to `removeUnknownsAndDefaults` in #741.

**Comment by MatthewHerbst** [comment]
@GreLI but isn't the simple fix to that to just make `role` known as I suggested in the first post above?

**Comment by GreLI** [comment]
I just don't want to keep it always, it should be optional.

**Comment by MatthewHerbst** [comment]
Ok, I can make a PR where keeping it is opt-in rather than opt-out (like `keepAriaAttrs` is). However, I feel like I still don't understand why you think it should be so optional. If someone specifies it, why should it not be kept by default? It's a valid tag on an SVG element.
