### ISSUE TITLE
[REQUEST] can removeStyleElement also remove class attribute from elements?

### ISSUE THREAD

**Issue by martenzander** [svg/svgo#792]
When exporting svgs from lets say Illustrator, the styles go into the `<style>`-tag. Illustrator is also generating some generic classes like `class="st0"` and applies it to the relevant elements.

When enabling `removeStyleElement` I also don't need the classes on my elements. 
Not sure yet if its okay to generalize this, maybe its worth making a new plugin like "**removeClassAttr**" or something?

**Comment by GreLI** [comment]
I think it can be done with `removeAttrs`. Maybe not that convenient, but still.
