### ISSUE TITLE
Remove "-inkscape-font-specification"

### ISSUE THREAD

**Issue by paulocoghi** [svg/svgo#797]
Even when exporting plain SVG's through Inkscape, there are cases where it inserts an "-inkscape-font-specification" inside an object style.

This style isn't considered, also because the standard `font-family` attribute is generated as well.

Thus, there are two cases for optimization:

**Case 1 - Inkspace font style together with other styles**
In this case, only the "-inkscape-font-specification" must be removed.

```xml
<!-- This -->
<text style="-inkscape-font-specification:'Source Sans Pro Bold';text-align:center">...</text>

<!-- Should become this -->
<text style="text-align:center">...</text>
```

**Case 2 - Inkspace style alone**
In this case, all the style attribute must be removed.

```xml
<!-- This -->
<text style="-inkscape-font-specification:'Source Sans Pro Bold'">...</text>

<!-- Should become this -->
<text>...</text>
```

**Comment by GreLI** [comment]
SVGO doesn't remove vendor prefixes (and all unknown attributes). It can be improved in `convertStyleToAttrs` plugin.

**Comment by paulocoghi** [comment]
Ok, thanks!

**Comment by thekalinga** [comment]
Does that mean, we have to manually update the script locally?

**Comment by paulocoghi** [comment]
I believe that we should create a new plugin, which is optional, to work in such cases. This way it becomes an option. Unfortunately, I am not with free time enough to work on this right now.

**Comment by jorgemoya** [comment]
I'm having the same problem. Did anyone come up with a solution?
