### ISSUE TITLE
convertPathData removes a perfect circle

### ISSUE THREAD

**Issue by pycbouh** [svg/svgo#806]
node 7.7.2
npm 4.1.2
svgo 0.7.2

We have an icon that contains, as far as I can tell, a perfect circle. That circle gets removed after running svgo with default settings. After playing around with custom config I concluded that convertPathData plugin is at fault, as disabling it fixes the issue, but causes 62.2% compression shrink to 32.2%. Trying to configure convertPathData yielded no changes in behaviour.

Example file and our result are attached:
[svg-with-circles.zip](https://github.com/svg/svgo/files/1362944/svg-with-circles.zip)

**Comment by pycbouh** [comment]
I looked further into this and found out that a path for the circle
> M7.9975,6.00125 C9.65875,6.00125 11.0013,7.33875 11.0013,8.99875 C11.0013,10.6587 9.65875,12.0025 7.9975,12.0025 C6.3375,12.0025 5,10.6587 5,8.99875 C5,7.33875 6.3375,6.00125 7.9975,6.00125 L7.9975,6.00125 Z

is successfully simplified into 
> M7.997 6.001a3.002 3.002 0 1 1 0 0z

However, this resulting string renders nothing.

**Comment by na-oma** [comment]
This appears to be a **rounding/precision/floating point issue**.
Try adding a scaled up version of your circle:
```svg
<svg xmlns="http://www.w3.org/2000/svg">
    <path fill="red" d="M7.9975,6.00125 C9.65875,6.00125 11.0013,7.33875 11.0013,8.99875 C11.0013,10.6587 9.65875,12.0025 7.9975,12.0025 C6.3375,12.0025 5,10.6587 5,8.99875 C5,7.33875 6.3375,6.00125 7.9975,6.00125 L7.9975,6.00125 Z"/>
    <path transform="scale(2)" fill="blue" d="M7.9975,6.00125 C9.65875,6.00125 11.0013,7.33875 11.0013,8.99875 C11.0013,10.6587 9.65875,12.0025 7.9975,12.0025 C6.3375,12.0025 5,10.6587 5,8.99875 C5,7.33875 6.3375,6.00125 7.9975,6.00125 L7.9975,6.00125 Z"/>
</svg>
```
The first will be simplified wrongly and disappear like in your example, the second will be simplified right, (scaling down would also disappear):
```svg
<svg xmlns="http://www.w3.org/2000/svg">
    <path fill="red" d="M7.997 6.001a3.002 3.002 0 1 1 0 0z"/><!--gets eliminated with --multipass -->
    <path fill="#00f" d="M15.995 12.002a5.993 5.993 0 0 1 6.008 5.995 6.003 6.003 0 0 1-6.008 6.008A5.994 5.994 0 0 1 10 17.997a5.983 5.983 0 0 1 5.995-5.995z"/>
</svg>
```
**The culprit lies in line:**
https://github.com/svg/svgo/blob/3ec0767ba0ca3aff507ace3b3798de69084c4649/plugins/convertPathData.js#L356
This normally checks, how different the summed angle is from 360° or 2*PI.
If it is too different, it is not a circle, if not, it is a circle.
In your example, the arc seems to be a bit too short (the difference too great), so it is not recognized as circle.

The problem is the error constant/epsilon of 1e-3. It normally is large enough to cover some precision/rounding/whatever, but with your small numbers, you incur a very big precision/rounding/whatever error, your arc is too short, so the constant is too small.

**Fix:**
Increasing it (and maybe other mentions of 1e-3) might work, but might break other stuff: a large error could lead to bigger almost-circles to be wrongly recognized as circles.
My math is rusty and my understanding of the code shallow, but it might be possibly to either set the error constant(s) adaptively depending on the scale/precision we are working in, or to use some the supplied precision arguments/create a new one.
http://www.floating-point-gui.de/errors/comparison/ (really!)
suggests using some kind of relative error.

**Comment by pycbouh** [comment]
@na-oma Thank you for being thorough! Scaling precision in checks would be great for the library IMO. Our image was created with Sketch, and, as far as I know, nothing about export settings for this one did stand out. So, other people may run into a similar issue as well.

As for a workaround, I used an older version of SVGO, which is published at https://jakearchibald.github.io/svgomg/. It resulted in a slightly bigger file, but the app didn't have any issues with our circle. And after that the latest version of SVGO stopped ruining the image too (guess, it sees no need to optimize it now).

**Comment by coderaiser** [comment]
Same problem with options: `convertPathData` and `convertShapeToPath`. They broke `svg`.

So I run:

```
svgo --enable={convertPathData,convertShapeToPath} img/spinner.svg
```

Original svg:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="rgb(49, 123, 249)">
  <path transform="translate(2)" d="M0 12 V20 H4 V12z">
    <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0" keytimes="0;.2;.5;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline"  />
  </path>
  <path transform="translate(8)" d="M0 12 V20 H4 V12z">
    <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0.2" keytimes="0;.2;.5;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline"  />
  </path>
  <path transform="translate(14)" d="M0 12 V20 H4 V12z">
    <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0.4" keytimes="0;.2;.5;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
  </path>
  <path transform="translate(20)" d="M0 12 V20 H4 V12z">
    <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0.6" keytimes="0;.2;.5;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
  </path>
  <path transform="translate(26)" d="M0 12 V20 H4 V12z">
    <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0.8" keytimes="0;.2;.5;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
  </path>
</svg>
```


Becames:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="16" height="16" fill="#317BF9">
    <path d="M2 12v8h4v-8z">
        <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin="0" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
    </path>
    <path d="M8 12v8h4v-8z">
        <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin=".2" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
    </path>
    <path d="M14 12v8h4v-8z">
        <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin=".4" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
    </path>
    <path d="M20 12v8h4v-8z">
        <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin=".6" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
    </path>
    <path d="M26 12v8h4v-8z">
        <animate attributeName="d" values="M0 12 V20 H4 V12z; M0 4 V28 H4 V4z; M0 12 V20 H4 V12z; M0 12 V20 H4 V12z" dur="1.2s" repeatCount="indefinite" begin=".8" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.8 0.4 0.8" calcMode="spline" />
    </path>
</svg>
```

Here is both of them: [spinners.zip](https://github.com/svg/svgo/files/2205192/spinners.zip)

**Comment by TrySound** [comment]
Cannot reproduce. Probably fixed. Opened new issues for animation bug https://github.com/svg/svgo/issues/1388
