### ISSUE TITLE
is removeScriptElement included package

### ISSUE THREAD

**Issue by elrumordelaluz** [svg/svgo#809]
Seems that [removeScriptElement](https://github.com/svg/svgo/blob/master/plugins/removeScriptElement.js) it isn't in the [package published on npm](https://unpkg.com/svgo@0.7.2/plugins/)

**Comment by JackNUMBER** [comment]
9f05ac8 has been pushed on March 23 and the npm package is based on releases. The last one is [v0.7.2](https://github.com/svg/svgo/releases/tag/v0.7.2) released on 29 January.

**Comment by elrumordelaluz** [comment]
yup seems to be included in `^1.0` versions
