### ISSUE TITLE
don't remove preserveAspectRatio with default values

### ISSUE THREAD

**Issue by PeterTheOne** [svg/svgo#812]
It looks like preserveAspectRatio with default values is removed, but preserveAspectRatio with the default values is needed for some versions of Internet Explorer to be displayed correctly.

**Comment by GreLI** [comment]
Internet explorer is rather outdated browser, so I don't think it worth supporting now. However, SVGO build with flexibility in its core, so you can just disable plugins like `removeUnknownsAndDefaults` or its params like `defaultAttrs`.

**Comment by PeterTheOne** [comment]
@GreLI Yes, IE is outdated but some clients/users still ask for support :( Thanks for the hint about `removeUnknownsAndDefaults`!
