### ISSUE TITLE
Any way to parse a folder recursively with output?

### ISSUE THREAD

**Issue by JackNUMBER** [svg/svgo#819]
Trying optimize a multiple files in multiple sub-folders and want to keep them unchanged so I set a destination folder. But it did not success to. 
I tried different position for the `-r` argument, I tried to with the `*` but the folders organisations is killed.
```
$ svgo -f source/folder -r -o output/folder --config=svgo-config.yml

Processing directory 'source/folder':
Error: No SVG files have been found in 'source/folder' directory.
    at processDirectory (/usr/lib/node_modules/svgo/lib/svgo/coa.js:375:24)
    at readdir.then.files (/usr/lib/node_modules/svgo/lib/svgo/coa.js:359:39)
```
How to use output and recursive arguments together?

**Comment by GreLI** [comment]
Actually, there is no “recursive” option currently. There was a PR, but it was lost in further changes.

**Comment by mellenbe** [comment]
See issue #690 and PR #861
