### ISSUE TITLE
Arc segment is parsed incorrectly

### ISSUE THREAD

**Issue by subzey** [svg/svgo#822]
According to the [spec](https://www.w3.org/TR/SVG/paths.html#PathDataBNF), arc segments features flags: a fixed value `0` or `1`. These flags are currently parsed as a number by svgo. This approach is more forgiving, but it's also a reason svg can be parsed incorrectly.

For example, an arc `a1 1 0 001 1`:

|      | Rx | Ry | rot | large arc | sweep | x | y |
|------|----|----|-----|-----------|-------|---|---|
| Spec |`1` |`1` | `0` | `0`       | `0`   |`1`|`1`|
| svgo |`1` |`1` | `0` | `001`     | `1`   |   |   |

As a result, svgs with `comma-wsp?` omitted after any of the flags makes svgo crash or produce incorrect results. This file is displayed correctly in all browsers and IE11+, but is broken after svgo 1.0.1.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 7 7">
  <path d="
    m 0 0
    a 1 1 0 001 1
      1 1 0 001 1
      1 1 0 001 1
      1 1 0 001 1
      1 1 0 001 1
      1 1 0 001 1
      1 1 0 001 1
  "/>
</svg>
```

**Comment by GreLI** [comment]
Thanks, that's interesting!

**Comment by ydaniv** [comment]
@GreLI this is failing a lot of valid content, e.g:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Twitter" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%"
fill="#1da1f3"/><path fill="#fff" d="M437 152a72 72 0 0 1-40 12 72 72 0 0 0 32-40 72 72 0 0 1-45 17 72 72 0 0 0-122 65 200 200 0 0 1-145-74 72 72 0 0 0 22 94 72 72 0 0 1-32-7 72 72 0 0 0 56 69 72 72 0 0 1-32 1 72 72 0 0 0 67 50 200 200 0 0 1-105 29 200 200 0 0 0 309-179 200 200 0 0 0 35-37"/></svg>
```

Any chance of getting it fixed?
