### ISSUE TITLE
removeTitle and other "disabled by default" plugins no longer disabled by default

### ISSUE THREAD

**Issue by povrazor** [svg/svgo#826]
Despite what https://github.com/svg/svgo/blob/master/README.md says, the removeTitle plugin is now enabled by default. This broke my toolchain. I've only noticed the change since `1.0.1`.

If I explicitly disable it with `--disable=removeTitle`, it works again as expected and described.

**Comment by povrazor** [comment]
Ah, looks like it's a lot more than `removeTitle` that got enabled by default. `removeViewBox` and possibly `removeDimensions` also got enabled.

If this is the new behaviour as of 1.0 that's fine, but the README.md should be updated accordingly.

**Comment by andrewmee** [comment]
I've just found the same thing has broken images in my project too (due to incorrectly starting to remove viewbox attributes with the new version).  As @povrazor said, they can be re-disabled to fix it, but would be good to either disable those again by default or update the release notes and readme to reflect this change.

**Comment by andrewmee** [comment]
FWIW it looks like this was a deliberate change, but perhaps one that was forgotten when writing up the release notes/updating the readme; https://github.com/svg/svgo/commit/055e303607d53a3d539761d8727d86c03b2e88c1

**Comment by GreLI** [comment]
Yep, forgot to update docs. It's intentional.

**Comment by GreLI** [comment]
Done in f03d83283813fdf9300d636a5ba240e0b1243573.

**Comment by GreLI** [comment]
v1.0.2 with the fix has been just released.

**Comment by povrazor** [comment]
Can we get a bit more warning next time? Say mark any "disabled by default" items that will be "switching soon" to enabled with an asterisk? Like I imagine there was a plan somewhere that documented this change before it happened. Would have saved some time to find that.
