### ISSUE TITLE
Update readme (which incorrectly references nonexistent transformsWithOnePath plugin)

### ISSUE THREAD

**Issue by alexjlockwood** [svg/svgo#827]

**Comment by GreLI** [comment]
Was it supposed to be a PR?

**Comment by GreLI** [comment]
Done in f03d83283813fdf9300d636a5ba240e0b1243573.

**Comment by GreLI** [comment]
v1.0.2 with the fix has been just released.

**Comment by meteorplus** [comment]
please accept this fix because it is throwing an error in 2018
https://github.com/svg/svgo/pull/980
thank you
