### ISSUE TITLE
Loss of precision in matrix values

### ISSUE THREAD

**Issue by chamkank** [svg/svgo#833]
There's a loss of precision that causes the right side of the svg to not show up after using svgo.

Original: https://pastebin.com/raw/synaGP4Z
Compressed with svgo: https://pastebin.com/raw/2MLGszMv

The issue happens here:
`transform="matrix(0.000397456 0 0 0.00062034 0 -0.000614588)`

That attribute becomes compressed to this:
`transform="matrix(.0004 0 0 .00062 0 0)"`

Which causes a noticeable part of the svg to be missing when compressed.

**Comment by GreLI** [comment]
SVGO rounds numbers, so that's normal behavior. You may disable `convertTransform`, tune `transformPrecision` or increase general precision with `--precision` option. By default `transformPrecision` value is two orders higher.

**Comment by chamkank** [comment]
Thanks for the quick response, `svgo disable=convertTransform` seems to work great.
