### ISSUE TITLE
addClassesToSVGElement not working as node module

### ISSUE THREAD

**Issue by ZebraFlesh** [svg/svgo#835]
I upgraded from 0.7.2 to 1.0.3 and found that `addClassesToSVGElement` is no longer applying a class name to any input files, but only when used as an npm module.

This node config fails in 1.0.3, but works in 0.7.2:
```
config.plugins.push({
  addClassesToSVGElement: { className: 'foo' }
});
```

But a similar config works from the 1.0.3 command line:
```
plugins:
- addClassesToSVGElement:
    className: "foo"
```

Not sure why this is failing after upgrade.

Environment:
OS: Windows 10
Node: 6.9.1

**Comment by candidodmv** [comment]
I'm with the same problem.

**Comment by oliverviljamaa** [comment]
I'm also experiencing the same issue.

**Comment by oliverviljamaa** [comment]
```js
{ sortAttrs: true }
```
seems to be the culprit.

seems to be t

**Comment by candidodmv** [comment]
Thanks @oliverviljamaa, this is really the source of this issue. Answering your question, I think this interference sortAttrs in other plugin is not intentionally, but we will need a answering of the maintainers
