### ISSUE TITLE
Add support of `--` (pass multiple files from `lint-staged`)

### ISSUE THREAD

**Issue by vrizo** [svg/svgo#840]
Hi, @GreLI!

Thanks for `svgo` — an excellent project which I regularly use in my work!

Problem description:
`lint-staged` is a very popular tool which runs commands (commonly linters) before committing the changes. It is included in `create-react-app` by default. It works perfectly with `stylelint`, `eslint`, etc., and I would like to add `svgo` to compress all SVG files before pushing to a repository. Unfortunately, `svgo` supports multiple files as input in `*.svg` format only, but doesn't support popular `--` operator. There is no need to compress each SVG file in a project all the time, that's why I'm using `lint-staged` to compress only new and modified SVGs.

Relevant config:

```javascript
  "pre-commit": [
    "lint-staged"
  ],
  "lint-staged": {
    "*.svg": [
      "svgo",
      "git add"
    ]
  },
```

What is expected to happen:
`lint-staged` passes all the commited `svg` files to `svgo` by using the following format:

```bash
svgo -- file1.svg file2.svg file2.svg
```

What happened:
In case of 2 or more files to be committed, `svgo` returns an error, because it doesn't support `--` operator.

```bash
✖ svgo found some errors. Please fix them and try committing again.

Unknown argument: /path/to/file1.svg
```

Please add support of multiple files after `--` operator.

Thanks!

**Comment by ai** [comment]
@GreLI +1 =^_^=

**Comment by gvincentlh** [comment]
Bump. We'd really like this feature as well.

**Comment by vrizo** [comment]
Hi, @GreLI! Just noticed that multiple files processing works perfectly now with `--`. All committed files are compressed automatically. I think we can close the issue. Thanks a lot!

**Comment by GreLI** [comment]
Ok. Glad for you!
