### ISSUE TITLE
disabling cleanupIDs won't merge transform with paths

### ISSUE THREAD

**Issue by macrozone** [svg/svgo#843]
svgo can flatten groups and apply the group transform to the paths itself, which is very handy. 

But if you pass `--disable cleanupIDs` this does not work anymore.

Reproduction:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns="http://www.w3.org/2000/svg"
   width="2245.04"
   height="1587.4012"
   viewBox="0 0 2245.04 1587.4012"
   >
   <g id="groupId"
     transform="matrix(1.3333333,0,0,-1.3333333,0,1587.4013)">
     <path
       d="m 134.3765,904.815 h 4.5485 v 4.5474 h 86.21475 v -84.747 H 134.3765 Z"
       id="myPathId"
    />
</g>
</svg>
```

optimizing this with `--enable cleanupIDs` will result in:

```
<svg xmlns="http://www.w3.org/2000/svg" width="2245.04" height="1587.401"><path d="M179.169 380.981h6.064v-6.063h114.953v112.996H179.17z"/></svg>
```

nice!

But using `--disable cleanupIDs` will return:

```
<svg xmlns="http://www.w3.org/2000/svg" width="2245.04" height="1587.401"><g id="groupId" transform="matrix(1.33333 0 0 -1.33333 0 1587.401)"><path d="M134.376 904.815h4.549v4.547h86.215v-84.747h-90.763z" id="myPathId"/></g></svg>
```
 :-(

This is either a regression or was done to fix a bug, because if you use the same svg in [svgom](https://jakearchibald.github.io/svgomg/) which uses an older version of svgo, the transform is applied in both cases.

EDIT: This doesn't happen, if neither the group `<g>` nor the `<path>` contains an id. If any of the two contains an id, the bug happens.

**Comment by GreLI** [comment]
It because of path having ID—it can be referenced by ID from elsewhere and with applied transformation, it will be a wrong figure (issue #532). However, that change happened a year and half ago.

**Comment by macrozone** [comment]
@GreLI thx, that makes sense. However its somewhat unexpected by just looking at the option.

I worked around it in my special case by renaming the ids to a custom attribute first and then applying svgo.
