### ISSUE TITLE
image broken after svgo run

### ISSUE THREAD

**Issue by staabm** [svg/svgo#845]
svgo broke a image. FF, Edge and Chrome do not render it anymore.
anything we/I could do about that?

thx in advance!

[sticky.svg.txt](https://github.com/svg/svgo/files/1490982/sticky.svg.txt)
(file uploaded as txt, as github does not support svg. just rename it back...)

windows10x64

svgo --version
1.0.3
node --version
v8.2.1
npm --version
5.5.1

**Comment by GreLI** [comment]
That was an interesting one. Seems like, it's a bad idea to remove `<g>` which is direct child of `<switch>`.

**Comment by staabm** [comment]
Thx for the fast fix!

**Comment by staabm** [comment]
any ETA on releasing a new version including this fix?

**Comment by GreLI** [comment]
Not yet, but I think in a few days.

**Comment by staabm** [comment]
friendly ping... any chanche to get a new release?

**Comment by GreLI** [comment]
Oh, sorry. Forgot about that completely. I've just released v1.0.4 with the fix.
