### ISSUE TITLE
Possible copy/paste bug (or something) in _path.js?

### ISSUE THREAD

**Issue by alexjlockwood** [svg/svgo#847]
Take a look at this line: https://github.com/svg/svgo/blob/4495a34f55560b2bc05cf837ba9dd01ca20cd479/plugins/_path.js#L755

and this line: https://github.com/svg/svgo/blob/4495a34f55560b2bc05cf837ba9dd01ca20cd479/plugins/_path.js#L769

I don't understand this logic... will either of these two if statements ever be true? Should it be using `||` instead of `&&` or something?

**Comment by GreLI** [comment]
Should be `||` of course.

**Comment by alexjlockwood** [comment]
I created a pull request here: #850
