### ISSUE TITLE
Confusion about a couple JsApi methods/documentation

### ISSUE THREAD

**Issue by alexjlockwood** [svg/svgo#851]
I have been analyzing the way svgo works for the past few days... and I have noticed some inconsistencies with the documentation for a few methods.

I want to clarify how each method is intended to behave before I submit a pull request to update the documentation.

## Question 1

The `hasAttr` method takes a string as its first argument:  https://github.com/svg/svgo/blob/ceccf1ffdcdcba0f422a49685c2f60520579e46a/lib/svgo/jsAPI.js#L134-L152

However, the `removeAttr` method calls `hasAttr` and in some cases passes an array as its first argument: https://github.com/svg/svgo/blob/ceccf1ffdcdcba0f422a49685c2f60520579e46a/lib/svgo/jsAPI.js#L235-L258

So my question is which of the two methods should be updated? Should the `hasAttr` documentation be updated, saying that it can take an array as an argument as well? Or should the `removeAttr` method be updated so that it never passes an array to the `hasAttr` method?

## Question 2

The documentation for the `computedAttr` method says that it should return an object or undefined, which makes sense: https://github.com/svg/svgo/blob/ceccf1ffdcdcba0f422a49685c2f60520579e46a/lib/svgo/jsAPI.js#L215-L233

However, as you can see on line 128, it is possible for the method to `return elem.hasAttr(name, val)`, which is a boolean: https://github.com/svg/svgo/blob/ceccf1ffdcdcba0f422a49685c2f60520579e46a/lib/svgo/jsAPI.js#L228

Should the documentation be updated to indicate that a boolean value can be returned as well? Or should the method be updated so that it is not possible for a boolean value to be returned?

**Comment by GreLI** [comment]
`hasAttr` is just a method to check for a certain attribute. `removeAttr` was introduces for [convertShapeToPath](https://github.com/svg/svgo/blob/1a3c32bb43f5382cb15148dc3b4e94ecb57938dc/plugins/convertShapeToPath.js#L65), and it's just a convenient way to remove a bunch of attributes in one line. Second parameter was added just for the sake of completeness. I don't think it's much use for an array in `hasAttr`.

`computedAttr ` is used to check for an attribute existence or a certain value, so boolean is a valid response, need to update the description.

**Comment by alexjlockwood** [comment]
So to clarify, should it be possible to pass an array to `hasAttr`? Because currently it is possible for an array to be passed as an argument.

**Comment by GreLI** [comment]
I don't think it worth it. Just can't think even a case where it could be useful. Unlike `removeAttr`, where removing a bunch of attrs is one of the primal cases.

What do you mean by “it's possible for an array to be passed”?

**Comment by alexjlockwood** [comment]
Right now if you call `removeAttr(name)` (where `name` is an array of attr names), the method will end up calling `this.hasAttr(name)` on line 248, right?

**Comment by GreLI** [comment]
Ah, yeah, it should have return earlier.

**Comment by alexjlockwood** [comment]
OK, great... that is kinda what I thought but wasn't sure. :)

I'll file a pull request to fix that.

**Comment by alexjlockwood** [comment]
Actually wait... I have one more question...

On line 246 you call `name.forEach(this.removeAttr, this)`: https://github.com/svg/svgo/blob/ceccf1ffdcdcba0f422a49685c2f60520579e46a/lib/svgo/jsAPI.js#L246

According to the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) for `Array#forEach`, it takes a `function callback(currentValue, index, array)` as its first argument.

On line 246, you pass `this.removeAttr`, which doesn't seem right (because the second argument for `this.removeAttr` is a string, but the second argument for the callback passed to `Array#forEach` is an index number.

Is this also a mistake?

**Comment by GreLI** [comment]
Yep, that's why on line 250 it checks for the 3rd parameter `recursive`—it would be an array in case of `forEach`.

**Comment by alexjlockwood** [comment]
OK, thanks.

I created a pull request here with what I assume should be the fix... LMK if I should change anything though: https://github.com/svg/svgo/pull/855
