### ISSUE TITLE
collapseGroups moves a group's non inheritable attrs to its children items

### ISSUE THREAD

**Issue by alexjlockwood** [svg/svgo#858]
Consider the following svgo test (called `collapseGroups.15.svg`):

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
    <g vector-effect="non-scaling-stroke">
        <path transform="translate(250, 250) scale(1.5, 1.5) translate(-250, -250)" fill="#7ED321" stroke="#000" stroke-width="15" d="M125 125h250v250h-250v-250z"/>
    </g>
</svg>

@@@

<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
    <path transform="translate(250, 250) scale(1.5, 1.5) translate(-250, -250)" fill="#7ED321" stroke="#000" stroke-width="15" d="M125 125h250v250h-250v-250z" vector-effect="non-scaling-stroke"/>
</svg>
```

The first SVG looks like this:

![screen shot 2017-11-26 at 11 08 51 am](https://user-images.githubusercontent.com/1380747/33243392-677bd082-d29a-11e7-8e3e-f8cff96c0bed.png)

The second SVG looks like this:

![screen shot 2017-11-26 at 11 08 56 am](https://user-images.githubusercontent.com/1380747/33243388-5835806e-d29a-11e7-9f83-91b88333aa01.png)

**The test should fail**, since the SVGs don't look the same. However when you run `npm test`, the test succeeds.

The issue is that the `vector-effect="non-scaling-stroke"` attribute is being moved from the group to the path. This should not happen, since the attribute is not supposed to affect the group's children nodes ([link to spec](https://www.w3.org/TR/SVGTiny12/painting.html#NonScalingStroke)).

Please let me know if you think this issue is specific to the `vector-effect` attribute, or if there may be other non inheritable attributes that will have the same issue.

**Comment by GreLI** [comment]
Actually, problem here is not about inheritance. It's about a property that has no effect on `<g>` element. I've fixed `removeNonInheritableGroupAttrs` plugin in 36db31adcfb733f357dee2a882de16122c4aefe9 and a165206632d322cf0dd03ef1fc8c4fe3cd2e658f, so it will remove such attributes. Normally they should not be on `<g>`'s.
