### ISSUE TITLE
convertPathData removes path which is a single point

### ISSUE THREAD

**Issue by chrisjshull** [svg/svgo#863]
svgo v0.7.2

[WarningSolid.svg.zip](https://github.com/svg/svgo/files/1511957/WarningSolid.svg.zip)
`<path d="M1,1.5 L1,1.5" id="Line-Copy"></path>` gets removed.

**Comment by GreLI** [comment]
See [StackOverflow question](https://stackoverflow.com/questions/44674723/imagemin-svgo-delete-path/46225550#46225550), it's a zero-length path.

**Comment by chrisjshull** [comment]
@GreLI, that's unfortunate. "Just don't make your SVGs that way" isn't really an option for me - my team isn't the one making the images. And I'm not familiar with all the tools out there, which could output this way for whatever internal reason.
