### ISSUE TITLE
怎么能保留自定义属性?

### ISSUE THREAD

**Issue by yangdan8** [svg/svgo#864]

**Comment by Volker-E** [comment]
Translation seems to be “How can I keep custom properties?”

**Comment by GreLI** [comment]
Seems like so. Answering the question: `data-*` attributes are kept by default, others can be kept by disabling `removeUnknownsAndDefaults`:
```sh
svgo --disable=removeUnknownsAndDefaults
```

**Comment by lixue007** [comment]
If I want to change the prefix of cleanupIDs, how can i do? @GreLI
