### ISSUE TITLE
Round/rewrite path ruins file

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#866]
I am using
[https://jakearchibald.github.io/svgomg/](https://jakearchibald.github.io/svgomg/)
for this file:
[https://commons.wikimedia.org/wiki/File:Earth_energy_budget.svg](https://commons.wikimedia.org/wiki/File:Earth_energy_budget.svg)
Even with the highest precission "_Round/rewrite path_" (without "Multipass") ruins the file

The minimal working example is:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg version="1.1" viewBox="0 0 744 556" xmlns="http://www.w3.org/2000/svg">
 <path transform="matrix(2.28 0 0 -.97 566.9 890.1)" d="m176.9 336.2a274.9 226.5 0 0 1-262.1 155.9 274.9 226.5 0 0 1-260.9-157.3" fill="#decd87"/>
</svg>
```

**Comment by TrySound** [comment]
Looks like the issue is solved
