### ISSUE TITLE
Round/Rewrite Path ruins SVG

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#868]
The option "Round/rewrite path" removes some lines/curves, some lines/curves are completely different place.
In the Attachment is the SVG before and after.

[ChangeRoundRewritePath.zip](https://github.com/svg/svgo/files/1527902/ChangeRoundRewritePath.zip)

**Comment by tschoartschi** [comment]
I have the same problem. Let me know if you need more testing data to solve this issue

**Comment by TrySound** [comment]
Looks like the issue is solved
