### ISSUE TITLE
new plugin: merge multiple Paths into one

### ISSUE THREAD

**Issue by deepsweet** [svg/svgo#87]

**Comment by atwood-cai** [comment]
hi: do you implement it ?

**Comment by GreLI** [comment]
@atwood-cai, there is `mergePaths`, which merges adjacent paths with same attributes into one after checking for their possible intersection (by comparing convex hulls for performance reasons).

**Comment by atwood-cai** [comment]
bingo. @GreLI ,

**Comment by ganlanyuan** [comment]
Hi, is there a way to prevent this behavior?
I tried:
```javascript
{
  plugins: [{
    mergePaths: {
      collapseRepeated: false,
      leadingZero: false,
      negativeExtraSpace: false
    }
  }]
}
```
But it didn't work?

**Comment by ganlanyuan** [comment]
```javascript
{
  mergePaths: false
}
```
This works.
Thanks
