### ISSUE TITLE
Option to Remove Self-closing Tags

### ISSUE THREAD

**Issue by pcarper** [svg/svgo#870]
An option to remove self-closing tags would be a nice enhancement to support HTML 4/5 requirements. 

Example Before: `<path d="M0 0h24v24H0z" fill="none"/>`
Example After: `<path d="M0 0h24v24H0z" fill="none"></path>`

Currently, I'm using this regex `<\s*([^\s>]+)([^>]*)/\s*>` to match self-closing tags and replacing matching groups with `<$1$2></$1>`.

btw, SVGOMG is a game changer. Great work!

**Comment by madhaze** [comment]
Why was this closed.  For those that have to support IE11.  This is a continual warning.

**Comment by jakub-g** [comment]
The option is actually there, but not well documented:

```
{
    js2svg: { useShortTags: false },
}
```

(found in https://github.com/svg/svgo/issues/439#issuecomment-466545528)
