### ISSUE TITLE
removeStyleElement not properly removed

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#873]
Prozessing the file [https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS.svg](https://commons.wikimedia.org/wiki/File:Instrumental_Temperature_Record_GISS.svg)
with the option:
>$ svgo -i input.svg -o output.svg --enable=removeStyleElement

removes the blue markes of the line.

Here is a minimal working example:
[min.svg.txt](https://github.com/svg/svgo/files/1565019/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 480 384" xmlns="http://www.w3.org/2000/svg">
 <style id="style4" type="text/css">
  .annualTemp{fill:none;stroke:#333;stroke-width:.5;stroke-linecap:butt;stroke-linejoin:bevel;marker:url(#tempMarker)}
 </style>
 <marker id="tempMarker" markerHeight="4" markerWidth="4" refX="2" refY="2">
  <circle id="circle6" cx="2" cy="2" fill="#00f" r="1.5" stroke="#00f"/>
 </marker>
 <g class="annualTemp" fill="none" stroke="#333" stroke-linejoin="bevel" stroke-width=".5">
  <path class="annualTemp" d="M99 60h30M75 297l3-15 3 6 3 6 3 18h3l3-15 3 30 3-24 3-36 3 66 3-30 3 15 3-3 3 6 3-18 3-33 3-12 3 36 3-21 3-24 3 18 3 36 3 12 3 9 3-30 3-12 3 54 3-12 3 3 3-6h3l3 3 3-6 3-51 3-18 3 66 3 27 3-24 3-36 3-3 3-18 3 33 3-12 3 3 3-15 3-45 3 36 3-6 3 42 3-54 3-18 3 15 3 36 3-33 3 12 3-24 3-33 3-9 3 24 3-6 3-15 3 21 3-21 3-30 3 39 3 33 3-12 3 12 3 9 3 24 3-33 3-21 3-24 3 63h3l3 21 3-72 3-3 3 6 3 21 3-27 3 12 3-12 3 87 3-30 3-24 3-9 3 12 3-36 3 15 3 39 3-30 3-42 3 66 3-9 3 33 3-87 3 36 3-24 3-27 3-24 3 63 3-63 3 51 3 12 3-24 3-39 3-15 3 33 3-54 3 9 3 66 3-3 3-27 3-45 3 27 3-33 3-48 3 72 3-3 3-45 3-24 3 3 3 18 3-42 3 27 3-9 3 42 3-42" stroke-width="1.5"/>
 </g>
</svg>
```

and svgcleaner removes `marker`  but it was still defined in `<style>` and is needed in `<path>`.

Similar problems in other SVGoptimisers:
https://github.com/scour-project/scour/issues/155 (scour you need the option `--keep-unreferenced-defs`:)
https://github.com/RazrFalcon/svgcleaner/issues/112

**Comment by TrySound** [comment]
removeStyleElement plugin does not have any safety checks. It just roughly drops style element. I consider to remove it in v3 as not very useful.
