### ISSUE TITLE
Plugin for StrokeToPath / StrokeToFill

### ISSUE THREAD

**Issue by denniske** [svg/svgo#874]
Is there a plugin for svgo that can do "StrokeToPath" from inkscape?

I want to convert a path with "stroke" like this:
`<path d="..." stroke="#000" stroke-width="1" fill="none"/> `

To a path with "fill":
`<path d="..." fill="#000"/>`

The svg should look the same as before the transformation.

Inkscape command that I want to reproduce:
```
inkscape $1 \
--verb=EditSelectAll \
--verb=SelectionUnGroup \
--verb=StrokeToPath \
--verb=FileSave \
--verb=FileQuit
```

This is commonly needed for svg font generation:
https://icomoon.io/#docs/stroke-to-fill

For example here:
https://github.com/nfroidure/svgicons2svgfont/issues/60

**Comment by GreLI** [comment]
No, it's actually quite a complicated task with many pitfalls and it's more about image editing than optimizing.

**Comment by denniske** [comment]
Thanks for the fast answer. I will take a look at some other libraries for this purpose.

**Comment by songhyeonYu** [comment]
custom pulgin
`
      {
        name: 'convertStrokeToFill',
        fn: () => {
          return {
            element: {
              enter(node) {
                if (node.name === 'path' && node.attributes['stroke']) {
                  node.attributes['fill'] = node.attributes['stroke'];
                }
              },
            },
          };
        },
      },
`

**Comment by giorgiabosello** [comment]
> custom pulgin `{ name: 'convertStrokeToFill', fn: () => { return { element: { enter(node) { if (node.name === 'path' && node.attributes['stroke']) { node.attributes['fill'] = node.attributes['stroke']; } }, }, }; }, },`

@songhyeonyu-onepredict how to pass it?

**Comment by elrumordelaluz** [comment]
> > custom pulgin `{ name: 'convertStrokeToFill', fn: () => { return { element: { enter(node) { if (node.name === 'path' && node.attributes['stroke']) { node.attributes['fill'] = node.attributes['stroke']; } }, }, }; }, },`
> 
> @songhyeonyu-onepredict how to pass it?

you have to pass into `svgo.config.mjs` something like:

```js
import { strokeToPathPlugin } from "./stroke-to-path-plugin.mjs";

export default {
  plugins: [
    strokeToPathPlugin,
    {
      name: "preset-default",
      params: {
        overrides: {
         // ...
        },
      },
    },
  ],
};
```

or in case you are using the API, loading the config file like:

```js
import { loadConfig, optimize } from "svgo";
const config = await loadConfig();
const result = optimize('<svg>...',config);
```

In any case, I think the `stroke-to-path` doesn't work as expected every time, using this approach (moving `stroke` value into `fill`).

**Comment by ProCode-Software** [comment]
The `svg-outline-stroke` has vulnerabilities

**Comment by elrumordelaluz** [comment]
> The `svg-outline-stroke` has vulnerabilities

can you please share more info? thanks!

**Comment by ProCode-Software** [comment]
It's depending on vulnerable versions of sharp and phin
![Screenshot_20240923_174303_Brave.jpg](https://github.com/user-attachments/assets/d189ec4e-43f7-40dd-8a18-21d139426a8a)

**Comment by KTibow** [comment]
`svg-outline-stroke` is also a dumb approach (it turns it into an image and back again)
