### ISSUE TITLE
xml:space='preserve' ignored, textaligment/number of spaces wrong

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#878]
Processiong following file: [https://commons.wikimedia.org/wiki/File:SVG_1.1_W3C_test_text-ws-02-t_NoLineBreak.svg](https://commons.wikimedia.org/wiki/File:SVG_1.1_W3C_test_text-ws-02-t_NoLineBreak.svg)
>$ svgo -i [SVG_1.1_W3C_test_text-ws-02-t_NoLineBreak.svg](https://upload.wikimedia.org/wikipedia/commons/5/5b/SVG_1.1_W3C_test_text-ws-02-t_NoLineBreak.svg) -o output.svg

leads to wrong spaces.

Mimimal working example:
[min.svg.txt](https://github.com/svg/svgo/files/1586236/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 480 360" xmlns="http://www.w3.org/2000/svg">
 <g font-family="sans-serif" font-size="40">
  <text x="15" y="105" fill="#00f" xml:space="preserve"> WS   with  indented lines.     </text>
  <text x="15" y="140" xml:space="preserve"> WS   with  indented lines.</text>
  <text x="15" y="225" fill="#00f" xml:space="preserve">WS non-indented lines.       </text>
  <text x="15" y="260">WS non-indented lines.</text>
 </g>
</svg>
```
> $ svgo -i min.svg -o output.svg --disable=addAttributesToSVGElement --disable=addClassesToSVGElement --disable=cleanupAttrs --disable=cleanupEnableBackground --disable=cleanupIDs --disable=cleanupListOfValues --disable=cleanupNumericValues --disable=collapseGroups --disable=convertColors --disable=convertPathData --disable=convertShapeToPath --disable=convertStyleToAttrs --disable=convertTransform --disable=inlineStyles --disable=mergePaths --disable=minifyStyles --disable=moveElemsAttrsToGroup --disable=moveGroupAttrsToElems --disable=prefixIds --disable=removeAttrs --disable=removeComments --disable=removeDesc --disable=removeDimensions --disable=removeDoctype --disable=removeEditorsNSData --disable=removeElementsByAttr --disable=removeEmptyAttrs --disable=removeEmptyContainers --disable=removeEmptyText --disable=removeHiddenElems --disable=removeMetadata --disable=removeNonInheritableGroupAttrs --disable=removeRasterImages --disable=removeScriptElement --disable=removeStyleElement --disable=removeTitle --disable=removeUnknownsAndDefaults --disable=removeUnusedNS --disable=removeUselessDefs --disable=removeUselessStrokeAndFill --disable=removeViewBox --disable=removeXMLNS --disable=removeXMLProcInst --disable=sortAttrs --pretty --indent=1

output:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg viewBox="0 0 480 360" xmlns="http://www.w3.org/2000/svg">
 <g font-family="sans-serif" font-size="40">
  <text x="15" y="105" fill="#00f" xml:space="preserve">
   WS with indented lines.
  </text>
  <text x="15" y="140" xml:space="preserve">
   WS with indented lines.
  </text>
  <text x="15" y="225" fill="#00f" xml:space="preserve">
   WS non-indented lines.
  </text>
  <text x="15" y="260">
   WS non-indented lines.
  </text>
 </g>
</svg>
```

**Comment by JoKalliauer** [comment]
Same with: [https://commons.wikimedia.org/wiki/File:Alloy_cooling_curves_mixed_crystals-2.svg](https://commons.wikimedia.org/wiki/File:Alloy_cooling_curves_mixed_crystals-2.svg)

```svg
 <text font-family="Arabic Typesetting" font-size="36" xml:space="preserve">
  <tspan x="54.8053" y="27.2658">2        3           4              5             6</tspan>
 </text>
```

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/releases/tag/v2.1.0
