### ISSUE TITLE
Error in parsing SVG: Unexpected end

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#879]
Processing file: [https://commons.wikimedia.org/wiki/File:Tsumeshogi-classic.svg](https://commons.wikimedia.org/wiki/File:Tsumeshogi-classic.svg) with
> svgo -i [Tsumeshogi-classic.svg](https://upload.wikimedia.org/wikipedia/commons/7/73/Tsumeshogi-classic.svg) -o output.svg

lead to an error:
`Error in parsing SVG: Unexpected end`

minimal working example (W3C-Valid file):
[min.svg.txt](https://github.com/svg/svgo/files/1587408/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"
  [
  <!-- Set the characters used for pieces here.
   The use of entities is the reason why the doctype is included,
   even though it's known to cause some problems. -->
]>

<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     version="1.1"
     width="226px" height="201px">
<text x="5" y="2">9</text>
</svg>

```

I think svgo has a prpblem with the comment in the doctype.

**Comment by GreLI** [comment]
Yep, SVGO is based on [SAX parser](https://github.com/isaacs/sax-js) which has such issues.

**Comment by strarsis** [comment]
PR for replacing sax with saxes: https://github.com/svg/svgo/pull/1281

**Comment by XhmikosR** [comment]
@TrySound this doesn't throw any error but results in an empty file with v2.1.0:

```
C:\Users\xmr\Desktop>svgo 1.svg --pretty -o 2.svg

1.svg:
Done in 5 ms!
0.492 KiB - 100% = 0 KiB
```

Shouldn't it throw an error if it has trouble parsing it?

**Comment by TrySound** [comment]
I will fix parsing soon
