### ISSUE TITLE
insufficient documentation

### ISSUE THREAD

**Issue by candidodmv** [svg/svgo#881]
Hi, I'm trying to use plugins but don't found documentation of how to do, also how to install. please could help me?

Thanks.

**Comment by Volker-E** [comment]
@candidodmv Plugins are all installed by default. Most of them are enabled per default. Updating the overview table in README.md would seem to make sense. Besides @GreLI there doesn't seem to be other maintainers working on svgo currently though.

**Comment by candidodmv** [comment]
@Volker-E thanks for answer, I was able to make use plugins.
