### ISSUE TITLE
Using the default settings for compression results in a noticeable change to the image.

### ISSUE THREAD

**Issue by eperret** [svg/svgo#883]
I ran the following svg file through the optimizer with the default setting and it removed the trunk from the 2 trees in the image.  Something needs to be fixed so that it doe does not make this noticeable of a change.
[noEvents.svg.zip](https://github.com/svg/svgo/files/1594012/noEvents.svg.zip)

As far as I can tell it is an issue with this plugin, https://github.com/svg/svgo/blob/master/plugins/convertPathData.js  When I set the "straightCurves" param to false, the resulting image looks correct.

**Comment by XhmikosR** [comment]
@TrySound I can't reproduce with 2.1.0, can you confirm?

**Comment by TrySound** [comment]
Yes, works in v2
