### ISSUE TITLE
Add optimization levels

### ISSUE THREAD

**Issue by szepeviktor** [svg/svgo#885]
Please consider providing optimization levels thus bundle of plugins.

Thank you.

**Comment by szepeviktor** [comment]
Or all plugins are enabled by default?

Readme does not reveal that.

**Comment by szepeviktor** [comment]
I think they are: https://github.com/svg/svgo/blob/91d98106d4c75a947301e152ad97dc947990e9e2/.svgo.yml

Please consider mentioning it in the readme: _All plugins are enabled by default_

**Comment by Volker-E** [comment]
@szepeviktor Most, but not all plugins are enabled by default. You can find out by looking at the source code of [each of the plugins](https://github.com/svg/svgo/tree/master/plugins) and look for `exports.active =` `true` (enabled) or `false` (disabled). 
A safe list of (default) plugins can be found at https://www.mediawiki.org/wiki/Manual:Coding_conventions/SVG

**Comment by szepeviktor** [comment]
@Volker-E Thank you.

Could you update the README with the list of enabled plugins? Or with the way described above?

**Comment by szepeviktor** [comment]
```js
$ grep -F -l 'exports.active = true;' * | sed -e 's/\.js//'
cleanupAttrs
cleanupEnableBackground
cleanupIDs
cleanupNumericValues
collapseGroups
convertColors
convertPathData
convertShapeToPath
convertStyleToAttrs
convertTransform
inlineStyles
mergePaths
minifyStyles
moveElemsAttrsToGroup
moveGroupAttrsToElems
removeComments
removeDesc
removeDoctype
removeEditorsNSData
removeEmptyAttrs
removeEmptyContainers
removeEmptyText
removeHiddenElems
removeMetadata
removeNonInheritableGroupAttrs
removeTitle
removeUnknownsAndDefaults
removeUnusedNS
removeUselessDefs
removeUselessStrokeAndFill
removeViewBox
removeXMLProcInst
```
