### ISSUE TITLE
Malformed SVG when displaying in Inkscape

### ISSUE THREAD

**Issue by iampeter** [svg/svgo#887]
I am running svgo v1.0.3 over this file:
https://gist.github.com/iampeter/6aaa951a1b20499e827f16a09877bf95

When opening in Inkscape afterwards, it looks like this:
![r1](https://user-images.githubusercontent.com/713801/34518276-057b6bec-f07f-11e7-8234-3c042f0cab92.png)

The original looks good:
![r2](https://user-images.githubusercontent.com/713801/34518277-0596547a-f07f-11e7-8126-f3dff35eb002.png)

**Comment by iampeter** [comment]
I believe the `convertPathData` plugin could be responsible.

**Comment by steveoriol** [comment]
I have the same issue with svgo v1.1.1

**Comment by XhmikosR** [comment]
@iampeter can you try with v2.1.0?

**Comment by TrySound** [comment]
Eva is alive in the last v1 and v2. Thanks!
