### ISSUE TITLE
addAttributesToSVGElement and aria-hidden

### ISSUE THREAD

**Issue by theamnesic** [svg/svgo#892]
Hi! 

When I use addAttributesToSVGElement with `aria-hidden` attribute, the attribute is duplicated.
But only with `aria-hidden` ...

Example : 

```javascript
addAttributesToSVGElement: { attribute: 'aria-hidden="true"' }
```
```html
<svg width="20" height="20" viewBox="0 0 20 20" aria-hidden="true" aria-hidden="true">
```

Tested with an other valid attribute :

```javascript
addAttributesToSVGElement: { attribute: 'role="navigation"' }
```
```html
<svg width="20" height="20" viewBox="0 0 20 20" role="navigation">
```

Or whatever :

```javascript
addAttributesToSVGElement: { attribute: 'phil-collins="true"' }
```
```html
<svg width="20" height="20" viewBox="0 0 20 20" phil-collins="true">
```

Any idea ?

Thanks !

**Comment by samikeijonen** [comment]
I was wondering the same thing. Anything we can do to help this get sorted?

**Comment by kylemh** [comment]
```
{
      addAttributesToSVGElement: {
        attributes: [
          'fill="currentColor"', // if fill is already defined, it won't be overridden
          'aria-hidden="true"', // SVG icons should simply be decorative
        ],
      },
    }```

yields me dupes for each in my bundle:
```
function _extends$b() { _extends$b = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends$b.apply(this, arguments); }
var ChevronRightSvg = (({
  styles = {},
  ...props
}) => React.createElement("svg", _extends$b({
  xmlns: "http://www.w3.org/2000/svg",
  fill: "currentColor",
  "aria-hidden": "true",
  className: (styles["icon"] || "icon") + " " + (styles["chevron-right"] || "chevron-right"),
  viewBox: "0 0 185.4 300",
  fill: "currentColor",
  "aria-hidden": "true"
}, props), React.createElement("path", {
  d: "M7.3 292.7c-9.8-9.8-9.8-25.6 0-35.4L114.6 150 7.3 42.7c-9.8-9.8-9.8-25.6 0-35.4s25.6-9.8 35.4 0L185.4 150 42.7 292.7c-4.9 4.8-11.3 7.3-17.7 7.3-6.4 0-12.7-2.5-17.7-7.3z"
})));

var ChevronRight = withIconProps(ChevronRightSvg);
ChevronRight.displayName = 'ChevronRight';
```

**Comment by kylemh** [comment]
Changed my config to this:

```
{
      "addAttributesToSVGElement": {
        "attributes": [{ "fill-rule": "currentColor" }, { "aria-hidden": "true" }]
      }
    }
```

and was able to include `aria-hidden` w/o dupes 💃

**Comment by XhmikosR** [comment]
`attributes` needs to be an array, not sure if it's/or if it can be documented, though @TrySound

**Comment by TrySound** [comment]
Agree, plugins docs are very poor now.

**Comment by TrySound** [comment]
Btw the link in docs refers to source code which has pretty clear example. Closing this issue as the plugin will be removed anyway in v3 in favour of custom plugins.
https://github.com/svg/svgo/blob/master/plugins/addAttributesToSVGElement.js#L30-L45

**Comment by thanabal13** [comment]
When I use addAttributesToSVGElement with fill: 'currentColor' attribute throws error (node:7496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isElem' of undefined
    at Object.exports.fn (/Users/thanabal-11026/Home/web/workspace/zohoshifts/jsapps/client/node_modules/broccoli-svg-optimizer/node_modules/svgo/plugins/addAttributesToSVGElement.js:55:13)
my configuration :
sourceDirs: ['app/styles/svgs'],
      optimizer: {
        plugins: [
          {
            'addAttributesToSVGElement': {
              attributes: [
                {
                  fill: 'currentColor'
                }
              ]
            }
          }
        ]
      }
