### ISSUE TITLE
Update README in npm package

### ISSUE THREAD

**Issue by strarsis** [svg/svgo#893]
In npm the README doesn't seem to be up to date, new plugins like 
the inlineStyles and prefixIDs plugins are missing, see 
https://www.npmjs.com/package/svgo#what-it-can-do.

**Comment by Landerson352** [comment]
Yes please! Spent a couple hours this morning trying to figure out why my styles were getting inlined (and breaking the image).

**Comment by strarsis** [comment]
@Landerson352: Inlining the styles shouldn't break an (SVG) image. It would be great if you could open a new issue for this.
