### ISSUE TITLE
Inkscape plugin

### ISSUE THREAD

**Issue by konsumer** [svg/svgo#897]
Is there interest in an Inkscape plugin? If I make one, should I offer a PR (it's one file that defines the UI that you copy into your plugin directory) or should I make a seperate project? If you prefer a separate project, can I PR for a blurb in your README?

**Comment by konsumer** [comment]
I made [inkscape-svgo](https://github.com/konsumer/inkscape-svgo) which works ok, but I need to clean up the options (maybe separate tabs to "basics" and "advanced") and better handling of inputs and things.

I ended up needing to make a CLI wrapper because of how inkscape handles options.

<img width="555" alt="screen shot 2018-01-30 at 6 35 27 pm" src="https://user-images.githubusercontent.com/83857/35602410-01755a7a-05ed-11e8-8765-6d1029de3cc2.png">

**Comment by konsumer** [comment]
any suggestions are welcome.

**Comment by GreLI** [comment]
“inkscape-svgo” is totally fine. Despite plugins: many of them have options, however, I don't know whether they're needed in the context of Inkscape.

For UI I'd suggested a list of plugins (at left) with checkboxes and a details window (at right) when you select a plugin.

**Comment by konsumer** [comment]
Yeh, I dropped all the options that require input, and split it into to categories: "Optimization" & "Removal".

Unfortunately, [inkscape's parameter UI config](http://wiki.inkscape.org/wiki/index.php/INX_Parameters) is pretty limited. Each option goes on a line of it's own, and is totally non-dynamic, so while I completely agree an info panel would be better, it doesn't really do that. I could put named options with tooltips that give more detail, but since all the descriptions are pretty short, they seem to fit well enough, and since it's 1-line-per-option, it wouldn't really save any space on the dialog.

These are the options I left out:

```
inlineStyles
cleanupListOfValues
prefixIds
removeAttrs
addAttributesToSVGElement
addClassesToSVGElement
removeElementsByAttr
```

I may add them back, but since the UI is non-dynamic, having a checkbox that toggles `inlineStyles` (which needs further input) doesn't work, for example, so it seemed a little wonky (like I could check for an empty text-box, but this seems a bit confusing for the end-user.) I'm in total agreement that maybe all the options don't need to be in there, but since I'm not sure what to remove, I just tried to make sensible "make it smaller without breaking it" sort of defaults.


This is what I have, currently:
<img width="558" alt="screen1" src="https://user-images.githubusercontent.com/83857/35618582-44586830-0630-11e8-8fb3-d253727dff27.png">
<img width="558" alt="screen2" src="https://user-images.githubusercontent.com/83857/35618588-488d7a08-0630-11e8-878c-e858ade9d4c6.png">

**Comment by konsumer** [comment]
For illustration, here is the same dialog with shorter options (I couldn't get a tooltip in the screenshot, but all description are in tooltips.)

It's a little quicker to visually scan, but it looks a little unbalanced.

<img width="233" alt="short" src="https://user-images.githubusercontent.com/83857/35619878-25153ada-0634-11e8-9c4f-0649eda3feac.png">
