### ISSUE TITLE
Text consisting of multiple tspans inserts a space

### ISSUE THREAD

**Issue by MarkJeronimus** [svg/svgo#899]
For example: "<span style="color:#808080">4x</span>12" becomes "<span style="color:#808080">4x</span> 12".

In SVG:

`<text style="font-size:17.5px;text-anchor:middle" x="174.10229" y="-185.7213"><tspan x="174.10229" y="-185.7213"><tspan style="fill:#808080">4x</tspan>12</tspan></text>`

becomes:

`<text x="174.102" y="-185.721" font-size="17.5" text-anchor="middle"><tspan x="174.102" y="-185.721"><tspan fill="gray">5x</tspan> 4</tspan></text>`

**Comment by GreLI** [comment]
Cannot reproduce (svgo v1.0.4):
```
$ svgo -s '<text style="font-size:17.5px;text-anchor:middle" x="174.10229" y="-185.7213">
<tspan x="174.10229" y="-185.7213"><tspan style="fill:#808080">4x</tspan>12</tspan>
</text>'

<text x="174.102" y="-185.721" font-size="17.5" text-anchor="middle">
<tspan x="174.102" y="-185.721"><tspan fill="gray">4x</tspan>12</tspan>
</text>
```
(added line-breaks for readability).

**Comment by MarkJeronimus** [comment]
Ah, I did not notice the package ([inkscape-svg](https://github.com/juanfran/svgo-inkscape)) I use is 3 years old. This bug is invalid then.

Though I tried to overwrite the files in the package with this repository and the plugin stops working (no no exceptions). :(
