### ISSUE TITLE
Unclear documentation on `--enable` or `--disable` multiple plugins

### ISSUE THREAD

**Issue by Volker-E** [svg/svgo#900]
Currently (as of v1.0.4), svgo doesn't proceed enabling/disabling multiple plugins as in:
```lang=bash
svgo to_be_optimized.svg --disable='convertPathData,removeXMLProcInst,removeTitle,removeDesc,removeViewBox' --enable='sortAttrs' --pretty
```
It falls back to default plugins without feedback about ignoring options.

It is not clearly stated that this is the only way right now 
```lang=bash
svgo to_be_optimized.svg --disable='convertPathData' --disable='removeXMLProcInst' --disable='removeTitle' --disable='removeDesc' --disable='removeViewBox' --enable='sortAttrs' --pretty
```

**Comment by GreLI** [comment]
Standard bash-like way is using curlies:
```
svgo --disable={collapseGroups,removeEmptyContainers}
```
And PRs are welcome!

**Comment by jmwebservices** [comment]
I do not believe curly brace expansion works in Windows. It would be great if the --disable option could simply accept a comma list of plugins.

**Comment by jmwebservices** [comment]
My PR https://github.com/svg/svgo/pull/1019
