### ISSUE TITLE
Is it possible to ignore optimisation for contents of path d attribute?

### ISSUE THREAD

**Issue by joepagan** [svg/svgo#903]
Hi,

I know this goes against the point of optimisation, but, I would like to keep the formatting of the `path` element's `d` attribute the same.

I want to animate certain parts of an SVG using [animejs](https://github.com/juliangarnier/anime), though [it appears that the formatted data needs to stay somewhat uniformed](https://github.com/juliangarnier/anime/issues/256) so the points on the path can be manipulated.

I have tried to set the following plugins to false already though my path info is still being optimised:

```
{mergePaths: false},
{convertPathData: false}
```

As an example, My original svg path d attribute contains the following:
```
M 0 77.6 L 185.9 77.6 C 211.8 77.6 230.8 103.3 248.1 91 C 259.3 83.1 259.4 50.5 284 50.5 C 336.9 50.5 350.3 77.5 378.5 77.5 C 404 77.5 411.4 61.4 430 39.9 C 453.9 12.4 472.4 41.2 502.9 59.9 C 533.4 78.6 548 81 564 81 C 580.8 81 623.6 82.3 623.6 82.3
```

When run through svgo

```
M0 77.6h185.9c25.9 0 44.9 25.7 62.2 13.4 11.2-7.9 11.3-40.5 35.9-40.5 52.9 0 66.3 27 94.5 27 25.5 0 32.9-16.1 51.5-37.6 23.9-27.5 42.4 1.3 72.9 20C533.4 78.6 548 81 564 81c16.8 0 59.6 1.3 59.6 1.3
```

I presume this may not be possible, though thought I would ask.

**Comment by GreLI** [comment]
It looks like there is some error in your config. The path data left intact when I run
```
svgo --disable=convertPathData
```

**Comment by joepagan** [comment]
Interesting, ok thanks, maybe there was a caching issue, I'll have another go tomorrow!
