### ISSUE TITLE
Single file version to embed in any webpage

### ISSUE THREAD

**Issue by lucasa** [svg/svgo#910]
Hi

Is there a single file javascript version of svgo that can be simple embeded in any webpage?

Thanks,
Lucas

**Comment by GreLI** [comment]
Not a one I'm aware of. Also, SVGO is build with Node.js API in it's core (namely dynamic `require`), so it's somewhat hard to bring into browser. However, you may be interested in [SVGOMG](https://jakearchibald.github.io/svgomg/).

**Comment by jamesd8** [comment]
My company is also interested in a stand-alone version that can run in a browser without any external framework dependencies (except JQuery, for example). We would pay for this to be added as a release target for this project moving forward.

**Comment by TrySound** [comment]
Browser es module is landed in `svgo/dist/svgo.browser.js`
