### ISSUE TITLE
Does this work alone without NodeJS in Solaris

### ISSUE THREAD

**Issue by surighanta** [svg/svgo#911]
Hey,

I am new to this and wondered if this works in Solaris + Without NodeJS. I mean just like a C compiled binary.

We had problems in installing NodeJS itself so we look for something that can stand on its own.

Any help is appreciated.

Thanks in advance!
Suresh

**Comment by strarsis** [comment]
@surighanta: Something like this?: https://www.alexkras.com/compile-node-js-to-native-binaries/
