### ISSUE TITLE
Doesn't finish on this SVG

### ISSUE THREAD

**Issue by kasbah** [svg/svgo#912]
SVGO (1.0.4) never finishes on [this svg](https://cloud.monostable.co.uk/top.svg) when used from the commandline with default settings.

![](https://cloud.monostable.co.uk/top.svg)

**Comment by GreLI** [comment]
At first look it's because of `mergePaths` plugin and plenty of elements. Disable it and all is ok. I'm investigating on what happens there.

**Comment by TrySound** [comment]
It's finished now. Takes 5 min but works. Will think about performance.
