### ISSUE TITLE
Unexpected remove of fill="#000"

### ISSUE THREAD

**Issue by vithar** [svg/svgo#917]
I use CSS to set `fill` for this SVG:

```xml
<svg>
    <path d="M0 0h37v44H0V0zm25 0l12 12V0H25z"/>
    <path d="M37 12h-8a4 4 0 0 1-4-4V0l12 12z" fill="#000" opacity=".3"/>
</svg>
```

But SVGO incorrectly removes `fill="#000"` and it break things.

**Comment by GreLI** [comment]
`fill="#000"` is a default value, thus being removed by `removeUnknownsAndDefaults` plugin. Disable it, if it's not a desired effect.

**Comment by yisibl** [comment]
Does using this option disable other features? If you just need not to delete the default color, you want to provide a separate parameter or option to control the default color.
