### ISSUE TITLE
Does not minify svgs that have the <use> tag in them

### ISSUE THREAD

**Issue by Scrum** [svg/svgo#921]
Pretty much what it sounds like. I created an example [here](https://glitch.com/edit/#!/lying-equinox?path=server.js:24:4). You can view the results of this code in three places:

1. No minification: https://lying-equinox.glitch.me/
2. Minification with minifySvg set to `false`: https://lying-equinox.glitch.me/minify_good
3. Minification with minifySvg set to default (which is true): https://lying-equinox.glitch.me/minify_bad

If you inspect element the `minify_bad` path, you can see how htmlnano butchers the `<use>` tag's contents. Not sure if this is intentional behavior or not but it makes dealing with svgs difficult (which is unfortunate because they tend to create a lot of whitespace and such if not minimized). 

> forwarded from here https://github.com/posthtml/htmlnano/issues/47#issue-301651816

**Comment by maltsev** [comment]
This issue is relevant to the old versions of SVGO. The latest one handles `<use>` well. So you could close this case.
