### ISSUE TITLE
Option -p 2 breaks svg file

### ISSUE THREAD

**Issue by shyr1punk** [svg/svgo#922]
Try optimize file with `-p 2` option and got next results:
Original: https://gist.github.com/shyr1punk/be4c9e65d0da86a8e1f8e80fb7a0083c
With `-p 2` option: https://gist.github.com/shyr1punk/3d9c534c6de600ee8e6653fa3744a48f
No `-p 2` option: https://gist.github.com/shyr1punk/564966b8b03729f3952d3481b8067733

![2018-03-14 17 10 08](https://user-images.githubusercontent.com/2280073/37410834-7a3e5e16-27b2-11e8-9d24-39d45c87effe.png)

**Comment by XhmikosR** [comment]
Not sure if this is an issue with svgo since you are explicitly using a low precision?

**Comment by TrySound** [comment]
Looks like this is fixed. I cannot reproduce the problem with `-p 2`
