### ISSUE TITLE
--enable=cleanupListOfValues removes stroke-dasharray

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#923]
Processing [File:Kalliauer_et_al_2018_Acta_Mechanica_Fig11.svg](https://commons.wikimedia.org/wiki/File:Kalliauer_et_al_2018_Acta_Mechanica_Fig11.svg) removes necessary `stroke-dasharray="none"`

> $ svgo -i [Kalliauer_et_al_2018_Acta_Mechanica_Fig11.svg](https://upload.wikimedia.org/wikipedia/commons/2/20/Kalliauer_et_al_2018_Acta_Mechanica_Fig11.svg) -o output.svg --enable=cleanupListOfValues  --pretty --indent=1

![kalliauer_et_al_2018_acta_mechanica_fig11](https://user-images.githubusercontent.com/15687581/37435524-f502c02a-27e3-11e8-854e-04b2ef6a54f5.png)

Minimal working example:
[input.svg.txt](https://github.com/svg/svgo/files/1813421/input.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg stroke="#000" viewBox="0 0 416 312" xmlns="http://www.w3.org/2000/svg">
 <g fill="none" stroke-dasharray="8, 8" stroke-width="3">
  <path d="M83 250c69-18 140-40 197-84 33-23 48-62 62-99 2-6 3-12 7-16"/>
  <path d="M83 250c29-34 57-72 97-94 33-13 69-10 104-11 22 1 45 2 65 13" stroke-dasharray="none" stroke-linejoin="round"/>
 </g>
</svg>
```
![input](https://user-images.githubusercontent.com/15687581/37435507-e0578ac0-27e3-11e8-80c9-39d20a3a2e58.png)

output:
[output.svg.txt](https://github.com/svg/svgo/files/1813422/output.svg.txt)
```svg
<svg stroke="#000" viewBox="0 0 416 312" xmlns="http://www.w3.org/2000/svg">
 <g fill="none" stroke-dasharray="8 8" stroke-width="3">
  <path d="M83 250c69-18 140-40 197-84 33-23 48-62 62-99 2-6 3-12 7-16"/>
  <path d="M83 250c29-34 57-72 97-94 33-13 69-10 104-11 22 1 45 2 65 13" stroke-linejoin="round"/>
 </g>
</svg>
```
![output](https://user-images.githubusercontent.com/15687581/37435515-e442e5f8-27e3-11e8-8152-6447e98fb1eb.png)

Conclusion `stroke-dasharray="none"` should not be deleted because the group above `stroke-dasharray="8 8"` is used.

**Comment by GreLI** [comment]
Cannot reproduce as of v1.0.5.

**Comment by JoKalliauer** [comment]
@GreLI 
You can reproduce it with https://jakearchibald.github.io/svgomg/ with the option: `Round/rewrite number lists`

I can reproduce in as of v1.0.5, with option `--enable=cleanupListOfValues`.
> svgo -i [Bug0923_Input.svg.txt](https://github.com/svg/svgo/files/2386663/Bug0923_Input.svg.txt) -o [Bug0923_Output.svg.txt](https://github.com/svg/svgo/files/2386664/Bug0923_Output.svg.txt) --pretty --indent=1  --enable=cleanupListOfValues

# Input
[Bug0923_Input.svg.txt](https://github.com/svg/svgo/files/2386663/Bug0923_Input.svg.txt)
```svg
<svg xmlns="http://www.w3.org/2000/svg" stroke="#000" viewBox="0 0 416 312">
 <g fill="none" stroke-dasharray="8, 8" stroke-width="3">
  <path d="M83 250c69-18 140-40 197-84 33-23 48-62 62-99 2-6 3-12 7-16"/>
  <path stroke-dasharray="none" stroke-linejoin="round" d="M83 250c29-34 57-72 97-94 33-13 69-10 104-11 22 1 45 2 65 13"/>
 </g>
</svg>

```

**Comment by GreLI** [comment]
Ah, really. Oh, that non-standard optional plugins without tests…
