### ISSUE TITLE
Buffer constructor runtime deprecation - this package emits a warning on Node 10

### ISSUE THREAD

**Issue by benjamingr** [svg/svgo#925]
Hey from Node.js here!, 

Starting on Node 10 this package will emit deprecation warnings.  See [this guide](https://github.com/ChALkeR/safer-buffer/blob/master/Porting-Buffer.md) on what you should do in order to migrate to `Buffer.alloc`/`Buffer.from`. 

See https://github.com/nodejs/node/issues/19079 for discussion around this change and why we can't make `new Buffer` work

**Comment by GreLI** [comment]
Thank you for touching! Will consider it in the future.

**Comment by benjamingr** [comment]
@GreLI would you like a PR?

**Comment by GreLI** [comment]
Yeah, would be great! The only thing to consider: Node.js version requirement. Now, it declared to support from 4.0.0.

**Comment by benjamingr** [comment]
See https://github.com/svg/svgo/pull/926
