### ISSUE TITLE
Using attribute selection with css-select is broken

### ISSUE THREAD

**Issue by ydaniv** [svg/svgo#930]
`getAttributeValue()` for a missing attribute returns `null`, but then this is compared to `!== undefined` in the base adapter in `hasAttr()` which returns `true`.

So either you return `undefined` as the base adapter expects, or you implement `hasAttr()` here.

I can send a PR, but would like to hear if there's any specific reason for preferring one over the other.

Thanks!

**Comment by TrySound** [comment]
Fixed in https://github.com/svg/svgo/pull/1395
