### ISSUE TITLE
removeXMLNS does not work in all cases

### ISSUE THREAD

**Issue by MattCCC** [svg/svgo#936]
Hi, 

firstly, thank you for svgo. It is a great tool that I'm using for quite long time now. Works great except:

removeXMLNS set to true does work well except it doesn't remove:
xmlns:xlink="http://www.w3.org/1999/xlink"

I bet it's because the attribute differs "xmlns:xlink" instead of "xmlns".

Could you please fix it in next version? Thank you.

**Comment by thomsj** [comment]
Does your SVG use any `xlink` attributes, such as `xlink:href`?
