### ISSUE TITLE
Required ViewBox is removed unless `removeViewBox` and `removeUnknownsAndDefaults` are disabled

### ISSUE THREAD

**Issue by coreyward** [svg/svgo#939]
Working with the following SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 448 449">
    <path d="M448 25.2v398.5c0 13.7-11.1 24.7-24.7 24.7H309.1V275h58.2l8.7-67.6h-67v-43.2c0-19.6 5.4-32.9 33.5-32.9h35.8V70.8c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4V275h58.4v173.5H24.7C11.1 448.5 0 437.4 0 423.8V25.2C0 11.6 11.1.5 24.7.5h398.5C436.9.5 448 11.6 448 25.2z"/>
</svg>
```

Running with default settings on `1.0.5`: (note: `--pretty` is on strictly for readability and isn't affecting the described issue)

```sh
$ svgo fb.svg -o - --pretty
```

Produces the following output:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
    <path d="M448 25.2v398.5c0 13.7-11.1 24.7-24.7 24.7H309.1V275h58.2l8.7-67.6h-67v-43.2c0-19.6 5.4-32.9 33.5-32.9h35.8V70.8c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4V275h58.4v173.5H24.7C11.1 448.5 0 437.4 0 423.8V25.2C0 11.6 11.1.5 24.7.5h398.5C436.9.5 448 11.6 448 25.2z"/>
</svg>
```

Note that the `viewBox` attribute was removed unsafely. 

Running again with `--disable=removeViewBox` doesn't change the output. 
Running again with `--disable=removeUnknownsAndDefaults` doesn't change the output.

Running with both disabled results in the desired SVG output:

```sh
$ svgo fb.svg --disable={removeViewBox,removeUnknownsAndDefaults} -o - --pretty
```

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 448 449">
    <path d="M448 25.2v398.5c0 13.7-11.1 24.7-24.7 24.7H309.1V275h58.2l8.7-67.6h-67v-43.2c0-19.6 5.4-32.9 33.5-32.9h35.8V70.8c-6.2-.8-27.4-2.7-52.2-2.7-51.6 0-87 31.5-87 89.4v49.9h-58.4V275h58.4v173.5H24.7C11.1 448.5 0 437.4 0 423.8V25.2C0 11.6 11.1.5 24.7.5h398.5C436.9.5 448 11.6 448 25.2z"/>
</svg>
```

**Comment by GreLI** [comment]
SVG is based on XML, meaning that attributes are case-sensitive. `viewbox` is meaningless attribute (don't mess with SVG `viewBox` attribute—with capital “B”!) and thus is being removed.

**Comment by coreyward** [comment]
Interesting. I'm not sure how this file was created, but browsers don't seem to care. Any idea why disabling `removeUnknownsAndDefaults` still results in the errant attribute being removed?

**Comment by GreLI** [comment]
Because it removes unknown attribute which lowercase `viewbox` is.

Browsers may treat it differently depending on how is SVG used. E.g. if it's inlined in HTML a loose HTML parsing may be used (and one don't need even to declare SVG xmlns). But that still is browser dependent.

**Comment by coreyward** [comment]
I think you misread. When `removeUnknownsAndDefaults` is *disabled* the attribute is still removed. So either it is still active or another plugin is removing the attribute.

**Comment by GreLI** [comment]
I cannot reproduce. `--disable=removeUnknownsAndDefaults` works for me:
```
$ svgo -s '<svg viewbox="0 0 448 449"/>' --disable=removeUnknownsAndDefaults
<svg viewbox="0 0 448 449"/>
```

**Comment by coreyward** [comment]
Ah, I still had the curly braces around the arguments to `--disable`. Apparently it silently ignores that if there's only a single argument. E.g. `svgo x.svg --disable={removeUnknownsAndDefaults}`

**Comment by devongovett** [comment]
Would it make sense to have an option to SVGO to indicate that the SVG was originally embedded in HTML? Writing lowercase attributes is completely valid according to the HTML spec.

> In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of ASCII lower and ASCII upper alphas.

See https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name

I'm working on an issue in Parcel (https://github.com/parcel-bundler/parcel/issues/5004) where we treat attributes in HTML case insensitively according to the spec, but embedded SVG becomes broken after being run through SVGO. However, even if we didn't lower case all attributes, this would still be broken since users can write their source HTML with lowercase attributes to begin with and it is completely valid when run in the browser, but will be broken by SVGO.

Happy to help however I can!

**Comment by GreLI** [comment]
It could be, but there is a lot of caveats and lot of changes in SVGO.
