### ISSUE TITLE
SVGO cant find a file/directory

### ISSUE THREAD

**Issue by ekctpemict** [svg/svgo#942]
Node: 6.11.1
NPM: 5.8.0
SVGO: 1.0.5
Windows 10 x64

`"scripts": {
    "build:svg": "svgo -o dist/svg/linkedin.svg -f assets/svg/linkedin.svg",
  }`

I have an Error:

> C:\OpenServer\domains\cv.local>npm run build:svg
> cv.local@1.0.0 build:svg C:\OpenServer\domains\cv.local
> svgo  -o dist/svg/linkedin.svg -f assets/svg/linkedin.svg
>
>Processing directory 'assets/svg/linkedin.svg':
>
>{ Error: ENOTDIR: not a directory, scandir 'C:\OpenServer\domains\cv.local\assets\svg\linkedin.svg'
    at Error (native)
  errno: -4052,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: 'C:\\OpenServer\\domains\\cv.local\\assets\\svg\\linkedin.svg' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cv.local@1.0.0 build:svg: `svgo  -o dist/svg/linkedin.svg -f assets/svg/linkedin.svg`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cv.local@1.0.0 build:svg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by GreLI** [comment]
The `-f` key is for processing directories. You should use `-o` key—actually it can process directories as well.
