### ISSUE TITLE
cleanupIDs fails when prefix is 8 or more characters long

### ISSUE THREAD

**Issue by tremby** [svg/svgo#943]
I'm trying to use the `cleanupIDs` plugin with `prefix` set, via the `img-loader` webpack loader.

It seems to work fine if the prefix is 7 or fewer characters long (such as `1234567`), but as soon as it's 8 or more characters long (like `12345678`) the SVG doesn't get optimized at all. I don't see any error messages.

**Comment by tremby** [comment]
Not sure if it's related, but unless I disable `multipass` I can't get *either* plugin to work, even with a short prefix.

**Comment by tremby** [comment]
If I reenable `multipass` at this point I get the ID prefixed multiple times. Let me know if I should open a separate issue for that.

**Comment by TrySound** [comment]
Should be fixed in 2.0.1
