### ISSUE TITLE
prefixIds plugin fails if an element has multiple classes

### ISSUE THREAD

**Issue by tremby** [svg/svgo#948]
If an element has multiple classes and prefixIds is enabled, the classes are joined with an underscore, and then the prefix is added once at the very beginning.

With input `class="cls1 cls2"` I would expect the output `class="prefix_cls1 prefix_cls2"` but the actual output is `class="prefix_cls1_cls2"`.

**Comment by vzaidman** [comment]
ill fix it

**Comment by vzaidman** [comment]
ill fix it

**Comment by vzaidman** [comment]
opened a PR about it:
https://github.com/svg/svgo/pull/950
