### ISSUE TITLE
No newline at end of file or Do not remove newline at end of file option

### ISSUE THREAD

**Issue by schalkneethling** [svg/svgo#951]
When using the SVGO-CLI on `.svg` files, the output removes the newline at the end of the file. Is there a way to tell SVGO to not remove this?

Currently using it as follows:

```
svgo jinja2/includes/icons/* --disable=removeViewBox
```

**Comment by schalkneethling** [comment]
Enabling `--pretty` pretty much solves this problem.

**Comment by adalinesimonian** [comment]
Support for enforcing a final newline (as well as choosing what EOL to use) has landed in e8321f0c27b563734d9c4d7240a1b5a0b904b4ec.
