### ISSUE TITLE
mergePaths  produces FATAL ERROR for big file

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#955]
Prozessing [File:Germany (+districts +municipalities) location map.svg](https://commons.wikimedia.org/wiki/File:Germany_(%2Bdistricts_%2Bmunicipalities)_location_map.svg) (~73MB) fails after needing more than 1,4GB RAM (I have 16GB RAM total, and during processing always more than 9GB free)

>$ svgo -i [Germany_%28%2Bdistricts_%2Bmunicipalities%29_location_map.svg](https://upload.wikimedia.org/wikipedia/commons/5/5a/Germany_%28%2Bdistricts_%2Bmunicipalities%29_location_map.svg) -o output.svg --enable=mergePaths --disable=convertPathData

```
<--- Last few GCs --->

[7416:0000020BE328C800]    62982 ms: Mark-sweep 1490.4 (1534.9) -> 1491.1 (1535.9) MB, 1607.5 / 0.0 ms  (+ 1173.9 ms in 248 steps since start of marking, biggest step 10.7 ms, walltime since start of marking 2853 ms) allocation failure scavenge might not [7416:0000020BE328C800]    65324 ms: Mark-sweep 1491.1 (1535.9) -> 1490.4 (1550.9) MB, 2340.4 / 0.0 ms  allocation failure scavenge might not succeed


<--- JS stacktrace --->
Cannot get stack trace in GC.


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory

```

**Comment by XhmikosR** [comment]
Isn't this the same issue as #954?

**Comment by JoKalliauer** [comment]
@XhmikosR Yes I think I accidentally reported it twice. (Also it has a slightly different error-message)

I just tried it on my current Fedora (Linux) and it worked, not sure if the issue still occurs at windows.

**Comment by XhmikosR** [comment]
I can definitely replicate #954 on Windows, so yeah.
