### ISSUE TITLE
delete objects outside visible area

### ISSUE THREAD

**Issue by JoKalliauer** [svg/svgo#956]
Is there an option to remove not visible objects, which are outside the viewbox, or outside width & height ?

**Comment by JoshyPHP** [comment]
@GreLI Would it be possible to use `intersects()` from `_path.js` using a simple rectangular path to represent the viewbox, to determine whether a given path intersects with the viewbox and therefore is visible?

**Comment by TrySound** [comment]
Solved by this I guess https://github.com/svg/svgo/blob/master/plugins/removeOffCanvasPaths.js

**Comment by danieltroger** [comment]
Hi @TrySound, I'm using svgo 3.0.5 but on this SVG

![theme-editor-file](https://github.com/svg/svgo/assets/4047180/c062e02c-051c-400f-8d16-2be6acd58a9d)

A LOT of off-screen objects are still preserved (`682.619 KiB - 0% = 682.619 KiB`), any idea why that's the case and if there is some tool to properly remove them?

You can see the not-removed objects by opening the file in inkscape, right clicking it and selecting "release clip"

**Comment by KTibow** [comment]
Update: I spent the last couple hours trying to crush this SVG down for fun (got it around half the size of stock SVGO), I used Inkscape and some custom SVGO plugins, it could probably be reduced further and the background/arrow have yet to be added back but enjoy
![img-b](https://github.com/svg/svgo/assets/10727862/07676c8c-12b9-4a41-8d53-8d290d798c3f)

**Comment by KTibow** [comment]
I'd check the SVG and see if there's still more groups being used. Groups break a lot of SVGO.
