### ISSUE TITLE
Converting simple shapes (rect, arc, line, polyline, polygone) to path elements and merging.

### ISSUE THREAD

**Issue by redscorpix** [svg/svgo#96]
Input:
&lt;rect x="2" y="2" fill="#FFFFFF" width="2" height="2"/&gt;
&lt;rect x="2" y="6" fill="#FFFFFF" width="2" height="2"/&gt;
&lt;rect x="2" y="10" fill="#FFFFFF" width="2" height="2"/&gt;
Paths:
&lt;path fill="#fff" d="M2,2 h2 v2 h-2z"/&gt;
&lt;path fill="#fff" d="M2,6 h2 v2 h-2z"/&gt;
&lt;path fill="#fff" d="M2,10 h2 v2 h-2z"/&gt;
Output:
&lt;path fill="#fff" d="M2,2 h2 v2 h-2z M2,6 h2 v2 h-2z M2,10 h2 v2 h-2z"/&gt;

**Comment by vedran-milic** [comment]
Is it possible to turn this feature off?

**Comment by derhuerst** [comment]
@vedran-milic Run svgo with `--disable convertShapeToPath`.

**Comment by vedran-milic** [comment]
@derhuerst Thanks

**Comment by JoKalliauer** [comment]
Is it posible to convert it the other way round:

I want to convert `<path` to `<rect` because ìn Inkscape <[flowRoot](https://www.w3.org/TR/2004/WD-SVG12-20041027/flow.html)> only works with `rect` properly but not with `path`.
