### ISSUE TITLE
Removing viewBox breaks scaling in <img> tag.

### ISSUE THREAD

**Issue by Huulivoide** [svg/svgo#970]
If the viewBox is removed the svg does not maintain aspect ratio if used as source for an HTML` <img>` tag.
This problem exist at least in Chrome and Firefox.

Therefore I think the removeViewBox plugin should be disabled by default.

Test here: https://codepen.io/Huulivoide/pen/NzPKoM

![viewbox-removed-scaling-broken](https://user-images.githubusercontent.com/294363/40707851-8c97b498-63fa-11e8-9572-326fdf7032e3.png)

**Comment by vzaidman** [comment]
if so, id also add a warning about this in the readme

**Comment by GreLI** [comment]
If you use a PNG file, it will be scaled as well. In other context (e.g. element background) SVG behaves as expected, so it's just an edge case due to wrong `<img>` element size. Probably, a bug in browsers.

**Comment by GreLI** [comment]
On the second thought it's not a bug, just `width` and `height` attributes have no effect in that context. It just behaves if they are absent, since only the sizes of `<img>` taken in account.

**Comment by Huulivoide** [comment]
This is because the preserveAspectRatio attribute defaults to "preserve" aspect ratio mode, if viewBox is defined. If no viewBox is defined then preserveAspectRatio attribute is ignored, be it defined or not.

So removing viewBox attrribute also has the side effect of modifying the implied value of the preserveAspectRatio attribute.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio

**Comment by GreLI** [comment]
Yeah, but usually intrinsic size from attributes `width` and `height` are in use, but it's ignored in this specific case. SVGO don't know how image will be used, that's why it is highly configurable. It has to bear reasonable balance between optimization and “safety”, so default options are usually ok, but not 100% fits to everyone. Otherwise, many optimization in 90%+ cases should be enabled manually, which is not user friendly.

**Comment by tkh44** [comment]
It is illogical for an optimization to modify the end result and thus create an unpredictable and unexpected output. When the `viewBox` attribute is present on an SVG tag it has a specific meaning that defines how that svg is to be displayed and rendered. *Removing the attribute changes the render behavior of the SVG*

> If you'd use a PNG file, it will be scaled as well. In other context (e.g. element background) SVG behaves as expected, so it's just an edge case due to wrong <img> element size. Probably, a bug in browsers.

We aren't using PNG files, we are using SVG files which use the `viewBox` to instruct the browser render engine to render the SVG in a specific manner.

> Yeah, but usually intrinsic size from attributes width and height are in use, but it's ignored in this specific case. SVGO don't know how image will be used, that's why it is highly configurable. It has to bear reasonable balance between optimization and “safety”, so default options are usually ok, but not 100% fits to everyone. Otherwise, many optimization in 90%+ cases should be enabled manually, which is not user friendly.

It seems to me that the safer option is to not *remove* such a key attribute when it comes to a render engine rendering the SVG. "Saftey" is not removing critical render instructions from an element in the name of optimization!
