### ISSUE TITLE
Support for asynchronous functions in plugins

### ISSUE THREAD

**Issue by Zulko** [svg/svgo#972]
If a SVGO plugin runs an asynchronous function, nothing waits for that function to end. This is a problem as many features in JS are provided by asynchronous libraries. Would it be possible to support asynchronous ``fn`` functions in plugins ?

**Comment by GreLI** [comment]
No such plans currently.

**Comment by glennosss** [comment]
FYI I used a Worker Thread/Atomics.wait() approach to allow me to use async code synchronically within svgo's plugin framework. For more information, see: https://github.com/glennosss/svgo-autocrop/blob/master/lib/WorkerTheadUtils.js
