### ISSUE TITLE
Replace svg width,height with viewBox to make it responsive

### ISSUE THREAD

**Issue by guylando** [svg/svgo#993]
Is it possible to replace svg width,height with viewBox?

for example 
<svg width="63" height="151"...
will be replaced with
<svg viewBox="0 0 63 151"...

**Comment by guylando** [comment]
I implemented a plugin which does this: https://github.com/guylando/svgo-addViewBox
You are welcome to add it to the official plugins list since its very useful to make svgs responsive when using them as an inline include (https://css-tricks.com/pretty-good-svg-icon-system/)

**Comment by mryarbles** [comment]
This functionality is essential.

**Comment by GreLI** [comment]
It's more like image editing rather than optimization, so it's out of SVGO's scope.
