### ISSUE TITLE
convertStyleToAttrs breaks IE11 in a case if CSS variables are used for colors

### ISSUE THREAD

**Issue by FlyingDR** [svg/svgo#995]
As of v1.0.5 `convertStyleToAttrs` produces output that conflicts with IE11 in a case if CSS variables are used for colors. Example of such SVG is export of [icomoon.io](https://icomoon.io/app). 

[Here](https://gist.github.com/FlyingDR/ab60fbc11dbb4e3ae81b5f47c36fc2e3) is test IcoMoon project, it can be loaded [here](https://icomoon.io/app/#/projects). It consists of single [`facebook.svg`](https://gist.github.com/FlyingDR/3b86ec8dbe68a9f48caef7c8d3fadd9a) icon. You can export SVG icons for the project by using `Generate SVG & More` below and then `Download`. Result of this export is [`symbol-defs.svg`](https://gist.github.com/FlyingDR/0cee581c365c4d8ccd3a2393bfe317fa). As you can see - it basically consists of 
```html
<path fill="#3a589b" style="fill: var(--color1, #3a589b)" d=..."></path>
```
Attempt to optimize this project using svgo with this command line:
```
svgo --disable removeUselessDefs --disable cleanupIDs --enable removeTitle symbol-defs.svg
```
results into following `<path>`:
```html
<path fill="var(--color1,#3a589b)" d=""/>
```
As you can see - result for `fill` attribute now contains CSS variable that is [not supported in IE11](https://caniuse.com/#feat=css-variables). As a result - icon looks like plain black square in IE11.

Of course it is possible to just disable `convertStyleToAttrs` plugin in this case but maybe it worth to handle such situation by e.g. adding plugin that will strip CSS variables or detect CSS variable and not replace attribute in this case.

**Comment by TrySound** [comment]
convertStyleToAttrs will be disabled by default in the next release
https://github.com/svg/svgo/pull/1365

**Comment by TrySound** [comment]
https://github.com/svg/svgo/releases/tag/v2.1.0
